### PR TITLE
Define GitSCM checkout logic for branches and forks

### LINKED ISSUE #1531: Travis CI from forked repositories
**Describe the bug**
When following guidelines set in [CONTRIBUTING.md](https://github.com/bbc/simorgh/blob/latest/CONTRIBUTING.md#contributing), I get the following error from Travis:
`The command "xvfb-run -a npm run test:prod:travis" exited with 1.`
_https://travis-ci.org/rhell/simorgh/jobs/514624945_

The build does also not report to the [original GitHub PR](https://github.com/bbc/simorgh/pull/1498).

By **not** changing the `README.md` as instructed to do so in the Contributing guidelines, that above error does not appear, and the [Travis CI builds pass](https://travis-ci.org/rhell/simorgh/builds/514627800). However, this is still not reported on the GitHub PR.

**To Reproduce**

1. Fork the Simorgh repository
2. Follow instructions set out in https://github.com/bbc/simorgh/blob/latest/CONTRIBUTING.md#contributing
3. Open a PR
4. Visit https://travis-ci.org and watch your build
4. See build fail, and not report into the Github PR

**Expected behaviour**
When committing to a PR on a forked repository, Travis should not error, and should also report the result back to the original GitHub PR.

https://github.com/bbc/simorgh/blob/latest/CONTRIBUTING.md#run-tests-on-your-fork should be updated.

**Screenshots**
image

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

### PR DESCRIPTION
**Pull request by alex-magana**
Resolves #1531
Required by https://github.com/bbc/simorgh/pull/1594

**Overall change:** _This PR changes the `checkout` in stage, `Checkout application repo` by setting the branch name and PR reference, for branches and PRs respectively._

**Code changes:** _No longer necessary since SCM configuration is no longer required (See file changes is 0 [zero])_

- Set `FETCH_HEAD` to the `branches` attribute in the checkout config for build initiated by `Pull requests` associated events on the webhook.
- Set `*/branch_name` to the `branches` attribute in the checkout config for build initiated by `push` events on the webhook.
- Set a `refspec` to reference a PR for builds initiated by `Pull requests` associated events on the webhook.
- Set a `name` to reference a branch for builds initiated by `push` associated events on the webhook.

**Repository settings changes:**
- Branch protection rules
Require `continuous-integration/jenkins/pr-merge` instead of `continuous-integration/jenkins/branch` 
for a PR merge.
This is necessary since the `continuous-integration/jenkins/branch` status is only posted from Jenkins when a branch is built. Due to this, merging a PR from a fork is blocked since builds initiated by a PR only report the `continuous-integration/jenkins/pr-merge` status. They do not report the `continuous-integration/jenkins/branch` status.

Screen Shot 2019-04-30 at 17 32 05

- Webhook https://ci.news.tools.bbc.co.uk/github-webhook/
Enable the `Pushes` and `Pull requests` on the webhook.

Screen Shot 2019-04-30 at 17 37 55

**Job config changes:**
- Add `Discover pull requests from forks` and `Discover pull requests from origin` under the `GitHub` `BranchSources` config in the simorgh job.

Screen Shot 2019-04-30 at 17 40 38

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by DemonusPC — DISMISSED** [review]
Looks dank to me

**Review by chris-hinds — DISMISSED** [review]
👍

**Comment by chris-hinds** [comment]
@alex-magana this Branch has some conflicts with the Jenkins file, and can you please speak with a tester about how/if this PR can be tested.

**Comment by staylos92** [comment]
This ticket does not need to go through formal "tester" testing. I'm happy for it to be merged once reviewed 👍

**Comment by alex-magana** [comment]
Blocked. Requires resolution of Jira ticket RESFRAME-2625.
See https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/architecture-decision-records/2019-02-13-jenkins-github-forks.md for further details.

**Comment by alex-magana** [comment]
From the discussion that followed the query on whether or not https://jira.dev.bbc.co.uk/browse/RESFRAME-2625 was going to be undertaken to unblock us, we resolved that the exposure GITHUB_TOKEN was part of a larger issue. The conclusion was that there are multiple resources e.g environment variables, certs etc that are used by the job that would be exposed even with the GITHUB_TOKEN resolved. As such we should work on an alternative to running the PR originating form forks on Jenkins.
I'll raise an issue to cater to this investigation.

**Comment by alex-magana** [comment]
https://github.com/bbc/simorgh/issues/2666 has been opened to investigate an alternative to
discovering branches from forks in the Simorgh jenkins pipeline.
As such, I'm closing this issue to pave way for https://github.com/bbc/simorgh/issues/2666

**Pull request closed without merging**
