### PR TITLE
If environment live return undefined to skip article tests for Persian

### PR DESCRIPTION
**Pull request by chris-hinds**
Resolves No issue

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by jamesbhobbs — APPROVED** [review]

**Review by thekp — APPROVED** [review]
i ran `npm run test:e2e:live_env` on your branch and the intended test passes 👍 

image

**Comment by chris-hinds** [comment]
have confirmed this fix is working locally when run against the live environment.

**Review by jamesdonoh — APPROVED** [review]
OK - so this will need removing once there are Persian articles on live?

**Comment by chris-hinds** [comment]
> OK - so this will need removing once there are Persian articles on live?

Correct, raising an issue now to make sure this is updated with a new live asset ID

**Comment by chris-hinds** [comment]
CC @jamesdonoh https://github.com/bbc/simorgh/issues/2335

**Pull request merged**
