### PR TITLE
webpack performance budget 

### LINKED ISSUE #1586: Webpack performance budgets
**Is your feature request related to a problem? Please describe.**
We do not currently have anything that tells us if our bundles significantly increase in size. Currently we could inadvertently make our bundles enormous without realising and hurt user experience.

**Describe the solution you'd like**
Set up appropriate `performance` options in Webpack to alert us to potential performance problems at build time. https://webpack.js.org/configuration/performance/

Thresholds should be set at a sensible initial limit and can be revised later.

**Describe alternatives you've considered**
RUM/synthetic performance testing would also alert us to unexpected increases in bundle size, but we would prefer to know before the change is released.

We should think about how and where we define our thresholds for bundle size and whether we can join these up with Lighthouse thresholds somehow.

**Testing notes**
- If you add an unexpectedly large amount to the bundle size then the PR build should fail on CI and merging should be impossible
- Ideally should also fail on developer's machine when building locally

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by thekp**
Resolves #1586 

**Overall change:** Update performance parameters in Webpack config to throw error if the asset or entry point size exceeds the set limit.

**Code changes:**

- Initially the Webpack performance check would run during the continuous integration step, however I have changed it so that it should run whenever Webpack builds.
- The performance check will now throw an error and stop the build if either the asset or entry point size exceeds the specified limit. 
- I have increased the maxEntryPointSize because when i ran the build locally, we seem to have already be exceeding the limit, with a bundle of 482kb.

**Warning with previous implementation:**
image

**Example of error being thrown:**
image

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by rossgaskell — DISMISSED** [review]
👍 🎉

**Review by chris-hinds — DISMISSED** [review]
👍

**Review by dr3 — DISMISSED** [review]

**Comment by PriyaKR** [comment]
Testing:

Looks like the threshold limit is underestimated so it throws error even without adding a heavy bundle file.
webpack_performance_issue

**Comment by rossgaskell** [comment]
Increased the limit to 616kb (current bundle size of 493kb + 25%)

**Comment by dr3** [comment]
is increasing by 25% not quite a lot?

**Comment by rossgaskell** [comment]
Not really. If we continue increasing the bundle size at the current rate, that only gives us another 8 weeks before we'll reach it

**Review by chris-hinds — APPROVED** [review]
👍

**Comment by dr3** [comment]
👋 Apologies, this PR needs a bump and changelog update :) Details can be found [here](https://github.com/bbc/simorgh/blob/a75ad1fbf4a720bf6147d7f57ee3d8e3a7337632/CONTRIBUTING.md#versioning-and-changelog)

**Review by jamesdonoh — APPROVED** [review]
Let's go with this 👍

**Comment by PriyaKR** [comment]
LGTM.Throws error when a js file of size >616KiB is added and also when an asset size exceeds the recommended size limit(240KiB).
Webpack_perf_recommendation

**Pull request merged**
