### PR TITLE
Enable the STY e2e's on localhost and test and enable smoke testing f…

### PR DESCRIPTION
**Pull request by chris-hinds**
…or ukchina STY's

Resolves N/A

**Overall change:**
Enables the e2e's for ukchina and gahuza on localhost and test. Also enables smoke testing against ukchina trad sty's

**Code changes:**

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added labels to this PR for the relevant pod(s) affected by these changes
- [ ] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by chris-hinds** [comment]
This PR enabled the e2e test for gahuza and ukchina on localhost and test.

When running the tests locally I am seeing some failures, these seem to be linked to CSP issues with includes see the below console errors

image

**Comment by chris-hinds** [comment]
A couple of failing tests;

```
Script Switching - ukchinaSimp - storyPage - /ukchina/simp/23298231

       should change to the correct script when switching script from simp to trad:



      AssertionError: expected 'zh-hans' to equal 'zh-hant'

      + expected - actual



      -zh-hans

      +zh-hant
```

**Review by karinathomasbbc — APPROVED** [review]

**Comment by andrewscfc** [comment]
> This PR enabled the e2e test for gahuza and ukchina on localhost and test.
> 
> When running the tests locally I am seeing some failures, these seem to be linked to CSP issues with includes see the below console errors
> 
> image

This relates to https://github.com/bbc/simorgh-infrastructure/issues/1041, it has not been refined and picked up as yet. I don't imagine it would cause tests to fail as I don't think we have any Cypress tests for includes as yet.

**Comment by chris-hinds** [comment]
> > This PR enabled the e2e test for gahuza and ukchina on localhost and test.
> > When running the tests locally I am seeing some failures, these seem to be linked to CSP issues with includes see the below console errors
> > image
> 
> This relates to [bbc/simorgh-infrastructure#1041](https://github.com/bbc/simorgh-infrastructure/issues/1041), it has not been refined and picked up as yet. I don't imagine it would cause tests to fail as I don't think we have any Cypress tests for includes as yet.

The e2e's seem to be failing as the CSP errors are causing `uncaught errors` and cypress just stops when it sees these. 

In this case I'd suggest we first target an asset without includes?

**Review by 12 — APPROVED** [review]

**Pull request merged**
