### PR TITLE
Allow Simorgh to be built on Windows

### PR DESCRIPTION
**Pull request by DemonusPC**
Simorgh is technically an open source project, which means we should be as cross platform as possible. Unfortunately eslint and some scripts prevent the project from being cross platform. This PR solves this problem by: 
- Modifying eslintrc file to be a standard javascript file and then enforcing the linebreak-rule depending on the operating system. The default is to enforce it on unix systems while on windows that rule will be disabled. 
- Changing the format of husky scripts from ./<file> to sh <file>. This is due to pathing problems when using Git Bash on Windows
- Adding a git attributes file with an end of line endings rule. This will make git enforce unix style line endings. So that they do not become windows like . 

- ~[ ] Tests added for new features~
- ~[ ] Test engineer approval~

### CODE REVIEW

**Comment by bcmn** [comment]
An alternative might be to add an [`.editorconfig`](https://editorconfig.org) file to the project? 🤔

**Comment by DemonusPC** [comment]
What sort of editors are supported? The eslint errors are automatically flagged in eslint so I don't think this is an editor error

**Comment by bcmn** [comment]
Editor support & plugins are listed on the site linked above. https://editorconfig.org/

It seems to include most modern editors I can think of off the top of my head.

**Comment by pjlee11** [comment]
Rather than turn the rule off entirely I would rather add `"linebreak-style": ["error", "unix"],` underneath [here](https://github.com/BBC-News/simorgh/blob/set-prodction-base-path-to-www.test/.eslintrc#L24) and then add a part in the README.md to mention that if working on a windows machine change `unix` to `windows` OR with @bcmn suggestion of adding an `.editorconfig` file

**Comment by DemonusPC** [comment]
Yes thats a good idea. Git should handle line nedings for us.

**Comment by jtart** [comment]
It would be preferable to add a `.editorconfig` file, and we could also add a `.gitattributes` file with line endings config, this along with not disabling the eslint config, would enforce consistency.

**Comment by pjlee11** [comment]
In the PR description could you elaborate on why the `.gitattributes` is required, why the `.js` needs to be appended to .eslintrc and why `module.exports = {` is needed. Just for future clarity, other than that good work 😎

**Review by pjlee11 — APPROVED** [review]
👍

**Review by jtart — APPROVED** [review]

**Pull request merged**
