### PR TITLE
Pass isAmp to the RequestContext

### LINKED ISSUE #4970: Pass isAmp to the RequestContext values
**Is your feature request related to a problem? Please describe.**
There are number of places in the codebase where we check wether an `amp` or `canonical` page was requested. So we end up having this check `isAmp = platform  === 'amp` .  https://github.com/bbc/simorgh/blob/55207a4d9ea91afbeea5615aa4514e9a9e9a1336/src/app/containers/MediaPlayer/index.jsx#L36

**Describe the solution you'd like**
Pass `isAmp` in the `RequestContextValues` and see whether we can remove the `platform` key from the values.

https://github.com/bbc/simorgh/blob/55207a4d9ea91afbeea5615aa4514e9a9e9a1336//src/app/contexts/RequestContext/index.jsx#L38-L51

**Describe alternatives you've considered**
Leave it as it is and continue doing `isAmp = platform === 'amp'` checks.

**Testing notes**
[Tester to complete]

Dev insight: Make sure there is no regression where the check was being used.

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves #4970

**Overall change:** 
Pass `isAmp` to the `RequestContext` to avoid having this check `isAmp = platform === 'amp'` across the codebase. 

**Code changes:**
- Remove most of the `platform === 'amp'` checks and replace them with `isAmp`.

---

- [X] I have assigned myself to this PR and the corresponding issues
- [X] I have added labels to this PR for the relevant pod(s) affected by these changes
- [X] I have assigned this PR to the Simorgh project

**Testing:**
- [X] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [X] This PR requires manual testing

### CODE REVIEW

**Review by AlistairGempf — COMMENTED** [review]
This all looks good but there are some examples in `src/app/lib/analyticsUtils/index.js` that use `if (platform === 'amp')`. Not sure if these could do with being updated too?

**Comment by DenisHdz** [comment]
> This all looks good but there are some examples in `src/app/lib/analyticsUtils/index.js` that use `if (platform === 'amp')`. Not sure if these could do with being updated too?

Looking at this file, I think it is better to keep it as it is, as it would require a lot of refactoring in other ATI files to pass `isAmp` instead of `platform` and we might end up breaking something.

**Review by rhenshaw56 — APPROVED** [review]

**Review by AlistairGempf — APPROVED** [review]
Agreed about the ATI complexity. Looks good.

**Review by j-pendlebury — APPROVED** [review]

**Comment by PriyaKR** [comment]
Looks good to me.Did a quick regression.

**Pull request merged**
