### PR TITLE
Integrate desktop width top story

### LINKED ISSUE #3144: Integrating desktop width top stories
Blocked on bbc/psammead#1761

WSFRONTPGS-129

**Is your feature request related to a problem? Please describe.**
There have been some updated designs for Top Story promos for 600px+ breakpoints.

**Describe the solution you'd like**
Pull in the new version of `psammead-story-promo` which includes new support for desktop width top story promos.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

### PR DESCRIPTION
**Pull request by ghost**
Resolves #3144

**Overall change:** Integrate desktop width top story. (breakpoints above 600px)
**Code changes:**

- Update `@bbc/psammead-story-promo` to version `2.7.3`
- Update snapshots

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by EinsteinNjoroge — APPROVED** [review]

**Review by EinsteinNjoroge — CHANGES_REQUESTED** [review]
Tests are failing due to duplicate packages

**Review by DenisHdz — COMMENTED** [review]
~Avoid this comment~

**Comment by amywalkerdev** [comment]
gel-foundations is 3.3.3 in story-promo but 3.3.2 everywhere else. Need to bump it to the same version so we don't get duplications

**Comment by ghost** [comment]
Close in favour of #3549

**Pull request closed without merging**
