### PR TITLE
WSTEAM1-177 - Brasil experiment teardown

### PR DESCRIPTION
**Pull request by amoore108**
Resolves WSTEAM1-177

Overall changes
======
Removes Optimizely logic from WSOJ components and pages

Code changes
======
- Removes Optimizely component for WSOJ and reinstates the `CpsRecommendations` component
- Removes `mappings.ts` file and usage for generating experimental fetch endpoints
- Removes recommendations fetch logic from `cpsAsset/utils/getAdditionalPageData` as this is now handled by the `getOnwardsData.ts` file
- Removes Optimizely specific tests

Testing
======
1. Visit a Live page and confirm that recommendations are rendering as expected on both Optimo Article and CPS story pages

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

### CODE REVIEW

**Review by shayneahchoon — APPROVED** [review]

**Review by HarveyPeachey — COMMENTED** [review]
Not sure if we've done this in the past, but should we remove the [Optimizely HOC](https://github.com/bbc/simorgh/blob/3d98e1dac0ba54cfe5ed3d6a8b6c8d2cd862a854/src/app/pages/StoryPage/index.jsx#L5-L9) when we have no experiments running on the page? It'll reduce the bundle size in the meantime before we do another experiment

**Comment by amoore108** [comment]
> Not sure if we've done this in the past, but should we remove the [Optimizely HOC](https://github.com/bbc/simorgh/blob/3d98e1dac0ba54cfe5ed3d6a8b6c8d2cd862a854/src/app/pages/ArticlePage/index.jsx#L5-L9) when we have no experiments running on the page? It'll reduce the bundle size in the meantime before we do another experiment

Good point! That would mean we would need to remove the OptimizelyPageViewTracking and other components too right? Makes sense I think not to have them when we're not running an experiment, but just a bit of pain/thing to remember to re-add when we do run one.

**Comment by HarveyPeachey** [comment]
> > Not sure if we've done this in the past, but should we remove the [Optimizely HOC](https://github.com/bbc/simorgh/blob/3d98e1dac0ba54cfe5ed3d6a8b6c8d2cd862a854/src/app/pages/ArticlePage/index.jsx#L5-L9) when we have no experiments running on the page? It'll reduce the bundle size in the meantime before we do another experiment
> 
> Good point! That would mean we would need to remove the OptimizelyPageViewTracking and other components too right? Makes sense I think not to have them when we're not running an experiment, but just a bit of pain/thing to remember to re-add when we do run one.

Ahh yeah forgot about those, yeah I don't know if there's a failsafe for when the optimizely object doesn't exist, you changed my mind, I'd say leave it

**Review by HarveyPeachey — APPROVED** [review]

**Comment by amoore108** [comment]
> Remove Optimizely HoCs and contexts

Oops, I was too slow to read. Committed in https://github.com/bbc/simorgh/pull/10742/commits/64f2eaa70cc484882ef8afa78c2b50c94a384d44. There were other `useContexts` referencing the older A/A MVT test as well that I've removed.

In 2 minds about the HoC though. Probably shouldn't be sending events to Optimizely unless we're running an experiment, so I guess if we just make sure to re-add them it should be ok. We'll know fairly quickly when we test the next experiment if they're missing I guess.

**Comment by HarveyPeachey** [comment]
> Oops, I was too slow to read. Committed in [64f2eaa](https://github.com/bbc/simorgh/commit/64f2eaa70cc484882ef8afa78c2b50c94a384d44). There were other `useContexts` referencing the older A/A MVT test as well that I've removed.
> 
> In 2 minds about the HoC though. Probably shouldn't be sending events to Optimizely unless we're running an experiment, so I guess if we just make sure to re-add them it should be ok. We'll know fairly quickly when we test the next experiment if they're missing I guess.

Yeah, in the click and view tracker hooks, we check for the optimizely object first, so maybe we could do something similar with the components later on 
https://github.com/bbc/simorgh/blob/3d98e1dac0ba54cfe5ed3d6a8b6c8d2cd862a854/src/app/hooks/useClickTrackerHandler/index.jsx#L21
https://github.com/bbc/simorgh/blob/3d98e1dac0ba54cfe5ed3d6a8b6c8d2cd862a854/src/app/hooks/useClickTrackerHandler/index.jsx#L62

**Pull request merged**
