### PR TITLE
Simplify fixture data into 1 folder

### PR DESCRIPTION
**Pull request by dr3**
**Overall change:** Removes prod/test data logic, combines into 1 folder

**Code changes:**

- Combines assets in prod and test data folders
- Updates server to read from single source for prod & test local

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by sareh** [comment]
Although it is tidier to have a single directory, it is now more difficult to know which Article fixture ids will be available on the Test environment and which will be available on the Live environment, for manual testing purposes.
Could you please update the table in the  `data/README.md` file - the final column has notes. Writing in that column `Local only` `Local and Test` `Local and Live` would add clarity. 
Thanks.

**Comment by jamesbhobbs** [comment]
@sareh Surely this list is unmaintainable and the docs are trying to do too much (test data shouldn't be expected to be stable for example and live assets can be removed)? It seems easier and almost as user-friendly to point out in our docs...

"The assets sequentially numbered are for local testing, those which aren't are either on test or live" Testing which they're on would take a few seconds and could also be explained.

PS much better to have a single dir IMO, thanks @dr3

**Comment by j-pendlebury** [comment]
There is one mention of `data/test` that was missed out and it lives [here
](https://github.com/bbc/simorgh/blob/dataShift/docs/Creating-Components.md#L102)
```
Pick a JSON file under `data/test/news/articles/[id].json`, and:
```

Also, conflict 🙈

**Review by ghost — APPROVED** [review]

**Comment by dr3** [comment]
resolved above :)

**Review by thekp — APPROVED** [review]
👍 LGTM
LGTM

**Review by j-pendlebury — APPROVED** [review]

**Comment by david-boydell** [comment]
Looks good, ready for merge.

**Comment by j-pendlebury** [comment]
@dr3

**Pull request merged**
