### PR TITLE
fix metadata warning

### LINKED ISSUE #2764: Fix React warnings in src/app/containers/Metadata/index.test.jsx
**Describe the bug**
There are React warnings in unit tests.

**To Reproduce**

1. Go to simorgh in terminal
2. Run npm run test:unit
3. Observe React warnings:

```
    console.log src/testHelpers/setupTests.js:19
      Test failed because too many React warnings were detected. Please fix the following:
      Warning: Failed prop type: Invalid prop `timeFirstPublished` of type `string` supplied to `Metadata`, expected `number`.
    console.error src/testHelpers/setupTests.js:30
      Warning: Failed prop type: Invalid prop `timeFirstPublished` of type `string` supplied to `Metadata`, expected `number`.
    console.error src/testHelpers/setupTests.js:30
      Warning: Failed prop type: Invalid prop `timeLastPublished` of type `string` supplied to `Metadata`, expected `number`.
```

**Expected behaviour**

No React warning for test suite.

**Testing notes**

No testing required.

### PR DESCRIPTION
**Pull request by Kachulio1**
Resolves #2764

**Overall change:** _ fix metadata warning_

**Code changes:**

- 
   changed timeFirstPublished in /src/app/components/Metadata/index.test.jsx to `type number`

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by chris-hinds** [comment]
👋 @Kachulio1 welcome to the codebase! Thanks for taking a look at this issue for us.

However I think we need to do a little more digging around this issue. The data here is used in two separate components, LinkedData and Metadata.

LinkedData is used to render structured data in the document head, and the structured data should follow the [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601) standard so would need to be a string.

Metadata is used to render the opengraph meta tags in the document head which also expect the [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601) standard.

So I think in this case that we should be passing a string to the component and the actual problem is that the component is expecting the incorrect prop type.

**Comment by FK78** [comment]
Hi @Kachulio1, thanks for taking a look at the issue, it has been solved in PR https://github.com/bbc/simorgh/pull/2972.

**Comment by amywalkerdev** [comment]
Going to close this based on the comments above, please feel free to keep contributing though and let us know if we can help!

**Comment by Kachulio1** [comment]
Thanks, @hindsc52 for the well-detailed explanation. @amywalker1987 I will thank you.

**Pull request closed without merging**
