### PR TITLE
WSTEAM1-403: Use app to strip page components

### PR DESCRIPTION
**Pull request by alex-magana**
Resolves [WSTEAMA-403](https://jira.dev.bbc.co.uk/browse/WSTEAMA-403)

Overall changes
======
Use the `.app` extension to strip the header, footer and onward journeys from the Optimo
article for the purpose of serving the content on the app.

Code changes
======

- Expose the isApp attribute via the RequestContext.
- Use isApp in the Footer component to conceal the footer.
- Use isApp in the Header component to conceal the site branding and the navigation.
- Use isApp in the ArticlePage component to conceal the secondary column that host the top stories and features.
- Update the pertinent snapshots, stories and test to include isApp in test assertions.

Testing
======
1. Visit an Optimo article page using the `.app` extension e.g `https://www.test.bbc.com/japanese/articles/cdd6p3r9g7jo.app`.
2. The page should not contain the site branding, navigation, footer and a secondary column (top stories and features).

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

### CODE REVIEW

**Review by karinathomasbbc — APPROVED** [review]
Looks good!

**Comment by amoore108** [comment]
Looks great 👍 

Just thinking, would it be worth having the check in the Header for `isApp` just before the return:
https://github.com/bbc/simorgh/blob/91c1e835421fa6a62f5be01cfa797bc5a0c8095a/src/app/legacy/containers/Header/index.jsx#L90

So something like:
```
if(isApp) return null;
```

Would just save passing the `isApp` flag around the components.

Could apply similar logic to the footer component and `return null` if its `isApp`, rather than `!isApp && ...`

More stylistic than anything, so not a major issue!

**Comment by alex-magana** [comment]
Thanks for the feedback Aaron.
The guard clause approach is most certainly apt.
For the Footer component, the guard clause can go [here](https://github.com/bbc/simorgh/blob/91c1e835421fa6a62f5be01cfa797bc5a0c8095a/src/app/legacy/containers/Footer/index.jsx#L44).
In the case of the Header component, since
- the AC for this ticket doesn't include concealing the ConsentBanner, and
- the ConsentBanner is rendered via the Header which also hosts the NavigationContainer and the BrandContainer,

we are not able to escape passing `isApp ` around. 
We should be able to use the guard clause in the Header once we have the
green light to conceal the ConsentBanner in which case we won't need to selectively 
hide the various components rendered via the Header.

**Comment by amoore108** [comment]
> Thanks for the feedback Aaron. The guard clause approach is most certainly apt. For the Footer component, the guard clause can go [here](https://github.com/bbc/simorgh/blob/91c1e835421fa6a62f5be01cfa797bc5a0c8095a/src/app/legacy/containers/Footer/index.jsx#L44). In the case of the Header component, since
> 
> * the AC for this ticket doesn't include concealing the ConsentBanner, and
> * the ConsentBanner is rendered via the Header which also hosts the NavigationContainer and the BrandContainer,
> 
> we are not able to escape passing `isApp ` around. We should be able to use the guard clause in the Header once we have the green light to conceal the ConsentBanner in which case we won't need to selectively hide the various components rendered via the Header.

Ah I see! No worries, good spot 👍 That makes sense to keep it where it is in the Header component.

**Review by amoore108 — APPROVED** [review]

**Pull request merged**
