### PR TITLE
Fixes RadioSchedule component issue with commas being read out on screen readers

### LINKED ISSUE #9593: Screen reader reads out commas on RadioSchedule
**Describe the bug**
When navigating the Radio Schedule component with a screen reader, visually hidden commas are read out. Similar to this bug: https://github.com/bbc/simorgh/issues/9559

Found this bug on TalkBack but all supported screen readers should be tested.

Additional example: https://www.bbc.com/persian/bbc_persian_radio/programmes/p0340vyx

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://www.bbc.com/hausa'
2. Navigate to 'Shirye-shiryenmu' heading using a screen reader
3. Swipe to the second card (Bug doesn't happen on cards with 'NA GABA/NEXT')
4. Swipe through the card's info
5. Two commas will be read out by the screen reader

**Expected behaviour**
Screen readers should pause instead of reading out 'comma'

**Screenshots**
image
image

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

### PR DESCRIPTION
**Pull request by pvaliani**
Resolves https://github.com/bbc/simorgh/issues/9593

**Overall change:**
Fixes an issue on screen readers where commas are read out via the screen reader over the radio schedule link entries

**Code changes:**

- Concatenates commas to the `formattedTime` to correct the screen reader issue

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by DarioR01 — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]

**Comment by pvaliani** [comment]
This fix was tested Android TalkBack, Chrome + Safari (Desktop + Mobile) but needs testing on an a11y laptop to check JAWS on Windows and NVDA.

**Comment by LilyL0u** [comment]
Testing checklist for a11y laptop:

- [ ] JAWS Chrome
- [ ] JAWS IE11
- [ ] NVDA Chrome
- [ ] NVDA Firefox ESR

**Comment by greenc05** [comment]
Thanks @pvaliani Did we check this is still formatted correctly without CSS?

**Comment by pvaliani** [comment]
> Thanks @pvaliani Did we check this is still formatted correctly without CSS?

Yes I have checked on the devices I can without an a11y laptop. Perhaps @DarioR01 could check with TalkBack. No worries!

image

**Comment by greenc05** [comment]
Thanks @pvaliani just one browser is sufficient for checking the formatting without CSS, looks good, thank you.

**Comment by paruchurisilpa** [comment]
Testing:

http://localhost:7080/persian/bbc_persian_radio/programmes/p0340vyx

- [x] JAWS Chrome
- [x] JAWS IE11
- [x] NVDA Chrome
- [x] NVDA Firefox ESR

LGTM..

**Comment by pvaliani** [comment]
> Testing:
> 
> http://localhost:7080/persian/bbc_persian_radio/programmes/p0340vyx
> 
> * [x]  JAWS Chrome
> * [x]  JAWS IE11
> * [x]  NVDA Chrome
> * [x]  NVDA Firefox ESR
> 
> LGTM..

Just re-running Chromatic checks and then will merge. Thank you :)

**Pull request merged**
