### PR TITLE
Storybook Proptypes fix

### LINKED ISSUE #1738: Storybook Proptype errors with RequestContext defaults
**Describe the bug**
Storybook examples have proptype errors due to required props not being passed in. 

**To Reproduce**

1. Go to branch `latest` 
2. run `npm install && npm run storybook`
3. Open console

**Expected behavior**
No proptype errors for RequestContextProvider

**Screenshots**
Screen Shot

These errors were introduced via this PR: https://github.com/bbc/simorgh/pull/1711

### PR DESCRIPTION
**Pull request by sareh**
Resolves #1738 

**Overall change:** Fixes only the `RequestContextProvider` proptype console errors in Storybook 
http://localhost:9001/?selectedKind=ConsentBanner

**Code changes:**

- Ensure RequestContextProvider in Storybook examples has all required props
- Update snapshots

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Comment by oluoluoxenfree** [comment]
Is this going to resolve all the errors? I still get these two:

```
Warning: Failed prop type: Caption: prop type `script` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
    in Caption (created by CaptionContainer)
    in CaptionContainer (created by VideoContainer)
    in figure (created by Context.Consumer)
    in StyledComponent (created by Figure)
    in Figure (created by VideoContainer)
    in VideoContainer
    in RequestContextProvider
    in div
```

```
checkPropTypes.js:20 Warning: Failed prop type: Invalid prop `ratio` of type `string` supplied to `ImagePlaceholder`, expected `number`.
    in ImagePlaceholder (created by StoryPromoFigure)
    in StoryPromoFigure (created by StoryPromo)
    in div (created by Context.Consumer)
    in StyledComponent (created by ImageGridItem)
    in ImageGridItem (created by StoryPromo)
    in div (created by Context.Consumer)
    in StyledComponent (created by StoryPromoWrapper)
    in StoryPromoWrapper (created by StoryPromo)
    in StoryPromo (created by StoryPromo)
    in StoryPromo
    in RequestContextProvider
    in ServiceContextProvider
```

Otherwise looks good :)

**Comment by sareh** [comment]
@oluoluoxenfree  It was originally just to fix the `RequestProviderContext` errors. ~I can expand the scope to fix the other errors too.~ Keeping the scope of this PR to be just to fix the current mentioned in the issue.

**Review by oluoluoxenfree — APPROVED** [review]
In that case looks good to me! Good work

**Review by Bopchy — APPROVED** [review]
Looks good 👍

**Comment by jamesbrumpton** [comment]
Once Jenkins passes, this can be merged.

**Pull request merged**
