### PR TITLE
Media page get data from Ares and stop serving fixture data

### LINKED ISSUE #3114: Remove data/ from RPM pack/
**Is your feature request related to a problem? Please describe.**
When Ares can return liveradio data we should remove the data/ from the RPM pack/. 

**Describe the solution you'd like**
Revert https://github.com/bbc/simorgh/issues/3113

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: no QA required

**Additional context**
This should just be a simple revert when the data is available

### LINKED ISSUE #3377: Remove support for `/afaanoromoo/bbc_oromo_radio/*`
**Is your feature request related to a problem? Please describe.**
We have some remapping logic in the getInitalData() for the media page and in the media page routing for `bbc_oromo_radio` support. This support is no longer needed. 

**Describe the solution you'd like**
Remove support for `bbc_oromo_radio`.

**Describe alternatives you've considered**
N/A

- ~[ ] This feature is expected to need manual testing.~

**Additional context**

### PR DESCRIPTION
**Pull request by pjlee11**
Resolves #3377
Resolves #3114
Part of #3330

**Overall change:** 

1) Reverts #3115 (remove `data/` from files used to build RPM)
2) Removes support for `bbc_oromo_radio`
3) Fetch data from basePath rather than localhost, therefore fetch from Ares on Test and Live

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- ~[ ] This PR requires manual testing~

### CODE REVIEW

**Review by chris-hinds — APPROVED** [review]

**Comment by pjlee11** [comment]
Mozart work needs to be done before this is merged. 

Update: PRs linked from https://github.com/bbc/simorgh/issues/3330

**Review by jamesbhobbs — CHANGES_REQUESTED** [review]
Blocked on making data available in test env

**Review by dr3 — CHANGES_REQUESTED** [review]
Need to stop data being served in server index

**Comment by pjlee11** [comment]
Blocked on https://github.com/bbc/mozart-routing/pull/916

**Comment by pjlee11** [comment]
Unblocked as bbc/mozart-routing#916 has been merged

**Review by dr3 — APPROVED** [review]

**Review by jamesbhobbs — APPROVED** [review]

**Pull request merged**
