### PR TITLE
Add Korean translations for 500 and 404 pages

### LINKED ISSUE #3287: Add translations for error pages for 4 live radio v1 services
**Is your feature request related to a problem? Please describe.**
We need to add the cookie / privacy banner translations for the 4 live radio v1 services

- Afaan Oromoo
- Amharic 
- Indonesia
- Korean 

**Describe the solution you'd like**
Add the translations to the service configs. Translations available on spreadsheet (pinned in ws-media slack channel or WSMEDIA-87)

**Testing notes**
[Tester to complete]

Dev insight: Unlikely to need a tester due to simplicity

**Additional context**
WSMEDIA-87

### PR DESCRIPTION
**Pull request by jroebu14**
Resolves https://github.com/bbc/simorgh/issues/3287

**Overall change:** Adds Korean translations for 500 and 404 pages.

**Code changes:**

- Added 500 and 404 translations to `src/app/lib/config/services/korean.js`

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

**Testing notes**

To observe the 404 error page
- go to http://localhost.bbc.com:7080/afaanoromoo/bbc_korean_radio/blah

To observe the 500 error page
- add `status = 500` here https://github.com/bbc/simorgh/blob/404Handling/src/app/routes/getInitialData/utils/fetchData/index.js#L16
- go to http://localhost.bbc.com:7080/korean

Translations can be verified here https://docs.google.com/spreadsheets/d/1IE6dvHfOJhYTIhC0kg8aRGnaj3fEg1NH9jQwo5NuUDQ/edit#gid=0

### CODE REVIEW

**Review by dr3 — APPROVED** [review]
Dont speak korean but LGTM assuming translations are tested before merge

**Review by Bopchy — APPROVED** [review]

**Comment by LilyL0u** [comment]
For the translation of the section 'Alternatively, please visit the [BBC News [service] homepage]' for 404 and 500 errors.

The word Korea is repeated twice, where it is not repeated in the translation document:

The page says 'BBC News 코리아 코리아 홈페이지를 방문해보세요' with the '코리아' repeated. The first word is part of the link 'BBC News Korea', the second one just says Korea again after the link.

The translation document says 'BBC News 코리아 홈페이지를 방문해보세요 ' without 코리아 repeated.

All other text fine.

**Comment by jroebu14** [comment]
@LilyL0u great spot! thanks

**Comment by LilyL0u** [comment]
Repeated word 'Korea'/'코리아' removed.

**Pull request merged**
