### PR TITLE
Move test service config

### LINKED ISSUE #2213: Move `src/app/lib/config/services/index.js` as it's not production code
**Is your feature request related to a problem? Please describe.**
Based on [this comment](https://github.com/bbc/simorgh/pull/2204/files#diff-8ceb5979c2ed1e22234d75af339bf68aR2) the file `src/app/lib/config/services/index.js` should be moved under `/app/testHelpers/` and all it's references updated. This is good house keeping. 

**Describe the solution you'd like**
Move `src/app/lib/config/services/index.js` under `/app/testHelpers/` and update all it's references.

**Describe alternatives you've considered**
Leave it where it is, which isn't good practice. 

**Testing notes**
[Tester to complete]

Dev insight: The unit tests passes cover all testing. 

**Additional context**
Follows up https://github.com/bbc/simorgh/pull/2204/

### PR DESCRIPTION
**Pull request by thekp**
Resolves #2213

**Overall change:** _move service config index file to /testHelper so that it is out of the application._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by FK78 — APPROVED** [review]

**Review by rhenshaw56 — COMMENTED** [review]
@thekp there's a conflict on this pr

**Review by FK78 — APPROVED** [review]

**Review by rhenshaw56 — APPROVED** [review]

**Comment by rhenshaw56** [comment]
@thekp more conflicts

**Review by dr3 — APPROVED** [review]

**Pull request merged**
