### PR TITLE
Chartbeat domains fix for LIVE env (Turkce, Indonesia, Portuguese)

### LINKED ISSUE #5736: Chartbeat not working on https://www.bbc.com/indonesia (and other sites)
**Is your feature request related to a problem? Please describe.**
Chartbeat is not working for the site :https://www.bbc.com/indonesia . If you use the chartbeat HUD you get a error message. Looking at the beacon we are setting the chartbeat host as indonesia.bbc.co.uk

The following may also have the same problem:
https://www.bbc.com/turkce ->  turkish.bbc.co.uk
https://www.bbc.com/portuguese -> brasil.bbc.co.uk

**Describe the solution you'd like**
Looking at a current PAL page, the chartbeat beacon should set the host as indonesian.bbc.co.uk. The beacon value needs to be updated to reflect this 

**Describe alternatives you've considered**
None

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
You can see the current behavior on the live pal homepage to compare the values sent by the chartbeat beacon on the old vs new pages.  If the fix has worked, the HUD should work on the new index.

### PR DESCRIPTION
**Pull request by sareh**
Resolves #5736

**Overall change:** 
Ensures chartbeat domain is correct for indonesia, turkce and portuguese by putting value in service config and not constructing from the service name.

Ensures chartbeat domain is `test.bbc.co.uk` for local, test, stage environment.

**Code changes:**
- Adds service config parameter `chartbeatDomain` with *correct* domains for all services.
- Uses these for the live environment.
- Ensures chartbeat domain remains `test.bbc.co.uk` for local, test, stage environment.

**Testing notes**
Instructions to install the Chartbeat HUD (browser extension) 
https://chartbeat.zendesk.com/hc/en-us/articles/115001293233-Install-the-Heads-Up-Display-HUD-
You can run this on a PAL site and see the domain value being the same as in the chartbeatDomain values in the PR. 

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by tochwill — APPROVED** [review]

**Review by rhenshaw56 — APPROVED** [review]

**Review by rhenshaw56 — COMMENTED** [review]
can we confirm most of these are already setup on the chartbeat dashboard ? can't find one for `naidheachdan`

**Comment by PriyaKR** [comment]
Testing it locally shows the host value as 'test.bbc.co.uk' also as per discussion looks like it can't be tested on locally.

**Comment by PriyaKR** [comment]
> can we confirm most of these are already setup on the chartbeat dashboard ? can't find one for `naidheachdan`

@sareh  this can be merged as this cannot be tested locally and also @rhenshaw56 has left a comment.

**Comment by sareh** [comment]
@rhenshaw56 I've asked @JonBeeb to add the list of domains to the ticket: https://github.com/bbc/simorgh/issues/5736#issuecomment-593900732
You're right, scotland, archive and naidheachdan domains are not on the list. I've confirmed with @jimjohnsonrollings that we can use `bbc.co.uk` for these, so I've just pushed an update for these. 
cc @PriyaKR

**Pull request merged**
