### PR TITLE
Fix word wrap issue - Story Promo

### LINKED ISSUE #6085: Burmese Top Stories layout on live is overlapping
**Describe the bug**

On the Burmese front page, for breakpoints 1008px+ (desktop layout) if there is a Headline that is long and doesn't have a space, it stretches out the image as well, leading to this overlap.

Screenshot 2020-04-03 at 09 31 42

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/burmese.amp or https://www.bbc.com/burmese in Firefox on a device that is greater than 1008px wide
2. Scroll down to Top Stories row 2
4. See overlapping story promos

**Expected behaviour**
No overlapping.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser Firefox nightly Version 76.0a1 & Firefox v74

Can not replicate in Chrome or Safari.

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by chewu**
Resolves https://github.com/bbc/simorgh/issues/6085

**Overall change:**
On the Burmese front page, for breakpoints 1008px+ (desktop layout) if there is a Headline that is long and doesn't have a space, it stretches out the image as well, leading to this overlap.

**Code changes:**
Update the const Link to add the new css.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by chewu** [comment]
TESTING:
Select any story promo and edit the text to remove any spaces between each word. I have attached screengabs for comparison.

Current Live:
Screenshot 2020-08-10 at 14 37 44

Dev/localhost:
Screenshot 2020-08-10 at 14 39 52

**Review by rhenshaw56 — APPROVED** [review]

**Review by chris-hinds — APPROVED** [review]
LGTM would be worth a quick regression test to ensure this doesn't affect other breakpoints in a negative way.

**Comment by paruchurisilpa** [comment]
Waiting for Che to resolve conflicts to test this...

**Comment by paruchurisilpa** [comment]
Looks good to me..Did regression and didn't notice any visual issues. Also added a long headline without spaces to ensure its not broken..

**Pull request merged**
