### PR TITLE
WSTEAM1-354: Make sure latest media appears second

### PR DESCRIPTION
**Pull request by shayneahchoon**
Resolves JIRA [number]

Overall changes
======
Changes styling to put latest media in front of related content sections. 

Screenshot 2023-04-17 at 10 21 29
Screenshot 2023-04-17 at 10 21 45
Screenshot 2023-04-17 at 10 21 57

Code changes
======

- _CSS changes on latest media page_

Testing
======
1. _List the steps used to test this PR._

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

### CODE REVIEW

**Comment by amoore108** [comment]
Looks good! I think the Latest Media section needs to appear below the Topics Tags when on Tablet/Mobile, so sitting between Topics Tags and Related Content.

**Review by HarveyPeachey — COMMENTED** [review]
I don't think we can use the order method as screen reader order would break based on the visual layout, so the page would compromise on accessibility as per your commit message. We probably have to go down the route of duplicating components and then removing the component/hiding it when it reaches the mobile breakpoint, and vice versa on other breakpoints. @greenc05 What's the best practice for re-ordering of elements based on breakpoints?

**Comment by greenc05** [comment]
@HarveyPeachey best practice would be not to re-order between breakpoint, have we spoken to UX @shayneahchoon is this absolutly necessary? Definatitly shouldn't use 'order' and duplicating componenets isn't good for page size...

**Comment by shayneahchoon** [comment]
Heya, alternative solution is here, which dynamically re-orders the components by applying a window resize listener to the app: https://github.com/bbc/simorgh/pull/10782

**Comment by amoore108** [comment]
@shayneahchoon Just thinking now that we're letting the 'Latest Media' follow the same UI flow as the 'Top Stories' and 'Features + Analysis' components, do we need to do this anymore? Shouldn't the 'Latest media' component just work if its put into the SecondaryColumn component?

**Comment by shayneahchoon** [comment]
Soz, yeah this PR isn't needed anymore I'm closing it.

**Pull request closed without merging**
