### PR TITLE
Add default brand image for ws services

### LINKED ISSUE #1791: Insert default brand image for WS services
**Is your feature request related to a problem? Please describe.**
We need a default image for our 3 new WS simorgh services

**Describe the solution you'd like**
Into config, like [existing services](https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/persian.js#L8) add the following images under the key `defaultImage`

https://news.files.bbci.co.uk/ws/img/logos/og/igbo.png
https://news.files.bbci.co.uk/ws/img/logos/og/yoruba.png
https://news.files.bbci.co.uk/ws/img/logos/og/pidgin.png

**Testing notes**
[Tester to complete]

Dev insight: None, this wont work yet due to its use in metadata

### PR DESCRIPTION
**Pull request by ghost**
Resolves #1791 

**Overall change:** Add default images link to `yoruba`, `pidgin` and `igbo` service configs
**Code changes:**

- Add `defaultImage` key to `yoruba`, `pidgin` and `igbo` service configs.

---

- [x]  I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by DenisHdz — COMMENTED** [review]
LGTM, but we could also add the `defaultImageAltText` for the three services

**Comment by ghost** [comment]
Will that be the same as `serviceName` or `brandName`?

**Comment by DenisHdz** [comment]
> Will that be the same as `serviceName` or `brandName`?

I believe `brandName`

**Comment by ghost** [comment]
Am not so sure about that. Maybe we can ask around if we really need `defaultImageAltText`.

**Comment by DenisHdz** [comment]
> Am not so sure about that. Maybe we can ask around if we really need `defaultImageAltText`.

Sure, but I can see it is used in the [Metadata](https://github.com/bbc/simorgh/blob/latest/src/app/components/Metadata/index.jsx#L89) and the Persian is using the [brandname](https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/persian.js#L9).

**Review by dr3 — DISMISSED** [review]

**Review by DenisHdz — DISMISSED** [review]
LGTM 👍

**Review by chris-hinds — DISMISSED** [review]
LGTM, A nice future enhancement would be to move `https://news.files.bbci.co.uk` to its own static const e.g. `STATIC_ASSETS_BASE=https://news.files.bbci.co.uk` and then use that to construct these urls.

**Comment by ghost** [comment]
Closing in favour of #1848. I could not determine why the Jenkins pipeline was failing.

**Pull request closed without merging**
