### PR TITLE
Resolves issue with mismatch of client and server propNames

### LINKED ISSUE #9613: Mismatch of Client and Server in propNames upon page loading
**Describe the bug**

This issue is related to the point raised in this issue https://github.com/bbc/simorgh-infrastructure/issues/1486:
'the Emotion cache is initialised on every request. Not sure if this is intentional or not. We also do not use the cache on the client side. Again, not sure if there is a reason for this.'

React expects that the rendered content is identical between the server and the client. Currently we have an issue where there is a mismatch between our `propNames` between client and server and it is believed to be linked to the Emotion cache.

 It can patch up differences in text content, but you should treat mismatches as bugs and fix them. In development mode, React warns about mismatches during hydration. There are no guarantees that attribute differences will be patched up in case of mismatches. This is important for performance reasons because in most apps, mismatches are rare, and so validating all markup would be prohibitively expensive.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'localhost:7080/pidgin'
2. Right Click and 'inspect' to bring up the console 
3. See that there is a mismatch of propNames in the console window

**Expected behaviour**
N/A - fix already created but there should be no mismatch of our propNames

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: iOS Big Sur 11.6
- Browser Chrome
- Version 94.0.4606.81

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

### PR DESCRIPTION
**Pull request by pvaliani**
Resolves #9613 

**Overall change:**
Imports the emotion cache to fulfill correct hydration of server-side transpiled JS to client to prevent a mismatch

**Code changes:**

As above

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by jroebu14 — APPROVED** [review]
Thanks for this!

**Review by nicola-d-bbc — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]
👍  Nice one - this was an annoying warning

**Comment by LilyL0u** [comment]
To test this, do I check out the branch and follow the reproduction steps to check the error is no longer there?

'Steps to reproduce the behaviour:

    Go to 'www.bbc.com/pidgin'
    Right Click and 'inspect' to bring up the console
    See that there is a mismatch of propNames in the console window'

**Comment by pvaliani** [comment]
> To test this, do I check out the branch and follow the reproduction steps to check the error is no longer there?
> 
> 'Steps to reproduce the behaviour:
> 
> ```
> Go to 'www.bbc.com/pidgin'
> Right Click and 'inspect' to bring up the console
> See that there is a mismatch of propNames in the console window'
> ```

Sorry I missed this. Yes that is correct. I'm not sure what else could be done to test it? @jroebu14 may perhaps have an idea.

**Comment by LilyL0u** [comment]
The error is not showing in the console on this branch:


Screenshot 2021-11-02 at 14 09 49

Compared to running locally on latest where we can see the error:
Screenshot 2021-11-02 at 14 12 09

**Pull request merged**
