### PR TITLE
Updates mediaType to prevent visually hidden text from appearing on a new line 

### LINKED ISSUE #9559: Screen Reader - StoryPromo component reads out "comma"
**Describe the bug**
For screen readers, we have a visually hidden element to give users more context when the story promo is displaying a media item.  We insert a comma into this element to coerce screen readers to pause.

However, some screen readers (at least Jaws and Talkback) read out "comma" rather than pausing. Lets check all [supported screen readers](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing.html)

This is likely due to the comma being a separate text node within the element

Screen Shot 2021-10-18 at 12 46 00

### PR DESCRIPTION
**Pull request by pvaliani**
Resolves #9559

**Overall change:**
Updates bug in `mediaType` to prevent visually hidden text from appearing on a new line - resolves screen reader issue with reading out comma aloud

**Code changes:**

As above/see files changes
---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by paruchurisilpa** [comment]
Checked using http://localhost:7080/amharic/articles/czqverekrldo on NVDA and JAWS . The comma is not being read out..

**Review by ryanmccombe — APPROVED** [review]
🥳

**Review by emilysaffron — COMMENTED** [review]
checked on /pidgin/58228654 using:
iphone 12 safari iOS 14.8
macbook pro on chrome 
voiceover works on both without reading out the comma 👍

**Comment by DarioR01** [comment]
Checked on: /pidgin/articles/c1x0rq3r97ko
Samsung A5 2017 Android 8.0.0
TalkBack works without reading the comma 👍

**Review by nicola-d-bbc — APPROVED** [review]
LGTM!

**Comment by DarioR01** [comment]
Retesting on TalkBack to check if changes to remove unwanted changes on integration tests snapshots reintroduced the original bug:
Pending

**Comment by paruchurisilpa** [comment]
This has been a11y tested and @DarioR01 fixed the issue with updating the snapshots which caused the spacing between commas and words to be different .. Ready to be merged now..

**Pull request merged**
