### PR TITLE
Update Section Label to use correct colour in secondary column

### LINKED ISSUE #6587: Update Section Label to use correct colour in secondary column
### Is your feature request related to a problem? Please describe.
Titles in the secondary column are created using `psammead-section-label`, which uses a link a colour (EBON). When used in the secondary column, these are not links and therefore should use `#3F3F42` (SHADOW).

### Describe the solution you'd like
- Update `psammead-section-label` component to use colour EBON _if the section label is a link_ and SHADOW if it's not.
- Ensure this change reflects correctly in the secondary column.

Note: This may require raising a Psammead issue. Whoever picks this up can create this if it's needed.

### Describe alternatives you've considered
n/a

### Testing notes
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.
- [x] This feature is expected to have a UX review.

### Additional context
n/a

### PR DESCRIPTION
**Pull request by FK78**
Resolves #6587

**Overall change:**
_Update Section Label to use correct colour in secondary column._

**Code changes:**

- _Update `@bbc/psammead-section-label` to 5.0.7._
- _Update snapshots._

Screenshot 2020-06-11 at 13 40 11

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by andrewscfc — APPROVED** [review]
Checked on Storybook in Features and Analysis, looking good 🚢

**Review by simonsinclair — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
LGTM..

**Comment by amywalkerdev** [comment]
Need to check if this is OK with the home team colours as it affects them too

**Comment by amywalkerdev** [comment]
Good from our side, we're happy to keep things consistant 😄

**Pull request merged**
