### PR TITLE
Update ichef locator for portrait videos

### LINKED ISSUE #2171: Update Ares ichef locators for portrait ratios for video
**Is your feature request related to a problem? Please describe.**
Currently, Ares is populating the `locator` field for image placeholder assets from `mpv`.

For Landscape-oriented images, this is of the following format: 
`"ichef.test.bbci.co.uk/images/ic/$recipe/p01k6mtv.jpg",`
For portrait images it is currently the same. 

In this ticket we should update to use the format `$widthxn`
`"ichef.test.bbci.co.uk/images/ic/$widthxn/p01mxrbn.jpg",`

**Describe the solution you'd like**
We have requested Ares to update the locators that they provide us on the Test & Live environments. 

**Tasks:**
- We should ensure that our fixture data reflects this `$widthxn` for Portrait placeholders only. Add fixture data in the `data/test/news/articles/`
- Ensure that fixture data within the AudioVideo container includes the correct portrait locator. 
- We should ensure our Image placeholder for video reflects the designs in our Zeplin documentation.

**Describe alternatives you've considered**
We explored this option but discussed against it:
- We update the value ourselves in a preprocessor step - when type of media `portrait`.

Ticket blocked on https://github.com/bbc/simorgh/pull/2151

**Testing notes**
[Tester to complete]

Dev insight: Updating fixture data. Unit tests should be sufficient. Manually viewing a portrait video example in the browser.
Only testing localhost. It will be broken on Test and Live environments until this is complete: https://github.com/bbc/simorgh/issues/2198 

**Additional context**

### PR DESCRIPTION
**Pull request by twinlensreflex**
Resolves #2171 

**Overall change:** 
Update Ares ichef locators for portrait ratios for video 

**Code changes:**

- Change `$recipe` to `$widthxn` in locator to get responsive placeholder images
- Snapshot updates
---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by jamesdonoh** [comment]
Just wondering, does `c0000000031o` need updating too?

**Comment by twinlensreflex** [comment]
> Just wondering, does `c0000000031o` need updating too?
`c0000000031o` had already been done, I think Sareh did it as part of the work we were doing on responsive AV.

**Review by jamesdonoh — APPROVED** [review]

**Review by 12 — APPROVED** [review]

**Comment by 12** [comment]
Assigning this to myself (despite code reviewing) in the event this fails to pass test.

**Comment by jamesbrumpton** [comment]
We do not have a way to test this right now due to video logic being removed. However, rather than this logic getting stale we'll merge now and test once we've implemented the AV logic back in.

**Pull request merged**
