### PR TITLE
Integrate main content with article component

### PR DESCRIPTION
**Pull request by briankabiro**
Need updating (or restarting) to match: #221

_Integrates the Main Content component with article component_

* [x] Fixes https://github.com/bbc/simorgh/issues/115
* [x] Tests added for new features

* [n/a] Test engineer approval

### CODE REVIEW

**Comment by thekp** [comment]
^ the duplication highlighted by CodeClimate is because we are passing static data from the Article to MainContent. This will not be an issue when we using real data feeds.

**Comment by jamesbhobbs** [comment]
@briankabiro we forgot to mention something critical for this repo which means we won't look at this PR yet. It has been branched from https://github.com/bbc/simorgh/pull/221/files The rule of this repo is that this must never be done. This is now blocked because the aforementioned branch isn't mergeable. This leads to wasted time and effort updating this branch.

Stated more positively we only ever branch from latest in order to maintain maximal productivity

We will merge the other branch and pick this one up later.

**Comment by pjlee11** [comment]
@benjaminhobbs that'll be my fault as I suggested this issue to look at following myself, @thekp and @briankabiro having get the other PR into code review and being a good task to be completed in an afternoon. In theory both pieces of work could (probably should) have been a single task and therefore a single PR.

**Comment by jtart** [comment]
Closed this PR as it is simpler to just start another PR and cherry-pick in the changes now it is unblocked.

**Pull request closed without merging**
