### PR TITLE
Dependency updates - all dependabot PRs combined

### PR DESCRIPTION
**Pull request by j-pendlebury**
Combines:

1. https://github.com/bbc/simorgh/pull/5113  Bump @storybook/theming from 5.2.8 to 5.3.0
2. https://github.com/bbc/simorgh/pull/5112  Bump @bbc/gel-foundations from 3.4.1 to 3.4.2
3. https://github.com/bbc/simorgh/pull/5111  Bump @loadable/component from 5.11.0 to 5.12.0
4. https://github.com/bbc/simorgh/pull/5110  Bump @storybook/react from 5.2.8 to 5.3.0
5. https://github.com/bbc/simorgh/pull/5109  Bump compression-webpack-plugin from 3.0.1 to 3.1.0
6. https://github.com/bbc/simorgh/pull/5108  Bump @bbc/psammead-grid from 1.1.0 to 1.1.1
7. https://github.com/bbc/simorgh/pull/5107  Bump @babel/core from 7.7.7 to 7.8.0
8. https://github.com/bbc/simorgh/pull/5106  Bump @babel/preset-env from 7.7.7 to 7.8.0
9. https://github.com/bbc/simorgh/pull/5105  Bump @babel/plugin-transform-runtime from 7.7.6 to 7.8.0
10. https://github.com/bbc/simorgh/pull/5104  Bump husky from 3.1.0 to 4.0.6
11. https://github.com/bbc/simorgh/pull/5103  Bump @loadable/babel-plugin from 5.11.0 to 5.12.0
12. ~https://github.com/bbc/simorgh/pull/5102  Bump eslint-plugin-import from 2.18.2 to 2.20.0~ left as `2.18.2` and pinned since the new version breaks our imports
13. https://github.com/bbc/simorgh/pull/5101  Bump @babel/plugin-proposal-object-rest-spread from 7.7.7 to 7.8.0
14. https://github.com/bbc/simorgh/pull/5100  Bump @babel/runtime from 7.7.7 to 7.8.0
15. https://github.com/bbc/simorgh/pull/5099  Bump @babel/polyfill from 7.7.0 to 7.8.0
16. https://github.com/bbc/simorgh/pull/5098  Bump @babel/preset-react from 7.7.4 to 7.8.0
17. https://github.com/bbc/simorgh/pull/5097  Bump core-js from 3.6.1 to 3.6.3
18. https://github.com/bbc/simorgh/pull/5096  Bump @storybook/addon-knobs from 5.2.8 to 5.3.0
19. https://github.com/bbc/simorgh/pull/5095  Bump @loadable/server from 5.11.0 to 5.12.0
20. https://github.com/bbc/simorgh/pull/5094  Bump @loadable/webpack-plugin from 5.7.1 to 5.12.0
21. https://github.com/bbc/simorgh/pull/5093  Bump @babel/plugin-proposal-throw-expressions from 7.7.4 to 7.8.0
22. ~https://github.com/bbc/simorgh/pull/5092  Bump @bbc/psammead-bulleted-list from 1.0.0 to 1.0.1~ already updated
23. https://github.com/bbc/simorgh/pull/5091  Bump terser-webpack-plugin from 2.3.1 to 2.3.2

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) - ran all page type tests, but not for all services  
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by j-pendlebury** [comment]
Had to pin the version of `"eslint-plugin-import"` to `2.18.2`, because the newer version breaks our imports, e.g.

```
simorgh/src/app/containers/ArticleMain/index.stories.jsx
11:25  error  Missing file extension "json" for "../../../../data/news/articles/c5jje4ejkqvo"  import/extensions
```

**Comment by j-pendlebury** [comment]
Issue for bumping `eslint-plugin-import` https://github.com/bbc/simorgh/issues/5156

**Review by oluoluoxenfree — APPROVED** [review]

**Comment by amywalkerdev** [comment]
This has not updated:
@loadable/component from 5.11.0 to 5.12.0

**Comment by j-pendlebury** [comment]
> This has not updated:
> @loadable/component from 5.11.0 to 5.12.0

All fixed now @amywalker1987

**Review by amywalkerdev — APPROVED** [review]
👍

**Comment by PriyaKR** [comment]
Regression looks good to me.

**Pull request merged**
