### PR TITLE
Use latest WS SVGs

### LINKED ISSUE #2730: Add branding to all WS sites in Simorgh
**Is your feature request related to a problem? Please describe.**
As a product owner who is thrilled that all the WS home pages are available on TEST, I think it might be beneficial to have the correct service branding in place on all of them, so the sites are more representative of production.

**Describe the solution you'd like**
I would like the service specific branding to be added to all the WS sites in Simorgh. Since they all say BBC News already, out of the box. I'd like to have the service names added to what's there already, rather than have the whole thing replaced, so that when we need to have BBC News in Reith we only need to change one SVG and not 41.

**Describe alternatives you've considered**
Not doing it, and adding each branding shortly before each site goes live.

### PR DESCRIPTION
**Pull request by sareh**
Resolves #2730

**Overall change:** Use latest World Service SVGs (for all apart from Telugu, Ukrainian and Uzbek, which will be updated in a future PR https://github.com/bbc/psammead/pull/1759)

**Code changes:**

- Use latest svgs from @bbc/psammead-assets & import the svgs into service configs
- Update snapshots 

Thai:
Screen Shot Thai brand and navigation

Punjabi:
Screen Shot Punjabi

Amharic:
Screen Shot Amharic

Tigrinya:
Screen Shot Tigrinya

~CI is currently failing on a check to prevent multiple versions of a dependency from being loaded. I'm not going to pull in all of the dependency updates in this PR (over a dozen), since there is already a PR that is doing this #3030. Once that is merged, I'll pull in latest and that should address the dependency error.
Blocked on this PR: https://github.com/bbc/simorgh/pull/3030~ Now unblocked. 

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by sareh** [comment]
These SVGs have been reviewed by Laura in the UX team and approved.

**Comment by andrew-nowak** [comment]
~~Seems to be missing~~
~~- uzbek~~
~~- telugu~~
~~- naidheachdan~~
~~- cymrufyw~~
~~- ukrainian~~
Addressed below

**Comment by DenisHdz** [comment]
> Seems to be missing uzbek?

Also Bengali, Telugu and Ukrainian?

**Comment by sareh** [comment]
@aacn500 @DenisHdz Yes those three SVGs will be updated in a future Psammead PR (https://github.com/bbc/psammead/pull/1759) - since they need renaming in psammead and bumping several dependencies. Didn't want that to hold up the Thai/Punjabi work.

**Review by DenisHdz — APPROVED** [review]
Good stuff 👍

**Review by andrew-nowak — APPROVED** [review]
sounds good to me

**Review by EinsteinNjoroge — APPROVED** [review]
LGTM

**Comment by sareh** [comment]
This work has already been Accessibility reviewed (with high contrast mode on IE and Firefox changing colours) and UX reviewed with Laura.

**Comment by jamesdonoh** [comment]
Force merging due to Travis hanging.

**Pull request merged**
