### PR TITLE
Temporary Removal of Yarn's Dependancy Cache

### PR DESCRIPTION
**Pull request by HarveyPeachey**
Resolves N/A

**Overall change:**
Due to cache files being pulled in, it can make it difficult for the Dev experience when it comes to code reviews, especially when PR's become hundreds of files changed. This is a temporary measure, to figure out the best way to implement the offline cache so that PR's don't become ridiculously massive.

**Code changes:**

- Deletes the `.yarn/cache` directory from source control
- Comments out `.yarn/cache` exclusion in `.gitignore`

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by MuhammadAHussain** [comment]
Do we also need to remove/comment out the step from Github workflows in unit tests?

**Comment by HarveyPeachey** [comment]
> Do we also need to remove/comment out the step from Github workflows in unit tests?

Nope. It basically means yarn just has to pull all the packages from NPM every time (which is what it had to do before), but looking at the workflows it looks like there's a `node_modules` caching step anyway which I was unaware of.

**Review by DarioR01 — COMMENTED** [review]
This change is creating some Lint warnings in some of the files, is that suppose to happen?

**Comment by HarveyPeachey** [comment]
> This change is creating some Lint warnings in some of the files, is that suppose to happen?

Which files? All this is doing is adding a commented line to the `.gitignore` file

**Comment by MuhammadAHussain** [comment]
> > Do we also need to remove/comment out the step from Github workflows in unit tests?
> 
> Nope. It basically means yarn just has to pull all the packages from NPM every time (which is what it had to do before), but looking at the workflows it looks like there's a `node_modules` caching step anyway which I was unaware of.

Sorry, should've clarified. I was referring to the `node_modules` caching step, I thought it was using the yarn cache folder but that isn't the case.

**Review by MuhammadAHussain — APPROVED** [review]
LGTM 👍

**Comment by DarioR01** [comment]
> > This change is creating some Lint warnings in some of the files, is that suppose to happen?
> 
> Which files? All this is doing is adding a commented line to the `.gitignore` file

One example:
.storybook/buildFontPreloads.test.js

If you scroll down the files changed there is a section with Unchanged files with check annotation, I don't know if this has to do with this PR to be honest.
58EF40EF-356F-4E21-BC12-3C9E8E9DB8F9

**Comment by HarveyPeachey** [comment]
> One example:
> .storybook/buildFontPreloads.test.js
> 
> If you scroll down the files changed there is a section with Unchanged files with check annotation, I don't know if this has to do with this PR to be honest.

Ahh yep, so this is a new thing GitHub introduced, which is currently in beta. It tries to automatically point out linting issues. But this will show up in every PR, see at the top it says 'Unchanged files with check annotations', so the changes in this PR aren't causing those. Some of those warnings maybe relevant, others not like the console logging in some of the files.

Maybe you could write up an issue to investigate these linting warnings that GitHub is outputting? You don't necessarily have to do the investigation, just write up the brief details for what needs to be looked at.

**Comment by DarioR01** [comment]
> > > Do we also need to remove/comment out the step from Github workflows in unit tests?
> > 
> > 
> > Nope. It basically means yarn just has to pull all the packages from NPM every time (which is what it had to do before), but looking at the workflows it looks like there's a `node_modules` caching step anyway which I was unaware of.
> 
> Sorry, should've clarified. I was referring to the `node_modules` caching step, I thought it was using the yarn cache folder but that isn't the case.

**Comment by DarioR01** [comment]
> > One example:
> > .storybook/buildFontPreloads.test.js
> > If you scroll down the files changed there is a section with Unchanged files with check annotation, I don't know if this has to do with this PR to be honest.
> 
> Ahh yep, so this is a new thing GitHub introduced, which is currently in beta. It tries to automatically point out linting issues. But this will show up in every PR, see at the top it says 'Unchanged files with check annotations', so the changes in this PR aren't causing those. Some of those warnings maybe relevant, others not like the console logging in some of the files.
> 
> Maybe you could write up an issue to investigate these linting warnings that GitHub is outputting? You don't necessarily have to do the investigation, just write up the brief details for what needs to be looked at.

Oh that looks great, me is also gonna send a complain to GitHub to have put the close with comment button next to comment :D

**Review by DarioR01 — APPROVED** [review]
LGTM

**Pull request merged**
