### PR TITLE
Package Bump to support Nepali numerals.

### PR DESCRIPTION
**Pull request by RayNjeri**
Signed-off-by: RayNjeri <rachael.njeri@andela.com>

Resolves #NUMBER

**Overall change:** _Bumps psammead-locales, psammead-calendars, psammead-timestamp-container packages inorder to get Nepali numerals working._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Review by HarveyPeachey — APPROVED** [review]
LGTM

**Review by 12 — APPROVED** [review]
LGTM 👍

**Review by jamesdonoh — APPROVED** [review]
Assuming change in numerals was agreed.

**Comment by RayNjeri** [comment]
> Assuming change in numerals was agreed.

Yes it was.

**Pull request merged**
