### PR TITLE
Remove Lighthouse from Simorgh

### PR DESCRIPTION
**Pull request by DemonusPC**
It was decided by the Simorgh core team that the Lighthouse tests should be ran in the CD pipeline. This means that the Travis tests are redundant and can be removed. (They were also giving wrong results) 
Since lighthouse requires Node version 10+ I had to remove lighthouse from simorgh to maintain the consistency. Otherwise developers would get inconsistent success/errors. 
 
**Code changes:**

- Removed redundant lighthouse commands
- Removed lighthouse from Travis
- Removed Lighthouse
- Removed lighthouse-ci

---

- [x] I have assigned myself to this PR and the corresponding issues
- ~[ ] Tests added for new features~
- [ ] Test engineer approval

### CODE REVIEW

**Review by chris-hinds — CHANGES_REQUESTED** [review]
As we are completely removing Lighthouse from this repo we should update the Readme to reflect these changes as Lighthouse is mentioned there.

**Review by chris-hinds — DISMISSED** [review]

**Comment by jamesdonoh** [comment]
Shouldn't this include an updated `package-lock.json`?

**Comment by DemonusPC** [comment]
@jamesdonoh I actually nuked simorgh and reinstalled from scratch and no changes were needed. So I guess no.

**Comment by jamesdonoh** [comment]
That doesn't make sense to me, surely lighthouse should no longer be in the package-lock.json after this PR?

**Comment by DemonusPC** [comment]
Alright let me try to rerun the installation step then

**Comment by chris-hinds** [comment]
> Alright let me try to rerun the installation step then

`npm uninstall <package_name>` should remove the package and remove it from both package.json and package-lock.json

**Review by chris-hinds — APPROVED** [review]
👍

**Review by jamesdonoh — APPROVED** [review]
OK to remove assuming we reinstate an equivalent process for local/CI using a consistent version of Lighthouse after we upgrade to Node 10.

**Pull request merged**
