### PR TITLE
Stop radio frequencies link covering entire page

### LINKED ISSUE #6000: Radio Schedules: Frequencies link takes over whole page
**Describe the bug**
The radio frequencies link has an absolute before psuedoelement that covers the entire page, as it is not contained within a relative element. There is no need for this before psuedoelement here.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to test.bbc.com/hausa?renderer_env=live
2. Click anywhere on the page where there isn't a link (for example, try to click the navigation drop-down button on mobile)
3. See error - you will be taken to the frequencies page.

**Expected behaviour**
The link should not have a before psuedoelement that covers the page.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by tochwill**
Resolves #6000

**Overall change:** 
We no longer use the Story Promo Link, as we had to override most of the styles from this component when using for the radio schedules link.

**Code changes:**
- Replaced `Link` with a styled a tag.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Review by Bopchy — APPROVED** [review]
Checked it out locally. Looks good 👍 

Sorry. Didn't realise this was still in Progress

**Comment by tochwill** [comment]
> Checked it out locally. Looks good 👍
> 
> Sorry. Didn't realise this was still in Progress

Sorry, I meant to put it back into Code Review - I accidentally caused an infinite loop in the useEffect so I closed the PR, removed my change that did that, and reopened (but didn't move back into review)

**Review by itimirichard — APPROVED** [review]
LGTM!

**Comment by PriyaKR** [comment]
Looks good locally.Can do a quick check when its on test.

**Pull request merged**
