### PR TITLE
What about this bump travis

### LINKED ISSUE #600: Bump package-lock to have the latest package dependencies
**Is your feature request related to a problem? Please describe.**
Currently the package-lock does not have the latest dependencies (and it differs via the npm version the local user is running to produce the package-lock)

**Describe the solution you'd like**
Update the package-lock

**Additional context**
There seems to be a Travis error with the latest dependencies pulled into the application.

### PR DESCRIPTION
**Pull request by pjlee11**
Resolves #600

This PR removes all local /node_modules and the package-lock.json and does a fresh npm install with node@8.11.4 and npm@6.4.1. Also tells Travis to use 6.4.1 via the .npmrc which also seems to fix the dot-notation problem eluded to here: 
https://github.com/bbc/simorgh/pull/601#issuecomment-418383523 (TL;DR the npm version seemed to cause black magic JS parsing issues)

- [x] Tests added for new features
- [x] Test engineer approval

### CODE REVIEW

**Review by radiocontrolled — APPROVED** [review]
👍

**Review by sareh — APPROVED** [review]

**Comment by jtart** [comment]
This needs a similar change in our Jenkins pipeline, so Jenkins can build using 6.4.1 too, else we will get potentially false results.

**Comment by sareh** [comment]
Blocked pending fix to Jenkins pipeline.

**Comment by pjlee11** [comment]
Unblocking and merging as currently Jenkins is running as 6.1 where the application wants to use 6.3. So merging 6.4.1 wouldn't actually be putting Jenkins out of sync with the application as it is already out of sync.

**Pull request merged**
