### PR TITLE
Upgrade to react 16.8.6 (current latest)

### PR DESCRIPTION
**Pull request by chris-hinds**
Resolves #380

**Overall change:** This PR updates our version of react from 16.7.0 to the current latests version 16.8.6

**Code changes:**

- Updated react version in package.json
- `npm install` which has updated the package-lock.json

---

**Testing Notes**

This PR is upgrading the version react to the current latest version. No code/features have changed, This PR will just require a regression.

- [X] I have assigned myself to this PR and the corresponding issues
- [N/A] Tests added for new features
- [ ] Test engineer approval
- [X] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by dr3 — DISMISSED** [review]
This also pulls in the grid fallback for story promo, but LGTM

**Comment by chris-hinds** [comment]
> This also pulls in the grid fallback for story promo, but LGTM

Spoke with @DenisBBC about this this morning, he was happy with it being pulled in.

**Review by DenisHdz — DISMISSED** [review]

**Review by 12 — DISMISSED** [review]

**Review by j-pendlebury — DISMISSED** [review]

**Comment by jamesbrumpton** [comment]
LGTM. Happy for this be merged.

**Comment by dr3** [comment]
@hindsc52 it has conflicts 😱

**Review by j-pendlebury — APPROVED** [review]

**Review by dr3 — APPROVED** [review]

**Pull request merged**
