### PR TITLE
Use semanticGroupName to define Radio Schedule position

### LINKED ISSUE #6314: Move Pashto radio schedule to sit above 'Interactivity'
**Is your feature request related to a problem? Please describe.**
The Pashto team would like to move the radio schedule on their front page to sit above the 'Interactivity' group.

**Describe the solution you'd like**
Move the Pashto radio schedule so it appears above the 'Interactivity group.

**Describe alternatives you've considered**
N/A

**Testing notes**

Dev insight: Add a screenshot to the PR description showing it is in the correct (updated) position

- [x] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves #6314

**Overall change:**
Use `semanticGroupName` to define the Radio Schedule position and update Pashto to sit above `Interactivity`

**Code changes:**
- Update services `frontPagePosition`

---

- [X] I have assigned myself to this PR and the corresponding issues
- [X] I have added labels to this PR for the relevant pod(s) affected by these changes
- [X] I have assigned this PR to the Simorgh project

**Testing:**

- [X] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [X] This PR requires manual testing

### CODE REVIEW

**Review by thekp — APPROVED** [review]
👍 lgtm

**Review by OlgaLyubin — APPROVED** [review]
Look good to me

**Review by itimirichard — APPROVED** [review]
Looks good to me.
Arabic - 
Screenshot 2020-04-27 at 11 04 07 AM

Pashto -
Screenshot 2020-04-27 at 11 05 11 AM

Korean -
Screenshot 2020-04-27 at 11 10 19 AM

**Comment by DenisHdz** [comment]
Updated Pashto Radio Schedule position to `Interactivity`

**Comment by PriyaKR** [comment]
This PR can be merged as several devs have tested it locally.

**Pull request merged**
