### PR TITLE
Revert Cypress version to 3.8.1

### PR DESCRIPTION
**Pull request by karinathomasbbc**
Due to issues running on Ubuntu, and failing cookie banner tests on Tigrinya

**Overall change:**
Downgrade Cypress from 4.4.0 to 3.8.1

**Code changes:**
- Update package.json

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added labels to this PR for the relevant pod(s) affected by these changes
- [ ] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by chris-hinds** [comment]
I think there were a load of api changes in cypress 4.4.0 and some of our tests were updated to reflect those changes @FK78 will no more.

Is it worth actually reverting that last PR?

**Comment by FK78** [comment]
> I think there were a load of api changes in cypress 4.4.0 and some of our tests were updated to reflect those changes @FK78 will no more.
> 
> Is it worth actually reverting that last PR?

Yep, I had to make a change, we need to revert that as well or we might have tests fail.

We should revert the last PR.

**Review by sareh — APPROVED** [review]

**Comment by karinathomasbbc** [comment]
We're going to revert https://github.com/bbc/simorgh/pull/5976 instead

**Comment by sareh** [comment]
@karinathomasbbc I tried reverting via github, but got this error message: 
Screensho
So if you could just update this PR with the changes, that would be useful.

**Pull request closed without merging**
