### PR TITLE
Dual timestamps for persian

### PR DESCRIPTION
**Pull request by rhenshaw56**
Updates persian locale to use dual timestamp from https://github.com/bbc/psammead/pull/1844

**Overall change:** Pass fa locale to persian service.

**Code changes:**

- Pass fa locale to persian service
- Updated version of psammead-locales
---
Screen Shot 2019-09-04 at 13 51 08

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by jamesdonoh — APPROVED** [review]
Thanks for opening 👍

**Comment by RayNjeri** [comment]
the screenshot above doesn't look right though everything else in the code seems just about right. shouldn't `august` be translated? cc: @jamesdonoh since you worked on the dual calendar in psammead

**Comment by jamesdonoh** [comment]
Good spot @RayNjeri, that doesn't look right. Investigating now.

**Comment by EinsteinNjoroge** [comment]
Should this timestamp be showing two different months? 
Screen Shot 2019-09-04 at 5 26 18 PM

**Comment by jamesdonoh** [comment]
@EinsteinCarrey which URL are you using?

**Comment by rhenshaw56** [comment]
> @EinsteinCarrey which URL are you using?

@jamesdonoh I think it's http://localhost:7080/persian/articles/c4vlle3q337o but google translated

**Comment by jamesdonoh** [comment]
OK, it's expected that they are different months because they are two different calendars (Gregorian and Jalaali). However the presence of an English month name after CSR spotted by @RayNjeri is not expected.

**Comment by jamesdonoh** [comment]
I think the issue described above affects multiple services, see https://github.com/bbc/simorgh/issues/3560

**Comment by jamesdonoh** [comment]
This has been updated to pull in `psammead-locales@2.2.2` which fixes the client-side rendering problem spotted by @RayNjeri above (see https://github.com/bbc/psammead/pull/2044 for details of fix). See screenshot below:

Screenshot 2019-09-06 at 14 42 16

**Review by dr3 — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
lgtm

**Review by dr3 — COMMENTED** [review]
@rhenshaw56  @jamesdonoh 146 stories failed to render.

**Comment by PriyaKR** [comment]
Looks good to me on articles and front page.Contains both Gregorian date and jalaali date.

But the simorgh storybook appears to be broken in IE11 thats why the chromaticQA tests are failing.

**Comment by jamesbrumpton** [comment]
lgtm

**Pull request merged**
