### PR TITLE
Update /news nav items

### LINKED ISSUE #5037: Update nav items for News
**Is your feature request related to a problem? Please describe.**
In order to not block releasing the nav on Articles, we need to ensure that the News nav contains up to date lists of links (and the Archive and Scotland navs contain no items)

**Describe the solution you'd like**
Update the /news service config with nav links to match nav on /news/newsbeat up to Video & Audio only.
NB. This is only enabled up to Test on Articles. That's fine.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by jimjohnsonrollings**
Resolves #5037 

**Overall change:** 
Adds some more nav items to the config for /news

**Code changes:**
- Adds nav items to the config for /news
- Updates snapshots

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Review by FK78 — APPROVED** [review]

**Review by HarveyPeachey — APPROVED** [review]
LGTM

**Review by sareh — APPROVED** [review]
👍 Looks good - links all render correctly 
Screenshot of navigation

**Review by FK78 — CHANGES_REQUESTED** [review]
Chromatic QA failing, component error for Radio Page.

`Error: Evaluation failed: TypeError: Cannot read property 'location' of undefined`

**Comment by jimjohnsonrollings** [comment]
> Chromatic QA failing, component error for Radio Page.

Previous change is being reverted which should resolve this.  Can wait and run the tests again once that's done.

**Review by FK78 — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Looks good to me..

**Pull request merged**
