### PR TITLE
Unit test to Front Page Main

### LINKED ISSUE #1800: Add unit tests to Front Page Main
**Is your feature request related to a problem? Please describe.**
The `FrontPageMain` doesn't have 100% test coverage.

**Describe the solution you'd like**
We should add unit tests with assertions (rather than snapshots) to the `FrontPageMain`.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests

**Additional context**

### PR DESCRIPTION
**Pull request by ghost**
Resolves #1800

**Overall change:** Add assertion tests on `FrontPageMain` container.
**Code changes:**

- Add assertion tests on sections and visually hidden text

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [x] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by dr3 — APPROVED** [review]
Simple nice to have, LGTM

**Review by j-pendlebury — APPROVED** [review]
Looks good to me 👍

**Comment by david-boydell** [comment]
Hi @sadickisaac, having checked out the branch `unit-test-frontpage-main`, when I run `npm run test:unit -- FrontPageMain` I get the error `Cannot find module 'core-js/modules/es.object.get-own-property-descriptor' from 'jest-setup.js'`

Is there something else I need to be doing?

image

**Comment by ghost** [comment]
@david-boydell `npm install` fixes that.

**Comment by david-boydell** [comment]
Thanks @sadickisaac, I'm finding fthat the tests are running but now failing.

I'm getting error messages along the lines of:

``` › 1 snapshot failed.
  console.error node_modules/prop-types/checkPropTypes.js:20
    Warning: Failed prop type: The prop `platform` is marked as required in `ImageComponent`, but its value is `undefined`.
```
Again, if there's something I'm doing wrong just let me know, I'm fairly new to the unit tests.

**Comment by ghost** [comment]
@david-boydell This warning is coming from `FigureContainer` which requires `platform` to be passed . However we are only interested in this test we only want to test if `FrontPageMain` renders the sections. If we were also testing that it displays the actual images in the container then the warnings above would have been an issue. For now we can ignore the warnings.

**Comment by david-boydell** [comment]
OK, thanks, this is ready for merge then.

**Pull request merged**
