### PR TITLE
Update assetsFilter to stop excluding part of vendor bundle

### LINKED ISSUE #3042: Fresh install of dependencies causes dev server to not work
**Describe the bug**
On branch `latest`, doing an `npm install` & `npm run dev` causes all simorgh pages to not be functioning correctly. e.g. images are not lazyloaded. 

**To Reproduce**

1. `npm install`
2. `npm run dev
3. Visit http://localhost.bbc.com:7080/pidgin or http://localhost.bbc.com:7080/arabic/articles/clr0em3yzkmo
4. See images not being lazy-loaded
Screen Shot 2019-08-09 Pidgin

**Expected behavior**
To have lazyloading images with the dev server. 

**Screenshots**
See above

Note: the correct JS bundle files seem to be loaded.

### PR DESCRIPTION
**Pull request by jamesdonoh**
Resolves https://github.com/bbc/simorgh/issues/3042

**Overall change:** _Updates regular expression used by assets filter which was was causing some of the vendor bundle to be excluded to file naming changes caused by something upstream_

**Unanswered questions**
- What has caused the change in bundle file naming?
- How can we avoid a repetition?

**Code changes:**

- Update regex and amend tests

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [NA] Test engineer approval

### CODE REVIEW

**Review by sareh — APPROVED** [review]
👍 Good spot, @jamesdonoh! Works locally for me. `npm ci && npm run dev`

On this branch:
Screen Shot 2019-08-12 at 13 34 27
On `latest`:
Screen Shot 2019-08-12 at 13 36 42

**Comment by pjlee11** [comment]
Great work spotting this @jamesdonoh, I'm slightly concerned why this PR was needed though. Would be good to get to the bottom of why the change is needed and what caused the regression

**Review by dr3 — APPROVED** [review]

**Comment by dr3** [comment]
I think webpack dev server was updated at some point, so for some reason it started serving a dev bundle with a name that we didn't expect. Why it suddenly used a name we dont like? Not sure

**Comment by sareh** [comment]
@pjlee11 It's likely that our regex was far too strict initially and the webpack dev server is now using `@` and `~` characters within the bundle names.

**Comment by dr3** [comment]
Doesnt need testing, merge merge merge

**Review by pjlee11 — APPROVED** [review]

**Pull request merged**
