### PR TITLE
Use Psammead Headings package in Simorgh

### LINKED ISSUE #975: Pull Headings component from component library
**Is your feature request related to a problem? Please describe.**
Blocked on our Headings component being merged into the component library: https://github.com/BBC-News/psammead/issues/12.

Once this is merged, we should remove the internal Headings component from Simorgh and pull in the external Headings component from Psammead.

**Describe the solution you'd like**
A single PR which removes the Headings component and imports the external one.

**Testing notes**
Will Cypress tests be required or are unit tests sufficient?

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by dr3**
Resolves #975

Pulls the @bbc/psammead-headings component into Simorgh and removes the existing component

# note

This PR has `ForwardRef` in the snapshot, this is because psammead uses styled components 4, while jest-styled-components doesn't support it yet. Our options are downgrade to styled-components 3 in psammead, wait for jest-styled-components to update or move away from react-test-renderer.

All of these are less than ideal, but we should address this in another issue and accept `ForwardRef` for now

- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Comment by dr3** [comment]
Blocked on #79 which is blocked in #80 
When it is unblocked a fresh npm install should make this ready

**Comment by ChrisBAshton** [comment]
No longer blocked!

**Comment by ChrisBAshton** [comment]
Waiiiit. Blocked on #79 and #80 in Psammead - not Simorgh!

So now blocked on https://github.com/BBC-News/psammead/pull/79

**Review by ChrisBAshton — DISMISSED** [review]
Nice 👍

**Review by ChrisBAshton — DISMISSED** [review]

**Review by sareh — DISMISSED** [review]
👍 Looks great.

**Comment by ChrisBAshton** [comment]
Blocked on #119.

**Comment by sareh** [comment]
I spun up Storybook locally and noticed that we now don't have anything in Simorgh to show our Headings - neither the Headline nor the SubHeading. 

This made me think that it would be useful to have the Storybook examples for the Headings container (both Headline nor the SubHeading). This would enable us to view and ensure our components are all looking as expected. 

With regards to this PR, I ran this branch locally and compared http://localhost:7080/news/articles/c9rpqy7pmypo with https://www.test.bbc.com/news/articles/c9rpqy7pmypo & all looked good. :)

**Review by sareh — APPROVED** [review]

**Review by ChrisBAshton — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
LGTM

**Pull request merged**
