### PR TITLE
Log join-us link on the console in production.

### LINKED ISSUE #1573: Add console log to advertise open job roles
**Is your feature request related to a problem? Please describe.**
We should add a console log message on simorgh pages advertising our Join us page https://bbc-news.github.io/join-us/

**Describe the solution you'd like**
Add a console message containing the link. The message should show in production, but not locally when running `npm run dev`

This will require some cross browser testing and accessibility testing.

**Testing notes**
Manual test of the console log to see whether the job roles ads are displayed.

Dev insight: Snapshot tests, perhaps storybook and manual testing

**Additional context**
This is our current console message on the news homepage
image

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by EinsteinNjoroge**
Resolves #1573 

**Overall change:** _Show the [Join Us](https://bbc-news.github.io/join-us/) link on the console in all pages_

**Code changes:**

- _Add an info logger to log [https://bbc-news.github.io/join-us/](https://bbc-news.github.io/join-us/) on the console in production only_

**note**
I manually tested this locally, with this logic it should show on production only
Untitled

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Comment by dr3** [comment]
How come we've gone for this vs the old design like below? This isn't very visible
image

**Comment by EinsteinNjoroge** [comment]
@dr3  Should we do both the message and the link?

**Comment by dr3** [comment]
Soz just realised the issue didn't explicitly say to do the same console log. We can just copy across the logic from https://github.com/bbc/morph-modules/blob/681e4f5eabc558c3006ece7d75f43a43e8efc604/news-front-page-js-bundle/src/modules/console/dev-tools-message.js
Modernise it, remove the `if (modernBrowser() && !devEnvironment()) {`, but the output can be the same

**Review by dr3 — APPROVED** [review]
LGTM, happy with manual testing only. It isn't a perfect console log, and has issues in some browsers and dark modes, but we can fix forward to improve it.

**Review by j-pendlebury — APPROVED** [review]

**Comment by david-boydell** [comment]
Looks fine, behaves as it does on Live. This is ready for merge.

**Pull request merged**
