### PR TITLE
Update ukraine_in_russian integration tests

### LINKED ISSUE #7027: Update `/ukrainian/ukraine_in_russian` integration tests
**Is your feature request related to a problem? Please describe.**
A part of this PR: https://github.com/bbc/simorgh/pull/6904 
We configured the Ukrainian idx page to have a header and footer of lang `uk` lang. 

**Describe the solution you'd like**
We could write integrations to check the correct lang is used in the correct html elements.
- ~~`<main>` should have lang attribute and value should be `ru-UA`~~
- `<header>` and `<footer>` should have lang attribute and value should be `uk`
- `<html>` should have lang attribute and value should be `ru-UA`

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves #7027
~Blocked on https://github.com/bbc/simorgh/pull/6904~

**Overall change:**
Add Integration tests for `ukrainian/ukraine_in_russian/` IDX page

**Code changes:**
- Add `Header` and `Footer` integration tests to check for the `lang` attribute
- Move the `RadioSchedule` test to `persian/afghanistan` folder as the Ukrainian IDX page won't have it

---

- [X] I have assigned myself to this PR and the corresponding issues
- [X] I have added labels to this PR for the relevant pod(s) affected by these changes
- [X] I have assigned this PR to the Simorgh project

**Testing:**

- [X] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by sareh — APPROVED** [review]
Looks good. :+1:

**Review by amywalkerdev — APPROVED** [review]
👍

**Review by tochwill — APPROVED** [review]

**Review by itimirichard — APPROVED** [review]

**Comment by amywalkerdev** [comment]
Tests failing locally, Khoa is sorting

**Comment by thekp** [comment]
image
Passes locally now ^ I had to rename the files.


`npm run test:integration` silently fails in our CI 👀 . However, we spotted it failing locally. I will raise an issue for the silent failures to be addressed.

**Review by amywalkerdev — APPROVED** [review]
👍 Works again now!

**Pull request merged**
