### PR TITLE
package-lock stablise to node 8.11.3 and npm 6.4.1

### PR DESCRIPTION
**Pull request by pjlee11**
No issue, this stabilises the package-lock to the version we specify for local dev

**Overall change:** _`npm i` with the correct node and npm version_

**Code changes:**

- changes package-lock

---

- ~[ ] I have assigned myself to this PR and the corresponding issues~
- ~[ ] Tests added for new features|~
- [ ] Test engineer approval
- [x] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
👍 I ran into this today.

**Review by dr3 — APPROVED** [review]
lgtm, get same locally

**Review by ghost — APPROVED** [review]

**Review by jamesdonoh — APPROVED** [review]
I assume you mean 8.11.3 :-) Any idea why `scripts/enforceVersions.sh` didn't prevent this?

**Comment by dr3** [comment]
@jamesdonoh Need to chec with @DemonusPC who pushed the package-lock. The script is on prepush though, so it could have been broken ina commit, then changed version, but not then update the package lock

**Comment by pjlee11** [comment]
Confirmed with @jamesbrumpton that the Travis and Jenkins automated tests cover the regression of this fix

**Pull request merged**
