### PR TITLE
Override width for STY page primary content grid

### LINKED ISSUE #6808: Horizontal scrollbar appearing at smaller viewports in Firefox
**Describe the bug**

- There is an overlap issue with the onward journeys
- Something is causing the page to have a horizontal scrollbar at smaller sizes in Firefox

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/kyrgyz/23292889
2. Reduce viewport width in Firefox until horizontal scrollbar appears
3. Scroll down to bottom of page, there is an overlap issue with the onward journeys
4. Something is causing the page to have a horizontal scrollbar at smaller sizes in Firefox

The problem is _not_ apparent on iOS 13.5 (iPhone SE 2nd generation). Problem also not occuring in Chrome 83.0.4103.61 on macOS Catalina 10.15.3.

**Expected behaviour**

Horizontal scrollbar should not appear at smaller viewports, the content should resize and all content on the page should fit within the viewport.

**Screenshots**
Screenshot 2020-06-05 at 11 02 57

**Desktop**

- OS: macOS Catalina 10.15.3
- Browser Firefox 76.0.1

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by HarveyPeachey**
Resolves #6808

**Overall change:**
Created a styled component to override grid on STY pages that contains main and related content. This overrides the `width` property at the group 3 GEL breakpoint to use `%` as it seems `initial` isn't behaving as intended on Firefox.

**Code changes:**

- Added styled component `GridPrimaryColumn` which overrides the default width value.
- Updated STY page snapshot.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by rhenshaw56 — APPROVED** [review]
Looks good!

**Review by FK78 — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Looks good except in IE11 , secondary column in getting pushed to  single column.. I have checked this in IE11 yesterday but it didn't show that issue :( but chromaticQA picked it up..

**Comment by paruchurisilpa** [comment]
This is how the page looks in IE11, twitter image is not displayed but it is nothing to do with this PR, have noticed it previously too..
Screenshot 2020-06-18 at 18 14 00

LGTM..

**Pull request merged**
