### PR TITLE
Remove isLive toggle

### LINKED ISSUE #9618: Promote Inline promo to LIVE
**Is your feature request related to a problem? Please describe.**
Promote inline promo to LIVE environment.

**Describe the solution you'd like**
Remove the feature toggle around the inline promo and remove the existing promo that is on LIVE.
The component will need to be refactored slightly (see comments on PR https://github.com/bbc/simorgh/pull/9531).

**Testing notes**
The inline promo should show in articles (where it meets the necessary criteria) on LIVE.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

### PR DESCRIPTION
**Pull request by mfonofm**
Resolves #9618 

**Overall change:**
Remove isLive toggle and refactor width of the promo

**Code changes:**

- Remove isLive toggle from StoryPage and getInitialData
- Remove Podcast Promo from the Secondary Column on Live
- Change width from explicit px values to percentage value
- Change text size to match the requirement set out by ux (below are the requirement)

***UX requirements around text.***
“episode” text should be set to 14px and the description/title should be 15px across all devices under 599px?
For those 600px and above use the styling on the current podcast promo:
Title = 16/20px
Body copy = 14/18px
episodes text = 14/18px

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by ryanmccombe — APPROVED** [review]

**Review by Louis-Matsika — APPROVED** [review]

**Review by Louis-Matsika — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]

**Comment by LilyL0u** [comment]
14px = 0.875rem.
15px = 0.9375rem
16px = 1rem (base)
18px = 1.125rem.

**UX requirements around text.**

- [x] “episode” text should be set to 14px 
- [x] and the description/title should be 15px across all devices under 599px?

For those 600px and above use the styling on the current podcast promo:

- [ ] Title = 16/18px

- [x] Body copy = 14/18px

- [x] episodes text = 14/18px

**Comment by LilyL0u** [comment]
For the UX requirements that say something like 'Title = 16/18px', is it the first number is for under 599 and the second number is for 600+? I think this is likely, but wanted to be certain.

**Comment by MuhammadAHussain** [comment]
> For the UX requirements that say something like 'Title = 16/18px', is it the first number is for under 599 and the second number is for 600+? I think this is likely, but wanted to be certain.

Double checked with UX, the second value is the line height, so in the example of 16/18px, 16px (is the font size) / 18px (is the line height).

**Comment by LilyL0u** [comment]
The requirements above say that the title should have a font size of 16px (1 rem) and a line height of 18px (1.125 rem). However when I check the element, the line height is 1.25 rem which is 20px. The font size is correct.
Screenshot 2021-11-09 at 08 14 02

**Comment by MuhammadAHussain** [comment]
> The requirements above say that the title should have a font size of 16px (1 rem) and a line height of 18px (1.125 rem). However when I check the element, the line height is 1.25 rem which is 20px. The font size is correct. Screenshot 2021-11-09 at 08 14 02

I think this was a mistake in the requirements I added to this PR. The correct size should be 16/20px (https://www.bbc.co.uk/gel/guidelines/typography). I'll update the requirements, apologies.

**Pull request merged**
