### PR TITLE
WSTEAM1-306: Remove secondary column and most read

### PR DESCRIPTION
**Pull request by shayneahchoon**
Resolves JIRA [WSTEAM1-306](https://jira.dev.bbc.co.uk/browse/WSTEAM1-306)

Overall changes
======
Secondary column and most read have been removed: 
Screenshot 2023-03-28 at 17 20 43

Code changes
======
- _Top stories and Features have been removed, but a place holder has been left in for latestMedia column._
- _Most read section has been removed completely._

Testing
======
1. _List the steps used to test this PR._

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

### CODE REVIEW

**Review by amoore108 — APPROVED** [review]
Looks good 👍 

Similar to the API PR, we should maybe hold off on this until the `latestMedia` visual components have been created so that we don't have a period of a blank secondary column.

I wonder though could we separate this out a bit and remove just the MostRead component? Its not tied to the secondary column, so we could remove it without much hassle.

**Review by Isabella-Mitchell — APPROVED** [review]
I also agree - this PR looks good  - though not sure the best order to merge this work in. 

For instance, the placeholder you've created seems to contribute to (if not complete) subtask [WSTEAM1-353](https://jira.dev.bbc.co.uk/browse/WSTEAM1-353) of ticket [WSTEAM1-307](https://jira.dev.bbc.co.uk/browse/WSTEAM1-307).

**Comment by shayneahchoon** [comment]
Heya, this PR removes just the Most Read section instead: https://github.com/bbc/simorgh/pull/10744. Should I keep this one open for reference?

**Comment by amoore108** [comment]
> Heya, this PR removes just the Most Read section instead: #10744. Should I keep this one open for reference?

Not really sure tbh, as once we build out the UI components for the new onward journeys, removing the secondary column will really become "replacing" the secondary column. Maybe this isn't needed just yet and removing the MostRead resolves the ticket for now?

**Pull request closed without merging**
