### PR TITLE
Hide test link on MAPs

### LINKED ISSUE #4761: Remove "test to MAP inline link on MAP" pages
**Is your feature request related to a problem? Please describe.**
We are currently displaying this link at the top of MAP pages: 
Screenshot 2019-11-22 at 17 17 50

We need to remove it before we can go live. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by ryanmccombe**
Resolves https://github.com/bbc/simorgh/issues/4761

**Overall change:** 
_Remove "test to MAP inline link on MAP" pages_

**Code changes:**
- _Remove the test link_
- _Update the puppeteer test to only ensure the bundle doesn't get included in a SSR_
- _Disable the remaining aspects of that test_

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added labels to this PR for the relevant pod(s) affected by these changes
- [ ] I have assigned this PR to the Simorgh project

**Testing:**
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by karinathomasbbc — APPROVED** [review]

**Comment by karinathomasbbc** [comment]
I guess my only comment would be... why can't we remove this link entirely?  Or could we create another test page type with this link on it?

**Comment by jamesdonoh** [comment]
I'd agree with Karina, it doesn't seem ideal that we would be outputting hidden markup in the page on live just to satisfy our e2e tests. What do others think about removing it completely and then thinking of a better way of implementing automated test coverage for this behaviour, as a separate task?

**Comment by ryanmccombe** [comment]
👍 updated to split the test into two, and disabled the second part of the test (the one which requires the link)

This seems safe because the code will never actually run in our current set up - we don't do any client-side navigation

**Review by jamesdonoh — APPROVED** [review]
Cheers 👍

**Pull request merged**
