### PR TITLE
Update snapshots

### PR DESCRIPTION
**Pull request by karinathomasbbc**
Resolves #N/A

**Overall change:**
Out of date snapshots were accidentally merged as part of a previous PR  #10613 (which resulted from #10606) 

**Code changes:**
Updated snapshots

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by amoore108 — APPROVED** [review]
These changes will likely be reverted when the work for fetching CPS assets from the BFF gets merged (https://github.com/bbc/simorgh/pull/10617)

Looks like the caching logic needed some conditions to only apply when on Test/Live, not locally. Since its occurring locally, its likely introduced this snapshot diff.

**Comment by karinathomasbbc** [comment]
> Looks like the caching logic needed some conditions to only apply when on Test/Live, not locally. Since its occurring locally, its likely introduced this snapshot diff.

Do you think we should update the caching logic as part of this PR?

**Comment by amoore108** [comment]
> 

I think if you add something like `['test', 'live'].includes(process.env.SIMORGH_APP_ENV)` around the checks for when the cache value should be used, that will probably highlight whether or not the snapshot changes are needed, e.g.:

`const cachedResponse = ['test', 'live'].includes(process.env.SIMORGH_APP_ENV) &&  cache && cache.get(url);`

**Review by Isabella-Mitchell — APPROVED** [review]
I noticed it in my PR, thanks for fixing.

**Pull request merged**
