### PR TITLE
Add separator to formatDuration

### LINKED ISSUE #2996: Descriptive durations should just have raw numbers with a space
**Is your feature request related to a problem? Please describe.**
The problem with adding translations for minutes and seconds is that it is difficult to do for all languages, especially for some Slavic languages that have multiple versions of plurals. 

**Describe the solution you'd like**
Instead of the minutes/seconds in story promo headline, we should just have numbers with a space

1. Use formatDuration instead of describeDuration in LinkContents. 
2. Replace the colons between the hours/minutes/seconds with spaces in the formatDuration function. For example "1:00" -> "1 00". This will avoid screen reader interpreting the numbers as a time, eg 'one o'clock'. 

We can't think of a downside of having a space instead of a colon as the screenreader reads it in the same way when the numbers are not '1:00'. 

**Describe alternatives you've considered**
Loads - but this is the most straightforward thing to do. 

**Testing notes**
To be tested with all supported assistive technology. 

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

### PR DESCRIPTION
**Pull request by ghost**
Resolves #2996, #2309

**Overall change:** Format durations in `LinkContents` to fix a11y bug

**Code changes:**

- Add second arg `separator` to `formatDuration`.
- Use formatDuration in `LinkContents` with a empty space separator

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by andrew-nowak — APPROVED** [review]
lgtm

**Review by dr3 — APPROVED** [review]

**Comment by staylos92** [comment]
So that when this is picked up for testing we have an idea of what testing is required could you please let us know if any a11y testing has been performed already as part of the development done on this PR?

**Comment by DenisHdz** [comment]
> So that when this is picked up for testing we have an idea of what testing is required could you please let us know if any a11y testing has been performed already as part of the development done on this PR?

We had problems with durations like `1:00` announced like `one o'clock` by some screen readers, so before the development of this PR, we tested the durations using `commas` with our supported Assistive Technology.

This PR should be fine, but it would be worth that testers check with the AT again to confirm that it works as expected, and the durations (hidden in the promo headline) are not announced like time (eg 'one o'clock' when `1,00`).

**Comment by david-boydell** [comment]
Looks good, this is ready for merge.

**Pull request merged**
