### PR TITLE
Fix bbc-a11y bugs and remove skipped tests

### LINKED ISSUE #418: Test for text resizing errors when bbc-a11y is updated
**Describe the bug**
The following [bbc-a11y](https://github.com/bbc/bbc-a11y) test, `Text must be styled with units that are resizable in all browsers`, is skipped in Simorgh (see: https://github.com/bbc/simorgh/blob/latest/a11y.js#L3). 

This is because  bbc-a11y itself always grabs the computed size of text in pixels, meaning the test will always fail. There is an issue raised on bbc-a11y related to this here: https://github.com/bbc/bbc-a11y/issues/262#issuecomment-409267398

**Additional context**
When this issue on bbc-a11y is fixed, we should adapt Simorgh so that it is not skipping `Text must be styled with units that are resizable in all browsers`, and fix any bugs that arise.

### PR DESCRIPTION
**Pull request by radiocontrolled**
This PR enables a [bbc-a11y](https://github.com/bbc/bbc-a11y) rule that ensures a `main` landmark role is present in the article, and adds the `main` role itself.

This PR skips another bbc-a11y rule, `Text must be styled with units that are resizable in all browsers` , which is failing due to an issue within bbc-a11y itself. There is another  outstanding issue to complete this work when the bbc-a11y issue is fixed: https://github.com/bbc/simorgh/issues/418. 

* [x] https://github.com/bbc/simorgh/issues/336
* [x] Tests added for new features (updated snapshots)

* [x] Test engineer approval

### CODE REVIEW

**Comment by radiocontrolled** [comment]
@greenc05 

On my branch, I am wondering why bbc-a11y gives errors like this:
```
✗ http://localhost:7080/article/scenario-27 --width 1008
  * Design: Content resizing: Text must be styled with units that are resizable in all browsers
    - Text styled with px unit: //div[@id='root']/main/h1
```

re: http://www.bbc.co.uk/guidelines/futuremedia/accessibility/mobile/design/content-resizing
We have the required meta tag `<meta name="viewport" content="width=device-width, initial-scale=1.0">`. 

Text is styled with an em in `src/app/components/Headings/index.jsx`:
```
export const Headline = styled.h1`
  color: ${C_EBON};
  font-family: ${FF_NEWS_SANS_REG};
  font-size: 2em;
`;
```

**what I've tried**
Setting  various enclosing elements, e.g. `html`, `body` to have a relative size (font-size: 100%)


I've also raised an issue on bbc-a11y here: 
https://github.com/bbc/bbc-a11y/issues/262

**Review by sareh — DISMISSED** [review]
Looks great. Good investigative work on the `bbc-a11y` issue.

**Review by jtart — DISMISSED** [review]

**Comment by radiocontrolled** [comment]
**Testing instructions**

* Manually verify that the following markup is rendered in the DOM: `<mail role="main">`
* Use JAWS to navigate by landmarks to the main landmark [(no. 7 in JAWS testing docs)](https://bbc-news.github.io/accessibility-news-and-you/accessibility-and-testing-with-jaws)
* Use iOS voice over to navigate by landmarks to the main landmark [(VoiceOver testing docs)](https://bbc-news.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os)
* verify that running `npm run bbc-a11y` does not return any errors.

**Comment by jamesbrumpton** [comment]
LGTM

**Pull request merged**
