### PR TITLE
Add fixture data for STY secondary column

### LINKED ISSUE #6489: Add STY secondary column live fixture data
**Is your feature request related to a problem? Please describe.**
Now that the new STY secondary column endpoint has been integrated, we should add in live fixture data for the remaining services which don't have it. ~We should also remove the default content and fixture data that are currently being used for the Features and Top Stories containers.~ - This is being solved in https://github.com/bbc/simorgh/pull/6483

**Describe the solution you'd like**
Add fixture data for services which don't currently have it. Fixture data for Igbo, Kyrgyz, Mundo, Pidgin and Zhongwen Traditional already exist so data will need to be added for the other services. The structure of the URL to get the data is as follows: 
https://www.bbc.com/{SERVICE}/sty-secondary-column.json
https://www.bbc.com/{SERVICE}/sty-secondary-column/{VARIANT}.json

An example of existing local fixture data: https://github.com/bbc/simorgh/tree/latest/data/igbo/secondaryColumn

**Describe alternatives you've considered**

**Testing notes**
Update Snapshots

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by FK78**
Resolves #6489

**Overall change:**
_Add fixture data for STY secondary column._

**Code changes:**

- _Fixture data for STY secondary column added for multiple services._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by HarveyPeachey — COMMENTED** [review]
Looks good I think it's just missing Zhongwen Simple: https://www.bbc.com/zhongwen/sty-secondary-column/simp.json

**Review by HarveyPeachey — APPROVED** [review]
LGTM

**Review by thekp — APPROVED** [review]
Some services have already got fixture data.

**Comment by paruchurisilpa** [comment]
This wouldnt need any testing, moving it to Ready to Merge..

**Pull request merged**
