### PR TITLE
Adding Condition to Index-Also Cypress Test

### LINKED ISSUE #3586: Figure out how best to e2e test Index Alsos
**Is your feature request related to a problem? Please describe.**
We current have an e2e test that checks for index also's on the front pages. However index also's are not required by editorial so will not always be present

Current test https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/frontPage/tests.js#L89

**Describe the solution you'd like**
Work out the best way to ensure we have test coverage for index also's with.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by jamesbrumpton**
Resolves #3586 

**Overall change:** _Urgent fix for broken Index-Also Cypress test._

**Code changes:**

- _Wrapping Index-Also test into a conditional block._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by j-pendlebury — APPROVED** [review]
This looks good to me, and it will work for now, however we should probably improve this in the future to have the 'Related content' text coming from config/translations.

Currently that offscreen text is hardcoded in the story promo: https://github.com/bbc/simorgh/blob/150b73c8b946371574dbd94087f1b38cbb5d7e5a/src/app/containers/StoryPromo/IndexAlsos/index.jsx#L51

**Review by chris-hinds — CHANGES_REQUESTED** [review]
This seems to now work as expected and doe not rely on index also's being present. Now that we have the top story promo on desktop please can you ensure we check for the index also's on desktop too and not just mobile.

**Comment by j-pendlebury** [comment]
Issue for updating the hardcoded string: https://github.com/bbc/simorgh/issues/3612

**Comment by j-pendlebury** [comment]
James ran these tests locally with different options - multiple index alsos, one index also, no index alsos, and they all passed.

**Comment by j-pendlebury** [comment]
To be fixed by https://github.com/bbc/simorgh/pull/3587

**Pull request closed without merging**
