### PR TITLE
Investigate Adding AMP support to Storybook

### LINKED ISSUE #911: Investigate how to get Storybook rendering AMP components
**Is your feature request related to a problem? Please describe.**
When we have an AMP component, e.g. an AMP Image component that renders`<amp-img>`, we want to make it visible in Storybook https://simorghstorybook.now.sh.  
However, because our standard Storybook setup does not include the AMP required markup and JS, (https://www.ampproject.org/docs/fundamentals/spec#required-markup) the component won't render accurately. 

**This is a prerequisite to adding AMP components to our application and also to our future component library.**

**Describe the solution you'd like**
- A storybook setup that displays AMP components
- What do we do if storybook just cannot render AMP components?

**Describe alternatives you've considered**
N/A

**Testing notes**
Add an AMP component, e.g. an AMP Image component that renders`<amp-img>`, and see it displayed correctly in Storybook https://simorghstorybook.now.sh.  

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by dr3**
Resolves #911

Adds storybook decorator to add required markup and JS, (https://www.ampproject.org/docs/fundamentals/spec#required-markup) when displaying an AMP component.

This PR piggy backs on Chris's PR to try adding amp-img so please only review the [final commit](https://github.com/BBC-News/simorgh/pull/933/commits/5458dd4b9a7b14efea74d7bf84a4312795aaa8b4).

The decorator uses `react-helmet` to add markup that AMP requires including the primary AMP js bundle script. This decorator can then simply be attached to a collection of stories using ```.addDecorator(AmpDecorator)``` 

- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by dr3** [comment]
All code climate issues are coming from @ChrisBAshton's WIP code which this branch uses as a starting point.

**Review by jtart — COMMENTED** [review]
This seems like this approach would work. Can you do a bit of write-up about explaining it on this PR?

**Comment by dr3** [comment]
This will be implemented cleanly in https://github.com/BBC-News/simorgh/issues/943

**Review by pjlee11 — DISMISSED** [review]
Looking at https://github.com/BBC-News/simorgh/pull/933/commits/5458dd4b9a7b14efea74d7bf84a4312795aaa8b4 the approach looks good to me. Thanks for opening up an implementation issue! 👍

**Review by pjlee11 — APPROVED** [review]

**Review by jtart — APPROVED** [review]

**Pull request closed without merging**
