### PR TITLE
Update package-lock to remove minimist vulnerability 

### PR DESCRIPTION
**Pull request by j-pendlebury**
Part of https://github.com/bbc/simorgh/issues/5905

**Overall change:** 
Removed and re-generated `package-lock` to pull in latest dependencies to remove `minimist` vulnerability.

**Code changes:**
- Removed and re-generated package-lock
- Updated snapshots
- Updated bulletin component test

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by j-pendlebury** [comment]
There are 2 vulnerabilities left which will be fixed by https://github.com/bbc/simorgh/pull/5976, afterwards #5905 can be completed by removing `npm audit` whitelist from package.json

**Review by Bopchy — APPROVED** [review]
Looks good

**Review by EinsteinNjoroge — APPROVED** [review]
👍

**Comment by PriyaKR** [comment]
Looks good to me.

**Pull request merged**
