### PR TITLE
Use latest version of chromatic UI Github action

### PR DESCRIPTION
**Pull request by karinathomasbbc**
Overall changes
======
Updates the chromatic GitHub action to the latest version

Code changes
======
- Update the .github/workflows/simorgh-misc-checks.yml file to use the latest version of Chromatic

Testing
======
Chromatic UI tests pass

### CODE REVIEW

**Review by amoore108 — APPROVED** [review]

**Comment by karinathomasbbc** [comment]
@amoore108 this has now broken the homepage example (unable to render), so I have marked the UI test as failed until I can figure out why...

**Comment by karinathomasbbc** [comment]
> @amoore108 this has now broken the homepage example (unable to render), so I have marked the UI test as failed until I can figure out why...

Rerunning the job to see if it was just a flake. I can't recreate locally when running Storybook, but I am going to try and invoke the CLI to see if it can still render the Homepage example as expected...

**Comment by amoore108** [comment]
> > @amoore108 this has now broken the homepage example (unable to render), so I have marked the UI test as failed until I can figure out why...
> 
> Rerunning the job to see if it was just a flake. I can't recreate locally when running Storybook, but I am going to try and invoke the CLI to see if it can still render the Homepage example as expected...

I can see it flash up quickly "Unable to render homepage for Kyrgyz" locally, but then it does render.

The `useEffect` that fetches the data won't wait to get the data before rendering, so it looks like it will always flash that message quickly and then show the actual Homepage component: https://github.com/bbc/simorgh/blob/da07c34c0e583f8c05b6fdddcb60f50365c7bcba/src/app/pages/HomePage/index.stories.tsx#L44-L61

Maybe a delay is needed for this story to allow it to complete the data fetch?

**Comment by karinathomasbbc** [comment]
> I can see it flash up quickly "Unable to render homepage for Kyrgyz" locally, but then it does render.

The new snapshot is "Unable to render homepage for news" so it looks like it is not honouring the service we have set in the homepage story file, and is using the default instead

**Comment by karinathomasbbc** [comment]
Same problem on this commit: https://5d28eb3fe163f6002046d6fa-etsweoqhgi.chromatic.com/?path=/story/pages-home-page--example

**Comment by karinathomasbbc** [comment]
But this one is fine 🤯 [Storybook permalink for branch](https://update-chromatic-github-action--5d28eb3fe163f6002046d6fa.chromatic.com/?path=/story/pages-home-page--example)

**Comment by karinathomasbbc** [comment]
OK, it seems to have fixed itself, so we're all good 👍

**Review by Isabella-Mitchell — APPROVED** [review]

**Pull request merged**
