### PR TITLE
Fix for IE 11 Grid Layout - Body Content

### PR DESCRIPTION
**Pull request by sareh**
Part of #821

This PR was opened as a result of investigating for a fix being needed for user testing pilot with a prototype next week. 

- Add IE 11 grid syntax
- Adding pretter-ignore command to ensure we have no spaces between parentheses in the IE repeat syntax: ()[]

**Before PR**
The content spans the width of the viewport, which is incorrect.
screen shot of article on Windows 7 - IE 11 - 1400px

**After PR**
The content respects the grid layout: 
1440px
screen shot of article on Windows 7 - IE 11 - 1400px

1010px
screen shot of article on Windows 7 - IE 11 - 1010px

650px
screen shot of article on Windows 7 - IE 11 - 650px

400px
screen shot of article on Windows 7 - IE 11 - 400px

Resources used:
https://medium.com/@elad/supporting-css-grid-in-internet-explorer-b38669e75d66
https://css-tricks.com/css-grid-in-ie-debunking-common-ie-grid-misconceptions/

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by dr3 — APPROVED** [review]
👍 LGTM - WIN7 IE10
WIN7 IE9 Unaffected as expected

**Review by bcmn — APPROVED** [review]
Looks great! 👏

**Comment by jamesbrumpton** [comment]
The base article looks to working as expected on IE11, however the footer appears to not have the same logic applied. See screenshot for reference.

image

**Comment by dr3** [comment]
@jamesbrumpton The footer doesnt have a grid fallback yet, work will need to be done to https://github.com/bbc/psammead/tree/latest/packages/components/psammead-sitewide-links as a further part of https://github.com/bbc/simorgh/issues/821

**Comment by jamesbrumpton** [comment]
After speaking with Drew, we're going to merge this work and another PR has been opened in order to deal with the lack of grid support for the footer on IE11.

**Pull request merged**
