### PR TITLE
Use updated site wide links

### LINKED ISSUE #3950: Scotland footer links display error
**Describe the bug**
On a BBC Scotland article page: https://www.test.bbc.co.uk/scotland/articles/czwj5l0n210o
The footer links are not displaying correctly.

**To Reproduce**
1. Go to: https://www.test.bbc.co.uk/scotland/articles/czwj5l0n210o
2. Scroll to the end of the page
3. The 'Terms of Use' link is where the 'Why you can trust the BBC' link usually is. The rest of the footer links are spread along the row below.

Footer1

**Expected behavior**
The footer links should all appear in the same section of the footer. E.g. 
Footer2

Note: There should be no 'Why you can trust the BBC' link. Nothing should take its place when this link is not present.

**Screenshots**
See above.

**Desktop (please complete the following information):**

- iOS and Windows

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by thekp**
Resolves #3950

**Overall change:** _Use the latest change of site wide links that accepts a new prop of `trustProjectLinks`_

**Code changes:**

- _remove the trust project link from footer.links in service configs because it is handled as it own prop now._
- _bump site wide links_
- _update snapshots_
- _removed trustProjectLink object from scotland service because it is not required on scotland service. When i pass an empty object to psammead, it treated as undefined and is a truthy_ 

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by sareh — APPROVED** [review]
👍 Looks great. Thanks for the changes.

**Comment by thekp** [comment]
Manually tested on Psammead PR already: https://github.com/bbc/psammead/pull/2340

**Review by EinsteinNjoroge — APPROVED** [review]

**Review by FK78 — APPROVED** [review]
LGTM, nice work.

**Comment by jamesbrumpton** [comment]
lgtm

**Pull request merged**
