### PR TITLE
Pull in most popular fixture data to data/

### LINKED ISSUE #1830: Pull in most popular fixture data
**Is your feature request related to a problem? Please describe.**
Integrate fixture data for most read data for news and persian services

**Describe the solution you'd like**
Pull fixture data from ares and place in the /data directory, similar to #1546 #1590 
There is a link to a feed in bbc/simorgh-infrastructure#355

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Confirm that the added data is correct (valid json, for the right service etc.) No observable impact to users in this ticket

**Additional context**

### PR DESCRIPTION
**Pull request by Bopchy**
Resolves #1830 

**Overall change:** _Adds most popular fixture data to data/prod and data/test._

**Code changes:**

- _Add most popular fixture data to data/test._
- _Add most popular fixture data to data/prod._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by andrew-nowak — CHANGES_REQUESTED** [review]
I'm possibly being overly cautious here, but could the fixture data in the prod & test directories be the same? I think the two sets of fixture data are used somewhat interchangeably

**Review by andrew-nowak — DISMISSED** [review]
awesome

**Review by dr3 — COMMENTED** [review]
Should this not be most read, instead of most popular?

**Review by 12 — CHANGES_REQUESTED** [review]
I agree with @dr3, this should be `read` not `popular`

**Comment by Bopchy** [comment]
👍 Changed to `read`

**Comment by Bopchy** [comment]
Accidentally closed this 🙈

**Review by pjlee11 — APPROVED** [review]
LGTM 👍

**Review by 12 — APPROVED** [review]

**Comment by staylos92** [comment]
This doesn't need testing by a tester

**Pull request merged**
