### PR TITLE
WSTEAMA-1474 - Move Serbian and Zhongwen to list of migrated services

### PR DESCRIPTION
**Pull request by louisearchibald**
Resolves JIRA [[1474](https://jira.dev.bbc.co.uk/browse/WSTEAMA-1474)]

Overall changes
======
Adds Serbian & Zhongwen to our list of migrated services in preparation for their upcoming Homepage release (10th Dec).

Code changes
======

- Adds `serbian` and `zhongwen` to `homePageServices` array.
- Updates related test.
- Updates snapshots.

### CODE REVIEW

**Review by karinathomasbbc — APPROVED** [review]
LGTM 🥇 

Out of interest, if we run Simorgh in production mode for live, what do we see?

```
yarn build:live && yarn start
``` 

If we compare local to the live version of the tipo homepage, are they the same?

| Local | Live (on test environment with renderer_env override) |
| -- | -- |
| http://localhost:7080/serbian/cyr | https://www.test.bbc.com/serbian/cyr?renderer_env=live| 
| http://localhost:7080/serbian/lat | https://www.test.bbc.com/serbian/lat?renderer_env=live |
| http://localhost:7080/zhongwen/simp | https://www.test.bbc.com/zhongwen/simp?renderer_env=live |  
| http://localhost:7080/zhongwen/trad | https://www.test.bbc.com/zhongwen/trad?renderer_env=live |

**Review by holchris — APPROVED** [review]

**Review by karinathomasbbc — CHANGES_REQUESTED** [review]
I had a midnight musing 

The E2E tests will fail once this PR reaches the live environment, as it will be trying to run FrontPage tests against the Homepage. We need to disable those tests in this PR completely, and to add one or both of the variant services to the Homepage E2E Tests.

Example of disabled front page test: https://github.com/bbc/simorgh/blob/cbf7c2b3d08a33775c51eeb94de750d0993a988b/cypress/support/config/settings.js#L42

Add an entry for live here: https://github.com/bbc/simorgh/blob/cbf7c2b3d08a33775c51eeb94de750d0993a988b/cypress/e2e/pages/homePage/urls.js#L14-L24

**Comment by karinathomasbbc** [comment]
Can we also have a look at the lighthouse tests:

🗑️ 
https://github.com/bbc/simorgh/blob/114ee5056e97ffb7ea94ba14c0af9ead11320688/lighthouse/lighthouserc.js#L2-L5

Add serbian/lat to the live array: https://github.com/bbc/simorgh/blob/114ee5056e97ffb7ea94ba14c0af9ead11320688/lighthouse/lighthouserc.js#L59-L65

**Review by karinathomasbbc — APPROVED** [review]
Niiiice! Thanks for making those updates.

**Comment by louisearchibald** [comment]
> LGTM 🥇
> 
> Out of interest, if we run Simorgh in production mode for live, what do we see?
> 
> ```
> yarn build:live && yarn start
> ```
> 
> If we compare local to the live version of the tipo homepage, are they the same?
> 
> Local	Live (on test environment with renderer_env override)
> http://localhost:7080/serbian/cyr	https://www.test.bbc.com/serbian/cyr?renderer_env=live
> http://localhost:7080/serbian/lat	https://www.test.bbc.com/serbian/lat?renderer_env=live
> http://localhost:7080/zhongwen/simp	https://www.test.bbc.com/zhongwen/simp?renderer_env=live
> http://localhost:7080/zhongwen/trad	https://www.test.bbc.com/zhongwen/trad?renderer_env=live

@karinathomasbbc Both serbian local pages look identical to the live tipo homepages 🎉 ✅ 
However the test zhongwen pages 404? The local ones too so they do match (lol) 😆 but not what I was expecting to see! 🤔

**Comment by karinathomasbbc** [comment]
> However the test zhongwen pages 404?

From doing a bit of digging about, it looks like the zhongwen tipo live page had been last updated in May 2024, meaning that it had possibly not been transliterated. I've re-saved it, and I am hoping that it generates the 2 variants behind the scenes 🤞 . Just waiting for the cache to expire and will try again in a few minutes. 

Otherwise, it could be that these topics won't work until transliteration is live - 5th December?

I think we should just re-check those URLs again closer to the release date, just to make sure everything is OK - I imagine that they will updated by Editorial in preparation for going live.

**Comment by louisearchibald** [comment]
> > However the test zhongwen pages 404?
> 
> From doing a bit of digging about, it looks like the zhongwen tipo live page had been last updated in May 2024, meaning that it had possibly not been transliterated. I've re-saved it, and I am hoping that it generates the 2 variants behind the scenes 🤞 . Just waiting for the cache to expire and will try again in a few minutes.
> 
> Otherwise, it could be that these topics won't work until transliteration is live - 5th December?
> 
> I think we should just re-check those URLs again closer to the release date, just to make sure everything is OK - I imagine that they will updated by Editorial in preparation for going live.

The date was pushed back by Editorial due to some problems found, so it's now 10th December! Thank you (for this and for your review & comments), I'll make a note on the ticket about re-checking these next week. 🙌

**Pull request merged**
