### PR TITLE
GNADTECH-2223 - Update Do Not Sell My Info footer link

### PR DESCRIPTION
**Pull request by jose-de-sousa**
Resolves [GNADTECH-2223](https://jira.dev.bbc.co.uk/browse/GNADTECH-2223)

**Overall change:**
The href value for the footer link "AdChoices / Do Not Sell My Info" has been updated.

**Code changes:**

- _Each instance of the href value has been amended._
- _Snapshots have been updated to reflect this._

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project

**Testing:**

- [X] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by jroebu14 — APPROVED** [review]
Looks good. Thanks for this 🙂

**Review by HarryVerhoef — APPROVED** [review]

**Comment by jroebu14** [comment]
@jose-de-sousa just needs updated with `latest` then we're happy for you to merge these changes 👍

**Comment by jose-de-sousa** [comment]
Hey @jroebu14, @HarryVerhoef, 

Just updating it now, thanks for the reviews.

**Comment by jose-de-sousa** [comment]
Sorry @jroebu14, @hamerm04,

Merging is blocked on the UI tests, which as far as I can tell are not related to this PR. However I'm unsure what the baseline for acceptability is, so am hesitant accept these myself. Could someone have a look and let me know what one should do in this scenrario please?

**Comment by jroebu14** [comment]
@jose-de-sousa no worries at all. We currently have a problem with our UI tests - because of the loading of fonts and images they always fail. I reviewed them and everything looks fine. There also seemed to be a flake with the audio player UI test - seems to be working now though https://bbc.github.io/simorgh/?path=/story/components-media-player--audio-skin

I accepted all as the new baseline and will merge your PR. Thanks for updating these links 🙂

**Comment by jose-de-sousa** [comment]
Great, thanks for assistance @jroebu14, 👍

**Pull request merged**
