### PR TITLE
Use @bbc/psammead-caption

### LINKED ISSUE #1002: Pull Caption component from Psammead
**Is your feature request related to a problem? Please describe.**
Once the component is added into Psammead...:

https://github.com/BBC-News/psammead/issues/57

...we should remove the component from Simorgh and import the Psammead version instead.

**Describe the solution you'd like**
A single PR which removes our code for this component and pulls in the external one.
 
**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Pages should look the same - regression check please.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by sareh**
Resolves #1002

Using `@bbc/psammead-caption`

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by bcmn — DISMISSED** [review]

**Review by ChrisBAshton — DISMISSED** [review]
🎉

**Review by bcmn — DISMISSED** [review]

**Review by ChrisBAshton — DISMISSED** [review]

**Review by pjlee11 — DISMISSED** [review]

**Comment by jamesbrumpton** [comment]
LGTM

**Review by dr3 — APPROVED** [review]

**Review by radiocontrolled — APPROVED** [review]
🍵

**Comment by jamesbrumpton** [comment]
Still LGTM

**Pull request merged**
