### PR TITLE
Navigation translations for simple/traditional scripts

### LINKED ISSUE #4514: Navigation translations for simple/traditional scripts
**Is your feature request related to a problem? Please describe.**
Service configs for UK China and Zhongwen services do not have navigation links for simple/traditional scripts.

**Describe the solution you'd like**
Add navigation links for both simple and traditional scripts for UK China and Zhongwen services. Link to the translations is on Slack.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by OlgaLyubin**
Resolves #4514 

**Overall change:**
Added navigation links for both simple and traditional scripts for UK China and Zhongwen services.

**Code changes:**
Added navigation translations to service configs.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by DenisHdz — APPROVED** [review]
LGTM

**Review by sareh — APPROVED** [review]

**Comment by PriyaKR** [comment]
Testing:

The navigation links when on `ukchina/simp` and `ukchina/trad` seem to link to simp and trad nav links when on frontpage.

But in case for eg when on `http://localhost:7080/ukchina/trad/horizon` and clicking on the sport nav it links to `http://localhost:7080/ukchina/simp/sport` is this expected behaviour?

**Comment by OlgaLyubin** [comment]
> Testing:
> 
> The navigation links when on `ukchina/simp` and `ukchina/trad` seem to link to simp and trad nav links when on frontpage.
> 
> But in case for eg when on `http://localhost:7080/ukchina/trad/horizon` and clicking on the sport nav it links to `http://localhost:7080/ukchina/simp/sport` is this expected behaviour?

Talked to my pod about this issue and it's decided that for now we can go ahead and merge this PR since ukchina and zhongwen are not live anyway. However, a  GitHub issue was raised about the problem with trad/simple variants not working properly:
https://github.com/bbc/simorgh/issues/4557

**Comment by PriyaKR** [comment]
Otherwise it looks good and can be merged.

**Pull request merged**
