### PR TITLE
Fix AMP validation failures for TC2 MAPs

### LINKED ISSUE #5782: Failing AMP Validation on TC2 Assets
**Is your feature request related to a problem? Please describe.**
AMP validation is failing on TC2 asset pages. 
e.g. https://validator.ampproject.org/#url=https%3A%2F%2Fwww.bbc.com%2Findonesia%2Fbahasa_inggris%2F2016%2F08%2F160817_video_inggris.amp

This is also causing the E2E tests to fail, so we had to temporarily disable them

We need to ensure we provide an image placeholder. 

**Describe the solution you'd like**
The TC2 ARES response does provide an image, but it is too small.

- The amp placeholder that's used within live radio is the correct colour.
- The 'media asset revoked'/'cannot be played' placeholder is the correct size

Use the default grey image and bbc image block as our amp iframe image placeholder. 

The logic that handles this placeholder is within `getPlaceholderSrcSet` inside the `MediaPlayerContainer` component.

**Testing notes**
- [x] This feature is expected to need manual testing.

Test Environment: https://validator.amp.dev/#url=https%3A%2F%2Fwww.test.bbc.com%2Fpersian%2Firan%2F2016%2F09%2F160907_tc2_testmap1.amp 
Live Environment: https://validator.ampproject.org/#url=https%3A%2F%2Fwww.bbc.com%2Findonesia%2Fbahasa_inggris%2F2016%2F08%2F160817_video_inggris.amp

**Additional context**
- The AMP validator chrome plugin will help debug

- [x] Add MAPs & Legacy MAPs to the AMP Validation test
- [x] Re-enable TC2 E2Es in all environments

### PR DESCRIPTION
**Pull request by karinathomasbbc**
Resolves #5782

**Overall change:** 
AMP Validation was failing on TC2 MAPs because src and srcSet was not defined for the iFrame. This is because TC2 MAPs do not currently have image placeholders for the media player, unlike CPS MAPs.
Image placeholders will be available in AReS v2, so in the meantime, a placeholder (grey background) image will be used instead.

**Code changes:**
- If locator or originCode return empty string & associated test
- If imageURL is empty string, use the default image which is the amp_audio_placeholder.png (used for live radio)
- Add MAPs and TC2 MAPs to CI AMP validation
- Re-enable E2Es for TC2 MAPs 

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Review by jroebu14 — APPROVED** [review]
Looks good although I think `utilities` is the norm instead of `helpers` in Simorgh

**Comment by karinathomasbbc** [comment]
> Looks good although I think `utilities` is the norm instead of `helpers` in Simorgh

Done :+1

**Comment by rebeccamcginn** [comment]
Did you consider using the existing transformer to add the imageUrl? 

https://github.com/bbc/simorgh/blob/latest/src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/legacyMedia/index.js

**Comment by ryanmccombe** [comment]
> Did you consider using the existing transformer to add the imageUrl?
> 
> https://github.com/bbc/simorgh/blob/latest/src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/legacyMedia/index.js

Aye there's a lot more going on here than I'd have expected.  I was under the impression all the logic for building the `srcSet` stuff was already there from the work articles did

I think simply adding an image URL to the JSON (eg, in the transformer) will cause this to start working, in the same way we did for the CPS maps: https://github.com/bbc/simorgh/blob/latest/src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/media/index.js#L36-L54

**Comment by karinathomasbbc** [comment]
> Did you consider using the existing transformer to add the imageUrl?
> 
> https://github.com/bbc/simorgh/blob/latest/src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/legacyMedia/index.js

I did not 😞 I'll take a look, thanks.

**Pull request closed without merging**
