### PR TITLE
Remove penultimate story promo list border

### LINKED ISSUE #5594: Story Promo List - border bottom
**Describe the bug**
In sections with 13 promos, the last row with regular promos without images takes two columns within 600-1007px.  

Since we remove the `border-bottom` from the last `story-promo-list` item in the list, we end up having this situation where the penultimate item has a border, not looking great.

Screenshot 2020-02-18 at 16 08 46

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to a Front Page with a section which has 13 promos
2. Resize the window between `600` and `1007`px
3. Scroll down to where the promos without image are

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves https://github.com/bbc/simorgh/issues/5594

**Overall change:** 
After adding the `border` prop to the `StoryPromoList` we can now determine when not to display it.

**Code changes:**
- Hide border from the penultimate story promo list when used to wrap promos without images 
- Bump `@bbc/psammead-story-promo-list`
- Update snapshots

**Before:**
before

**After:**
after

---

- [X] I have assigned myself to this PR and the corresponding issues
- [X] I have added labels to this PR for the relevant pod(s) affected by these changes
- [X] I have assigned this PR to the Simorgh project

**Testing:**
- [X] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [X] This PR requires manual testing

### CODE REVIEW

**Review by OlgaLyubin — COMMENTED** [review]
Looks good on all browsers and storybook 👍 Just needs snapshots to be updated because Jenkins is complaining

**Review by OlgaLyubin — APPROVED** [review]
LGTM 👍

**Review by Bopchy — CHANGES_REQUESTED** [review]
Looks great! 

Needs conflicts to be fixed though. Otherwise LGTM 👍

**Review by Bopchy — APPROVED** [review]

**Comment by PriyaKR** [comment]
Looks good to me.

Screenshot 2020-04-02 at 16 25 37

**Pull request merged**
