### PR TITLE
Added persian live asset ID to cypress test

### LINKED ISSUE #2335: Add live Persian asset to articleSpec e2e's
**Is your feature request related to a problem? Please describe.**
As part of https://github.com/bbc/simorgh/pull/2332 we skipped the Persian articleSpec as the asset used was no longer available on live.

**Describe the solution you'd like**
When we have Persian articles available on live we should update the config with the correct live and test assets.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Cypress tests passing are valid regression

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by HarveyPeachey**
Resolves #2335

**Overall change:** Added live [asset](https://www.bbc.com/persian/articles/c7eel0lmr4do) to Persian Cypress tests.

**Code changes:** 

- Added live Persian asset to end to end tests

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by dr3 — APPROVED** [review]

**Review by RayNjeri — APPROVED** [review]
LGTM

**Review by sareh — APPROVED** [review]
:+1: Looks good!

**Comment by HarveyPeachey** [comment]
This might be blocked on #2916

**Comment by jamesbrumpton** [comment]
This is blocked pending https://github.com/bbc/simorgh/issues/2916

**Review by jamesdonoh — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
It doesn't need any further testing, putting it to ready for merge..

**Pull request merged**
