### PR TITLE
Use "property" attribute on facebook's "og:" meta tags

### LINKED ISSUE #5305: Fix metadata key for Facebook Open Graph only
**Describe the bug**
Currently our metadata follows a structure relatively similar to this

```html
<meta name="description" content="blah" />
<meta name="og:*" content="blah" />
<meta name="twitter:*" content="blah" />
```

Whilst this is all well and good for typical `meta` tags (such as `description`), and for [Twitter's Cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started), it is not suitable for [Facebook's Open Graph](https://developers.facebook.com/docs/sharing/opengraph/using-objects#create) format.

Our Open Graph meta tags should follow the following structure:

```html
<meta property="og:*" content="blah" />
```
**Note: the `name` key is replaced with `property`**

This should **only** apply to `og:` meta tags.

Thankfully, [Twitter](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#twitter-cards-and-open-graph) is able to interpret this format too.

**To Reproduce**
Steps to reproduce the behaviour:

1. Observe the `head` of any Simorgh page
2. Note the `meta` tags where `name="og:*"`
3. See mismatch with OG standard [defined here](https://developers.facebook.com/docs/sharing/opengraph/using-objects#create).

**Expected behaviour**
Open Graph tags should have a key of `property`, and not `name`.

**Screenshots**
image

**Testing notes**

- [x] This bug fix is expected to need manual testing.
- [x] Snapshots will need updating

### PR DESCRIPTION
**Pull request by pharingee**
Resolves #5305

**Overall change:** 
Fix facebook's open graph sharing data.

**Code changes:**
- Rename `name` attribute to `property`
- Update unit tests
- Update e2e tests

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by karinathomasbbc — APPROVED** [review]
Looks good 👍

**Review by FK78 — APPROVED** [review]

**Review by HarveyPeachey — APPROVED** [review]
LGTM

**Review by 12 — APPROVED** [review]
Looks good. Have run through the open graph debug tool again and error has cleared. Good job 👍

**Comment by 12** [comment]
Also passes Twitter validation tool.

**Pull request merged**
