### PR TITLE
Remove react-universal-app and copy across

### LINKED ISSUE #1219: Remove react-universal-app dependency
**Is your feature request related to a problem? Please describe.**
"We were using after.js but it made lots of assumptions about your project structure (and not really maintained). It provided a wrapper around React-routing. We built our own as we needed the control. We could use React-routing directly in Simorgh, which is what most people do. Can also look at next.js."

**Describe the solution you'd like**
A PR to remove the `react-universal-app` dependency, and copy over the necessary parts (i.e. the [src/](https://github.com/jtart/react-universal-app/tree/master/src) folder). Remember to give Jordan credit (comment, etc)!

**Describe alternatives you've considered**
Leave in, but react-universal-app is likely to change in the future and may no longer suit our requirements.

It's also an additional abstraction complication when onboarding new joiners.

**Testing notes**
Regression testing of the application/article page.

Dev insight: Regression test only.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by dr3**
Resolves #1219 

**Overall change:** Move the `react-universal-app` code base over to simorgh, giving credit

This is direct move across with only a few changes to appease eslint. This will be refactored in a future PR.

**Code changes:**

- Copy the code across
- Add enzyme temporarily to be refactored out at a later date 
---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [x] Test engineer approval
- [x] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by ChrisBAshton — APPROVED** [review]
Nice one Drew 👍 (thanks for everything, @jtart !)

**Review by sareh — APPROVED** [review]
👍 Looks good. We can refactor the work in future PRs.

**Comment by jtart** [comment]
Build it with hooks!

**Comment by jamesbrumpton** [comment]
LGTM 👍

**Pull request merged**
