### PR TITLE
Introduce BBC Reith Qalam and improved Social Embed lazy-loading

### LINKED ISSUE #7946: Update service configs for Arabic, Pashto, Persian & Urdu to use Qalam
**Is your feature request related to a problem? Please describe.**
Update service configs for all RTL services to use Qalam instead of Nassim font

**Describe the solution you'd like**
- Replace references of `F_NASSIM*_BOLD` `F_NASSIM*_REGULAR` with `F_QALAM_BOLD` and `F_QALAM_REGULAR` respectively
- Update Arabic font https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/arabic.js#L267
- Update Persian font https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/persian.js#L274
- Update Pashto font https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/pashto.js#L262
- Update Urdu font https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/urdu.js#L250
- Update tests & snapshots as appropriate

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by simonsinclair**
No issues, but also resolves https://github.com/bbc/simorgh/issues/7946.

### To be completed
- ~~Fix CORS on https://ws-downloads.test.files.bbci.co.uk~~ Thanks, @chris-hinds .
- ~~Upload Reith Qalam fonts to https://ws-downloads.files.bbci.co.uk (live).~~
- ~~Merge https://github.com/bbc/simorgh/pull/8453 into this branch.~~
- ~~UX review.~~

### Overall change

This PR introduces BBC Reith Qalam, which replaces BBC Nassim. Due to the way in which dependencies are updated, it also includes @andrewscfc's improvements to Social Embed lazy-loading.

Screenshot 2020-11-26 at 15 16 19

### Code changes

- A whole lot of package updates.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project

### Testing

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] ~~If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)~~
- [x] This PR requires manual testing [See comment](https://github.com/bbc/simorgh/pull/8452#issuecomment-734357502)

### CODE REVIEW

**Comment by simonsinclair** [comment]
CORS policy errors will prevent this PR from being tested locally unless a plugin like [Allow CORS](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en) is installed. @chris-hinds is looking into a longterm solution for this.

**Review by andrewscfc — APPROVED** [review]

**Review by chris-hinds — APPROVED** [review]

**Review by SetJackal — APPROVED** [review]

**Comment by simonsinclair** [comment]
This PR has been reviewed by Fan from UX.

**Comment by paruchurisilpa** [comment]
Not able to check social embeds lazy loading PR of Andrews as part of this ( as its integrated with Reith Qalam PR) because I didnt find any social embeds stories but I have tested that in isolation which works fine.

**Comment by paruchurisilpa** [comment]
Progress so far:

Checked Reith Qalam fonts for Urdu/Pashto/Persian and Arabic pages and the font loads OK and didn’t notice any styling issues on various pages across browsers and devices.

http://simorgh-infrastructure.api.bbci.co.uk/arabic
http://simorgh-infrastructure.api.bbci.co.uk/pashto
http://simorgh-infrastructure.api.bbci.co.uk/urdu
http://simorgh-infrastructure.api.bbci.co.uk/persian
http://simorgh-infrastructure.api.bbci.co.uk/arabic/middleeast-53435260 — Recommendations
http://simorgh-infrastructure.api.bbci.co.uk/arabic/magazine-54029177 — FIX pages
http://simorgh-infrastructure.api.bbci.co.uk/urdu/entertainment-55157674 - STY
http://simorgh-infrastructure.api.bbci.co.uk/urdu/entertainment-55157674.amp - AMP Page

Needs to check PGL, includes , IDT2 content

**Comment by paruchurisilpa** [comment]
http://simorgh-infrastructure.api.bbci.co.uk/urdu/pakistan-55119555 --> PGL
https://www.bbc.com/arabic/world-50151093 --> Includes

Tested most of the assets and they look good to me.

Happy for this to be merged..

**Pull request merged**
