### PR TITLE
Add external link translations

### LINKED ISSUE #9333: Update external links translations
**Is your feature request related to a problem? Please describe.**

> As a WS screenreader user
> I want external links to be identified as <external> in my language
> so that I know if I click on the link I'll be taken from the BBC website

Currently some of the translations for WS are "external link" where the translation should be "external" as the screen reader adds the semantics of 'link' itself.

Some users are having the experience where the word link is announced twice, once from the translation and once from the screen reader semantics e.g. 'Google, external link, link'.

Depending on the screen reader it should be announced as 'Google, external, link' or 'Link, Google, external')

**Describe the solution you'd like**
Update the services configs for external links with the label "External" in the spreadsheet here on line 32 where required: https://docs.google.com/spreadsheets/d/1f1x53UDjmzJCf0Pv94t1AOPceCapolFxeu77LMyA4IM/edit?usp=sharing

the RtoL languages will need extra checks with editorial for the ordering of the linktext 

<google-sheets-html-origin><style type="text/css"></style>

Service|Text|RtoL
---|---|---
Persian | [linktext]، خارجی |RtoL
Igbo | [linktext], na mpụta
Pidgin | [linktext], outside
Yoruba | [linktext], ìta
Urdu | [linktext], بیرو |RtoL
Pashto | بهرنی [linktext] |RtoL 
Arabic | [linktext]، خارجي |RtoL
Thai | [linktext] จากภายนอก
Punjabi | [linktext], ਬਾਹਰੀ
Afaan Oromoo | [linktext], alaan
Amharic | [linktext], ውጫዊ
Indonesian | [linktext], eksternal
Tigrinya | [linktext] ደጋዊ
Korean | [linktext], 외부 사이트
Afrique | [linktext], externe
Gahuza | [linktext], bivuye ahandi
Somali | [linktext], kale
Swahili | [linktext], ya nje
Azeri | [linktext], BBC-dən kənar
Hausa | [linktext], waje
Vietnamese | [linktext], bên ngoài
Kyrgyz | [linktext], баракчалар
Japanese | [linktext]は外部ページです
Nepali | [linktext], बाह्य
Uzbek (Cyrillic) | [linktext], ташқи
Uzbek (Latin) | [linktext], tashqi
Sinhala | [linktext], බාහිර
Bengali | [linktext], বাইরের
UK China (Simp) | [linktext], 外部
UK China (Trad) | [linktext], 外部
Turkce | [linktext], dış
Burmese (Unicode) | [linktext] ပြင်ပစာမျက်နှာ
Cymru Fyw | [linktext], dolen allanol
Gujarati | [linktext] બહારની
Marathi | [linktext], बाहेर
BBC News Mundo | [linktext], externo
Naidheachdan | [linktext], taobh a-muigh
Portuguese | [linktext], externo
Russian | [linktext], внешняя
Serbian(Cyr) | [linktext], спољна
Serbian (Lat) | [linktext], spoljna
Tamil | [linktext], வெளி
Telugu | [linktext], ఇతర
Ukrainian | [linktext], зовнішнє
Russian for the Ukrainian service | [linktext], внешняя  
Hindi | [linktext], बाहरी
Zhongwen (Simp) | [linktext], 外部
Zhongwen (Trad) | [linktext], 外部

**Describe alternatives you've considered**

**Expected behaviour:**
Given I use a screenreader 
When I navigate to an external link on an optimo page
it should announce the link name, external and the screen reader semantics of link
and external should be in the language of that article

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

### PR DESCRIPTION
**Pull request by nicola-d-bbc**
Resolves #9333

**Overall change:**
Added updated translations to external link text in service config.

**Code changes:**

- Updated externalLinkText to provided text.
---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by pvaliani — APPROVED** [review]
Nice one!

**Review by Louis-Matsika — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]

**Comment by greenc05** [comment]
I'm unsure if all the translations have a 'comma'?

**Comment by LilyL0u** [comment]
In the Arabic translation, is there supposed to be a comma and an apostrophe?

, ، خارجي

Do you have the translation sheet link? Means if things like this are actually correct I won't think they might not be and keep asking you!

**Comment by nicola-d-bbc** [comment]
> In the Arabic translation, is there supposed to be a comma and an apostrophe?
> 
> , ، خارجي
> 
> Do you have the translation sheet link? Means if things like this are actually correct I won't think they might not be and keep asking you!

Hey, there's a table of translations on the linked ticket, and can also be found here: https://docs.google.com/spreadsheets/d/1f1x53UDjmzJCf0Pv94t1AOPceCapolFxeu77LMyA4IM/edit?usp=sharing

**Comment by LilyL0u** [comment]
It is hard to tell because some of the translations in the translation sheet have commas and some don't (as @greenc05 pointed out), but I think Arabic has a double comma in it in the code. The apostrophe is the arabic comma 

'The comma in the Arabic script (used by Arabic, Urdu, and Persian, etc.) is inverted, upside-down: ⟨،⟩ ( U+060C ، ARABIC COMMA), in order to distinguish it from the Arabic diacritic ḍammah ⟨ُ⟩, representing the vowel /u/, which is similarly comma-shaped.' 

and so when there is also another comma added it means there are two.

On the other side of this, in the code for Urdu you have an inverted comma, but in the Urdu translation in the translation sheet there is an english alphabet comma ',' However, in that above info it says Urdu also uses the inverted comma, and I can see that in the other parts of the code the inverted comma is used. So I think you were probably right to use the inverted comma even though it isn't in the translation sheet 🤞

**Pull request merged**
