### PR TITLE
Remove now deploy step from travis and now.json

### LINKED ISSUE #1252: Replace now.sh usage with GitHub pages
**Is your feature request related to a problem? Please describe.**
We can't continue using now.sh: https://simorghstorybook.now.sh/

We should follow the [psammead approach](https://github.com/bbc/psammead) and make our Storybook available on GitHub Pages: https://bbc.github.io/psammead/

**Describe the solution you'd like**
A PR to Simorgh and Infrastructure to remove usage of now.sh and add GitHub Pages deployment to our pipeline. Then we should delete our now.sh account for housekeeping.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Once merged, we should be able to visit https://bbc.github.io/simorgh/ and see our Simorgh Storybook and https://simorghstorybook.now.sh should 404.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by chris-hinds**
Resolves #1252 

**Overall change:** 
This PR removes the now.sh deploy stage from Travis which was used to deploy the Simorgh Storybook to Now.

**Code changes:**

- Removed now.sh deploy stage from travis.yaml
- Removed now.json as it it no longer required

---

- [X] I have assigned myself to this PR and the corresponding issues
- [N/A] Tests added for new features
- [ ] Test engineer approval
- [X] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by ChrisBAshton — APPROVED** [review]

**Review by dr3 — APPROVED** [review]

**Comment by dr3** [comment]
We should also disable the now.sh service, I think that might be @benjaminhobbs?

**Comment by jamesbhobbs** [comment]
@dr3 it's actually on my personal account, so there's nothing to deactivate. The only thing needed is removing the token from travis, I can do this once this is merged, someone remind me

**Comment by chris-hinds** [comment]
This needs another review by someone with write access before it can be merged. @benjaminhobbs do you mind giving a thumbs up?

**Comment by jamesbrumpton** [comment]
Happy for this to be merged when possible.

**Review by pjlee11 — APPROVED** [review]

**Comment by chris-hinds** [comment]
> @dr3 it's actually on my personal account, so there's nothing to deactivate. The only thing needed is removing the token from travis, I can do this once this is merged, someone remind me

Reminder to remove the token from Travis @benjaminhobbs

**Pull request merged**
