### PR TITLE
Bump packages

### PR DESCRIPTION
**Pull request by samora**
Resolves #NUMBER

**Overall change:** Merged and fixed conflicts in dependabot PRs.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Review by jamesdonoh — APPROVED** [review]
Looks good, thanks @samora, this definitely needs manual testing.

**Review by oluoluoxenfree — APPROVED** [review]
You've got conflicts, otherwise looks fine to me

**Comment by amywalkerdev** [comment]
Bundle sizes need updating:

Bundle size for Burmese is too large at 651 kB. Please update thresholds in './scripts/bundleSizeConfig.js'
etc

**Comment by PriyaKR** [comment]
Looks good to me.

**Comment by PriyaKR** [comment]
Looks good to me.

**Pull request merged**
