### PR TITLE
updated podcast brasil with new apple link

### LINKED ISSUE #9477: Update Brasil podcast third party links
**Is your feature request related to a problem? Please describe.**
Update the third party/external links for a Brasil (portuguese) podcast brand. 

Brand PID - p09qw1cn

Live page: https://www.bbc.com/portuguese/podcasts/p09qw1cn

Following link to be added to the page, displayed before the RSS feed link: 

Apple - https://podcasts.apple.com/us/podcast/bbc-l%C3%AA/id1586358051

External links data can be found here in Simorgh: https://github.com/bbc/simorgh/tree/latest/src/app/routes/onDemandAudio/tempData/podcastExternalLinks

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

### PR DESCRIPTION
**Pull request by DarioR01**
Resolves #9477

**Overall change:**
Added new apple link to Podcast Brasil

**Code changes:**

- expanded json file for podcast external link brasil to have an extra redirect on Apple podcast

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by amoore108 — APPROVED** [review]

**Review by MuhammadAHussain — APPROVED** [review]
LGTM 👍

**Comment by skwong25** [comment]
**Testing**

- Apple podcast link is present and functioning on the webpage. Tested locally on the following: 
- Desktop: Firefox, Safari, Chrome, Opera
- Mobile: Chrome, Opera Mini, Samsung Browser

Comments: 

1. Noticing strange behaviour with the podcast links, including the Apple link. Sometimes they open with a single click and sometimes _only_ with a double click (i.e non-responsive after a single click). This is happening across the majority of desktop & mobile browsers (e.g Desktop - Firefox Chrome, Opera). I would have expected these links to open with a single click but not sure what the design is.

2. On some mobile devices (e.g Samsung Galaxy S21) the addition of the Apple link pushes the links over two lines. I believe this is intended, however we think the grey line (e.g after 'Arquivo completo' in below screenshot) should not go over to the second line as it becomes an unnecessary divider that throws off the alignment. It's suggested that this could be fixed by not allowing the line to ‘travel alone’ - it needs to stay with the preceding words even if it means all the words go onto the next line. 

Samsung Galaxy S21 Chrome

**Comment by gavinspence** [comment]
Thanks for raising these issues @skwong25! As @rebeccamcginn mentioned, I think we can raise a separate ticket for the first issue on links requiring double click to open. I assume it will be a bug across other podcast pages with this component. 

@emilymynall can you take a look at how this component should flow over 2 lines? I believe this is according to spec, but if we want to make changes then we can raise a separate issue. Happy for this to be merged and we can follow up accordingly.

**Comment by emilyatkins** [comment]
@gavinspence design is fine - all as per spec when running over 2 lines

**Comment by skwong25** [comment]
Thanks @gavinspence @emilyatkins for looking at the above! I have created a new bug ticket capturing the general single-click issue: https://github.com/bbc/simorgh/issues/9510. Will move this ticket into Ready To Merge column.

**Pull request merged**
