### PR TITLE
Updates to Korean, Pashto, Persian, Serbian and Uzbek nav bars

### PR DESCRIPTION
**Pull request by jordit**
Resolves JIRA n/a

Overall changes
======
Updates to navs to replace Most watched with Video topics, add radio link to Korean, Tv bulletin to Uzbek and Satelite TV to Pashto

Code changes
======

- Replaced /media/video with video topic on Persian, Pashto, Serbian Latin and Serbian Cyrilic config files
- Replaced /media/video with link with TV bulletin page on Uzbek config
- Added Radio to navigation section on the Korean config.
- Added Satellite TV to navigation section on the Pashto config.

Testing
======
1. Manual tests 
- Nav Video links on Persian (4ht link), Pashto (7th link on nav) Serbian Latin and Serbian Cyrillic (6th link) open video topics not Most watched
- last link on Uzbek nav opens Video bulletin page (www.bbc.com/uzbek/bbc_uzbek_tv/tv_programmes/w13xttqv)
- third link on Korean nav opens Radio programme page (www.bbc.com/korean/bbc_korean_radio/programmes/w13xttll)

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

### CODE REVIEW

**Comment by karinathomasbbc** [comment]
Testing: 
✅ [Korean Radio](https://fa-ko-ps-sr-uz-navs--5d28eb3fe163f6002046d6fa.chromatic.com/iframe.html?args=&knob-Select%20a%20service=korean&id=containers-navigation--canonical&viewMode=story) 
✅ [Pashto Satellite Broadcast & Video](https://fa-ko-ps-sr-uz-navs--5d28eb3fe163f6002046d6fa.chromatic.com/iframe.html?args=&knob-Select%20a%20service=pashto&id=containers-navigation--canonical&viewMode=story)
✅ [Persian Video](https://fa-ko-ps-sr-uz-navs--5d28eb3fe163f6002046d6fa.chromatic.com/iframe.html?args=&knob-Select%20a%20service=persian&id=containers-navigation--canonical&viewMode=story)
✅ [Uzbek TV Bulletin](https://fa-ko-ps-sr-uz-navs--5d28eb3fe163f6002046d6fa.chromatic.com/iframe.html?args=&knob-Select%20a%20service=uzbek&id=containers-navigation--canonical&viewMode=story)
✅ [Serbian cyr video](https://fa-ko-ps-sr-uz-navs--5d28eb3fe163f6002046d6fa.chromatic.com/iframe.html?args=&knob-Select%20a%20service=serbianCyr&id=containers-navigation--canonical&viewMode=story)
✅ [Serbian lat video](https://fa-ko-ps-sr-uz-navs--5d28eb3fe163f6002046d6fa.chromatic.com/iframe.html?args=&knob-Select%20a%20service=serbianLat&id=containers-navigation--canonical&viewMode=story)

**Review by karinathomasbbc — APPROVED** [review]
🎸

**Comment by jordit** [comment]
thanks @karinathomasbbc

**Review by amoore108 — APPROVED** [review]

**Comment by jordit** [comment]
thank you as ever @amoore108 have a great Easter break

**Comment by amoore108** [comment]
> thank you as ever @amoore108 have a great Easter break

Same to you @jordit !

**Pull request merged**
