### PR TITLE
Add caption block to MediaPlayer

### LINKED ISSUE #866: Video/Audio Caption
**Is your feature request related to a problem? Please describe.**
We should display a caption if the media block has caption data.

**Describe the solution you'd like**
We should have this stucture:
```
<figure>
    <video />
    <figcaption>caption here</figcaption>
</figure>
```

Note that we should ensure this works for the AMP variant as well as for canonical.

- The approach should reuse/adapt the existing image caption code as far as possible to reduce maintenance overhead.
- We should ensure that italics are still not rendered in video captions for Arabic-script sites (as with image captions).

We should have a storybook item showing the Video block with Caption for AMP and Canonical variants. Can use the Image examples in Psammead as a reference of how to have AMP and Canonical variants: https://bbc.github.io/psammead/?path=/story/image-ampimg--landscape-image
https://github.com/bbc/psammead/tree/latest/packages/components/psammead-image/src

The caption should be the same one as that used for the image, except this has visually hidden text that says 'Video caption,' or 'Audio caption,' rather than 'Image caption,'. 

screen shot of video in article

https://app.zeplin.io/project/5baa564c05c2eba0d2b89568/screen/5c596fa94e189735593e60e8

Note: captions can display rich text formatting.

**Describe alternatives you've considered**
N/A

**Testing notes**

This should only have unit tests for the component, since it won't be integrated into the article yet.
The caption should meet all accessibility criteria that exist for the image caption. 

This will require an `a11y` swarm once the logic is ready/available.

We can test using fixture data taken from this Test article. This is because this article has a variety of video blocks: https://www.test.bbc.co.uk/news/articles/c2nn1prnl39o.json 

Storybook should have an example of a 'video component' without a caption and one with a caption. Note: the 'video component' renders just text values at the moment - we have another PR to add in an actual video element.

Captions on RTL services (Arabic, Persian, Pashto and Urdu) can't use italics, so audio/video captions should not appear in italics.

**Additional context**
**This issue does not have a video rendering as a prerequisite.** It should be sufficient to just have a figure and a figcaption element, without the video actually rendering. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by 12**
Resolves #866 

**Overall change:** Adds caption back to media player block. 

**Code changes:**

- Modify `MediaPlayer/index.jsx` to display the media caption beneath the player / placeholder if it exists
- Update snapshots
- Add Cypress E2E test to verify that the caption is displayed.
- Added unit test coverage for captions.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Review by RayNjeri — APPROVED** [review]
Tested with this test asset `c3wmq4d1y3wo` LGTM.

**Review by rhenshaw56 — APPROVED** [review]

**Review by jamesdonoh — CHANGES_REQUESTED** [review]
I think we also need explicit unit test coverage for when there is/is not a caption (on both AMP/canonical).

https://github.com/bbc/simorgh/blob/latest/src/app/containers/MediaPlayer/index.test.jsx seems to only use ~one~two fixtures and doesn't check the output for the different possible variations in blocks data.

Compare https://github.com/bbc/simorgh/blob/latest/src/app/containers/ArticleFigure/index.test.jsx that tests a number of different variations.

**Comment by jamesdonoh** [comment]
In addition this PR needs a two-engineer a11y swarm.

**Review by jamesbrumpton — APPROVED** [review]
I'm happy with the Cypress tests

**Review by jamesdonoh — APPROVED** [review]
Yep!

**Comment by HarveyPeachey** [comment]
**A11y Swarm**

_(Rowland):_
- [x] https://bbc.github.io/accessibility-news-and-you/accessibility-news-and-testers
  - [x] Axe
  - [x] Design
  - [x] Colour Contrast
  - [x] Colour blindness
  - [x] Windows HCM
  - [x] FF Colour Preferences
  - [x] Text 200%, Page 200%
  - [x] Icons
  - [x] Heading Order
  - [x] Keyboard Navigation - Tab navigation isn't working as expected as it skips article content on asset: c3wmq4d1y3wo - This might be to do with placeholders not caption as caption is not a link
  - [x] No JS (n/a)

_(Harvey):_
- [x] Screen readers
  - [x] ZoomText Magnifier/Reader
     - 8- Reads out caption text but doesn't mention it is a video caption
     - 9- Same as above
     - 10- Same as above
  - [x] Dragon NaturallySpeaking
  - [x] JAWS
     - 4- Reads out "video caption" then "blank" then the video caption text.
  - [x] Read&Write 
     - 4- Reads out the video caption text with no mention of it being a video caption, if caption is highlighted.
     - 5- If whole article is highlighted then it will read out "video caption" before reading out the caption text.
     - 6- It will only read out "video caption" if the mouse is held right at the beginning of the caption.

_Mac, iOS, and Android (Ray):_ 
- [x] VoiceOver iOS (iPhone/iPad)
- [x] VoiceOver OS (Mac)
- [x] TalkBack (Chrome on Android)

**Comment by greenc05** [comment]
Sounds as expected for ZoomText, Jaws and Read&Write

Please double check that it’s the same for Jaws when looking at an image with a caption e.g. 
Reads out “image caption” then “blank” then the image caption text.

And lets re-check the keyboard navigation, did it skip the entire page content including the banner and footer links? If so it’s your settings… (and note that the caption shouldn't be in the tab order, but the play button should be)

**Comment by HarveyPeachey** [comment]
> Sounds as expected for ZoomText, Jaws and Read&Write
> 
> Please double check that it’s the same for Jaws when looking at an image with a caption e.g.
> Reads out “image caption” then “blank” then the image caption text.
> 
> And lets re-check the keyboard navigation, did it skip the entire page content including the banner and footer links? If so it’s your settings… (and note that the caption shouldn't be in the tab order, but the play button should be)

~Look like it isn't the same as with an image caption Jaws doesn't say "blank" in between, I'm not sure what's causing this blank to be read out.~ This is the same as the Figure Image caption as they both say blank on IE11.

Keyboard navigation is fine it didn't skip the navigation parts of the page only the content with the video players, this is because the Play button work hasn't been brought into Simorgh yet so this has nothing to do with this PR.

**Comment by jamesbrumpton** [comment]
lgtm

**Pull request merged**
