### PR TITLE
Persian article redirect tests

### LINKED ISSUE #1704: Article redirect tests
**Is your feature request related to a problem? Please describe.**

Where _:service_ is any service that should be served exclusively off .com (that is all non-UK services)

_NB scenarios below in strikethru relating to HTTPS uplift are out of scope till https://github.com/bbc/simorgh-infrastructure/issues/632 is resolved_

**Not .co.uk**

Given I go to https://www.bbc.co.uk/:service/articles/:id
Then I am given a 301 redirect to https://www.bbc.com/:service/articles/:id

~**Not http**~

~Given I go to http://www.bbc.co.uk/:service/articles/:id~
~Then I am given a 301 redirect to https://www.bbc.com/:service/articles/:id~

**AMP not on .co.uk**

Given I go to https://www.bbc.co.uk/:service/articles/:id.amp
Then I am given a 301 redirect to https://www.bbc.com/:service/articles/:id.amp

~**AMP not on http**~

~Given I go to http://www.bbc.co.uk/:service/articles/:id.amp~
~Then I am given a 301 redirect to https://www.bbc.com/:service/articles/:id.amp~

**Describe the solution you'd like**
- We should handle redirects within Mozart https://github.com/bbc/simorgh-infrastructure/issues/435. This ticket is only capturing the testing of redirects for our application. 
- These tests should only run against Test and Live environments, not local. 
- These can be run separately to the PR life cycle as a cron job.

Note: that until all of these services are routed on live, the tests should only be run against the test environment. An issue should be created to enable these on live when they are available.

**Describe alternatives you've considered**
We considered having the Cypress end-to-end tests in our current test suite repository, but decided against it - see the discussion thread below

**Testing notes**
We will need to add Cypress tests to make sure that the redirects happen as expected.
`Given I visit URL A, When I am redirected (served a 301 redirect), Then I will land on URL B`

Dev insight: Cypress tests will be sufficient.

### PR DESCRIPTION
**Pull request by alex-magana**
Resolves https://github.com/bbc/simorgh/issues/1704

**Overall change:** Groups test helpers in a directory, `cypressSharedHelpers` and redirect tests to the third party suite.

**Code changes:**

- Adds redirect specs to the `3rdPartyCypress` suite. These tests are meant to serves as a warning for faulty third party dependencies.
- Group shared helpers to avoid duplication.

---
- [ ] Add directory, `3rdPartyCypress`, to exclude patterns, once PR is approved.
    - Run trial with `{3rdPartyCypress,cypress}/{integration,support}/**/*.js` to check if exclude pattern applies to 3rdPartyCypress suite.
    - Addresses `codeclimate — 6 issues to fix`
- [ ] Test redirect specs without branch flags on Travis

---
- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by jamesbhobbs — CHANGES_REQUESTED** [review]
We shouldn't be sharing helpers between cypress instances, this risk failing the production tests which are only run on latest branch. We should duplicate the helpers and config. We also shouldn't use helpers at all and should use commands instead.

**Comment by alex-magana** [comment]
@benjaminhobbs Re 👇 
> We shouldn't be sharing helpers between cypress instances, this risk failing the production tests which are only run on latest branch. We should duplicate the helpers and config. We also shouldn't use helpers at all and should use commands instead.
The shared modules have been reverted. Please let me know if this is fine.

**Comment by jamesbhobbs** [comment]
@alex-magana it's a lot better thanks, I've reassigned this to the core pod as I've just created a new stream of work for them that this fits well with. I've subsequently assigned the PR to myself to handle. You can move while we refactor most of our e2e tests and make this one consistent too.

**Comment by jamesbhobbs** [comment]
Replaced by https://github.com/bbc/simorgh/pull/2817/files

**Pull request closed without merging**
