### PR TITLE
propose new method of styling components

### PR DESCRIPTION
**Pull request by jroebu14**
**Overall change:**
Proposes a change to component standards around how we write styles.

This change is using the `css` prop to write styles rather than using `styled` API from the `@emotion/styled` package.

[Full details here](https://github.com/bbc/simorgh/blob/122ffad4123d13bc7afa2bfa2dd4b03109464ca1/docs/Coding-Standards/Styles.md#use-the-css-prop-from-emotion-with-object-styles-rather-than-the-styled-api).

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by amoore108** [comment]
Looks good! Should we follow or try to stick to any particular convention, as Emotion has a variety of ways of using `css()`, like https://emotion.sh/docs/best-practices#consider-defining-styles-outside-your-components, as well as the other methods in this doc?

**Comment by jroebu14** [comment]
@amoore108 I like that example! [I've updated the code examples to align with that](https://github.com/bbc/simorgh/pull/10248/commits/6a0e61cdb58c561f39505c25f48cd12c63e55d32). Let me know if that looks better.

**Comment by DarioR01** [comment]
Yes, this is looking good. I am a little sad about Styled components, as I liked that approach, but emotion themed seems very interesting if we follow the Best practices that @amoore108 shared.

**Comment by jroebu14** [comment]
Thanks for taking a look @DarioR01. It would be good to hear an argument for sticking with styled components! It's good to challenge new ideas especially if they come from me 😄

**Review by amoore108 — APPROVED** [review]

**Review by RetiredBlob — APPROVED** [review]

**Review by nicola-d-bbc — COMMENTED** [review]
Looks good! Might take some getting used to tho

**Comment by jroebu14** [comment]
@nicola-d-bbc I can help you write some new components in this style 🙂

**Pull request merged**
