### PR TITLE
npm dedupe

### PR DESCRIPTION
**Pull request by jamesbhobbs**
**Overall change:** ran `npm dedupe`

**Code changes:**

- none other than the script run

---

- [x] I have assigned myself to this PR and the corresponding issues
~~- [ ] Tests added for new features~~
- [ ] Test engineer approval

### CODE REVIEW

**Review by dr3 — APPROVED** [review]

**Comment by chris-hinds** [comment]
@benjaminhobbs Snyk is failing die to a HV found in the version of lodash specified in the package-lock.json file.

Snyk Info
```
Introduced through: webpack-merge@4.2.1, babel-plugin-styled-components@1.10.6, assets-webpack-plugin@3.9.10, @babel/core@7.4.5, brotli-webpack-plugin@1.1.0, winston@3.2.1, styled-components@4.3.2, @babel/preset-env@7.4.5, @babel/preset-react@7.0.0
```

Looks like a fix has been pushed to master in lodash however it has yet to be published. As this change is not urgent I'd suggest holding off merging until the HV has been fixed and published.

**Comment by jamesbhobbs** [comment]
@hindsc52 you're right but we already have this vuln: https://snyk.io/test/github/bbc/simorgh

**Review by chris-hinds — APPROVED** [review]

**Comment by jamesbhobbs** [comment]
Note for tester, please just smoke test major functionality across chrome, firefox and IE/opera-mini. Highly unlikely this has broken anything.

**Comment by PriyaKR** [comment]
Looks good to me.

**Pull request merged**
