### PR TITLE
Update config links to be relative

### LINKED ISSUE #2123: Cypress tests failing on non local environments if you're in the UK
**Describe the bug**
Run all E2E tests on test, stage or live and three different groups of tests will fail:
- Amp Cookie Banner Test
- Canonical Cookie Banner Test
- Article Body Tests - checkout this PR https://github.com/bbc/simorgh/pull/1871(this PR combines the `newsBodyspec.js` and `persianBodyspec.js` into one article body tests
This is because we are redirecting to .co.uk and there is this "CypressError: cy.visit() failed because you are attempting to visit a second unique domain."

**To Reproduce**

1. Be in UK
2. Run E2Es against test, stage or live.

**Expected behavior**
Tests pass

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
- This is blocking https://github.com/bbc/simorgh/pull/1871
- We should investigate the bug and if necessary create separate issues for each part of the fix

### PR DESCRIPTION
**Pull request by dr3**
Resolves #2123

**Overall change:** Makes cookie banner links (and others) relative links to fix cypress test issues when in UK

**Code changes:**

- Makes a bunch of links relative

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by sareh** [comment]
@dr3 I suggest we update how we're testing external links in our application, rather than update our links to make testing easier. 

The reason we have absolute links to BBC pages outside of our application, is to ensure we link over https to `https://www*bbc*` pages throughout.

**Comment by dr3** [comment]
@sareh I agree this isnt the perfect solution, its more a quick fix to solve our e2e problem.

>is to ensure we link over https to `https://www*bbc*` pages throughout

Not sure why this is a problem, all simorgh pages are over `https://www*bbc*`, so their relative links will be

**Review by jamesbhobbs — CHANGES_REQUESTED** [review]
All these links now fail locally on manual testing, I don't think this is an improvement. Also, unrelated to this PR, I'm very concerned that this total local breakage breaks no e2es locally.

**Comment by dr3** [comment]
Closing as not desired affect

**Pull request closed without merging**
