### PR TITLE
Create a cypress failure verification step

### PR DESCRIPTION
**Pull request by DemonusPC**
**Overall change:** 
Apparently adding perl to our commands was a bad idea. So it was decided that we need a way to test if correct error codes are produced by cypress. This PR adds a very simple script that runs cypress in a failure state and verifies that the error code is indeed 1. 

**Code changes:**
- Added a simple script that runs cypress in a failure state and flips the error codes.
- Added a make file script to run the boom script. 
- Added a `Verify` step to both the test and live e2e pipeline

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by dr3 — COMMENTED** [review]
.

**Review by dr3 — CHANGES_REQUESTED** [review]
Sorry I dont understand the point of this change. Your running the cypress suite, a whole extra time, to assert its true failure code? Why not just be sure when we run it properly? Seems like a lot of wasted time on an important e2e pipeline

**Comment by jamesdonoh** [comment]
This isn't quite what I was expecting - as described in https://github.com/bbc/simorgh-infrastructure/issues/717 the idea was that there would be a new e2e test(s) that was guaranteed to fail and that we independently verify that failing e2es block release, not just that we rerun the current tests but invert the status.

**Review by jamesdonoh — COMMENTED** [review]
This isn't quite what I was expecting - as described in https://github.com/bbc/simorgh-infrastructure/issues/717 the idea was that there would be a new e2e test(s) that was guaranteed to fail and that we independently verify that failing e2es block release, not just that we rerun the current tests but invert the status.

**Comment by DemonusPC** [comment]
After a conversation with @jamesdonoh it was decided that we should first look at simplifying our commands before we go into testing and verifying them. This will ensure that the solution to this problem will be as simple as possible

**Pull request closed without merging**
