### PR TITLE
Update dependency check

### LINKED ISSUE #2779: Use latest version of dependency-check package
**Is your feature request related to a problem? Please describe.**
as a part of #2778 we locked the dependency-check package to an older known working version.

**Describe the solution you'd like**
To be able to use the latest version of the dependency-check package https://github.com/dependency-check-team/dependency-check/releases

**Describe alternatives you've considered**

**Testing notes**
Doesn't require testing effort from tester.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

### PR DESCRIPTION
**Pull request by samora**
Resolves #2779 

**Overall change:** Update to new version of `dependency-check`.

I found a lot of issues getting `dependency-check` to work. It seems to not have been working properly before because it only finds `require` statements. I found a replacement, `depcheck` which has better support.

Added a script which makes it work to suit our needs.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)

### CODE REVIEW

**Review by chris-hinds — CHANGES_REQUESTED** [review]
Could we improve the console output after running this test. And what happens if we do find unused deps? we would want this script to fail the ci pipeline

By improve I really mean to say, why are we logging an empty object

Current log output

```
0 unused dependencies.

0 missing dependencies.
{}
```

**Review by thekp — APPROVED** [review]
I tested this locally by installing a random module and running your new script, looks like it works.
👍 
image

**Review by EinsteinNjoroge — APPROVED** [review]
LGTM

**Review by chris-hinds — APPROVED** [review]

**Comment by chris-hinds** [comment]
happy for this to be merged once cI passes

**Pull request merged**
