### PR TITLE
Dependabot PRs - Tranche 1

### LINKED ISSUE #1489: nanoid should not be used for keys in lists
**Describe the bug**
We are currently using https://github.com/ai/nanoid to generate `key` props to uniquely identify children in some lists, however `nanoid` values are not stable. The docs for `nanoid` explicitly say not to do this: https://www.npmjs.com/package/nanoid#react

This hurts performance because it prevents React from making optimisations to avoid re-rendering more than it needs do, for more context see https://shripadk.github.io/react/docs/reconciliation.html#keys

Examples of using `nanoid`:
- https://github.com/bbc/simorgh/blob/latest/src/app/containers/Blocks/index.jsx#L23
- https://github.com/bbc/simorgh/blob/latest/src/app/components/ErrorPage/index.jsx#L52

**Expected behavior**
We should be using stable keys for item in lists for optimal render performance.

**Additional context**
Possibly relevant/related: https://github.com/bbc/simorgh/issues/1487

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

### PR DESCRIPTION
**Pull request by ryanmccombe**
Resolves: #1489 (one of these bumps does - sitewide-links)

**Overall change:** Combining all the dependabot PRs that were passing CI into one branch

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Comment by ryanmccombe** [comment]
This should be ready for QA - these dependencies have wide reach so a quick, broad regression test would probaby be the best bet

**Review by chris-hinds — APPROVED** [review]
Updates look good to me, and works as expected locally.

**Review by jamesbhobbs — APPROVED** [review]

**Comment by PriyaKR** [comment]
@ryanmccombe Regression looks good except the IE11 issue - the images doesnt seem to appear on article page `http://localhost:7080/news/articles/c6v11qzyv8po` and frontpage `http://localhost:7080/igbo`

I have also tried to verify whether this is an existing issue on latest branch locally on my machine can't reproduce it on latest branch locally.

**Comment by ryanmccombe** [comment]
@PriyaKR This PR doesn't touch the images so I don't think this is related

Talking to Jonathan about this, we think it might be the same issue that you had on one of his PRs where using `npm run dev` and then looking at the site in IE won't load the polyfills

Latest will also have this issue if you do `npm run dev` on that branch, but it won't have the issue if you're assessing the latest branch using an online server (eg, the test server)

There's a separate issue to look at this problem: https://github.com/bbc/simorgh/issues/2117

**Comment by PriyaKR** [comment]
yeah the IE11 issue is on latest branch too.So this PR looks good can be merged.

**Pull request merged**
