### PR TITLE
Add styled-components babel plugin

### PR DESCRIPTION
**Pull request by jtart**
_Adds a babel-plugin for styled-components to [properly support server-side rendering](https://www.styled-components.com/docs/tooling#serverside-rendering) and to [aid debugging](https://www.styled-components.com/docs/tooling#better-debugging)._

- [ ] ~~Tests added for new features~~
- [x] Test engineer approval

### CODE REVIEW

**Comment by sareh** [comment]
@jtart This looks good. 
Only the `Link` in the `InlineLink` and `Text` snapshots have the classname as a descriptive name `Link`.  Do you know why it is limited to just these two containers?

Looking at the docs here https://www.styled-components.com/docs/tooling#better-debugging I notice that it might be because we're not explicitly setting the `displayName` in our components.

**Comment by jtart** [comment]
@sareh I suspect this is because of the contexts components run in on tests. All components have a descriptive classname on the running application.

**Comment by sareh** [comment]
@jtart OK, thanks. I'd suggest adding `"fileName": false,` to your config, since that will shorten the very long class names, whilst still giving us enough to be able to debug. 

**Before** 
e.g. `MainContent__StyledMainContent-s1t1vsss-0`
screen shot of markup with filenames in classnames

**After** 
e.g.`StyledMainContent-s1t1vsss-0`
screen shot of markup without filenames in classnames

**Comment by jamesbhobbs** [comment]
@jtart should we also use: https://github.com/QuickBase/babel-plugin-styled-components-css-namespace to prepare for when we bring in envelopes or have any external code? I can easily imagine us missing this in the future.

**Comment by jtart** [comment]
@benjaminhobbs it sounds sensible that we might want to use something like that, but i'm loathe to do it in this PR, especially as we haven't spent too much time on Envelope integration yet.

**Comment by sareh** [comment]
@benjaminhobbs Were you thinking of something like `{"cssNamespace": "simorgh"}`, or ideally `si` for brevity, so this would namespace our work to `.si` classes? 

@jtart Agreed that this doesn't need to happen in this PR.

**Review by sareh — APPROVED** [review]

**Review by DemonusPC — APPROVED** [review]
Looks good. Just as a reminder, if you decide to add more environments in the .babelrc file make sure you configure the plugins for styled-components properly as shown in this document: https://github.com/styled-components/babel-plugin-styled-components/issues/78

**Comment by jamesbrumpton** [comment]
LGTM

**Comment by jamesbhobbs** [comment]
@sareh @jtart agree it didn't need doing here, re implementation detail I've no opinion, merely wanted to flag namespacing being important in the future on this PR as it was somewhat relevant.

**Pull request merged**
