### PR TITLE
Integrate Media Player to 2.5.0 into Simorgh

### PR DESCRIPTION
**Pull request by simonsinclair**
- ~Waiting on https://github.com/bbc/simorgh/pull/5142.~
- **Investigating e2e's failing on `local`, but not `test`.**

**Overall change:** 
These changes introduce Psammead Media Player 2.5.0, which handles timeouts for AV embeds.

**Code changes:**
- Update `package.json` and `package.lock.json`.
- Update seven relevant snapshots.

**Notes:**
- [x] 2.4.1
- [x] 2.4.2
- [x] 2.4.3
- [x] 2.4.4
- [x] 2.4.5
- [ ] 2.5.0

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by amywalkerdev** [comment]
This probably needs https://github.com/bbc/simorgh/pull/5142 to be merged first as it bumps gel foundations

**Review by 12 — APPROVED** [review]
LGTM 👍

**Review by j-pendlebury — APPROVED** [review]

**Comment by amywalkerdev** [comment]
articles - news - Canonical Canonical Tests for news articles Media Player: Canonical plays media when a user clicks play:
[0m[31m     CypressError: Timed out retrying: cy.its() errored because the property: 'embeddedMedia' does not exist on your subject.

**Comment by simonsinclair** [comment]
Attaching an on `load` event to Canonical MP in 2.5.0 has created a strange interaction with some of our e2e tests in Simorgh. This is likely due to a bug in Cypress, but until we can afford more time to solve this problem a manual revert of this feature has been issued: https://github.com/bbc/psammead/pull/2991

Cc @jamesdonoh.

**Pull request closed without merging**
