### PR TITLE
Use Psammead Utilities

### LINKED ISSUE #1112: Use Psammead Utilities
**Is your feature request related to a problem? Please describe.**
We are currently still using styles and assets from `src/app/lib/constants/styles` & Typography classes from `src/app/lib/constants/typography`

**Describe the solution you'd like**
Use variables provided by `@bbc/psammead-assets` & `@bbc/gel-foundations`

**Testing notes**
[Tester to complete]

Dev insight: Regression testing - all should remain the same.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by sareh**
Resolves #1112

- Use `@bbc/psammead-assets`
- Use `@bbc/gel-foundations`
- Remove styles, typography & media queries from Simorgh.

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Comment by sareh** [comment]
Because we've deleted files, the CodeClimate test coverage percentage drops. We can ignore this.

**Review by ChrisBAshton — APPROVED** [review]
🎉

**Review by radiocontrolled — APPROVED** [review]
⛹️

**Comment by ChrisBAshton** [comment]
James said at standup that this is ok from Test perspective.

Whilst a UX review wouldn't hurt, this is a refactor rather than a new or edited feature.

Happy to merge.

**Pull request merged**
