### PR TITLE
Update turkce nav bar to add link to Earthquake topic

### PR DESCRIPTION
**Pull request by jordit**
Resolves #n/a

**Overall change:**
Updating the navigation bar for BBC Turkce to add a link to the Earthquake topic and remove linkt to UK topic.

**Code changes:**

- edited navigation section in src/app/lib/config/services/turkce.ts
- updated snapshots

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by mfonofm — APPROVED** [review]
👍

**Comment by jordit** [comment]
Thanks @mfonofm  greatly appreciated.

**Review by HarveyPeachey — APPROVED** [review]

**Comment by karinathomasbbc** [comment]
Yay, I can see the update on Storybook - https://update-turkce-nav--5d28eb3fe163f6002046d6fa.chromatic.com/?path=/story/containers-navigation--canonical (select turcke from the service dropdown)

**Review by karinathomasbbc — APPROVED** [review]

**Comment by jordit** [comment]
Thanks all.

**Pull request merged**
