### PR TITLE
Improving commit readability

### PR DESCRIPTION
**Pull request by FK78**
**Overall change:** 
_Adding a git commit template to create a convention._

**Code changes:**
- _Created `.gitmessage`._
- _Updated `CONTRIBUTING.md`_

**Instructions on how to use the template**

1. Checkout this branch `git checkout improve commits`
2. Configure git to use the template `git config --local commit.template "path_to_template_file/filename"`
3. Make a change to a file, then stage it.
4. Commit the change using `git commit`.
5. Fill in the template and push your changes.

OPTIONAL: Change git text editor to nano using `git config --global core.editor "nano"`.

The default text editor used by git is `vim`, help files for `vim` can be found [here](https://vimhelp.org/).

**Template**
Screenshot 2020-03-06 at 13 49 37

Article about git commit messages: https://backlog.com/blog/git-commit-messages-bold-daring/

### CODE REVIEW

**Comment by sareh** [comment]
@fk78 

Can we add this with npx as a script instead of adding a dependency to the application? 

https://github.com/commitizen/cz-cli/blob/master/README.md#if-your-repo-is-commitizen-friendly

It would be good to update the Contributing.md file to state that this is a convention.

**Comment by FK78** [comment]
> @FK78
> 
> Can we add this with npx as a script instead of adding a dependency to the application?
> 
> https://github.com/commitizen/cz-cli/blob/master/README.md#if-your-repo-is-commitizen-friendly
> 
> It would be good to update the Contributing.md file to state that this is a convention.

According to [this](https://github.com/commitizen/cz-cli/blob/master/README.md#if-your-repo-is-not-commitizen-friendly) we can't, the repository has to be made `Commitizen-friendly`.

**Comment by sareh** [comment]
@FK78 Okay, thanks. I think it's important to ensure that this isn't being added to our production JS bundle. 
Also, I'm wondering if there's any reason this cli tool has been chosen instead of any alternative tool? It'd be good to know in the PR description, since there isn't an issue attached to this PR at the moment.

**Comment by FK78** [comment]
> @FK78 Okay, thanks. I think it's important to ensure that this isn't being added to our production JS bundle.
> Also, I'm wondering if there's any reason this cli tool has been chosen instead of any alternative tool? It'd be good to know in the PR description, since there isn't an issue attached to this PR at the moment.

I've not found any other CLI tools like this one, if you know of any others I am open to looking into them.

This PR was made in response to the comments James had left on Slack about improving readability.

**Review by rhenshaw56 — APPROVED** [review]

**Comment by 12** [comment]
Think this should be discussed with wider Simorgh community before it gets merged.

**Pull request closed without merging**
