### PR TITLE
Use npm package for styles

### LINKED ISSUE #1013: Use @bbc/psammead-styles in Simorgh
**Is your feature request related to a problem? Please describe.**
We now have the npm package `@bbc/psammead-styles`. We should use the styles variables it gives us within Simorgh components and containers.

**Describe the solution you'd like**
- `npm install @bbc/psammead-styles --save`
- Replace all instances of Style variables in Simorgh to use Psammead utilities. 

**Describe alternatives you've considered**
N/A

**Testing notes**
Regression test - everything should be exactly the same as it currently is. 

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by dr3**
Resolves #1013

Use `@bbc/psammead-styles` in simorgh

- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by dr3** [comment]
BLOCKED ON https://github.com/BBC-News/psammead/pull/74

Cant currently use the library as it isnt published as ES5

**Comment by dr3** [comment]
This PR works if you do `npm link ../psammead/packages/utilities/psammead-styles` when youve checked out https://github.com/BBC-News/psammead/pull/74 and run `npm run build`

**Comment by pjlee11** [comment]
Package-lock seems to have change loads, might be worth double checking node/npm version

**Review by bcmn — DISMISSED** [review]

**Comment by bcmn** [comment]
Anyone work out why CC thinks the coverage has gone down? I'm not sure I see it... 🤔

**Comment by dr3** [comment]
@bcmn Talked to phil about this, he said 
>so was 10000 lines of code and 9400 were tested and now it’s 9900 lines of code and 9400 are tested
>so percentage changes

**Review by sareh — DISMISSED** [review]
👍 Looks great!

**Comment by pjlee11** [comment]
FYI the numbers above that Drew quoted are hypothetical. A clearer explanation would be that the percentage can drop just from removing tested code. 

Example:
I have 100 lines of code and 83 are tested, this means the test coverage is 83%. I delete 12 lines of tested code. I know have 88 lines and 71 are tested, this means the test coverage is now 80%.

**Review by pjlee11 — APPROVED** [review]

**Review by ChrisBAshton — APPROVED** [review]

**Review by sareh — APPROVED** [review]
👍 Looks good!

**Comment by jamesbrumpton** [comment]
LGTM

**Pull request merged**
