### PR TITLE
delete child metadata component in container

### PR DESCRIPTION
**Pull request by jroebu14**
Resolves https://github.com/bbc/simorgh/issues/3598

**Overall change:** Removes the metadata component from the metadata container because the container only drills props down to the component. Now all SEO metadata is contained in one place.

**Code changes:**

- Moves the metadata component code into the metadata container
- Deletes the metadata component

---

**Testing notes**
Requires a light regression testing the same as the testing that was required in this PR - https://github.com/bbc/simorgh/pull/4083

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Review by thekp — APPROVED** [review]
👍

**Review by rhenshaw56 — APPROVED** [review]
Looks good!

**Review by jamesdonoh — APPROVED** [review]
Seems like a good simplification - thanks!

**Comment by PriyaKR** [comment]
Looks good to me.

**Pull request merged**
