### PR TITLE
Remove Comscore Analytics toggle from test & live in Simorgh

### LINKED ISSUE #7483: Toggle "ON" comscore analytics
**Is your feature request related to a problem? Please describe.**

This is blocked on this issue: https://github.com/bbc/simorgh/issues/7627

We've implemented AMP and Canonical Comscore analytics, however, it is not toggled "ON"

**Describe the solution you'd like**
We should toggle on Comscore Analytics when we are happy for it to go LIVE
https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/toggles/liveConfig.js#L16

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by itimirichard**
Partially Resolves #7483

**Overall change:**
_Toggle on comscore on live._

**Code changes:**

- _Set comscore `enabled` to `true` in liveConfig.js ._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by DenisHdz — APPROVED** [review]

**Comment by karinathomasbbc** [comment]
Now that we have Remote Toggles enabled on Live, should it also be (or has it already been) switched on using iSite?

Ideally, we're trying to move away from code toggles if possible. 

I believe this PR should actually be the removal of the ComScore analytics toggle from the config files & move to using iSite. Happy to discuss (cc @tochwill )

**Review by mmcculloch — APPROVED** [review]

**Comment by mmcculloch** [comment]
> Now that we have Remote Toggles enabled on Live, should it also be (or has it already been) switched on using iSite?
> 
> Ideally, we're trying to move away from code toggles if possible.
> 
> I believe this PR should actually be the removal of the ComScore analytics toggle from the config files & move to using iSite. Happy to discuss (cc @tochwill )

Ah only just saw this, perhaps the default for comscore analytics should be false? Yeah a bit of discussion needed.

**Comment by karinathomasbbc** [comment]
Just a heads up - if you merge this PR and have not yet configured it in Live iSite, Comscore will not be enabled. Depending on what you want to do - wait until it's Live, and then enable? Or otherwise, set the Live feature toggle up in advance 👍

**Comment by itimirichard** [comment]
> Just a heads up - if you merge this PR and have not yet configured it in Live iSite, Comscore will not be enabled. Depending on what you want to do - wait until it's Live, and then enable? Or otherwise, set the Live feature toggle up in advance 👍

Yes, I'm aware of that. Thank you Karina

**Review by sareh — APPROVED** [review]
Great. The iSite form on Test and Live has been set up - with `comscoreAnalytics` toggle set to be enabled on Test and disabled on Live.

**Comment by itimirichard** [comment]
Going to merge this in. This will be tested when these changes are on test

**Pull request merged**
