### PR TITLE
Africa Eye programme fixture data

### LINKED ISSUE #7543: Mock Africa Eye page data
**Is your feature request related to a problem? Please describe.**
Based on https://www.bbc.co.uk/programmes/w13xttpn 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by karinathomasbbc**
Resolves #7543

**Overall change:**
Adds local fixture data based on https://www.bbc.co.uk/programmes/w13xttpn and associated children e.g. https://www.bbc.co.uk/programmes/p08n8hh4 (append .json to the end of the URL to get the page data)

**Code changes:**
- Add fixture data for all Africa Eye episodes
- Page and data routing in local environment

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by RichardPK — APPROVED** [review]

**Review by rebeccamcginn — APPROVED** [review]

**Comment by rebeccamcginn** [comment]
Thanks for spending the time to get the data. If you remove the routing and have only the fixture data, it will pass diff coverage. We can add the routing later on when we come to build the page.

**Comment by karinathomasbbc** [comment]
The problem will just surface again if I remove the routing from src/server/local/index.js -> https://github.com/bbc/simorgh/issues/7482 was created to tackle this in future. I have admin privileges so I can push this through for now

**Comment by rebeccamcginn** [comment]
You could merge the fixture data then add unit tests then add the routing?

**Comment by karinathomasbbc** [comment]
I've already tried, and am really struggling to get them to work, and I don't think I'll be able to get it done by the end of the week 😢 Overall, the code is covered by the src/server/index.test.js. I'll see what I can do

**Comment by rebeccamcginn** [comment]
We could attempt to write them together in the next Tiny Changes

**Comment by karinathomasbbc** [comment]
Decided to comment out the local server changes, so you can reinstate them later if needed 🏳️

**Pull request merged**
