### PR TITLE
Update all psammead dependencies

### LINKED ISSUE #2924: Use psammead-story-promo-list@2.0.0
**Is your feature request related to a problem? Please describe.**
After https://github.com/bbc/psammead/pull/1643 we will have a `@bbc/psammead-story-promo-list@2.0.0`. This no longer has the vertical spacing built in, and the simorgh FrontPageSection will have to apply the vertical spacing itself.

**Describe the solution you'd like**
Pull in `@bbc/psammead-story-promo-list@2.0.0`, apply vertical spacing (possibly using `styled(StoryPromoUl)`, or some other construct) in Simorgh.

Required spacing -

below 400px: `margin-top: 0.5rem;`
400px & above: `margin-top: 1rem;`

These values may be tweaked again by future changes, but for now just replicate the values deleted in https://github.com/bbc/psammead/pull/1643

**Describe alternatives you've considered**
Don't just replicate the values deleted in https://github.com/bbc/psammead/pull/1643, but attempt to understand what is useful for future changes.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

### PR DESCRIPTION
**Pull request by sareh**
Resolves #2924 
Updates all of our Psammead dependencies, so we're using the latest packages and so that there is no duplication in packages in the Simorgh bundle. 

**Overall change:** Update to use latest dependencies

**Code changes:**

- Update to use latest dependencies
- Update snapshots. 
- Update to use getSansRegularItalic for Caption text
- Update to add dir attributes where required for Consent Banner
- Updating FrontPageMain due to major version bump to using @bbc/psammead-story-promo-list@2

No duplication of packages in Simorgh:
Screen Shot 2019-08-09 at 09 38 00

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by thekp — APPROVED** [review]

**Review by dr3 — APPROVED** [review]
LGTM, needs a FULL regression test of components on all pages

**Review by andrew-nowak — CHANGES_REQUESTED** [review]
this causes a regression on mobile widths on front pages

live:
image
this branch:
image


look at https://github.com/bbc/simorgh/pull/3033/files#diff-a2df2ae2165edc2019fe63a16f9ce6fd for a way to avoid this

**Comment by sareh** [comment]
@aacn500 I've pushed the change. Could you please re-review? 
Branch: 
Screen Shot 2019-08-09 at 10 27 17
Live: 
Screen Shot 2019-08-09 at 10 27 30

**Review by thekp — APPROVED** [review]

**Review by andrew-nowak — APPROVED** [review]
thanks for updating

**Comment by sareh** [comment]
There seems to be these diffs in page spacing raised by chromatic qa on the three WS Front pages: https://www.chromaticqa.com/snapshot?appId=5d28eb3fe163f6002046d6fa&id=5d4d3cffa869c600201fa294
@aacn500 Would you be able to approve if they meet your new UX requirements?

**Comment by sareh** [comment]
Update pushed to address that issue. 
Mobile breakpoint: 
Screen Shot 2019-08-09 at 11 44 33
Large breakpoint: 
Screen Shot 2019-08-09 at 11 44 40

**Review by andrew-nowak — APPROVED** [review]
more spacings issues got fixed; looks good again

**Comment by PriyaKR** [comment]
LGTM.

**Pull request merged**
