### PR TITLE
fix sw and manifest paths

### PR DESCRIPTION
**Pull request by andrew-nowak**
added a bunch of labels for ✨ visibility ✨ 

**Overall change:** A bunch of the service worker and manifest paths are still using the outdated `/articles/X` path

**Code changes:**

- Delete `/articles` from swPath and manifestPath
- Don't delete `/articles` from the news service config

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by j-pendlebury — APPROVED** [review]
Looks good

**Review by jamesbhobbs — APPROVED** [review]
Good spot

**Review by DenisHdz — APPROVED** [review]
LGTM

**Comment by jamesbhobbs** [comment]
No testing needed

**Pull request merged**
