### PR TITLE
add lunar-light background to amp ads container

### LINKED ISSUE #6447: AMP Ads: Should have a grey background
**Is your feature request related to a problem? Please describe.**
Background behind ad should be `#F6F6F6` - 'Lunar Light' as shown in the designs [here](https://app.zeplin.io/project/5c8a5e021d454124ef90669f/screen/5e790b9088869d6a1a17279b).

This issue is dependent on - https://github.com/bbc/psammead/issues/3458.

Ensure we have a wrapper component that has this background colour, and adds the width, padding and margins required for leaderboard ads as specified in the zeplin designs. We can extend this to support MPUs later when they are implemented - refer to https://www.bbc.co.uk/gel/guidelines/grid#grid-sizes for the margin sizes at each breakpoint.

Ensure colour contrast meets requirements:
Given there is advertising on the page
When the ‘ADVERTISEMENT’ label is displayed
Then this must meet the colour contrast ratio of 4.1:5 (as this is key to understanding)

**Describe the solution you'd like**
Add a grey background behind AMP leader board ad so that it displays as shown in the designs.

Screenshot 2020-05-07 at 14 40 57

**Describe alternatives you've considered**
N/A.

**Testing notes**
- Ensure this is covered by a snapshot test

- [x] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by EinsteinNjoroge**
Resolves #6447 

**Overall change:**
_Apply lunar-light background to amp ads container, adjust `width` to 100% and apply padding to the top and bottom of ads container._

**Code changes:**

- _Import `C_LUNAR_LIGHT` from psammead-styles._
- _Adjust width and paddings on ads container._
- _Apply the lunar-light color as background to amp ads container._
- _Add snapshot test for frontpages amp._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by Bopchy — COMMENTED** [review]
Had a look at this locally, and it looks like the background doesn't span the width of the screen at 1008px+ as shown in Zeplin (made the background red to make it more visible)

Screenshot 2020-05-12 at 19 46 09

**Comment by EinsteinNjoroge** [comment]
@ruth I forgot to update the width of the container, should be okay now.

**Review by thekp — APPROVED** [review]
Thanks for the updates. It looks good to me locally.

image
image

**Review by j-pendlebury — APPROVED** [review]
LGTM 👍

**Review by OlgaLyubin — APPROVED** [review]
Background looks good on all browsers 👍

**Comment by PriyaKR** [comment]
Not able to test because of toggles service broken down.

**Comment by PriyaKR** [comment]
Looks good to me except the padding at the top seems to be different when compared with the zeplins designs.

**Comment by PriyaKR** [comment]
Can be merged and UX can review on test.

**Pull request merged**
