### PR TITLE
Adding tigrinya translations

### LINKED ISSUE #3409: Add translations for error pages for Tigrinya
**Is your feature request related to a problem? Please describe.**
We need to add the cookie / privacy banner translations for the following live radio service

-Tigrinya 

**Describe the solution you'd like**
Add the translations to the service configs. Translations available on spreadsheet (pinned in ws-media slack channel or WSMEDIA-87)

**Testing notes**
[Tester to complete]

Dev insight: Unlikely to need a tester due to simplicity

**Additional context**
WSMEDIA-87

### PR DESCRIPTION
**Pull request by ibMadbouly**
Resolves #3409 #3411 #3410 

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**
Based on `Tigrinya` translations provided by editorial

`src/app/lib/config/services/tigrinya.js`

-  500 and 404 translations  
-  cookie and privacy banner translations
-  Footer translations

**Testing Notes: **
to observe `404` try : http://localhost:7080/tigrinya/blah 

To observe the `500` error page
 add status= 500, here 
https://github.com/bbc/simorgh/blob/404Handling/src/app/routes/getInitialData/utils/fetchData/index.js#L16

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by ryanmccombe — APPROVED** [review]

**Review by pjlee11 — APPROVED** [review]
LGTM 👍

**Review by jroebu14 — APPROVED** [review]
Looks fine. I'd leave a link to the translations sheet in the testing notes to help QA when they pick this up

**Comment by LilyL0u** [comment]
For the translation of 404/500 page link - words in brackets are a hyperlink  (ከም ኣማራጺ ከኣ  [BBC News [service] homepage] ረኣይ።) the last characters are within the hyperlink in the page, but outside the hyperlink in the translations sheet. Need to remove the last characters from the hyperlink.

**Comment by LilyL0u** [comment]
Brackets to be removed in the line ከም ኣማራጺ ከኣ [BBC News ረኣይ።]. Checking with translators about the inclusion of ረኣይ። in the hyperlink

**Comment by ibMadbouly** [comment]
@LilyL0u should be addressed on PR #3835

**Pull request merged**
