### PR TITLE
Fix for single CPS related content sizing

### LINKED ISSUE #6180: Related Content looks strange with 1 item
If 1 piece of related content on a MAP and STY, image is large, and low quality images don't look great on desktop.

When only one related content link is added to a STY or MAP page then the image is large and poor quality. 

Go to: https://www.bbc.com/swahili/gnb-52278110
Note the size of the image: 

This was related to the grid changes put in recently, and we could control the grid if we decided.

The column size should always span a single item in the two column layout like the following screenshot:
Screenshot 2020-06-05 at 12 14 55

https://bbcnews.slack.com/archives/CJT0284G2/p1586941247026000

### PR DESCRIPTION
**Pull request by HarveyPeachey**
Resolves #6180

**Overall change:**
Added Grid for single item layout.

**Code changes:**

- Added a grid to the `singleTransform` function
- Updated snapshots

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by oluoluoxenfree — APPROVED** [review]

**Review by simonsinclair — APPROVED** [review]
Great work, Harvey.
I found myself creating a Story that renders a single promo to review this. Would it make sense to add one? It would also help us to track visual regressions for this special case.

**Comment by HarveyPeachey** [comment]
> Great work, Harvey.
> I found myself creating a Story that renders a single promo to review this. Would it make sense to add one? It would also help us to track visual regressions for this special case.

I nearly made one but noticed one already exists for a single item: https://bbc.github.io/simorgh/?path=/story/containers-cps-related-content-canonical--pidgin-ltr-with-one-item

I feel like we need to consider a refactor on a lot of the story's we have in Simorgh to make use of knob's to aid with this, as there seems to be a lot of individual stories which can be condensed. @simonsinclair

**Comment by simonsinclair** [comment]
> I nearly made one but noticed one already exists for a single item: https://bbc.github.io/simorgh/?path=/story/containers-cps-related-content-canonical--pidgin-ltr-with-one-item

I totally missed that, thanks! 

> I feel like we need to consider a refactor on a lot of the story's we have in Simorgh to make use of knob's to aid with this, as there seems to be a lot of individual stories which can be condensed. @simonsinclair

I agree, there are cases where using [Storybook Knobs](https://github.com/storybookjs/storybook/tree/master/addons/knobs) would cut down duplication  in Stories and/or make them easier to maintain. If there are specific components you've identified that would benefit from this, it would be worth raising issues for them.

**Comment by paruchurisilpa** [comment]
LGTM..

**Pull request merged**
