### PR TITLE
Ensure ws-downloads origin is in resource hints

### PR DESCRIPTION
**Pull request by sareh**
Part of #3779

**Overall change:** Ensures ws-downloads origin is in the resource hints.

Test notes: 
We should have `https://ws-downloads.files.bbci.co.uk` in `<link rel="preconnect" >` & `<link rel="dns-preconnect" >` tags. 

Test link: http://localhost.bbc.com:7080/persian/articles/c4vlle3q337o
Screenshot persian page with ws-downloads resource hints

**Code changes:**

- Add ws dowloads font origin to assets list

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by dr3 — COMMENTED** [review]
Will this not preconnect to `ws-downloads.files.bbci.co.uk` on every service? Even those without ws fonts?

**Comment by sareh** [comment]
@dr3 Yes, this is to more immediately fix the issue that we're not preconnecting at all.  We have an upcoming issue here to https://github.com/bbc/simorgh/issues/3850 move all of our Reith fonts to be served via `ws-downloads`.

**Comment by dr3** [comment]
>We have an upcoming issue here to #3850 move all of our Reith fonts to be served via ws-downloads.

But that still wont fix the issue, as many services dont have fonts at all :(

**Comment by sareh** [comment]
@dr3 Okay. Currently we have the `gel` preconnect/dns-prefetch for all sites too, even those without the Reith fonts, so it's following that pattern.

**Comment by sareh** [comment]
I've created a separate issue to conditionally load the font preconnect/dns-prefetch tags here: https://github.com/bbc/simorgh/issues/3851

**Review by dr3 — APPROVED** [review]

**Review by jamesdonoh — APPROVED** [review]

**Review by chris-hinds — APPROVED** [review]

**Comment by staylos92** [comment]
LGTM 👍

**Pull request merged**
