### PR TITLE
Use psammead timestamp container

### LINKED ISSUE #1856: Whitespace added beneath each Story Promo on Feature phone FF48
Using Firefox 48 on feature phones adds a large amount of whitespace between each story promo. This has been observed on the Jio Phone the Nokia 8110, both of which use this browser.

**To Reproduce**

1. Navigate to a front page, currently options are http://localhost:7080/igbo, /yoruba or /pidgin
2. Scroll down to and past the first story promo

**Expected behavior**
There is 16px of padding between the first story promo and the second.

**Screenshots**

**Featurephone (please complete the following information):**

- Device: Nokia 8110
- OS: Nokia_8110_4G
- Browser: Firefox
- Version: 48

**Additional context**
It's worth mentioning that I have checked this on Firefox 48 in browserstack and I have not been able to recreate.

### LINKED ISSUE #1865: Pass padding prop to Timestamp container
**Is your feature request related to a problem? Please describe.**
Introduced a padding prop for padding control.

**Describe the solution you'd like**
Pull in psammead timestamp container, removing the old unneeded timestamp container in simorgh.

Make timestamp padding optional via a prop for world service frontpages in story promo

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests and storybook verification

**Additional context**

### PR DESCRIPTION
**Pull request by dr3**
Resolves #1865
Resolves #1856

**Overall change:** Pulls in timestamp container from psammead

**Code changes:**

- Pulls in timestamp container from psammead
- Provides scripts value for typography
- Updates tests to provide context to things that use timestamps
- Passes `padding=false` to the psammead container, removing the padding

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Comment by DenisHdz** [comment]
Blocked on [Psammead#590](https://github.com/bbc/psammead/issues/590)

**Review by j-pendlebury — APPROVED** [review]

**Review by DenisHdz — APPROVED** [review]
LGTM 👍

**Comment by jamesbrumpton** [comment]
LGTM

**Pull request merged**
