### PR TITLE
ATI domain preconnect

### LINKED ISSUE #2759: Preconnect for ati domain
**Is your feature request related to a problem? Please describe.**
Lighthouse screenshot of an article page - we should add a preconnect link for the ATI domain. Screen Shot of lighthouse - preconnect

**Describe the solution you'd like**
- Add the ATI domain to the list of asset domains (which should change depending on 
- When running lighthouse, we should no longer get the warning in the screenshot above. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests updating should be sufficient. 

**Additional context**

### PR DESCRIPTION
**Pull request by sareh**
Resolves #2759 

**Overall change:** Adding a preconnect link to the head with href of the ATI domain.
On localhost and Test environments, we have this:
`<link rel="preconnect" href="https://logws1363.ati-host.net?" crossorigin="anonymous"/>`
On Live we will have this:
`<link rel="preconnect" href="https://a1.api.bbc.co.uk/hit.xiti?" crossorigin="anonymous"/>`

And the lighthouse error which is on the issue is no longer being shown. 

**Code changes:**

- Add `SIMORGH_ATI_BASE_URL` to preconnect list of domains.
- Add domain to `assetOrigins` list in unit test 

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by sareh** [comment]
Tests are failing on CI due to this issue: https://github.com/bbc/simorgh/issues/2772

**Comment by dr3** [comment]
https://github.com/bbc/simorgh/issues/2759#issuecomment-515972543

**Review by chris-hinds — APPROVED** [review]
Needs updating with latest etc, But am happy with these changes.

**Review by rhenshaw56 — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
* On local host , I was able to see preconnect link:
<link rel="preconnect" href="https://logws1363.ati-host.net?" crossorigin="anonymous"/>

* I don't see the lighthouse error on article page anymore

Can be merged..

**Pull request merged**
