### PR TITLE
Amp Ad Breakpoint fix

### LINKED ISSUE #6460: Amp Ads: Incorrect breakpoints between mobile and desktop sizes
**Describe the bug**
The current AMP ads props specify that a larger (728px or 970px) ad should be shown once the breakpoint of 600px is reached. This results in the Ad going outside of the viewport.

Breakpoint Code:
https://github.com/bbc/simorgh/blob/eeee60d275e9b21bf6eb854fe2967c78a184738b/src/app/containers/Ad/Amp/index.jsx#L58

**To Reproduce**
Steps to reproduce the behaviour:

1. You may have to temporarily remove the `geoIp.advertiseCombined` locally or test via a VPN.
2. Resize window to 600px or slightly above.
3. Go to http://localhost.dev.bbc.co.uk:7080/pidgin.amp
4. Should look like screenshot below

**Expected behaviour**
This breakpoint should be set to `GEL_GROUP_4_SCREEN_WIDTH_MIN` (1008px)

We have been given these as requirements, so we should make sure that these are incorrect, and update them in confluence (`/WSFrontPGS/Adverts`)

Screenshot 2020-05-12 at 11 38 28

**Screenshots**
image

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by mmcculloch**
Resolves #6460 

**Overall change:**
Set Amp Ad breakpoint to 1008px

**Code changes:**

- Used `@bbc/gel-foundations/breakpoints` to set breakpoint for mobile/desktop switch

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by OlgaLyubin — APPROVED** [review]
LGTM 👍

**Review by DenisHdz — APPROVED** [review]
Looks good 👍

**Review by sareh — APPROVED** [review]
:+1: Looks good!

**Comment by PriyaKR** [comment]
Breakpoint is set at 1008px looks good to me.

**Pull request merged**
