### PR TITLE
Use new persian svg

### PR DESCRIPTION
**Pull request by dr3**
**Overall change:** Use new persian svg

**Code changes:**

- Pull in new updated & minifed SVGS
- Use persian svg

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Comment by sareh** [comment]
@dr3 This PR pulls in a new brandSvg into Simorgh and it works well. 
It would be useful to have a Storybook story for the Brand container here to give visibility to developers, UX and Test as to the integration of Psammead utilities and components within Simorgh.

**Review by sareh — APPROVED** [review]
Looks great. Thanks for adding the stories. 

Screen Shot brand - persian

Note for testers to see inclusion of Persian SVG on Storybook here: http://localhost:9001/?selectedKind=Brand&selectedStory=persian

**Review by ghost — APPROVED** [review]
LGTM 👍

**Comment by jamesbrumpton** [comment]
LGTM. Happy for this to be merged.

**Pull request merged**
