### PR TITLE
Version lock to revert inline link styling changes

### LINKED ISSUE #2370: Bump to revert inline-link changes
**Describe the bug**
The bug is described [here](https://github.com/bbc/simorgh/pull/2258#pullrequestreview-258785470). ~The solution is to version lock the inline-link component and the paragraph + caption because they use inline-link.~ Update: bump the inline-link, caption and paragraph to revert the new inline link styles that went live with dependabot.

These version locks can be removed when the [psammead bug](https://github.com/bbc/psammead/issues/936) is fixed. 

**To Reproduce**

1. On Firefox, create a link that ends very close to the end of the paragraphs column
2. Hover on the inline
3. See the content of the link jump to the next line due to additional padding/margin on hover

**Expected behavior**
The text content shouldn't jump to a new line. 

**Screenshots**
image

image

- Browser: FireFox

### PR DESCRIPTION
**Pull request by pjlee11**
Resolves #2370

**Overall change:** Locks the following packages at the version:
- `@bbc/psammead-caption@1.1.8`
- `@bbc/psammead-inline-link@1.0.1`
- `@bbc/psammead-paragraph@1.0.6`

So that the inline link styling is not using the background colour styling. 

**Inline link screenshots**
Hover
image

Default 
image

**Code changes:**

Package.json changes to lock the versions of inline-link we pull in.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by jamesbhobbs — CHANGES_REQUESTED** [review]
Reverting is fine, version locking in this way seems strange...

Version locking such as this means we're choosing to be out of date. If this work isn't ready for live then the components shouldn't be normal release versions they should be alpha or RC versions.

I don't agree with removing the caret, I believe we should use the proper npm versioning protocol in the source packages.

**Comment by dr3** [comment]
I agree, should have been an alpha release, we should probably revert the psammead change, publish it as patch, then release as alpha

**Comment by pjlee11** [comment]
The fix PR is being pushed as we speak and the a11y swarm is being scheduled for Monday. Only one version bump in the `inline-link` package actually relates to production code, the rest are dependency or devDeps updates for the package. 

The admin of merging a revert felt like overkill to me. We would have to publish a revert for inline-link (PR 1), then caption and paragraph (PR 2), bump simorgh to use the reverted versions (PR 3) to then publish inline-link as an alpha (PR 4) and then publish caption and paragraph as an alpha (PR 5). Then after a11y and test early next week turn the alpha's into production versions (PR 6 & 7) then to be bumped in Simorgh (PR 8) seemed to be overkill when we could just version lock for 4 working days and have 3 PRs, one to lock, one to fix forward and one to bump to production after a11y and test.

Happy to change if you disagree but I felt that 8 PRs compared to 3 PRs seems like a better use of time.

**Comment by jamesbhobbs** [comment]
@pjlee11 I think the points you're raising are showing the inadequacies of our psammead tooling. We should not work around this with bad practices. We should follow best practices and improve our tooling - which several people already started on.

So do the painful thing now, and let's get the understanding of the hassle when you wrongly publish something embedded in the engineers' minds, then urgently work on improving the very limited tooling in psammead.

**Comment by pjlee11** [comment]
Superseded by https://github.com/bbc/simorgh/pull/2418

**Pull request closed without merging**
