### PR TITLE
New apup fixtures

### LINKED ISSUE #2844: Add new APUP fixtures
**Is your feature request related to a problem? Please describe.**
Assets have been created on Test and Live for Arabic, Pashto and Urdu.  They should be added as fixture data too.

**Describe the solution you'd like**
Add the six new fixtures.

**Describe alternatives you've considered**
N/A

**Testing notes**
N/A

**Additional context**
The same content will have different IDs on Test and Live.

### PR DESCRIPTION
**Pull request by jimjohnsonrollings**
Resolves #2844 

**Overall change:** 
Adds six fixtures, which are actual content on Test and Live for Arabic, Pashto and Urdu

**Code changes:**

- Adds six fixtures
- Updates test for new number of fixtures

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by jamesdonoh — APPROVED** [review]

**Review by 12 — APPROVED** [review]

**Comment by staylos92** [comment]
This does not need testing by a tester

**Comment by jimjohnsonrollings** [comment]
@jamesbrumpton noticed that this didn't work as expected because I'd put one of the fixtures in the wrong service.  Fixing now.  Good job this was tested by a tester eh @staylos92

**Review by 12 — APPROVED** [review]

**Review by jamesdonoh — APPROVED** [review]

**Review by 12 — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
This does not need testing by a tester, moving to Ready to merge..

**Comment by 12** [comment]
This still needs code reviews before merge as tests have been updated.

**Comment by paruchurisilpa** [comment]
Thanks @rhell

**Review by dr3 — APPROVED** [review]

**Pull request merged**
