### PR TITLE
Prevents Optimizely from sending events if variation key is null

### LINKED ISSUE #9809: Optimizely Events Are Appearing in Results On Desktop View
**Describe the bug**
https://github.com/bbc/simorgh/pull/9743#issuecomment-1016326217

**Screen width > 1007** 
Firefox / Safari / Google (latest) 

- Console Message: 
 `Feature high_impact_feature_analysis_promo is not enabled for user 45773300-b00d-477d-a07a-c2397fc3c3e3.`
- Optimizely Clicks & View event messages show in console (unexpected) ie: 
`Tracking event component_views for user 45773300-b00d-477d-a07a-c2397fc3c3e3`
- Clicks & Views events seem to be logging in Optimizely Results (unexpected) 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

### PR DESCRIPTION
**Pull request by HarveyPeachey**
Resolves #9809

**Overall change:**
Adds `hasVariationKey` boolean where it is `false` when the variation key returned from Optimizely's decision engine is `null`, this is used to conditionally add the optimizely object to the `eventTrackingData`, so it will prevent Optimizely events from firing when the variation key is `null`.

**Code changes:**

- Adds hasVariationKey Boolean
- Conditionally adds the optimizely object to `eventTrackingData` based on hasVariationKey

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by amoore108 — APPROVED** [review]

**Review by MuhammadAHussain — APPROVED** [review]
LGTM 👍

**Review by mfonofm — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Testing:

URL - http://localhost:7080/hindi/articles/c0469479x9xo

Before viewing the page:

Screenshot 2022-01-31 at 14 22 24

After viewing the page:

* Loaded the page - 1 Pageview
* Changed to Mobile Viewport - 2 Pageview
* Going back to DesktopViewport - 3 Pageview
* Changed to Mobile Viewport - 4 Pageview

Screenshot 2022-01-31 at 14 53 21

@HarveyPeachey ,should it have a view in Optimizely if Optimizely is not enabled for viewport >1007..I thought this issue would fix that..

**Comment by HarveyPeachey** [comment]
> @HarveyPeachey ,should it have a view in Optimizely if Optimizely is not enabled for viewport >1007..I thought this issue would fix that..

@paruchurisilpa This work was done to prevent component views and component clicks from firing when the user isn't participating in the experiment. For page_views I guess it depends on what we're defining page_views to be if it's the number of views regardless of whether a user has been bucketed into an experiment, or we don't fire the page view when a user is placed in no experiments. If it's the second we may need to re-think how the page view event firing works

**Comment by paruchurisilpa** [comment]
> > @HarveyPeachey ,should it have a view in Optimizely if Optimizely is not enabled for viewport >1007..I thought this issue would fix that..
> 
> @paruchurisilpa This work was done to prevent component views and component clicks from firing when the user isn't participating in the experiment. For page_views I guess it depends on what we're defining page_views to be if it's the number of views regardless of whether a user has been bucketed into an experiment, or as it is now where we fire the event when the user loads the page. If it's the first we may need to re-think how the page view event firing works

@JonBeeb can you please confirm the pageview behaviour ?

**Comment by HarveyPeachey** [comment]
After a brief call, we've decided to merge this and have the page_view firing fix in a separate PR

**Pull request merged**
