### PR TITLE
Adding No-JS fallback for Media pages

### PR DESCRIPTION
**Pull request by rebeccamcginn**
https://github.com/bbc/simorgh/issues/4760

**Overall change:** 
When JavaScript is disabled, the media player/live radio will now be replaced by a grey box containing text telling the user to enable JavaScript to see the content.

**Code changes:**

- Added the noJSMessage and service props for live radio on AMP
- Added the placeholder image prop for media player

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added labels to this PR for the relevant pod(s) affected by these changes
- [ ] I have assigned this PR to the Simorgh project

**Testing:**
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by greenc05** [comment]
@rebeccarfmcginnbbc just checking what mark up will go in the noscript tag? Will it follow the screen reader UX? https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/5e2b162c84cd309968

Also should this have an a11y swarm label or is that being done as part of another ticket?

**Comment by FK78** [comment]
[PR](https://github.com/bbc/simorgh/pull/5371) which will resolve Jenkins failures.

**Comment by ryanmccombe** [comment]
> Also should this have an a11y swarm label or is that being done as part of another ticket?

We're going to a11y swarm the pages before launch.

We track our pre-launch checklists in Dropbox rather than Github: https://paper.dropbox.com/doc/MAPs-Release-Checklist-6220--Att6yQOeCACDqv7lVvV8uMrHAg-mSkuigjCB1WEwxHyyHIEG

**Review by ryanmccombe — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]

**Review by FK78 — APPROVED** [review]

**Pull request merged**
