### PR TITLE
Arabic translation updates

### PR DESCRIPTION
**Pull request by jimjohnsonrollings**
Resolves N/A

**Overall change:** 
Updates Arabic translations

**Code changes:**
- Updates Arabic translations
- Moves some commas so they render in the right place, despite counter-intuitivity
- Updates snapshots

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by thekp — APPROVED** [review]
LGTM 👍

**Comment by sareh** [comment]
Looking at the storybook examples, I'm surprised we don't have an example of a RTL service front page: https://bbc.github.io/simorgh/?path=/story/pages-front-page--news. 
I think we could remove all but one of pidgin/igbo/yoruba/thai/punjabi and add in arabic. We should be capturing diffs that break right-to-left front pages in storybook with Chromatic.

**Comment by jimjohnsonrollings** [comment]
@sareh would that work given Arabic front page isn't live yet?

**Comment by sareh** [comment]
@jimjohnsonrollings It would, since it involves using fixture data and passing it in here: https://github.com/bbc/simorgh/blob/latest/src/app/pages/FrontPage/index.stories.jsx#L36-L42

**Comment by jimjohnsonrollings** [comment]
@sareh 👍

**Review by sareh — APPROVED** [review]
👍 Looks great. Thanks for the updates @jimjohnsonrollings

**Review by thekp — APPROVED** [review]
Nice one Jim 💯

**Pull request merged**
