### PR TITLE
Add lang to media player embed src

### LINKED ISSUE #3342: Lang attribute on AV embed endpoint
**Is your feature request related to a problem? Please describe.**
In the Mozart page templates for the `/ws/*` media embed endpoints we currently have `<html lang="en">` hardcoded. We need to be able to set the lang attribute on the embed endpoint based on parameters in the request URL. This is needed so we can set the lang based on the current language of the service, page or block.

Any changes made to the `/ws/av_embeds_media` template should also be made to `/ws/av_embeds_articles` template. ~It is also worth evaluating if the 2 different payload could share a unified template~ < not possible. 

**Describe the solution you'd like**
Edit the lang attribute in the Mozart page [template](https://github.com/bbc/mozart-page-configs/blob/master/templates/ws/av_embeds.mustache#L2) so that it can be defined in the request URL. 

**Describe alternatives you've considered**
If it is not possible to use the request URL to vary the lang then we will need to create a template for each service. 

**Testing notes**
We will want to make sure that the relevant `lang` code is returned as expected when visiting `ws` sites. 

**Media liveradio AV embed URLs**
https://www.test.bbc.com/ws/av-embeds/media/bbc_korean_radio/liveradio should have `lang="ko"`
https://www.test.bbc.com/ws/av-embeds/media/bbc_indonesia_radio/liveradio should have  `lang="id"`
https://www.test.bbc.com/ws/av-embeds/media/bbc_tigrinya_radio/liveradio should have  `lang="ti"`
https://www.test.bbc.com/ws/av-embeds/media/bbc_amharic_radio/liveradio should have  `lang="am"`
https://www.test.bbc.com/ws/av-embeds/media/bbc_afaanoromoo_radio/liveradio should have  `lang="om"`

**Articles AV embed URLs**
https://www.test.bbc.com/ws/av-embeds/articles/c3wmq4d1y3wo/p01kdbnv should have `lang="en-gb"`
https://www.test.bbc.com/ws/av-embeds/articles/c3wmq4d1y3wo/p01k6msp should have `lang="en-gb"`

- [x] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by pjlee11**
Resolves #3342

Needs https://github.com/bbc/psammead/pull/2312 merged prior to this PR being merged. 

**Overall change:** Adds `lang` param to the av-embed URL. 

**Code changes:**

- Gets the `lang` value from the service context and passes it in the embed URL. 
- Bumps in latest version of `@bbc/psammead-media-player`

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

BBC-a11y should be run against these changes.

### CODE REVIEW

**Review by ibMadbouly — APPROVED** [review]
👍 LGTM

**Review by 12 — APPROVED** [review]
Assuming the work has been done for Mozart to prevent breaking articles, this LGTM

**Review by jamesdonoh — APPROVED** [review]
Chatted to Phil about this in person and LGTM given the constraints around `bbc-a11y` and Mozart.

**Comment by pjlee11** [comment]
After speaking IRL with @jamesdonoh I'm going to summarise the events prior to this PR. 

1) We decided that as we currently can't add `lang` to the iframe that SMP generates we decided there was little use in the iframe in our embed having `lang` - [issue](https://github.com/bbc/simorgh/issues/3877)

2) `bbc-a11y` failed on the live radio pages expecting the embed iframe to have a `lang` and other a11y best practices writing says similar. Now we need to add `lang` - [issue](https://github.com/bbc/simorgh/issues/3342) 

3) Due to articles only supplying an optimo ID and vpid to the embed endpoint (EG: `https://www.test.bbc.com/ws/av-embeds/articles/c3wmq4d1y3wo/p01k6msp`) we cannot assume the `lang` from the URL.

4) Mozart creates the page template for the embed route, including the `<html>` tag which needs the `lang` attribute, and as the Morph module outputs the envelope format it required Mozart to compose the page. Mozart does not have access to the page data at the point of composition. This means the easiest way to get a lang value into the template without significant changes to both morph and mozart is to add it as a required prop in the URL. 
EG: https://www.test.bbc.com/ws/av-embeds/articles/c3wmq4d1y3wo/p01k6msp/en-GB

5) The lang is required in the URL and it has to match a whitelist of lang's in Mozart. This means that when adding a new service to use the AV embed logic the whitelist in Mozart will need updating.

**Pull request merged**
