### PR TITLE
Use dashes in env stamped file names to fix test coverage

### LINKED ISSUE #1232: Code coverage is returning unknown
**Describe the bug**
The code coverage generated by `npm run test:unit` is returning `unknown` in the test coverage table

**To Reproduce**

1. Run `npm run test:unit`
2. See error

**Expected behavior**
It should return the correct test coverage table

**Additional context**
This was introduced by https://github.com/bbc/simorgh/commit/dd0aa079f74c25a0c1752435b309796636b57d0c But the reason for the bug is unknown

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

### PR DESCRIPTION
**Pull request by dr3**
Resolves #1232

**Overall change:** Changes env stamped files from using the format `name.env.ext` to `name-env.ext

**Code changes:**

- Change asset files to use dashes
- Change sw files to use dashes
- Update .env files to reference new assets file names
- Change `npm run dev` to wait for the new file name

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by pjlee11 — CHANGES_REQUESTED** [review]
As we've namespaced the output files to be `thing-{env}` might be good to make the pattern consistent with the `.env.{env}` files. Therefore changing the line below, and updating the files `.env.test` and `.env.live` to match the `-` pattern

https://github.com/bbc/simorgh/blob/latest/src/server/env/index.js#L8

**Comment by dr3** [comment]
> Need to change this file as well, no?
> 
> https://github.com/bbc/simorgh/blob/latest/src/server/env/index.js#L8

Do you mean `.env.test` etc?

**Comment by dr3** [comment]
> As we've namespaced the output files to be `thing-{env}` might be good to make the pattern consistent with the `.env.{env}` files. Therefore changing the line below, and updating the files `.env.test` and `.env.live` to match the `-` pattern
> 
> https://github.com/bbc/simorgh/blob/latest/src/server/env/index.js#L8

I think we should keep it as `.env.thing` is an industry standard e.g. https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables#what-other-env-files-can-be-used

I think here we should be consistent with industry in this instance at the expense of application consitency

**Comment by pjlee11** [comment]
Ahhh okay, yeah let's do that. Inconsistency for the sake of consistency 🙃 haha

**Review by pjlee11 — DISMISSED** [review]

**Review by bcmn — APPROVED** [review]
Looks good!

**Review by ChrisBAshton — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
LGTM

**Pull request merged**
