### PR TITLE
Bump everything else, except storybook-helpers

### PR DESCRIPTION
**Pull request by dr3**
**Overall change:** Bumps everything except `@bbc/psammead-storybook-helpers` because it has breaking changes

**Code changes:**

psammead-copyright
1.2.6 | PR#1998 Add note about role text to accessibility notes for image source

psammead-section-label
2.3.10 | PR#1993 Talos - Bump Dependencies

psammead-styles
2.1.3 | PR#1948 Show different font types in storybook

psammead-story-promo
2.7.7 | PR#1987 Fix font-size and line-height not being applied in IE11

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by jamesbhobbs** [comment]
Major change in the minifier I suggest we manually test this.

**Review by thekp — APPROVED** [review]
🎉

**Review by oluoluoxenfree — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]

**Review by chris-hinds — APPROVED** [review]

**Comment by chris-hinds** [comment]
Please ensure this is tested as per @benjaminhobbs comment [here](https://github.com/bbc/simorgh/pull/3604#issuecomment-528545170)

**Comment by PriyaKR** [comment]
Looks good to me.

**Pull request merged**
