### PR TITLE
[NEWSWORLDSERVICE-1663] - Adds Translation Context

### PR DESCRIPTION
**Pull request by HarveyPeachey**
Resolves NEWSWORLDSERVICE-1663

**Overall change:**
Adds translation context

**Code changes:**
- Adds translation context
- Adds LoadableConfig with chunk name hinting for bundling with service config
- Adds new types to support translations
- Adds various test for new translation context

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by HarveyPeachey** [comment]
Having a slight issue with this PR. It seems to create unnecessary bundle increases, when we follow the loadable pattern that we use for our [service context](https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/loadableConfig.ts). What seems to happen is that when we use context providers configured this way in our [page handler](https://github.com/bbc/simorgh/blob/186dfdd88c9d5d2ce877207d19c0a0787d459c14/src/app/legacy/containers/PageHandlers/withContexts.jsx#L41-L45), each context used with the loadable strategy produces code (See attached file) in the commons chunks, [which is used across all page types](https://latest--5d28eb3fe163f6002046d6fa.chromatic.com/?path=/story/docs-javascript-bundling-strategy--page#code-splitting). In this example, this means that the user will download the separated themes and translations as bundles, as well as the code which enables the loadable strategy, basically meaning users are downloading bigger bundles when we separate out the current service configs into different contexts.

Does anyone know of any ways around this with our webpack and loadable strategy? I would have thought it would compile the code in a way to reduce duplication but it doesn’t seem to.

What this might mean if we carry on with this work currently, is a better dev experience by separating out concerns from the current service config, but increasing bundle sizes for our end users. One suggestions is keeping everything in the current service context, but separate out the concerns like translations into different files, and just import them and spread them in the main service config?

https://gist.github.com/HarveyPeachey/75a61b85eaf2f0f8ead96138df3b02fd

**Comment by HarveyPeachey** [comment]
https://github.com/bbc/simorgh/pull/10615

**Comment by eagerterrier** [comment]
@HarveyPeachey - is this still valid?

**Comment by HarveyPeachey** [comment]
> @HarveyPeachey - is this still valid?

I think it's on the backburner, feel free to close it, we can always restore the branch

**Comment by HarveyPeachey** [comment]
Closing in favour of alternate approach NEWSWORLDSERVICE-1709

**Pull request closed without merging**
