### PR TITLE
Upgrade Storybook to v5

### LINKED ISSUE #1410: Update Simorgh Storybook to v5
**Is your feature request related to a problem? Please describe.**
We should update our Simorgh Storybook from v4 to v5. 

**Describe the solution you'd like**
Update our Simorgh Storybook from v4 to v5, using the Psammead example as reference: https://github.com/bbc/psammead/pull/323

**Describe alternatives you've considered**
N/A

**Testing notes**
Regression of Storybook on Simorgh, including making sure that no new errors appear in the console.

Dev insight: Running storybook should work as expected. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by 12**
Resolves #1410 

**Overall change:** Upgrades Storybook

**Code changes:**

- Storybook bumped to `@storybook/react@5.0.11`
- Sub-dep `create-react-context` added to license exception as it is actually licensed under the MIT license, but our license checker was saying otherwise.
- Remove Storybook Cypress tests that can no longer exist due to new storybook document structure.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by dr3 — CHANGES_REQUESTED** [review]
Jenkins failure 🙈

**Review by dr3 — DISMISSED** [review]
LGTM, few console warnings but nothing that wasn't there before

**Review by dr3 — APPROVED** [review]

**Comment by 12** [comment]
Additional issues have been created to resolve those console errors. #1773 #1776

**Review by oluoluoxenfree — APPROVED** [review]
LGTM!

**Comment by david-boydell** [comment]
This looks good, RFM.

**Review by chris-hinds — APPROVED** [review]

**Pull request merged**
