### PR TITLE
Add `cache-control` header to Next.js pages

### PR DESCRIPTION
**Pull request by amoore108**
Overall changes
======
Sets the `cache-control` header on Next.js pages to ensure the CDN serves cached copies of the page to users where applicable.

Testing
======
1. _List the steps used to test this PR._

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

### CODE REVIEW

**Review by HarveyPeachey — APPROVED** [review]
Probably worth having a unit test to check the header is set correctly on responses

**Review by andrewscfc — APPROVED** [review]

**Comment by amoore108** [comment]
> Probably worth having a unit test to check the header is set correctly on responses

Would that be in the form of an integration test? Or just a unit test to check that `setHeaders` is called with the correct cache-control values.

**Comment by HarveyPeachey** [comment]
> > Probably worth having a unit test to check the header is set correctly on responses
> 
> Would that be in the form of an integration test? Or just a unit test to check that `setHeaders` is called with the correct cache-control values.

I guess just a check it's called with the correct cache values will do. Integration might be overkill, I guess at that point you're kind of testing the framework, not sure what the best testing strat is really

**Comment by amoore108** [comment]
> > > Probably worth having a unit test to check the header is set correctly on responses
> > 
> > 
> > Would that be in the form of an integration test? Or just a unit test to check that `setHeaders` is called with the correct cache-control values.
> 
> I guess just a check it's called with the correct cache values will do. Integration might be overkill, I guess at that point you're kind of testing the framework, not sure what the best testing strat is really

I'll add a unit test for it, but worth thinking about how we test `getServerSideProps` and the responses in general. I think we use `supertest` for the Express app, but not sure how well it would integrate with Next, as as you say you're kind of testing implementation details at that point.

**Pull request merged**
