### PR TITLE
Bump package lock and pin lighthouse-ci@1.3.1

### LINKED ISSUE #1408: Lighthouse tests fail on fresh package-lock install
**Describe the bug**
Our lighthouse tests fail when a fresh package-lock is created. 

**To Reproduce**

1. Go to simorgh latest
2. `rm package-lock.json`
3. `npm install`
4. `npm run test:lighthouse`

**Expected behavior**
The lighthouse tests should run and pass.

**Screenshots**
image

**Additional context**
This is a prerequisite of the spartacus library work, and so should be addressed soon. 

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

### PR DESCRIPTION
**Pull request by pjlee11**
Resolves #1408 

**Overall change:** _Fresh installs the package-lock and pins the package `lighthouse-ci` at version `1.3.1`_

**Code changes:**

- Removes `package-lock.json` and `npm install` to create a new `package-lock.json` 
- Pins `lighthouse-ci@1.3.1`
- Also updates the globalStyle snapshot as it has changed with the dependencies

---

- [x] I have assigned myself to this PR and the corresponding issues
- ~[ ] Tests added for new features~
- [x] Test engineer approval
- [x] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Comment by pjlee11** [comment]
I noticed that we seem to be installing lighthouse @3.2.1 and as a second dependency @ 4.2.0 ...

```
│ ├─┬ lighthouse-logger@1.2.0
├─┬ lighthouse@3.2.1
│ ├── lighthouse-logger@1.2.0 deduped
├─┬ lighthouse-ci@1.4.1
│ ├─┬ lighthouse@4.2.0
│ │ ├── lighthouse-logger@1.2.0 dedupe
```

**Comment by pjlee11** [comment]
My initial thoughts are that lighthouse@4.x.x is causing the failure and a fresh package-lock install is bumping `lighthouse-ci@1.3.1` to be `lighthouse-ci@1.4.1` which then pulls in lighthouse@4.x.x

**Comment by pjlee11** [comment]
I've created the issue https://github.com/bbc/simorgh/issues/1419 to re-evaluate why lighthouse@4.2.1 does not work with our lighthouse test scripts

**Review by dr3 — APPROVED** [review]
Not ideal, but understandable. Annoying `lighthouse-ci` didnt make moving to 4 a breaking change

**Review by sareh — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
👍

**Pull request merged**
