### PR TITLE
Remove simorgh jenkinsfile and redundant scripts

### PR DESCRIPTION
**Pull request by andrewscfc**
I have been fairly bold deleting things here, please shout on this PR if I've gone too far!

- Removes jenkinsfile as we no longer use jenkins to deploy simorgh itself (this jenkinsfiles for infra remain in the infra repo)
- Delete unused makefile, I believe that used to be used as part of the jenkins deploy
- Removed unused `ci` scripts in package.json
- ~Removed legacy lighthouse scripts now replaced by contents of /lighthouse directory~
- Removed scripts relating to 'signing the build'; these were used for velocity and we no longer pay for that service
- Removed, scripts/jenkinsProductionFiles.sh not really sure what it's for but seems to be related to jenkins again 🤷 

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by chris-hinds** [comment]
Some of the lighthouse files here are used to run LH on GH Actions

**Comment by andrewscfc** [comment]
> Some of the lighthouse files here are used to run LH on GH Actions

Are we using the LH solution developed by @jroebu14 and @rebeccamcginn here or do we have two solutions in use at the same time?

**Comment by chris-hinds** [comment]
> > Some of the lighthouse files here are used to run LH on GH Actions
> 
> Are we using the LH solution developed by @jroebu14 and @rebeccamcginn here or do we have two solutions in use at the same time?

Currently two solutions.......

**Comment by andrewscfc** [comment]
> > > Some of the lighthouse files here are used to run LH on GH Actions
> > 
> > 
> > Are we using the LH solution developed by @jroebu14 and @rebeccamcginn here or do we have two solutions in use at the same time?
> 
> Currently two solutions.......

Okay, I've reinstated those scripts for now, be good to use the same solution as codebuild when we can

**Comment by rebeccamcginn** [comment]
Thanks for doing this! It looks fine, but I'll let the more experienced sign off on it

**Review by chris-hinds — APPROVED** [review]

**Review by FK78 — APPROVED** [review]

**Pull request merged**
