### PR TITLE
fix #1035: moves contexts to contexts/ dir

### LINKED ISSUE #1035: Move contexts to contexts/ dir
**Is your feature request related to a problem? Please describe.**
Our contexts currently live inside the src/app/components folder, which is confusing as these are contexts, not presentational components.

In #972 we decided that [having a contexts/ folder is a good idea](https://github.com/BBC-News/simorgh/issues/972#issuecomment-440732176).

By moving contexts to src/app/contexts, we have to update relative paths in some of the presentational components - so this issue can be seen as a prerequisite for moving context-dependent components over to Psammead.

**Describe the solution you'd like**
Move contexts to separate `contexts/` dir.

**Testing notes**
[Tester to complete]

Dev insight: Regression tests only.

- [ ] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by ChrisBAshton**
Resolves #1035

moves contexts to contexts/ dir

- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by pjlee11 — DISMISSED** [review]
Nice one

**Review by dr3 — DISMISSED** [review]

**Review by bcmn — APPROVED** [review]
Do the changes to package-lock have to be in this PR, seeing as it isn't related to dependency changes at all? Otherwise, looks great!

**Review by dr3 — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
LGTM

**Comment by jamesbrumpton** [comment]
LGTM

**Pull request merged**
