### PR TITLE
eslint-disable puppeteer import

### PR DESCRIPTION
**Pull request by jroebu14**
**Overall change:** Disables eslint on puppeteer import so the commit hook doesn't fail.

**Code changes:**

- Adds `eslint-disable-next-line import/no-unresolved` above  `puppeteer` import

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

**Testing notes**
No testing required.

### CODE REVIEW

**Review by dr3 — APPROVED** [review]

**Review by chris-hinds — APPROVED** [review]
👍

**Comment by jamesbhobbs** [comment]
@jroebu14 I think there's a real problem with this in jenkins. I'm not certain though, but I've run it several times.

**Comment by jroebu14** [comment]
@benjaminhobbs yeh I've no idea why it's failing. Is anyone else complaining about the puppeteer import preventing them from committing changes? If not then I'll close this and find out why it only affects me.

**Comment by dr3** [comment]
It happened in a pre commit script for @lokh01 yesterday

**Comment by jamesbhobbs** [comment]
As this perpetually errors for an unknown reason closing in favour of https://github.com/bbc/simorgh/pull/3248

**Pull request closed without merging**
