### PR TITLE
Suppress timestamp on LIV promos

### LINKED ISSUE #6063: Suppress timestamp when promoting LIV assets
**Is your feature request related to a problem? Please describe.**
The timestamp on LIV assets refers to when the page was first created, not last updated. This means we display misleading timestamps on promos.

**Describe the solution you'd like**
Suppress the timestamp when promoing an LIV asset.
"Just adding an extra condition here: https://github.com/bbc/simorgh/blob/latest/src/app/containers/StoryPromo/index.jsx#L153"

**Describe alternatives you've considered**
Finding the timestamp of the latest post in the live page - but that would mean making calls to all sort of APIs which aren't in Mozart.

**Testing notes**
Manually testing by adding an LIV asset on the front page feed locally and seeing it not show a timestamp. 

Dev insight: Manual testing for now, but we should add integration testing when we have that set up for front pages. 

- [x] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by Bopchy**
Resolves #6063 

**Overall change:**
_Add condition to suppress timestamp when promoing LIV assets._

_Manually checked this by having a look at LIVE StoryPromos on [http://localhost:9001/?path=/story/pages-front-page--news](http://localhost:9001/?path=/story/pages-front-page--news) locally._

**Before**
Screenshot 2020-04-01 at 19 54 50

**After**
Screenshot 2020-04-01 at 19 55 29

**Code changes:**

- _Add `isLive` check._
- _Add test._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by DenisHdz — APPROVED** [review]
LGTM 👍

**Review by OlgaLyubin — APPROVED** [review]
Looks good 👍

**Review by sareh — APPROVED** [review]
👍 Looks good. 
That news front page story was replaced in another PR, so anyone testing this can now look at a live promo on the arabic front page story:
http://localhost:9001/?path=/story/pages-front-page--arabic
Screenshot 2020-04-02 at 10 28 17

**Comment by PriyaKR** [comment]
LGTM 
Screenshot 2020-04-02 at 11 32 41

**Pull request merged**
