### PR TITLE
Adds gaelic/Naidheachdan translation to top stories & features analysis title in AMP

### LINKED ISSUE #9228: Add translation to the Naidheachdan service (for amp pages)
**Is your feature request related to a problem? Please describe.**
Update the following on  Naidheachdan  
‘Top Stories’: ‘Prìomh Sgeulachdan’ 
‘Features & Analysis’:‘Sgeulachdan Aithriseach
 

**Describe the solution you'd like**
Update the following config file and add the values
https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/naidheachdan.js

topStoriesTitle: ,
featuresAnalysisTitle:

**Describe alternatives you've considered**

**Testing notes**
View an amp page to check the titles have been updated
https://www.bbc.co.uk/naidheachdan/57747079.amp 

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

### PR DESCRIPTION
**Pull request by pvaliani**
Resolves #9228 

This is a PR which should be merged in tandem with the following related ticket https://github.com/bbc/simorgh/pull/9233 

NOTE: We were unable to build Simorgh via `yarn dev` until applying a fix to the resolutions object in package.json.

Therefore the fix in #9233 should be tested and merged before merging this tickets fix for the translation.

The bug can be viewed here: 

https://www.bbc.co.uk/naidheachdan/57862954.amp

**Overall change:**
Adds translation of "top stories" and the features analysis title on Naidheachdan

**Code changes:**

- Adds ‘Top Stories’: ‘Prìomh Sgeulachdan’ and ‘Features & Analysis’:‘Sgeulachdan Aithriseach' to Naidheachdan config file due to missing translation
- Adds appropriate asset fixture file to Data folder in order to test the aforementioned feature

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by jroebu14 — APPROVED** [review]
Thanks!

**Review by HarryVerhoef — APPROVED** [review]
Nice one!

**Review by rebeccamcginn — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]

**Comment by ryanmccombe** [comment]
Mind squashing the commits if you get time?  There's an unsigned commit in this branch.

**Review by ryanmccombe — APPROVED** [review]

**Comment by JonBeeb** [comment]
View an amp page to check the titles have been updated
https://www.bbc.co.uk/naidheachdan/57849613.amp

Test https://www.test.bbc.co.uk/naidheachdan/57849613.amp?renderer_env=live

**Comment by LilyL0u** [comment]
Screenshot 2021-07-19 at 17 45 55

Looks good to me! Or should I say 'A ’coimhead math dhòmhsa!'

**Comment by LilyL0u** [comment]
I find it a little amusing that 'Sgeulachdan Aithriseach' translates to Factual Stories. Because you would hope all the news is factual.
That's Google's translation anyway.

**Pull request merged**
