### PR TITLE
add most read fixture data

### LINKED ISSUE #4574: Add Fixture data for Most Read for all services.
**Is your feature request related to a problem? Please describe.**
We should have local fixture data for Most Read, for each of the services. 

**Describe the solution you'd like**
We should have fixture data files with Most Read JSON data.  They should be in the files 
`/data/:service/mostRead/index.json`
or for services that have variants, like zhongwen, ukchina & serbian:
`/data/:service/mostRead/variantname.json`

Where to get the example data:
`https://ares-broker.api.bbci.co.uk/api/most/read/persian`
Note that the services with variants are at the endpoints of this format:
`https://ares-broker.api.bbci.co.uk/api/most/read/ukchina_trad`

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: No tests are needed for this step. 

- [ ] This feature is expected to need manual testing.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by thekp**
Resolves #4574

**Overall change:** _Added most read fixture data from the ares-broker api._

**Code changes:**

- _added /data/:service/mostRead/index.json for each service or /data/:service/mostRead/variant.json for services with variant_ 

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by sareh — APPROVED** [review]
👍 Looks great!

**Comment by sareh** [comment]
The unit test in `dataValidator/index.test` fails to run on CI, giving the following error:
```
Summary of all failing tests

 FAIL  dataValidator/index.test.js

  ● Test suite failed to run


    Call retries were exceeded


      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)
```
When reading up on the issue, a suggested solution is to pass the `--runInBand` flag to `jest` (alias `-i`) that runs all tests serially in the current process, rather than creating a worker pool of child processes that run tests.

However, this will make the unit tests slower to run.  We should firstly see if this flag _does_ fix the issue, and if it does, discuss whether the tradeoff for keeping the datavalidator tests as they are (running against the 320 files from the `/data` directory).

**Comment by sareh** [comment]
An alternative that was suggested was to remove the `dataValidator` directory, since it is no longer being used. https://github.com/bbc/simorgh/issues/4588

**Comment by EinsteinNjoroge** [comment]
**Note** Currently, we don't have most-read data for `cymrufyw`, `scotland` and `Naidheachdan`.

**Comment by EinsteinNjoroge** [comment]
I noticed we already have `/most/read.json` for `persian` and `pidgin`. Should we consider removing them?

**Review by EinsteinNjoroge — COMMENTED** [review]
**Note** Currently, we don't have most-read data for `cymrufyw`, `scotland` and `Naidheachdan`.

@sareh @thekp I noticed we already have `/most/read.json` for `news`,`persian` and `pidgin`. Should we consider removing them?

**Comment by sareh** [comment]
@EinsteinNjoroge Good spot! Yes it'd be good to remove those, since those paths are no longer needed. Since @thekp is busy today, would you mind making the change?

**Comment by hotinglok** [comment]
@sareh @EinsteinNjoroge I noticed that we have this for `news` as well. However, the `read.json` and the new `index.json` in `/mostRead` have difference between the files for all of the services with remaining `/most/read.json` files. Is this expected?

**Comment by EinsteinNjoroge** [comment]
@lokh01  since `/most/read.json` was added four months ago, I'd expect that the the data has changed since then.

**Review by hotinglok — APPROVED** [review]
LGTM

**Review by RayNjeri — APPROVED** [review]

**Pull request merged**
