### PR TITLE
Use React recommended minifier

### LINKED ISSUE #2542: Use React's recommended minimizer
**Is your feature request related to a problem? Please describe.**
The react docs suggest using terser https://reactjs.org/docs/optimizing-performance.html#webpack we are not using it

**Describe the solution you'd like**
Use it if it is more performant

**Describe alternatives you've considered**
Open to alternatives that are shown to be better

**Testing notes**
Regression would be required as its compromising the bundles.

Dev insight: Regression needed as minimizing could break anything.

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by jamesbhobbs**
Cuts 2kb from gzipped bundle.

Resolves #2542

**Overall change:** Use terser for minification

**Code changes:**

- Use terser for minification

---

- [x] I have assigned myself to this PR and the corresponding issues
~- [ ] Tests added for new features~
- [ ] Test engineer approval

### CODE REVIEW

**Comment by chris-hinds** [comment]
According to the web-pack docs terser is enabled by default when running in production mode or by simply setting

```
optimization: {
    minimize: true
}
```

**Comment by jamesbhobbs** [comment]
> According to the web-pack docs terser is enabled by default when running in production mode or by simply setting
> 
> ```
> optimization: {
>     minimize: true
> }
> ```

Seems like those docs are wrong, tried here https://github.com/bbc/simorgh/pull/2551 and that approach does nothing.

**Review by chris-hinds — APPROVED** [review]

**Review by thekp — APPROVED** [review]

**Comment by PriyaKR** [comment]
@benjaminhobbs I find the image assets are not being displayed on article and frontpage.

**Comment by PriyaKR** [comment]
Regression looks good to me.

**Pull request merged**
