### PR TITLE
Canonical referral link

### LINKED ISSUE #1972: Get Referrer URL for Client-side Canonical links
**Is your feature request related to a problem? Please describe.**
As part of the [ATI work](https://github.com/bbc/simorgh/pull/1651) we have a requirement to set the variable `x6` to be the referrer url. This is not currently working for Canonical pages.

Since we're using React Router for our client-side routes, we should use the history API to find the previously-visited Simorgh page. 

**Describe the solution you'd like**
Access previous page via the History API - using render props of the Route. Explanation of this approach is here: https://www.freecodecamp.org/news/hitchhikers-guide-to-react-router-v4-4b12e369d10/ 

Pass this value to the ATIAnalytics module - so that the value `x6` surfaces it. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests

### PR DESCRIPTION
**Pull request by rhenshaw56**
Resolves #1972 

**Overall change:** Passed previous pathname value to the ATIAnalytics module.

**Code changes:**

- Updated unit tests
- added effect for saving value in the state during unmounting
- passed value to request context
- use value in ati analytics container
- add logic to distinguish different user journeys
- add check to clear previous path on back clicks ( see [previous review](https://github.com/bbc/simorgh/pull/2145))
---
**To Test**
- download the [`tag inspector` add-on](https://chrome.google.com/webstore/detail/at-internet-tag-inspector/epdfbeoiphkaeapcohmilhmpdeilgnok?hl=en) in chrome (or check the ATI outbound request in the network tab)
- visit http://localhost:7080/news/articles/c0g992jmmkko and check the ATI beacon's referrer (field `x6` in the outbound request) is not set
- click the link in the body of the article `placed on the tomb of the unknown warrior` which links through to http://localhost:7080/news/articles/c6v11qzyv8po. Check the referrer (`x6`) of the new page is set to the previous page `http://localhost:7080/news/articles/c0g992jmmkko`
- Finally click the link `which were later donated to local hospices` which links through to http://localhost:7080/news/articles/c0g992jmmkko. Again check the new beacon's referrer is set to the previous page this time `c0g992jmmkko`

---
- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by pjlee11 — APPROVED** [review]
LGTM 👍

**Review by jamesdonoh — CHANGES_REQUESTED** [review]
Nice job @rhenshaw56 - my only thought is that `usePrevious` while useful might be a little bit cryptic, do you think you could add some documentation explaining what it does, perhaps structured like the official React docs for things like `useRef` (https://reactjs.org/docs/hooks-reference.html#useref)? This would also help others to reuse it.

**Review by jamesdonoh — APPROVED** [review]
Great - thanks for docs!

**Comment by jamesbrumpton** [comment]
LGTM

**Pull request merged**
