### PR TITLE
Add unit tests for cases of incomplete data

### LINKED ISSUE #585: Unit Test Coverage for Components & Containers
**Is your feature request related to a problem? Please describe.**
Components and Containers do not have 100% test coverage. 
```
-----------------------------------------------|----------|----------|----------|----------|-------------------|
File                                           |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------------------------------------------|----------|----------|----------|----------|-------------------|
 src/app/components/MainContent                |       80 |      100 |        0 |       80 |                   |
  index.jsx                                    |       80 |      100 |        0 |       80 |                15 |
 src/app/components/Video                      |       75 |      100 |        0 |       75 |                   |
  index.jsx                                    |       75 |      100 |        0 |       75 |                12 |
 src/app/containers/Article                    |      100 |    85.71 |      100 |      100 |                   |
  index.jsx                                    |      100 |    85.71 |      100 |      100 |                 8 |
 src/app/containers/Document                   |        0 |      100 |        0 |        0 |                   |
  index.jsx                                    |        0 |      100 |        0 |        0 |    7,8,9,11,12,16 |
 src/app/containers/Image                      |    94.74 |     87.5 |      100 |    94.44 |                   |
  index.jsx                                    |    94.74 |     87.5 |      100 |    94.44 |                25 |
 src/app/containers/InlineLink                 |    85.71 |       50 |      100 |    85.71 |                   |
  index.jsx                                    |    85.71 |       50 |      100 |    85.71 |                13 |
 src/app/containers/MainContent                |    84.62 |      100 |       75 |    84.62 |                   |
  index.jsx                                    |    84.62 |      100 |       75 |    84.62 |             10,11 |
 src/app/containers/Text                       |    66.67 |       50 |       50 |       75 |                   |
  index.jsx                                    |    66.67 |       50 |       50 |       75 |                 8 |
```

**Describe the solution you'd like**
We should add unit tests with assertions (rather than snapshots) for these components.

### PR DESCRIPTION
**Pull request by sareh**
Part of #585 

Adds unit tests for 
- Image Container
- x

- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by sareh** [comment]
Running just these tests with `npx razzle test --env=jsdom`, I see them passing:
```
 PASS  src/app/containers/Image/index.test.jsxropTypes.js:19
  Image
    with no data
      ✓ should return null (13ms)
    with data
      ✓ should render an image with alt text (4ms)
      ✓ should render an image with alt text and offscreen copyright (1ms)
      ✓ should render an image with alt text and caption
    with incomplete data
      no rawImage block
        ✓ should return null if there is no image block (2ms)
      no altText block
        ✓ should return null (2ms)

Test Suites: 1 passed, 1 total
Tests:       6 passed, 6 total
Snapshots:   3 passed, 3 total
Time:        2.212s
Ran all test suites related to changed files.
```

However, there is no change in the code coverage in the output. It still states that line 25 is not covered in the tests:
```
--------------------------|----------|----------|----------|----------|-------------------|
File                      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------------|----------|----------|----------|----------|-------------------|
 src/app/containers/Image |    94.74 |     87.5 |      100 |    94.44 |                   |
  index.jsx               |    94.74 |     87.5 |      100 |    94.44 |                25 |
```
https://github.com/bbc/simorgh/blob/latest/src/app/containers/Image/index.jsx#L25

**Review by radiocontrolled — APPROVED** [review]
This PR looks good to me. I am also not sure why the coverage report line 25 referenced here is not changing: https://github.com/bbc/simorgh/pull/586#issuecomment-416908428

**Comment by jamesbrumpton** [comment]
Nothing required from Test on this PR. Happy for it to be merged after passing 2nd Code Review. Ta!

**Comment by pjlee11** [comment]
I think I've already covered these two test as part of the container image refactor - On latest https://github.com/bbc/simorgh/blob/latest/src/app/containers/Image/index.test.jsx#L47-L65. This was added as part of https://github.com/bbc/simorgh/issues/516

**Comment by sareh** [comment]
Closed as duplicate.

**Pull request closed without merging**
