### PR TITLE
Storybook style revamp

### PR DESCRIPTION
**Pull request by DarioR01**
Resolves JIRA [N/A]

Overall changes
======
Maked our storybook documentation look better with a new colour theme and logo

preview:

**_New:_**
Screenshot 2023-05-18 at 15 14 52

**_Previous:_**
Screenshot 2023-05-18 at 15 15 17

Code changes
======

Create storybook colour theme.
Pass the colour theme into the storybook preview.

Testing
======
N/A

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

### CODE REVIEW

**Review by HarveyPeachey — COMMENTED** [review]
Hmm the [storybook permalink](https://storybook-style-revamp--5d28eb3fe163f6002046d6fa.chromatic.com/?path=/story/docs-a11y-testing-cross-device--page) isn't showing the revamp for some reason

**Comment by DarioR01** [comment]
> Hmm the [storybook permalink](https://storybook-style-revamp--5d28eb3fe163f6002046d6fa.chromatic.com/?path=/story/docs-a11y-testing-cross-device--page) isn't showing the revamp for some reason

I left it on Thursday in a working state... what happened in 1 week 🤦 . Anyway, reloading the page does show the revamp. But let me see if I can fix this issue, maybe I missed something in the config 🤷‍♂️

**Comment by DarioR01** [comment]
> Hmm the [storybook permalink](https://storybook-style-revamp--5d28eb3fe163f6002046d6fa.chromatic.com/?path=/story/docs-a11y-testing-cross-device--page) isn't showing the revamp for some reason

Fixed. Storybook has to be fully published or the changes would not display. I also changed a small mistake in the config that was causing the issue.

**Review by HarveyPeachey — APPROVED** [review]

**Review by shayneahchoon — APPROVED** [review]
Looks super nice!

**Pull request merged**
