### PR TITLE
Russian and Kyrgyz config updates

### PR DESCRIPTION
**Pull request by jimjohnsonrollings**
Addresses parts of #4273 and #4274 

**Overall change:**
- Updates Russian and Kyrgyz configs ready for Articles

**Code changes:**

- Corrects values in Russian and Kyrgyz configs
- Adds Reith fonts to Russian (noting that this means Russian launch becomes blocked pending a future version of Reith)
- Adds Russian translations
- Updates some snapshots

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by jimjohnsonrollings** [comment]
Blocked by https://github.com/bbc/psammead/pull/2471

**Comment by jimjohnsonrollings** [comment]
Now blocked by https://github.com/bbc/psammead/pull/2477

**Comment by jimjohnsonrollings** [comment]
Now by https://github.com/bbc/psammead/pull/2486

**Comment by jimjohnsonrollings** [comment]
Blocked by https://github.com/bbc/simorgh/issues/4402

**Comment by jimjohnsonrollings** [comment]
No longer blocked.  Ready for code review

**Review by sareh — APPROVED** [review]

**Review by amywalkerdev — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
lgtm

**Pull request merged**
