### PR TITLE
Fix long headlines overflowing on Opera Mini Extreme Mode

### LINKED ISSUE #6247: Opera Mini Extreme mode - headlines overflowing
**Describe the bug**
For those services with long headlines, they are overflowing out of the main content.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://www.bbc.com/thai' on an Opera Mini browser
2. Turn on Extreme mode
3. See headlines overflowing

**Expected behaviour**
 Layout to look similar to that as on the standard 'automatic' mode.

**Screenshots**
headline-overflow-1
headline-overflow-2

**Smartphone (please complete the following information):**

- Device: Nexus 5X
- OS: Android 8
- Browser: Opera Mini
- Version: 46

**Testing notes**

- [X] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves #6247

**Overall change:**
Apply [overflow-wrap: break-word;](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) to the Story Promo Headline Link to prevent the text from overflowing its line box. 

**Code changes:**
- Add `StyledLink` to `StoryPromo` container with `overflow-wrap: break-word;`
- Update snapshots

---

- [X] I have assigned myself to this PR and the corresponding issues
- [X] I have added labels to this PR for the relevant pod(s) affected by these changes
- [X] I have assigned this PR to the Simorgh project

**Testing:**
To make the page take the entire screen do the following:
-  Go to Opera Mini > settings > Page layout
-  Turn off text wrap.

- [X] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [X] This PR requires manual testing

### CODE REVIEW

**Review by thekp — APPROVED** [review]

**Comment by DenisHdz** [comment]
Please note that this could be applied in the `story-promo` package, but I am up to get this merged asap to be able to confirm it works on live too, and then apply it in Psammead and remove it from Simorgh.

**Review by j-pendlebury — APPROVED** [review]

**Comment by PriyaKR** [comment]
@DenisHdz On android opera mini the frontpage layout in extreme mode for eg.thai doesn't look similar to the automatic mode.

operamini_automatic_mode
operamini_extreme_mode

**Comment by DenisHdz** [comment]
> @DenisHdz On android opera mini the frontpage layout in extreme mode for eg.thai doesn't look similar to the automatic mode.
> 
@PriyaKR There is another issue for fixing the layout bugs https://github.com/bbc/simorgh/issues/5684. This PR is just about fixing the long headlines overflowing outside the main content.

If you access the live Thai site https://www.bbc.com/thai, you can see that you are able to scroll horizontally to the right, as the text is overflowing which is wrong.

**Comment by PriyaKR** [comment]
> > @DenisHdz On android opera mini the frontpage layout in extreme mode for eg.thai doesn't look similar to the automatic mode.
> 
> @PriyaKR There is another issue for fixing the layout bugs #5684. This PR is just about fixing the long headlines overflowing outside the main content.
> 
> If you access the live Thai site https://www.bbc.com/thai, you can see that you are able to scroll horizontally to the right, as the text is overflowing which is wrong.

There is spacing issue too between the words.
operamini_extreme_mode

**Comment by DenisHdz** [comment]
> > > @DenisHdz On android opera mini the frontpage layout in extreme mode for eg.thai doesn't look similar to the automatic mode.
> > 
> > 
> > @PriyaKR There is another issue for fixing the layout bugs #5684. This PR is just about fixing the long headlines overflowing outside the main content.
> > If you access the live Thai site https://www.bbc.com/thai, you can see that you are able to scroll horizontally to the right, as the text is overflowing which is wrong.
> 
> There is spacing issue too between the words.

@PriyaKR I believe this is due to the same layout bug as I mentioned previously because I can also see the gaps on the live site.

The main purpose of this PR is to avoid that the text overflows outside of the main content as you can see below. 

headline-overflow


Could you please confirm that?

**Comment by PriyaKR** [comment]
ok fine looks good.

**Pull request merged**
