### PR TITLE
Tidy files

### LINKED ISSUE #940: Move GitHub templates into .github folder
**Is your feature request related to a problem? Please describe.**
We currently have a mixture of `.github/` folder containing pull request template & issue templates, and various files in the root (CODE_OF_CONDUCT.md). Leave CONTRIBUTING.md so it's as obvious as possible for people new to the repo. Follow @sareh 's suggestion and is common practice, e.g. required by Google on their OSS repos.

GitHub supports serving the [code of conduct](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/) file from the `.github/` directory, so we should tidy up our repo by serving these 'meta' files from one place.

**Describe the solution you'd like**
Move the `CODE_OF_CONDUCT.md` file to the `.github/` folder. If there are any other moveable files, they should be moved too.

**Testing notes**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by jamesbhobbs**
Resolves #940 and most of #1535 (all except merging files to make CR clearer)

**Overall change:** Moves file listed in PRs above

**Code changes:**

- Files moved listed clearly in commit messages

---

- [x] I have assigned myself to this PR and the corresponding issues
~~- [ ] Tests added for new features~~
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Comment by sareh** [comment]
Since this is an open source project, I think it is important to keep these files at the top level.
In particular the Code of Conduct. Having that be visible to those visiting the repository for the first time.
We should really also mention both these files at the bottom of our readme.

**Comment by jamesbhobbs** [comment]
@sareh please comment on the issue, and come to an agreement with peers, I don't mind, this is WIP for refactoring much more than just that, hence I didn't put it in CR yet (but wanted remote tests running).

**Comment by sareh** [comment]
Okay. Will do. Usually issues with Refinement Needed shouldn't be picked up for this reason - they haven't been agreed to be carried out yet.

**Comment by jamesbhobbs** [comment]
Coverage diffs on this should be ignored, except to ensure that we're still checking coverage in the correct places. I believe I've updated this config, please let me know if I missed anything though.

**Review by jroebu14 — DISMISSED** [review]
This looks good to me

**Review by dr3 — APPROVED** [review]
LGTM

**Review by jroebu14 — APPROVED** [review]

**Comment by PriyaKR** [comment]
Regression looks good to me.

**Pull request merged**
