### PR TITLE
Bumping dependencies

### PR DESCRIPTION
**Pull request by FK78**
Resolves multiple dependabot PRs.

**Overall change:** _Bumping dependencies._

**Code changes:**
- _Bump @babel/core from 7.8.7 to 7.9.0_
- _Bump @babel/plugin-proposal-object-rest-spread from 7.8.3 to 7.9.0_
- _Bump babel-loader from 8.0.6 to 8.1.0_
~- _Bump @bbc/psammead-locales from 4.1.2 to 4.1.4_~
- _Bump eslint-plugin-react-hooks from 2.5.0 to 2.5.1_
~- _Bump @bbc/psammead-timestamp-container from 2.7.7 to 2.7.9_~
- _Bump react from 16.13.0 to 16.13.1_
- _Bump @babel/plugin-transform-runtime from 7.8.3 to 7.9.0_
- _Bump morgan from 1.9.1 to 1.10.0_
- _Bump prettier from 1.19.1 to 2.0.1_

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by EinsteinNjoroge — APPROVED** [review]
There are lots of changes that have been introduced by prettier but overall looks good.

**Review by thekp — APPROVED** [review]
LGTM, looks like most of the changes are because of the prettier breaking change bump.

https://prettier.io/blog/2020/03/21/2.0.0.html

**Review by j-pendlebury — APPROVED** [review]
so. many. files.

Looked through majority of them and it LGTM 👍

**Comment by j-pendlebury** [comment]
image

although there are some files that were pulled in from latest that need fixing now

**Comment by PriyaKR** [comment]
LGTM.

**Pull request merged**
