### PR TITLE
Allow tree shaking, stop forcing everything to be CJS

### PR DESCRIPTION
**Pull request by dr3**
**Overall change:** Stops everything being forced to be commonjs :face-palm:

**Code changes:**

- Removes `@babel/plugin-transform-modules-commonjs`
- Uses `"sourceType": "script"` on logger files

Why `"sourceType": "script"` on logger files:
These files are script files, not modules. I have tried to turn them into modules however I always get a `nodeLogger is not a function` error, despite them console logging as one.
I have raised https://github.com/bbc/simorgh/issues/2419 to try and resolve this.

Testing notes:
Regression on logging on client & server and just ensuring no js errors crop up on server or client 

---

- [x] I have assigned myself to this PR and the corresponding issues
- ~[ ] Tests added for new features~
- [ ] Test engineer approval

### CODE REVIEW

**Review by jamesbhobbs — APPROVED** [review]

**Review by thekp — APPROVED** [review]
nice 🌮

**Comment by PriyaKR** [comment]
Seeing `failed prop type warnings` in the console which is not seen on `latest`.
Failed_prop_type

**Comment by dr3** [comment]
@PriyaKR doing `console.log(frontPageData.content.groups[5].items[0].indexImage);` in FrontpageMain, on this branch and latest both show undefined, so it looks like this console error always existsed, but was supressed. Odd, this is ok to merge with :)

**Comment by PriyaKR** [comment]
Looks good to me can be merged.

**Pull request merged**
