### PR TITLE
Reconciles old & new InlineLink components

### LINKED ISSUE #887: Reconcile InlineLink container files
**Is your feature request related to a problem? Please describe.**
Currently there are both `.index|.test|.jsx` and `index.new|.test|.jsx` files in `containers/InlineLink` these are artifacts from the [work to implement fragments/urlLinks](https://github.com/BBC-News/simorgh/pull/780).

image

**Describe the solution you'd like**
- We should overwrite the files without `.new` from the `.new` files. 
- We should ensure all components using the non `.new` files suffer no regression, if so fix
- We should  ensure all components using the `.new` files are updated following the reconciliation.

**Testing notes**
Will Cypress tests be required or are unit tests sufficient?

**Additional context**
The [issue around caption rendering logic](https://github.com/BBC-News/simorgh/issues/801) has potential to affect this ticket 

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by bcmn**
Resolves #887. Follows on from (& blocked by) #1025.

## Changes
- Removes deprecated InlineLink container, it's test, & it's snapshots.
- Renames `containers/InlineLink/index.new.jsx`, `containers/InlineLink/index.new.test.jsx`& `containers/InlineLink/__snapshots__/index.new.test.jsx.snap` to take their place.
- Removes Text component test & story which assumes old InlineLink behaviour
- Finally, updates Paragraph container to reflect rename.

The only remaining markdown link outside of a markdown file is in a Text component story, which will be deleted in a following PR.

---

- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by ChrisBAshton — DISMISSED** [review]
Thank you so much 🎉 can't wait to reconcile these inline links!

**Review by ChrisBAshton — APPROVED** [review]

**Review by sareh — APPROVED** [review]
👍 Looks good!

**Review by dr3 — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
dashboard
Error within the console when using an inline link. This was found to be on `latest` too. Therefore this was not caused by this work. Thanks, Ben.

**Comment by jamesbrumpton** [comment]
LGTM

**Pull request merged**
