### PR TITLE
Recommendations click tracking

### LINKED ISSUE #9081: Use view and click tracking hooks on recommendations component
**Is your feature request related to a problem? Please describe.**
As an owner of the world service I want to know how links/promos perform within the Onward Journeys block so that we can get feedback on the recommendations. I also  want to know if how users are interacting with this component compared to other components on the page. 

**Describe the solution you'd like**
To track the block so we can compare it to other components on the page, add tracking to the block. This should send a view event for the block and a block click event if a link/promo is clicked. The conent of the of the view and click event for the block must be the same so ATI can calculate the click/view value.  
To track what links clicked, add tracking to the links in the Onward Journey block. This should send a view event for each link/promo in the block and a click event if a link/promo is clicked. The content of the view and click event for the link must be the same so ATI can calculate the click/view value.
This means:
view events:
A single view event for the block
A view event for each link

click events:
A click event for the block
A click event for the link

**Example**
Clicking the '"Promising Young Woman"' link on the page https://www.bbc.com/mundo/noticias-56885546

image-2021-04-26-16-49-04-330

Each link has its own click and view event.

### The link click event

`atc=PUB-[Campaign]-[Creation]-[Variant]-[Format]-[General Placement]-[Detailed Placement]-[Advertiser ID]-[Url]&type=AT`

```
(atc)
atc=PUB-[cps_wsoj]-[%22Promising%20Young%20Woman%22%3A%20la%20inquietante%20realidad%20que%20retrata%20la%20pel%C3%ADcula%20nominada%20a%205%20premios%20Oscar]-[]-[CHD=promo::2]-[mundo.also_in_the_news.story.56885546.page]-[]-[mundo]-[https://www.bbc.com/mundo/noticias-56669604 ]
&type=AT
```

### The link view/impression event

`ati=PUB-[Campaign]-[Creation]-[Variant]-[Format]-[General Placement]-[Detailed Placement]-[Advertiser ID]-[Url]&type=AT`

```
(ati)
atc=PUB-[cps_wsoj]-[%22Promising%20Young%20Woman%22%3A%20la%20inquietante%20realidad%20que%20retrata%20la%20pel%C3%ADcula%20nominada%20a%205%20premios%20Oscar]-[]-[CHD=promo::2]-[mundo.also_in_the_news.story.56885546.page]-[]-[mundo]-[https://www.bbc.com/mundo/noticias-56669604 ]
&type=AT
```

### Example values from click/impression events
the values are

Campaign | cps_wsoj
-- | --
Creation | link text
Variant | empty
Format | [CHD=promo::1]
General placement | page
detailed placement | empty
advertiser ID | site of link
url | url of link

Examples:
|                    |                                                                                                                                            |
| ------------------ | ------------------------------------------------------------------------------------------------------------------------------------------ |
| Campaign           | cps_wsoj                                                                                                                        |
| Creation           | %22Promising%20Young%20Woman%22%3A%20la%20inquietante%20realidad%20que%20retrata%20la%20pel%C3%ADcula%20nominada%20a%205%20premios%20Oscar |
| Variant            | empty                                                                                                                                      |
| Format             | [CHD=promo::2] (Note that 2 indicates that this promo is the 2nd recommendation)                                                           |
| General Placement  | mundo.also_in_the_news.story.56885546.page                                                                                                 |
| Detailed Placement | empty                                                                                                                                      |
| Advertiser ID      | mundo                                                                                                                                      |
| Url                | https://www.bbc.com/mundo/noticias-56669604                                                                                                |

Note: To capture the relative location of the item within the block use the follow in the format string (starting with 1) CHD=promo::n

###  The Block click event
Send a block level click event if any link/promo within the block is clicked. (we are only tracking the interaction and not tracking the link location)

Don't send a click event if any other part of the block is clicked.
`atc=PUB-[Campaign]-[Creation]-[Variant]-[Format]-[General Placement]-[Detailed Placement]-[Advertiser ID]-[Url]&type=AT`

`atc=PUB-[article-sty]-[wsoj]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]&type=AT`

### The block view/impression event
`ati=PUB-[Campaign]-[Creation]-[Variant]-[Format]-[General]-[Detailed]-[Advertiser]-[Url]&type=AT`

`ati=PUB-[article-sty]-[wsoj]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]&type=AT`

### Accessibility
The solution should have no adverse affects with any of our support assistive technology. This will require a developer accessiblity swarm to check that nothing unexpected is read out, such as 'clickable'. e.g. Only the content and HTML semantics should be announced for elements, nothing extra to the defined screen reader UX for components. Note as we are using the same technical solution, this testing should be carried out on either this Issue or https://github.com/bbc/simorgh/issues/9082 - which ever is completed first.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
The WS event tracking matrix contains all tracking campaigns and which components are appear on which page types NEWSWORLDSERVICE/WS+event+matrix.

### PR DESCRIPTION
**Pull request by jroebu14**
Resolves https://github.com/bbc/simorgh/issues/9081

**Overall change:**
Implements view and click tracking hooks in the recommendations component.

Implements 2 different types of tracking:
**Block level tracking**
Tracks view and click events on the whole component. Only 1 view event and 1 click event is sent per page view.

**Link level tracking**
Tracks view and click events on each individual promo item. Only 1 view event and 1 click event per promo item per page view.

**Code changes:**
- Implements view and click tracking hooks in Recommendations.
- Refactors structure of `eventTrackingData` in `StoryPromo` component so that there can be a distinction between block and link level tracking.
- Refactors `getHeadlineUrlAndLive` utility function by splitting it up into 3 functions so that we can use to get the heading and url data for event tracking.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- We should test this locally before going to the test environment because it changes up the implementation of all existing event tracking.
- Recommendations component can be tested here http://localhost:7080/mundo/noticias-56669604
- Ensure all existing event tracking still works as expected.

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by ryanmccombe — APPROVED** [review]

**Review by rebeccamcginn — APPROVED** [review]

**Review by HarryVerhoef — APPROVED** [review]
Nice one! 🚀

**Comment by LilyL0u** [comment]
I see some differences to what is expected and laid out in the issue https://github.com/bbc/simorgh/issues/9081

**Block** view and click looks as expected but **link** views and clicks are different.

_Expected:_
PUB-[Campaign]-[Creation]-[Variant]-[Format]-[General Placement]-[Detailed Placement]-[Advertiser ID]-[Url]

_Actual:_
PUB-[Campaign]-[Creation]-[Variant]-[Format]-[General Placement]-[Detailed Placement]-**EMPTY-[Advertiser ID instead of URL]**
What is different: 
1. No url Is present 
2. advertiser ID is in a different location
3. The [General Placement] text is a bit different here with an extra ‘also_in_the_news::’ before the expected text. Maybe this is fine.

e.g I see
PUB-[article-sty]-[La conmovedora historia de cómo una madre y el hombre preso por la muerte de su hija se unieron para atrapar al verdadero asesino]-[]-[CHD=promo::1]-[**also_in_the_news::** mundo.also_in_the_news.story.56669604.page]-[]- **[]-[mundo]**

There are also some differences in the click event information:

Expected:
PUB-[cps_wsoj]-[%22Promising%20Young%20Woman%22%3A%20la%20inquietante%20realidad%20que%20retrata%20la%20pel%C3%ADcula%20nominada%20a%205%20premios%20Oscar]-[]-[CHD=promo::2]-[mundo.also_in_the_news.story.56885546.page]-[]-[mundo]-[https://www.bbc.com/mundo/noticias-56669604]

Actual:
PUB-[article-sty]-[La conmovedora historia de cómo una madre y el hombre preso por la muerte de su hija se unieron para atrapar al verdadero asesino]-[]-[CHD=promo::1]-[**also_in_the_news::** mundo.also_in_the_news.story.56669604.page]-[]- **[]-[]**

Where the characters in bold are different.

1. The URL is missing again
2. No advertiser ID (mundo)
3. The [General Placement] text is a bit different here with an extra ‘also_in_the_news::’ before the expected text. Maybe this is fine.

The campaign name is different but I expect this is correct

**Review by HarryVerhoef — APPROVED** [review]

**Comment by LilyL0u** [comment]
✅  View events now include the URL and the advertiser ID in the right place. 

✅  Click events now have the advertiser ID present and in the correct location 

🔴  but click link event is still missing the URL at the end.
e.g

PUB-[article-sty]-[Soy una mujer genocida y aún me persiguen los recuerdos de lo que hice]-[]-[CHD=promo::3]-[also_in_the_news::mundo.also_in_the_news.story.56669604.page]-[]-[mundo]-[]

The last brackets are expected to contain a URL.

**Comment by jroebu14** [comment]
@LilyL0u thanks! Should be fixed now

**Comment by LilyL0u** [comment]
The last brackets now contain the URL on the click event :)

PUB-[article-sty]-[Estrenos 2020: las 10 mejores películas de lo que va del año según la BBC (y que seguramente no pudiste ver en el cine)]-[]-[CHD=promo::4]-[also_in_the_news::mundo.also_in_the_news.story.56669604.page]-[]-[mundo]-**[http://localhost:7080/mundo/vert-cul-53370542]**

**Comment by LilyL0u** [comment]
The expected block click information is

PUB-[article-sty]-[wsoj]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]

But now also contains the URL like:
PUB-[article-sty]-[wsoj]-[]-[]-[also_in_the_news::mundo.also_in_the_news.story.56669604.page]-[]-[]-[http://localhost:7080/mundo/vert-cul-53370542]

Do we want this?

**Comment by jroebu14** [comment]
Good spot @LilyL0u

My mistake. I have fixed this now. Thanks for catching these bugs! Can you please retest when you have time?

**Comment by LilyL0u** [comment]
Looks good to me now. Link click event info includes the URL, block click event does not include the URL

**Comment by JonBeeb** [comment]
Hi just to confirm the component block level tracking and the link level tracking have different campaignIDs 
Block: (page id eg article-sty)
Link: cps_wsoj
So the link would be something like: 
PUB-**[cps_wsoj]**-[%22Promising%20Young%20Woman%22%3A%20la%20inquietante%20realidad%20que%20retrata%20la%20pel%C3%ADcula%20nominada%20a%205%20premios%20Oscar]-[]-[CHD=promo::2]-[mundo.also_in_the_news.story.56885546.page]-[]-[mundo]-[https://www.bbc.com/mundo/noticias-56669604]

**Comment by jroebu14** [comment]
@JonBeeb @LilyL0u I've fixed that issue now

**Comment by LilyL0u** [comment]
Block view and click events have [article-story] for the campaign ID
Link view and click events now have [cps_wsoj] for the campaign ID

**Review by mukama — APPROVED** [review]

**Pull request merged**
