### PR TITLE
Update podcast external links for Arabic and Marathi

### PR DESCRIPTION
**Pull request by georgva0**
Resolves #NUMBER

**Update podcast external links for Arabic and Marathi**
Adding missing Spotify and Apple Podcasts links to Arabic.js and Marathi.js in `/src/app/routes/onDemandAudio/tempData/podcastExternalLinks`

**Code changes:**

Adding missing value pairs. 

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by DarioR01 — APPROVED** [review]

**Comment by amoore108** [comment]
Looks good @georgva0 . I think these 2 objects should be merged into one? : https://github.com/bbc/simorgh/blob/103903336e1368a674c1a29b4fd35b032fa9a820/src/app/routes/onDemandAudio/tempData/podcastExternalLinks/marathi.js#L23-L38

They both have the key `p0b1s4nm` and the same Spotify `linkUrl `. The bottom one could probably be removed if they are the same.

**Comment by georgva0** [comment]
Thanks @amoore108 , I removed the duplication. Getting some errors on the workflow run on the linter. Are the linter rules available to have a look at somewhere? I have lint autosave enabled but maybe my rules are not the same for line length

**Comment by amoore108** [comment]
> Thanks @amoore108 , I removed the duplication. Getting some errors on the workflow run on the linter. Are the linter rules available to have a look at somewhere? I have lint autosave enabled but maybe my rules are not the same for line length

Do you have the 'Prettier - Code Formatter' extension installed if your are using VSCode? We have a `.prettierrc` file that should be all that is needed for formatting.

If you are using VSCode and have the extension installed, its worth checking the Settings and making sure Prettier is selected as the default formatter:
Screenshot 2021-11-16 at 10 53 02

**Comment by georgva0** [comment]
yeah, prettier is set as default globally, but probably my .prettierrc file is a bit different 
image

**Review by ryanmccombe — APPROVED** [review]

**Comment by amoore108** [comment]
> yeah, prettier is set as default globally, but probably my .prettierrc file is a bit different image

Do you also have the 'Format on Save' option checked in the settings too?:
Screenshot 2021-11-16 at 11 29 22

**Comment by georgva0** [comment]
yeah, format on save is enabled. I guess that's where the problem is - that my file is a bit different. 
image

**Comment by amoore108** [comment]
> yeah, format on save is enabled. I guess that's where the problem is - that my file is a bit different.)

There should be a `.prettierrc` file in the root of the Simorgh project that controls some of the formatting.

I would try closing down VSCode fully and then run `yarn install` from your command terminal to ensure the latest version of Prettier is installed in the project. Then open VSCode again and see if the formatting errors are highlighted in the file. I recall a couple of other engineers experiencing the same issues when we upgraded Prettier a few weeks ago, so it could just be a version mismatch.

If it still doesn't work, I can correct the formatting changes on my end to get the PR through.

**Comment by georgva0** [comment]
@amoore108 did yarn install, restarted VLC and tried fix the errors within Github as well, but no luck so far. I can see the .prettierrc file in the root too. maybe best if you can correct the formatting changes on your side to get the PR through? I'll try to compare the files after to see where the problem is.

**Comment by amoore108** [comment]
> @amoore108 did yarn install, restarted VLC and tried fix the errors within Github as well, but no luck so far. I can see the .prettierrc file in the root too. maybe best if you can correct the formatting changes on your side to get the PR through? I'll try to compare the files after to see where the problem is.

No worries. I've pushed in a formatting fix which seems to have resolved the build issue.

**Pull request merged**
