### PR TITLE
Delete automated tests for Media Asset Pages

### PR DESCRIPTION
**Pull request by karinathomasbbc**
Overall changes
======
Tests for Media Asset Pages are flaky, however, pages are no longer being routed to the MediaAssetPage, but use the MediaArticlePage instead.

Code changes
======

Delete E2E & integration tests for MediaAssetPages

Testing
======
PR checks pass (and run faster!)

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

### CODE REVIEW

**Review by Nabeel1276 — APPROVED** [review]
Just to confirm, Is the reason for removal due to Media Asset Pages being routed to MediaArticlePage?

**Comment by karinathomasbbc** [comment]
We have decided to keep the media asset page tests (as they are providing coverage for the media article page), and instead disable the flaky test(s)

**Comment by karinathomasbbc** [comment]
> Just to confirm, Is the reason for removal due to Media Asset Pages being routed to MediaArticlePage?

Good question @Nabeel1276, and now based on the discussions we've had with the team, yes, the MediaAssetPage is no longer rendering, however it is being rerouted to the MediaArticlePage. Removing these tests mean that we lose coverage, so we've decided to keep them for now, but disable the ones which are causing an issue.

**Comment by Nabeel1276** [comment]
> We have decided to keep the media asset page tests (as they are providing coverage for the media article page), and instead disable the flaky test(s)

Cool, thank you!

**Pull request closed without merging**
