### PR TITLE
Upgrade Simorgh to use Node 10

### LINKED ISSUE #941: Upgrade to Node v10
**Is your feature request related to a problem? Please describe.**
Now that [Node v10 is in long term support](https://nodejs.org/en/blog/release/v10.13.0/), let's update our [.nvmrc](https://github.com/BBC-News/simorgh/blob/latest/.nvmrc) and [.npmrc](https://github.com/BBC-News/simorgh/blob/latest/.npmrc) files and package-lock.json so that we're all running the latest stable version.

**Describe the solution you'd like**
Update Node version references everywhere where appropriate, and update the README.

Ensure that Node v10 runs locally with no issues, and ensure that CI continues to pass.

**Testing notes**
Ensure the build still passes.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by DemonusPC**
Resolves #941

**Overall change:** 
Upgraded Simorgh to use Node 10, and added a small fix so that the tests pass correctly.

**Code changes:**
- Updated the .nvmrc file to use the latest stable Node version 10 (v10.15.3)
- Updated the Jenkinsfile to use the node-10 container
- Added a small config change to the utility function. This is because the newer version of node needs more specificity when calling the `Object.defineProperty()` function. This doesn't change the behaviour of the tests in any way. 

---

- [ ] I have assigned myself to this PR and the corresponding issues
- ~[ ] Tests added for new features~
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by chris-hinds — CHANGES_REQUESTED** [review]
The readme will also need to be updated https://github.com/bbc/simorgh#installation

**Review by chris-hinds — APPROVED** [review]

**Review by rossgaskell — APPROVED** [review]
🎉 🎉 🎉 🎉
Welcome to 2018

**Comment by DemonusPC** [comment]
I will merge this first thing in the morning on Monday (13th of May 2019)

**Review by sareh — APPROVED** [review]

**Comment by PriyaKR** [comment]
LGTM.

**Pull request merged**
