### PR TITLE
WSTEAMA-1062: Add linting to ensure .only fails lint checks

### PR DESCRIPTION
**Pull request by karinathomasbbc**
Resolves JIRA https://jira.dev.bbc.co.uk/browse/WSTEAMA-1062

Overall changes
======
_A very high-level summary of easily-reproducible changes that can be understood by non-devs, and why these changes where made._
Add linting to prevent `describe.only` and `it.only` tests

Code changes
======
- Adding a new linting package & enable it

Testing
======
Run `yarn test:lint` locally with a file which had it.only = linting failed as expected
PR checks should also fail if there's a test with it.only implemented 

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

### CODE REVIEW

**Comment by amoore108** [comment]
Is the expected behaviour for this to auto-remove `.only` on save? It appears to do that for me, but I find using `.only` quite useful when wanting to run one or a sub-test of tests.

**Comment by karinathomasbbc** [comment]
> Is the expected behaviour for this to auto-remove `.only` on save? It appears to do that for me, but I find using `.only` quite useful when wanting to run one or a sub-test of tests.

Oh... let me check, we probably wouldn't want it to auto-fix, but we would want it to fail the linting checks in the PR so that we can't merge.

**Comment by amoore108** [comment]
> > Is the expected behaviour for this to auto-remove `.only` on save? It appears to do that for me, but I find using `.only` quite useful when wanting to run one or a sub-test of tests.
> 
> Oh... let me check, we probably wouldn't want it to auto-fix, but we would want it to fail the linting checks in the PR so that we can't merge.

Could just be a case of removing the `{fix: true}` bit, but yea definitely like the idea of it failing lint checks. I've been caught out with leaving a rogue `.only` before!

**Comment by karinathomasbbc** [comment]
> > > Is the expected behaviour for this to auto-remove `.only` on save? It appears to do that for me, but I find using `.only` quite useful when wanting to run one or a sub-test of tests.
> > 
> > 
> > Oh... let me check, we probably wouldn't want it to auto-fix, but we would want it to fail the linting checks in the PR so that we can't merge.
> 
> Could just be a case of removing the `{fix: true}` bit, but yea definitely like the idea of it failing lint checks. I've been caught out with leaving a rogue `.only` before!

It is! That seems to work OK. It is a autofixable lint error, but will only happen automatically if you run `yarn test:lint:fix`

And yes, we have also been caught out by this - I accidentally `it.only`'ed an integration test months ago, and it has been like that until we figured out why and fixed it (see https://github.com/bbc/simorgh/pull/11341 🤦) - hopefully this will make sure we don't get caught out in future!

**Comment by amoore108** [comment]
> It is! That seems to work OK. It is a autofixable lint error, but will only happen automatically if you run `yarn test:lint:fix`
> 
> And yes, we have also been caught out by this - I accidentally `it.only`'ed an integration test months ago, and it has been like that until we figured out why and fixed it (see #11341 🤦) - hopefully this will make sure we don't get caught out in future!

Nice, thanks for this!

**Review by amoore108 — APPROVED** [review]

**Review by pvaliani — APPROVED** [review]
Still buzzin to have spotted this one. This will help in the future, niceee

**Pull request merged**
