### PR TITLE
Add tests for CpsOnwardJourney

### LINKED ISSUE #6519: Add unit tests for `CpsOnwardJourney` component
**Is your feature request related to a problem? Please describe.**
When reviewing a refactor for the `CpsOnwardJourney` container it was identified the component had no unit tests: https://github.com/bbc/simorgh/pull/6393#pullrequestreview-411912690 

We were happy enough to merge this PR facilitate UX testing for Story page rollout but we need unit tests to properly cover this component and prevent regressions.

**Describe the solution you'd like**
Add unit tests covering functionality of `CpsOnwardJourney` component.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by andrewscfc**
Resolves https://github.com/bbc/simorgh/issues/6519

**Overall change:**
Adds various unit tests covering the configurable functionality used across the various CPS onward journey components.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by karinathomasbbc — APPROVED** [review]
LGTM 👍

**Comment by andrewscfc** [comment]
Just dismissing your review @karinathomasbbc as I realised that the last skip link test didn’t actually work, I didn’t `await` the a `waitFor` call, when I did the correct element didn’t seem to be focused. I’ve simplified the test as it was always a bit of a ‘nice to have’ to retest the skip link behaviour, that should be tested in the `SkipLinkWrapper` component itself.

Please feel free to disagree on this and we can invest more time?

**Comment by karinathomasbbc** [comment]
Happy with the tests (increased coverage), plsu with the addition of snapshots, it means that devs are forced to update them if this component changes. 👍

**Review by karinathomasbbc — APPROVED** [review]

**Review by rhenshaw56 — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Doesn't need manual testing, moving it to Ready to merge..

**Pull request merged**
