### PR TITLE
Psammead package bumps

### PR DESCRIPTION
**Pull request by jroebu14**
**Overall change:** #2328
**Code changes:**

 - update `psammead-image-placeholder` from `1.0.1` to `1.0.2`
| 1.0.2 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |

 - update `psammead-copyright` from `1.0.2` to `1.0.3`
| 1.0.3 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |

 - update `psammead-media-indicator` from `1.0.3` to `1.1.1`
| 1.1.1 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |
| 1.1.0   | [PR#776](https://github.com/bbc/psammead/pull/776) Add `topStory` prop, change padding <400px and bump dependencies |
| 1.0.5   | [PR#788](https://github.com/BBC/psammead/pull/788) Use rem for the width and height of the Media SVGs |
| 1.0.4   | [PR#769](https://github.com/bbc/psammead/pull/769) Fix stories not appearing in storybook when using `install:packages:link` |

 - update `psammead-story-promo-list` from `1.0.2` to `1.0.3`
| 1.0.3 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |

 - update `psammead-consent-banner` from `1.0.0` to `1.0.2`
| 1.0.2 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |
| 1.0.1   | [PR#713](https://github.com/bbc/psammead/pull/713) Update `styled-components` to 4.3.2 |

 - update `psammead-caption` from `1.1.7` to `1.1.11`
| 1.1.11 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |
| 1.1.10   | [PR#769](https://github.com/bbc/psammead/pull/769) Fix stories not appearing in storybook when using `install:packages:link` |
| 1.1.9 | [PR#745](https://github.com/bbc/psammead/pull/745) Use `@bbc/psammead-inline-link@1.1.1` and update 'with inline link' story |
| 1.1.8 | [PR#763](https://github.com/bbc/psammead/pull/763) Change text colour to `C_CLOUD_DARK` for `C_METAL` |

 - update `psammead-paragraph` from `1.0.5` to `1.0.9`
| 1.0.9 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |
| 1.0.8   | [PR#769](https://github.com/bbc/psammead/pull/769) Fix stories not appearing in storybook when using `install:packages:link` |
| 1.0.7   | [PR#746](https://github.com/bbc/psammead/pull/746) Use `@bbc/psammead-inline-link@1.1.1` and add a 'with inline link' story |
| 1.0.6   | [PR#713](https://github.com/bbc/psammead/pull/713) Update `styled-components` to 4.3.2 |

 - update `psammead-storybook-helpers` from `3.1.0` to `3.1.1`
| 3.1.1 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |

 - update `psammead-brand` from `4.1.4` to `4.1.8`
| 4.1.8 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |
| 4.1.7   | [PR#787](https://github.com/bbc/psammead/pull/787) Fix brand colour in Firefox high contrast mode |
| 4.1.6   | [PR#789](https://github.com/bbc/psammead/pull/789) Use rem for the `BrandSvg` height |
| 4.1.5   | [PR#769](https://github.com/bbc/psammead/pull/769) Fix stories not appearing in storybook when using `install:packages:link` |

 - update `psammead-sitewide-links` from `1.0.2` to `1.0.4`
| 1.0.4 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |
| 1.0.3   | [PR#769](https://github.com/bbc/psammead/pull/769) Fix stories not appearing in storybook when using `install:packages:link` |

 - update `psammead-navigation` from `1.0.1` to `1.0.3`
| 1.0.3 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |
| 1.0.2 | [PR#769](https://github.com/bbc/psammead/pull/769) Fix stories not appearing in storybook when using `install:packages:link` |

 - update `psammead-assets` from `1.0.2` to `1.0.4`
| 1.0.4 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |
| 1.0.3   | [PR#787](https://github.com/bbc/psammead/pull/787) Fix brand stories in Firefox high contrast mode |

 - update `psammead-figure` from `1.0.2` to `1.0.4`
| 1.0.4 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |
| 1.0.3 | [PR#769](https://github.com/bbc/psammead/pull/769) Fix stories not appearing in storybook when using `install:packages:link` |

 - update `psammead-section-label` from `1.0.2` to `1.0.4`
| 1.0.4 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |
| 1.0.3   | [PR#769](https://github.com/bbc/psammead/pull/769) Fix stories not appearing in storybook when using `install:packages:link` |

 - update `psammead-headings` from `2.0.2` to `2.0.4`
| 2.0.4 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |
| 2.0.3 | [PR#769](https://github.com/bbc/psammead/pull/769) Fix stories not appearing in storybook when using `install:packages:link` |
| 2.0.2   | [PR#713](https://github.com/bbc/psammead/pull/713) Update `styled-components` to 4.3.2 |

 - update `psammead-story-promo` from `1.0.0-alpha.4` to `1.1.0-alpha.6`
| 1.0.0-alpha.6   | [PR#893](https://github.com/bbc/psammead/pull/893) Fix knobs for story promo stories |
| 1.0.0-alpha.5   | [PR#769](https://github.com/bbc/psammead/pull/769) Fix stories not appearing in storybook when using `install:packages:link` |

 - update `psammead-inline-link` from `1.1.0` to `1.1.6`
| 1.1.6 | [PR#942](https://github.com/bbc/psammead/pull/942) Revert new inline-link styling due to [bug](https://github.com/bbc/simorgh/issues/2370) |
| 1.1.5 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |
| 1.1.4 | [PR#769](https://github.com/bbc/psammead/pull/769) Fix stories not appearing in storybook when using `install:packages:link` |
| 1.1.3 | [PR#775](https://github.com/bbc/psammead/pull/775) Add section to readme regarding using this component without a wrapper and padding/margin |
| 1.1.2 | [PR#687](https://github.com/bbc/psammead/pull/687) Change visited text colour to `C_CLOUD_DARK` for `C_METAL` |
| 1.1.1 | [PR#761](https://github.com/bbc/psammead/pull/761) Link default `color` should be `Ebon` not `Postbox` |

 - update `psammead-styles` from `1.0.0` to `1.1.2`
| 1.1.2 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |
| 1.1.1 | [PR#769](https://github.com/bbc/psammead/pull/769) Fix stories not appearing in storybook when using `install:packages:link` |
| 1.1.0   | [PR#764](https://github.com/bbc/psammead/pull/764) Add function to get serif bold font |
| 1.0.1   | [PR#677](https://github.com/bbc/psammead/pull/677) Use `@bbc/gel-foundations@3.0.0` |
 
 - update `psammead-visually-hidden-text` from `1.0.1` to `1.0.3`
| 1.0.3 | [PR#783](https://github.com/bbc/psammead/pull/783) Update to latest psammead-test-helpers. Update snapshots. |
| 1.0.2 | [PR#769](https://github.com/bbc/psammead/pull/769) Fix stories not appearing in storybook when using `install:packages:link` |

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by dr3** [comment]
@jroebu14 Can you check psammead package changelogs for what changes we expect to propogate please?

**Review by dr3 — DISMISSED** [review]
@jroebu14 Can you check psammead package changelogs for what changes we expect to propogate please?

**Comment by jroebu14** [comment]
@dr3 I've included the changelogs in the PR description

**Review by chris-hinds — APPROVED** [review]
LGTM based on the changelogs.

**Review by dr3 — APPROVED** [review]
Please test WITH CAUTION, checking each of the changes in the PR description

**Comment by PriyaKR** [comment]
Testing: [https://github.com/bbc/psammead/pull/1038](url) has to be merged before this has been picked up for testing.

**Comment by jamesbhobbs** [comment]
Closing as we have many deps lower in tree to update.

**Pull request closed without merging**
