### PR TITLE
Bump rich-text-tranforms@1.1.1 to fix client side XML parsing bug

### LINKED ISSUE #4408: CPS Pages - Any blocks with `bold` or `italic` dont transform on client correctly
**Describe the bug**

**To Reproduce**

1. Go to http://localhost:7080/igbo/afirika-23252735
2. Click on `Test MAP to MAP inline link`
3. See blocks
4. Refresh
5. See more blocks

**Expected behavior**
All blocks render, with no different on server to client

**Desktop (please complete the following information):**

Mac Chrome 77.0.3865.120

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by pjlee11**
Resolves #4408

**Overall change:** Bumps `@bbc/psammead-rich-text-transforms@1.1.1`

---

- [x] I have assigned myself to this PR and the corresponding issues
- ~[ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)~
- ~[ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)~
- [x] This PR requires manual testing

## Testing notes
- `npm run start && npm run build` 
- visit http://localhost.bbc.com:7080/pidgin/tori-49450859
- click "Test MAP to MAP inline link" 
- Ensure that paragraphs that contain bold (blocks that have `candy_xml` mark up type) render as expected. This can also be checked by refreshing the page to get a server render and ensure no new content appears after the refresh. 

# Client side parsing bug prior to PR
Client side parsing failing

# Client side render following this PR
Client side parsing working

### CODE REVIEW

**Review by ryanmccombe — APPROVED** [review]

**Review by dr3 — APPROVED** [review]

**Comment by pjlee11** [comment]
I got excited at the look of the merge button and clicked it by mistake 🤦‍♂ Will put this in "Ready for Test" and the testing instructions can be run against most recent latest

**Comment by LilyL0u** [comment]
Link "Test MAP to MAP inline link" is no longer on the page so I went straight to the URL. Is this a key step of the test? @pjlee11 

The page http://localhost.bbc.com:7080/pidgin/tori-49450859 does not have the link and also has a 'Page not available' page showing within the frame.


Text with candy_xml markup type and <bold> show as bold in the paragraph text.

Image 28-10-2019 at 11 24
Image 28-10-2019 at 11 25

**Comment by pjlee11** [comment]
@LilyL0u It is a key part of the test, seems like it might be because of the `.bbc.com` in the localhost URL which got changed recently. Try http://localhost:7080/pidgin/tori-49450859 instead 😄

**Comment by LilyL0u** [comment]
Works with new link. Bold text renders as bold after clicking the link and no new content after refresh.

**Pull request merged**
