### PR TITLE
Bump psammead media player for valid amp

### LINKED ISSUE #4078: Make live radio pages amp valid, plus add to validation test
**Is your feature request related to a problem? Please describe.**
Bump in the psammead media player changes that make the component AMP valid. Also add the live radio URL to the `amp:validate` command. 

**Testing notes**
[Tester to complete]

Dev insight: Automated test will suffice

- ~[ ] This feature is expected to need manual testing.~

### PR DESCRIPTION
**Pull request by pjlee11**
Resolves #4078 4078

**Overall change:** Bumps psammead media player to include changes to make the player AMP valid. Also updates the `amp:validate` command to check the live radio URL.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- ~[ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)~
- ~[ ] This PR requires manual testing~

**Before this PR** 
image

**After this PR** 
image

### CODE REVIEW

**Review by dr3 — APPROVED** [review]
LGTM assuming passes

**Comment by pjlee11** [comment]
@dr3 it's run as part of `npm run test` so has to pass for the PR checklist to be mergeable, plus see screenshot in description

**Review by simonsinclair — APPROVED** [review]
This looks good. 👍

**Review by ibMadbouly — APPROVED** [review]
LGTM 👍

**Pull request merged**
