### PR TITLE
Disabled live radio e2es for 18 services

### LINKED ISSUE #6660: Investigate: Can we disable some of the live radio E2E tests?
**Is your feature request related to a problem? Please describe.**
In analysing the metrics for Cypress tests in the Test & Live environments (https://paper.dropbox.com/doc/E2E-Test-Improvements--A0vzJEsibrpNfQAoG0O6NPY3Ag-hW9KxI5VIfsUPvBQbn5Yu#:uid=509547277800101499136606&h2=Metrics:-Before) we have discovered that the live radio E2E tests run for all 23 services. These tests also run on canonical & AMP, therefore 46 in total. The tests take approx 30 minutes to run.

**Describe the solution you'd like**
Could we experiment with reducing the number of live radio tests which run in Test / Live E2Es by disabling certain services?

Can we select a cross section of live radio services to cover the main variants?
- RTL vs LTR service
- persian has 2 urls - bbc_persian_radio and bbc_dari_radio
- afaanoromoo redirects to bbc_oromo_radio

**Describe alternatives you've considered**

**Testing notes**

**Additional context**

### PR DESCRIPTION
**Pull request by LilyL0u**
**Overall change:**

As part of reducing the run time of the Cypress tests, I am disabling some of the services that run on live radio pages.

Keeping 

afaanoromoo (keeping due to the two different url issue)
Hindi (having a redirect related to hindi radio soon, not sure if keeping it in is needed but can remove later)
Korean (LTR)
Persian (bbc_persian_radio and bbc_dari_radio) (RTL)

Removed

Afrique
Amharic
Arabic
Bengali
Burmese
Gahuza
Hausa
Indonesia
Kyrgyz
Nepali
Pashto
Sinhala
Somali
Swahili
Tamil
Tigrinya
Urdu
Uzbek

**Code changes:**

Changed enabled to false.
---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**

Running these services on my machine took 73.36 seconds on test and 72.25 seconds on live when just running the live radio page type.

### CODE REVIEW

**Comment by karinathomasbbc** [comment]
To save us having to come back and update the tests when Hindi is redirected (because they are no longer broadcasting live radio), is it just worth disabling it now, and selecting another service instead?

**Comment by karinathomasbbc** [comment]
Also remember amharic is used for smoke testing, so we have that too.

**Review by karinathomasbbc — APPROVED** [review]

**Review by sareh — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]
👍

**Comment by LilyL0u** [comment]
> To save us having to come back and update the tests when Hindi is redirected (because they are no longer broadcasting live radio), is it just worth disabling it now, and selecting another service instead?

@karinathomas  Removed

**Pull request merged**
