### PR TITLE
Fix malformed seo urls

### LINKED ISSUE #7890: Simorgh getting requests with a `.` in the url
## Description

We are seeing requests with a `.` in the url instead of a `/`. We are not sure at what part of the stack this happening. 

- Is Mozart receiving requests with a `.` in the url and sending it to Simorgh
- Is Mozart sending the correct request and Simorgh is somehow transforming the url to include the `.` instead of a `/`

### Examples of malformed URLs
```
/zhongwen/trad.comments_on_china/2013/05/130515_coc_taiwanese_chinese
/zhongwen/trad.comments_on_china/2014/12/141203_coc_mainland_view_twelection
```

According to our logs Simorgh is receiving hundreds of these requests a day.

## Task
To identify the source of these malformed url's i.e. is it a bug in Mozart or Simorgh. Is it just a bug with our logging (less likely) and to either raise a fix PR or an issue to get the bug fixed.

### PR DESCRIPTION
**Pull request by rhenshaw56**
Resolves #7890 

**Overall change:**
_Fixes malformed SEO urls in TLD logic._

Mostly due to application of regex on entire url, so paths with a `"co"` or `"com"` like `/zhongwen/trad/comments_on_china/2013/05/130515_coc_taiwanese_chinese` was getting transformed to `/zhongwen/trad.comments_on_china/2013/05/130515_coc_taiwanese_chinese`

See [Url value in SEO tool](https://bit.ly/33F05S1)

**Code changes:**

- _Applyy tld regex only on origin._
- _Add unit test specific to this case_

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [X] I have assigned this PR to the Simorgh project

**Testing:**

- [X] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [X] This PR requires manual testing

### CODE REVIEW

**Review by karinathomasbbc — APPROVED** [review]
Amazing! Thanks for fixing this 🎉

**Review by andrewscfc — COMMENTED** [review]
Looks good, should we address the security warnings while we are here? Do we just need to escape the dots `.` e.g. `/(\.com|\.co\.uk)/g;`?

**Comment by rhenshaw56** [comment]
> Looks good, should we address the security warnings while we are here? Do we just need to escape the dots `.` e.g. `/(\.com|\.co\.uk)/g;`?

@andrewscfc yes just the dot parts in the origin.

**Comment by rhenshaw56** [comment]
> Looks good, should we address the security warnings while we are here

@andrewscfc what security warnings ?

**Comment by andrewscfc** [comment]
> > Looks good, should we address the security warnings while we are here
> 
> @andrewscfc what security warnings ?

I'm seeing these in the PR from Code QL:
image

**Comment by karinathomasbbc** [comment]
The integration test snapshots are failing, however it is highlighting a possible issue with the fix. The canonical link should not include .amp at the end.
image

**Review by chris-hinds — APPROVED** [review]
Nice work @rhenshaw56 do you think there is anything we can do about these warnings? https://github.com/bbc/simorgh/security/code-scanning/11?query=ref%3Arefs%2Fpull%2F8032%2Fhead

**Comment by rhenshaw56** [comment]
> Nice work @rhenshaw56 do you think there is anything we can do about these warnings? https://github.com/bbc/simorgh/security/code-scanning/11?query=ref%3Arefs%2Fpull%2F8032%2Fhead

I just pushed a commit that should fix that and the failing tests cc @karinathomasbbc

**Comment by karinathomasbbc** [comment]
> > Nice work @rhenshaw56 do you think there is anything we can do about these warnings? https://github.com/bbc/simorgh/security/code-scanning/11?query=ref%3Arefs%2Fpull%2F8032%2Fhead
> 
> I just pushed a commit that should fix that and the failing tests cc @karinathomasbbc

Nice thanks! :shipit:

**Comment by paruchurisilpa** [comment]
Checked zhongwen STY & PGL's using SEO URL and seems to work as expected without any issues..LGTM..

**Pull request merged**
