### PR TITLE
Mundo + Brasil translations

### PR DESCRIPTION
**Pull request by jimjohnsonrollings**
Part of #4274 

**Overall change:** 
- Updates translations for Mundo and Brasil

**Code changes:**
- Updates translations for Mundo and Brasil
- Updates snapshots

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by simonsinclair — COMMENTED** [review]
This looks good. Do we need any translations for these additions from `latest`? https://github.com/bbc/simorgh/blob/3a3bfdc0692a536e51aee46fc3e17fc0a4cd16c6/src/app/lib/config/services/mundo.js#L59-L63

**Comment by jimjohnsonrollings** [comment]
> This looks good. Do we need any translations for these additions from `latest`?
> 
> https://github.com/bbc/simorgh/blob/3a3bfdc0692a536e51aee46fc3e17fc0a4cd16c6/src/app/lib/config/services/mundo.js#L59-L63

Yeah probably.  Irritating that whoever added them to latest didn't do them :(

**Comment by jimjohnsonrollings** [comment]
I've updated Mundo with those additional fields.  We don't have them for Brasil so they'll have to stay as they are until the media pod request them.

**Review by simonsinclair — COMMENTED** [review]
I might be missing something, but don't think these translations are covered by any tests. Would it make sense to update our snapshot coverage here to prevent any future regressions?

Edit: We'd need to snapshot test every container for every service to do this, which could get a bit crazy. It's probably worth discussing if this would be worthwhile in a dedicated issue.

**Review by simonsinclair — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]

**Review by j-pendlebury — APPROVED** [review]

**Pull request merged**
