### PR TITLE
all service configs need langs

### PR DESCRIPTION
**Pull request by andrew-nowak**
Unblocks #NUMBER 

**Overall change:** Adds a `lang` key to the three service configs which were missing one

**Code changes:**

- ⬆️ 

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by ghost** [comment]
I know this is not part of your PR but am just curios to what happens to `isoLang`? is there anywhere that we use `isoLang`?

**Review by EinsteinNjoroge — APPROVED** [review]

**Review by dr3 — APPROVED** [review]

**Comment by andrew-nowak** [comment]
> I know this is not part of your PR but am just curios to what happens to `isoLang`? is there anywhere that we use `isoLang`?

@sadickisaac Great question! isoLang is what we use in the hreflang meta tags (eg. `<link data-react-helmet="true" rel="alternate" href="https://www.bbc.com/igbo" hreflang="ig">`) which Google requires to be in 'ISO 639-1' format (see https://support.google.com/webmasters/answer/189077?hl=en) but 'pcm' (and possibly other services' language codes) do not exist in ISO 639-1 so we can't put a value there.

The lang attribute in `<html>` in contrast accepts BCP47 (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang#Language_tag_syntax) which does include among others 'pcm', and these should be covered in our service configs.

The reason these weren't needed before was that our frontpages found the BCP47 language value from the ares data feed, but the new localised error pages don't have a data feed to draw upon so we need a default language for each service

**Comment by ghost** [comment]
@aacn500 Thanks for the explanation and link to the resources. 👍

**Comment by PriyaKR** [comment]
LGTM.

**Pull request merged**
