### PR TITLE
Move preprocessor

### PR DESCRIPTION
**Pull request by dr3**
**Overall change:** Move preprocessor rules around

Moves them into contained folders in the `/folder/index.js` and `folder/index.test.js` structure, as well as moving them into folders for their page type

**Code changes:**

- Move preprocessor rules

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by jroebu14 — COMMENTED** [review]
What about placing the preprocessor functions in the same folder as the functions that use them? e.g in `src/app/routes/getInitialData/frontpage/index.js`

This means you don't need to go far to get the relevant code and you don't need to mirror the same folder structure in a global utils folder.

**Comment by dr3** [comment]
> What about placing the preprocessor functions in the same folder as the functions that use them? e.g in `src/app/routes/getInitialData/frontpage/index.js`
> 
> This means you don't need to go far to get the relevant code and you don't need to mirror the same folder structure in a global utils folder.

@jroebu14 When we add CpsAsset page type, it will need to use `rules/article/timestamp`. Keeping them here implies type, but doesnt lock them to a single page type. E.g. two getInitialData's going to `rules/article/timestamp` is nicer than 1 getInitialData, going into another to use its rule?

Thoughts? 🙈

**Comment by jroebu14** [comment]
Emm I guess that's a good reason for `timestamp` alone to be in a shared utils folder then. I'm not sure what it does but if we want to imply type then this could be done in the naming of function/file e.g. `addTimestampToArticleBlocks` or something.

**Comment by dr3** [comment]
>Emm I guess that's a good reason for timestamp alone to be in a shared utils folder then.

@jroebu14 On reflection, It can be when it is shared. Just if we move rules into the getInitialData, having shared ones means the rules will be entirely split up. Keeping them here makes more sense IMO


Re the naming ones like `filterUnknownContentTypes` could get quite long if name spaced

**Review by pjlee11 — APPROVED** [review]
LGTM 👍

**Comment by AlistairGempf** [comment]
> What about placing the preprocessor functions in the same folder as the functions that use them? e.g in `src/app/routes/getInitialData/frontpage/index.js`
> 
> This means you don't need to go far to get the relevant code and you don't need to mirror the same folder structure in a global utils folder.

@dr3 Similar question to this one, is there a reason for not importing and exporting all the frontpages rules from a file such as `src/app/lib/utilities/preprocessor/rules/frontPage/index.js`? Would reduce the number of lines of importing making it a bit easier to read.

**Review by ryanmccombe — APPROVED** [review]

**Comment by dr3** [comment]
Out of date and crazy conflicts, will redo at later date

**Pull request closed without merging**
