### PR TITLE
Add Fixuture data for MAP V1

### LINKED ISSUE #3826: Add Fixture Data for MAP v1
**Is your feature request related to a problem? Please describe.**
Add local fixture data for all the payloads we have chosen for our v1 test implementation

**Describe the solution you'd like**
See payloads here: 
https://ares-broker.test.api.bbci.co.uk/api/asset/japanese/video-23248670
https://ares-broker.test.api.bbci.co.uk/api/asset/korean/media-23248686
https://ares-broker.test.api.bbci.co.uk/api/asset/pidgin/23248703
https://ares-broker.test.api.bbci.co.uk/api/asset/punjabi/media-23248705
https://ares-broker.test.api.bbci.co.uk/api/asset/sinhala/23248970
https://ares-broker.test.api.bbci.co.uk/api/asset/thai/thailand-23248713
https://ares-broker.test.api.bbci.co.uk/api/asset/uzbek/sport-23248721

Copy these into JSON files within Simorgh's data directory, so they are available for local development / storybook / testing

- Get ARES response from links above 
- Add to JSON files within the simorgh /data directory following the existing naming pattern

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: No tests needed - this is just JSON dev data

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by ibMadbouly**
Resolves #3826 

for the following services
- Japanese
- Korean
- pidgin
- punjabi
- thai
- sinhala
- Uzbek

fixture data added based on `AReS` payloads (listed in the issue)

**Code changes:**
at `/data` directory added `json` file for each `/mediaAssetPage` directory 

**Testing notes**
the following URLs need to be tested for `.json` , `.amp` and like its 

`http://localhost:7080/sinhala/23248970`
`http://localhost:7080/thai/thailand-23248713`
`http://localhost:7080/uzbek/sport-23248721`
`http://localhost:7080/japanese/video-23248670`
`http://localhost:7080/pidgin/23248703`
`http://localhost:7080/punjabi/media-23248705`
`http://localhost:7080/korean/media-23248686`

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by ryanmccombe — APPROVED** [review]
Looks good 👍 
We will need an english one too as mentioned at refinement - @aeroplanejane

**Review by pjlee11 — APPROVED** [review]
LGTM

**Comment by ibMadbouly** [comment]
>  We will need an english one too as mentioned at refinement - @aeroplanejane

**Comment by paruchurisilpa** [comment]
Looks good to me..

**Comment by chris-hinds** [comment]
Are there any e2e's already setup for the media asset pages? If so could they be enabled on this PR to run against localhost now that we have fixture data

**Comment by pjlee11** [comment]
@hindsc52 the Cypress tests were added for all services in https://github.com/bbc/simorgh/pull/3836. The new assets being added in this PR should override the asset URLs in 3836

**Comment by chris-hinds** [comment]
> @hindsc52 the Cypress tests were added for all services in #3836. The new assets being added in this PR should override the asset URLs in 3836

Good to go from me then. Thanks for the explanation.

**Review by chris-hinds — APPROVED** [review]

**Pull request merged**
