### PR TITLE
WSTEAMA 439 Route Kyrgyz Homepage

### PR DESCRIPTION
**Pull request by holchris**
[Resolves JIRA 439](https://jira.dev.bbc.co.uk/browse/WSTEAMA-439)

Overall changes
======
Adds logic and unit tests to ensure that on all environments (local, test, live) the homepage is rendered when service=kyrgyz 

Code changes
======
- Adds tests for migrated services and services with variants 
- Adds logic to reflect new tests

Testing 
======
Unit tests updated to reflect new logic

### CODE REVIEW

**Review by amoore108 — APPROVED** [review]
Looks good 👍 Is this to be merged in today (12th)? or are we holding off until tomorrow?

**Review by alex-magana — APPROVED** [review]

**Comment by holchris** [comment]
@amoore108 I am unsure, I will find out in standup!

**Comment by holchris** [comment]
This is getting merged tomorrow morning @amoore108!

**Comment by amoore108** [comment]
> This is getting merged tomorrow morning @amoore108!

Cool, thanks for confirming! 👍

**Pull request merged**
