### PR TITLE
Update tests for STY features

### LINKED ISSUE #6479: Update test for STY features.
**Is your feature request related to a problem? Please describe.**
Update tests for STY page features.

**Describe the solution you'd like**

**STY Features To Test to add/consider**
- **Secondary column**
  - **Features/Top stories.**
    - Should not render images for top stories.
    - What happens when top stories or features are not given
    - Add test when features or top stories are empty
  - **Most read**
    - Is it enough to test whether ol is in the page or should we replace that with a snapshot?
https://github.com/bbc/simorgh/blob/76225ee9728c1dca8ccdaeff2da39926fb154f84/src/app/containers/MostRead/index.test.jsx#L42-L43
    - Add test when most read empty
- **Social Embeds**
    - For amp we should add an e2e test to ensure that it is rendered correctly the current snapshot test is not sufficient.
- **Includes**
  - IDT1 and VJ
    - Add e2e test to make sure interactive includes are interactive.

**Describe alternatives you've considered**

**Testing notes**
  - Everything above looks good for me interms of testing. For Most Read I think testing whether ol is in the page is enough..

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ X ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by FK78**
Resolves #6479

**Overall change:**
_Increasing test coverage for STY features._

**Code changes:**

- _Test added to ensure Top Stories are not rendering images._
- _Test added to ensure Top Stories is not rendering when empty._
- _Test added to ensure Features Analysis is not rendering when empty._
- _Test added to ensure Most Read is not rendering when data response is empty._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks great.

**Review by rhenshaw56 — APPROVED** [review]

**Comment by andrewscfc** [comment]
It's not specifically part of this issue, but I think our view without Features and Analysis and Top Stories is less than ideal:
image

I think we should raise a bug for this and see if it needs fixing before go live.

**Comment by HarveyPeachey** [comment]
> I think we should raise a bug for this and see if it needs fixing before go live.

Bug has been raised https://github.com/bbc/simorgh/issues/6521

**Comment by paruchurisilpa** [comment]
This doesn't need any testing. moving to Ready to merge...

**Pull request merged**
