### PR TITLE
WSTEAM1-425: Handle Next.JS `node_modules` with Yarn workspaces

### PR DESCRIPTION
**Pull request by shayneahchoon**
Resolves JIRA [WSTEAM1-425](https://jira.dev.bbc.co.uk/browse/WSTEAM1-425)

Overall changes
======
Change the ws-nextjs-app project to a workspace.
Under this PR, the nextjs app and the simorgh express app become two separate workspaces, with the simorgh express app acting as the top-level workspace. 

For the express app, you continue to just run `yarn` to install the dependencies for the express and run `yarn dev`/`yarn build` etc as normal.

For the nextjs app nothing changes either, you just run `yarn` in the `ws-next-js` dir as before and run `yarn dev`/`yarn build` etc as normal. Under the hood, node modules specific to the Next app are installed in a `node_modules` dir in the `ws-nextjs-app` dir while ones shared between Express and NextJS are installed in the route directory.

Code changes
======
- _List the ws-nextjs-app as a workspace within the repo `package.json`._
- _Remove the yarn.lock file for ws-nextjs-app._
- _Simplify `scripts/installNodeModules` as yarn workspaces now take care of `ws-nextjs-app` sub-repo_
- _Remove all duplicate dependencies from next `package.json`_
- _Remove the Next.JS app startup command from `yarn start`, as this will be handled automatically by the Lambda function_

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

### CODE REVIEW

**Comment by amoore108** [comment]
Thanks for taking a look at this, looks like an interesting approach. I ran it locally and it looks like the workspace creates a symbolic link to the Express app in the Next.JS node_modules. I _think_ this is ok? Seems to include the entire root folder though, and the `ws-nextjs-app` as well so there is potentially an infinite recursion going on? 

Do the `yarn build:` commands continue to work as expected too? Just thinking there may be some deploy pipeline updates required if they behave differently. 

Screenshot 2023-05-30 at 10 38 32

**Comment by amoore108** [comment]
Thanks for trying those changes.

I ran `yarn` in the root of the app (so the Express app) and it seems to have Next in its `node_modules` folder, so I guess its installing the Next.JS app dependencies too maybe?

I tried deleting the `node_modules` folder from the Next.JS app and it still runs without it, so it looks like its using the root `node_modules`.

Not sure this is what we want. It may not be possible to share the dependencies between the apps, we may just have to redefine them again in the Next.JS app package.json file.

Curious if @andrewscfc knows of any other approaches.

**Comment by shayneahchoon** [comment]
Yeah, from my understanding yarn basically installs all the common dependencies from the specified workspaces into the top level project's `node_modules` folder. And then it uses symbolic links to direct imports from each workspace towards that top level `node_modules` folder.

**Comment by amoore108** [comment]
Superseded by https://github.com/bbc/simorgh/pull/10873

**Comment by andrewscfc** [comment]
Reconsidering this approach @shayneahchoon / @amoore108 , gonna do a few experiments

**Review by amoore108 — APPROVED** [review]

**Review by karinathomasbbc — APPROVED** [review]
Thanks for doing this, and for the sage advice to ignore all 100000 changes to the yarn cache!!

**Pull request merged**
