### PR TITLE
Refactor figure into ImageWithPlaceholder & Article Figure

### LINKED ISSUE #2263: Horizontal spacing between image and headline incorrect at 240px
**Describe the bug**
Horizontal spacing between image and headline incorrect at 240px

**Expected behaviour**
Ensure the image remains correctly sized
image

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by dr3**
Resolves #2263

**Overall change:** WS refactored our code to use Figure, then articles went and made Figure full of articles specific logic... 🙈 This splits them back apart, WS uses 'ImageWithPlaceholder', Articles use ArticleFigure & ImageWithPlaceholder.

This is needed as the articles logic is breaking frontpage images on 240px breakpoints, Also, its just alot of unneeded css and dom stuffs

**Code changes:**

- Split up figure

**Testing notes:**
This affects all images on articles and frontpages. No changes should be introduced, except for fixing #2263

It splits the Figure stories into `ArticleFigure`, `ArticleFigure - AMP` which are articles only, and `ImageWithPlaceholder`, `ImageWithPlaceholder - AMP` which are used by both pages.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by dr3** [comment]
NB: This is entirely a quick refactor to solve the WS frontpage issue, to get our pages live for v1. We should add unit assertion tests in another issue, but as this is purely a refactor and no real logic is being added, its fine for now

**Comment by 12** [comment]
Can you amend the issue this relates to? I'm intrigued to know what Articles have done that has made the current container unusable for front pages.

**Comment by dr3** [comment]
@rhell https://github.com/bbc/simorgh/issues/2263#issuecomment-507788372

**Review by sareh — APPROVED** [review]
Looks great! 👍 Thanks for the refactor.

**Review by j-pendlebury — APPROVED** [review]

**Review by DenisHdz — APPROVED** [review]

**Comment by david-boydell** [comment]
Looks good, this is ready for merge

**Pull request merged**
