### PR TITLE
No italics in Arabic script fragments

### LINKED ISSUE #1731: No italics for Arabic-script language blocks
**Is your feature request related to a problem? Please describe.**
As a reader of an Arabic-script site (Persian, Arabic, Urdu, Pashto)
I never want to see italics
So that I can read the text

Given I am on an article that uses an Arabic script
And one of the fragment blocks contains the italic attribute
Then I see that fragment as if it did not have an italic attribute

Given I am on an Arabic-script article
Then I see no italic text

Note:
- Exclusion for nested blocks: e.g. `fa` article with  `en-gb` block - italic should work in the `en-gb` block but not for the `fa` blocks. 

**Describe the solution you'd like**

- [ ] Pull in [work in psammead which disabled italics in persian](https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap#L59-L65)
* this means:
  * Updating `psammead-styles` to version `1.1.0` if/where needed ([see work in psammead to de-italicise caption](https://github.com/bbc/psammead/pull/939))
  * [using functions like `getSansItalic` where we currently use `font-style: italic`](https://github.com/bbc/psammead/blob/799c4c667098094e1acd801ee2b51f4edf5433bb/packages/components/psammead-caption/src/index.jsx#L22)
 * Rethinking our approach to `<i>` and `<b>` tags in [`Fragment`](https://github.com/bbc/simorgh/blob/2b72dbef65d90018dcdde9f04e3058a404510422/src/app/containers/Fragment/index.jsx)

**Describe alternatives you've considered**
Fixing these issues by using
```
 [lang=fa] & {
    font-style: normal;
  }
```
but the approach in this ticket removes duplication and will handle this for more languages than just farsi.

**Testing notes**
-  [Farsi article c19v65z3lg5o](http://localhost.bbc.co.uk:7080/persian/articles/c19v65z3lg5o) has italics in the headline in the data (on  `فوتبال` )

Regression is sufficient & manual testing. 

Dev insight: Unit tests should be sufficient.

**Additional context**

### PR DESCRIPTION
**Pull request by twinlensreflex**
Resolves #1731 

**Overall change:**
* Utilises psammead-styles _new_ `getSansItalic` function 

**Code changes:**

- Made `i` tag in Fragment a styled component which uses `getSansItalic`
- Use ServiceContext to provide service
- Update snapshots

**Testing this change**
- use the persian data from this commit 97c858a (reverted because this is just for testing)
- Without the changes in this PR this should mean that `http://localhost.bbc.co.uk:7080/persian/articles/c0000000026o` has an italicised first paragraph ( text reading: `دونالد ترامپ، رئیس جمهور آمریکا در توییتر خود تأیید کرده است که یکی از مقام‌های ارشد کره شمالی برای دیدار با مقامات آمریکایی به نیویورک می‌رود.`). With the changes the first paragraph is no longer italicised.
- You can check a non persian article `http://localhost.bbc.co.uk:7080/news/articles/c0000000029o` and `Pellentesque et orci et arcu sollicitudin sagittis` should still be italicised.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by dr3 — CHANGES_REQUESTED** [review]
image

This change means that serif italic text shows as sans. This is a limitation of the `getSansItalic` style functions which always set `font-family`, `font-weight` & `font-style`. We could expand these functions to be like `getSansItalic(service, { style: true })` to only set style? Can you maybe write an issue to do this please?

For now, adding these styles to the italic tag fix this issue
```
font-family: inherit;
font-weight: inherit;
```

**Comment by twinlensreflex** [comment]
Thanks @dr3. Which pod should the issue be for?

**Review by dr3 — APPROVED** [review]

**Comment by dr3** [comment]
> Thanks @dr3. Which pod should the issue be for?

@el I think articles, as it would be used only in Fragments :)

**Review by 12 — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
lgtm

**Pull request merged**
