### PR TITLE
Create image placeholder

### LINKED ISSUE #449: Placeholder image
**Is your feature request related to a problem? Please describe.**
Users should have a visual indication of when an image needs to load or is simply missing (after failing to load).

**Describe the solution you'd like**
Add a placeholder image to all lazy-loaded images.
This will be displayed before images are loaded client-side or the request fails.

**Testing**
- Automated test for checking the presence of the placeholder
- Manual tests where we throttle an image request and even drop the connection for an image

### PR DESCRIPTION
**Pull request by pjlee11**
Part of #449 

_This PR creates an image placeholder component as the wrapper now acts as a placeholder with the padding bottom defined by the image's ratio meaning it is fully responsive. It also creates a base64 SVG for the BBC blocks in the image placeholder. Add stories and tests for the Image placeholder._

Update: the integration of this component will be handled in another PR.  

- [x] Tests added for new features
- [ ] Test engineer approval

## Test instructions 
To see the placeholder rendering at various ratio's and being fully responsive visit storybook with this branch checked out. This should be tested across different browsers.

### CODE REVIEW

**Review by jamesbhobbs — DISMISSED** [review]
PRs this size are not okay. Needs breaking down a lot.

**Comment by pjlee11** [comment]
@benjaminhobbs this is based off of https://github.com/bbc/simorgh/pull/652 because of obvious conflicts across the two PR's. The actual changes being made here are 4 commits. This therefore needs a rebase following the merge of #652 hence the blocked label

**Comment by pjlee11** [comment]
From UX: 
*Background colour* for placeholder is: $chalk, #ECEAE7.
*BBC blocks colour* for placeholder is: $stone, #D5D0CD.

**Comment by pjlee11** [comment]
The UX colour specs for the BBC Blocks SVG are slightly different to the SVG we re-used from the front-page. The colour in the spec is $stone `#D5D0CD` and the base64'd SVG is `#BCBCBC` (see screenshot)

This is blocked until UX produce a new SVG asset.

image

**Comment by pjlee11** [comment]
Following the merge of #652 this PR needs a rebase. 
`git pull --rebase origin latest` 
Which should reduce the commits from 45 to 9 and files changed from 26 to roughly 12. Following that the base 64'd SVG will need to be updated once UX supply it.

**Comment by pjlee11** [comment]
Rebasing is great ...

screen shot 2018-10-03 at 12 42 20

**Review by bcmn — DISMISSED** [review]

**Review by jtart — DISMISSED** [review]
This PR doing 2 things:
1) Adding an ImagePlaceholder component
2) Integrating the ImagePlaceholder component into Figure and making required API changes

The work is complex in its nature, regardless of it touching many places.

It should therefore be split down, as it introduces too much overhead across the workflow - code reviews; UX, a11y, regression, and integration testing.

**Comment by pjlee11** [comment]
@jtart good point, I'll revise this to be creating the component and then integrate it in a seperate PR

**Review by bcmn — DISMISSED** [review]

**Review by radiocontrolled — DISMISSED** [review]
Great work & testing instructions.
I approve - but you need to force Jenkins to run again as its failed to access Simorgh: https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/bbc-news-simorgh/detail/image-placeholder-div/10/pipeline

**Review by radiocontrolled — APPROVED** [review]

**Review by bcmn — APPROVED** [review]

**Comment by pjlee11** [comment]
@jamesbrumpton has raised the issue that the colour contrast of the image placeholder does not meet our accessibility guidelines. Having spoke with UX about the designs we agreed to merge this as is and address any changes in the future, we did this because: 
a) The image placeholder is not yet integrated. 
b) The placeholder is not information that's meant to be read. It's filling the visual 'gap' of an image that is still loading or hasn't loaded, or is missing.

I've opened a seperate issue to address this issue - https://github.com/BBC-News/simorgh/issues/769

**Comment by pjlee11** [comment]
#769 was deemed unnecessary (see reason on the issue), merging this now.

**Pull request merged**
