### PR TITLE
Fix promo image on IE11

### LINKED ISSUE #8964: Podcast promo image on IE11
**Describe the bug**
The podcast promo image is huge

Image from iOS (7)

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/arabic/podcasts/p02pc9qc
2. Observe huge image

**Expected behaviour**
The image should not be huge as shown in designs or other browsers

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Internet Explorer
- Version: 11

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by mukama**
Resolves https://github.com/bbc/simorgh/issues/8964

**Overall change:**
Updates the `OnDemandAudioPage` component to add grid support for Internet Explorer 11.

**Code changes:**
- Adds `parentColumns` and `parentEnableGelGutters` properties. These are used when adding fall back support for unsupported browsers.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by greenc05** [comment]
A few CSS changes here for IE11, please can we check this with the Jaws screen reader in IE11 for the elements in question and that there are no advers affects?

**Comment by mukama** [comment]
> A few CSS changes here for IE11, please can we check this with the Jaws screen reader in IE11 for the elements in question and that there are no advers affects?

@greenc05 I have tested locally with Jaws Screen Reader on Windows10(both IE11 and Edge) - The changes look and sound good to me :)

**Review by HarryVerhoef — APPROVED** [review]
Nice one!

**Review by FK78 — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
LGTM, can be merged..

**Pull request merged**
