### PR TITLE
Toggles preload for Article canonical

### LINKED ISSUE #9801: Use `data-hero` for AMP images
In order to improve LCP on AMP pages, I've come across an article that suggest the use of `data-hero` tag

https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/optimize_amp/#preload-hero-images

**Describe the solution you'd like**
For `amp-image` tags to use `data-hero` attribute.
data-hero should only be applied to the "[hero image](https://en.wikipedia.org/wiki/Hero_image)" (first image on page). This is to avoid blocking bandwidth for other critical resources. [more here](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-optimizer-guide/explainer/?format=websites#hero-image-optimization)

**Testing notes**
[Tester to complete]

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

### PR DESCRIPTION
**Pull request by DarioR01**
Resolves #9801 

**Overall change:**
After trying to understand why we had this feature toggled off for Article pages, I could not find anything. The feature seems to work and adds `<link>` tags in the head for images we intend to preload (The same behaviour we have in story pages).
The existing [PR](https://github.com/bbc/simorgh/pull/9847) for data-hero should also add a data-hero attribute to amp hero images for Article pages now that this feature is toggled on.

**Code changes:**

- use `useToggle` to toggle preload in article pages
- Moves `componentsToRender` inside `ArticlePage` to make use of useToggle

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**
I tested this with http://localhost:7080/mundo/articles/ce42wzqr2mko
Screenshot 2022-03-07 at 10 34 32

once this PR is merged test https://github.com/bbc/simorgh/pull/9847 again to see if data-hero attribute is applied to Article pages' images.

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by HarveyPeachey — COMMENTED** [review]
Nice and elegant, might be worth adding a test case to check the link element is being added correctly?

**Comment by DarioR01** [comment]
> Nice and elegant, might be worth adding a test case to check the link element is being added correctly?

I believe this is already being tested [here](https://github.com/bbc/simorgh/blob/2cbffcaf2b154301688f8f50a9780eab7a0cafd7/src/app/containers/ImageWithPlaceholder/index.test.jsx#L30).
Unless you mean page specific tests for both Story and Article pages. In which case I will add them shortly :D

**Comment by HarveyPeachey** [comment]
> > Nice and elegant, might be worth adding a test case to check the link element is being added correctly?
> 
> I believe this is already being tested [here](https://github.com/bbc/simorgh/blob/2cbffcaf2b154301688f8f50a9780eab7a0cafd7/src/app/containers/ImageWithPlaceholder/index.test.jsx#L30). Unless you mean page specific tests for both Story and Article pages. In which case I will add them shortly :D

Siiiick, nah that should be enough test coverage in my eyes

**Review by HarveyPeachey — APPROVED** [review]
⛴  it

**Review by amoore108 — APPROVED** [review]

**Pull request merged**
