### PR TITLE
Update fixtures

### PR DESCRIPTION
**Pull request by jimjohnsonrollings**
Part of #4275 

**Overall change:**
- Updates some article fixture data

**Code changes:**

- Updates fixture data for 9 services: Hindi, Marathi, Nepali, Bengali, Sinhala, Tamil, Telugu, Gujarati, Punjabi

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Review by RayNjeri — COMMENTED** [review]
Looks good but this test seems to be failing https://github.com/bbc/simorgh/blob/b608054646e74dc6f507c86a4fff89daf13227a1/dataValidator/helpers/dataLoader/readScenario.js#L35

**Comment by jimjohnsonrollings** [comment]
> this test seems to be failing

Thanks - should be sorted now.

**Review by HarveyPeachey — APPROVED** [review]
LGTM.

Checked all articles locally.

**Review by rhenshaw56 — APPROVED** [review]

**Comment by PriyaKR** [comment]
Looks good to me.

**Pull request merged**
