### PR TITLE
Latest consent banner

### LINKED ISSUE #1903: RTL layout for cookie & privacy banner
**Is your feature request related to a problem? Please describe.**
We should now have translations for the cookie and privacy banners. 

For right-to-left sites the layout is currently still left-to-right as can be seen here:

Screen Shot 2019-06-11 at 07 49 50

The layout _should_ be right-to-left: with the title on the right and the buttons/links on the left. 
Note: this is not just regarding `dir="rtl"` on the `<html>` tag (#611) - it is also regarding the layout of the actual component. 

**Describe the solution you'd like**
The consent banner component, that's used for both Cookie and Privacy banners, should be updated to flip for right-to-left scripts.

It should have a prop which flips from the LTR layout to the RTL layout. Prior to this ticket being picked up, we should discuss naming of such a prop, since it'll form the pattern going forwards for all RTL internationalisation.

This should be implemented and tested for all RTL sites (Persian, Arabic, Urdu, Pashto)

**Describe alternatives you've considered**
This approach of having a page-level RTL plugin being used: https://github.com/bbc/simorgh/issues/2035

**Testing notes**
[Tester to complete]

Dev insight: Unit tests & snapshot tests should be sufficient.

### PR DESCRIPTION
**Pull request by sareh**
Resolves #1903

**Overall change:** Latest consent banner - enabling RTL as well as LTR layouts

Pashto
Screen Shot 2019-08-09 at 08 36 40

Urdu
Screen Shot 2019-08-09 at 08 36 27

Arabic
Screen Shot 2019-08-09 at 08 36 08

News (for regression)
Screen Shot 2019-08-09 at 08 35 55

Pidgin (for regression)
Screen Shot 2019-08-09 at 08 35 32

**Code changes:**

- Passing in `dir` attribute
- Adding unit tests & refactoring existing tests. 

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by sareh** [comment]
The Code Climate warnings about duplication are in the unit tests and refactoring these in my opinion will make the tests less readable.

**Review by j-pendlebury — APPROVED** [review]
LGTM 👍

**Comment by sareh** [comment]
CI is currently failing on a check to prevent multiple versions of a dependency from being loaded. I'm not going to pull in all of the dependency updates in this PR (over a dozen), since there is already a PR that is doing this. Once that is merged, I'll pull in `latest` and that should address the dependency error.

**Review by 12 — COMMENTED** [review]
CI is failing for this: 

```
ERROR in Duplicate Sources / Packages - Duplicates found! ⚠️
```

EDIT: Just noticed Sareh's comment above 🤦‍♂

**Review by RayNjeri — APPROVED** [review]

**Comment by sareh** [comment]
Blocked on this PR: https://github.com/bbc/simorgh/pull/3030

**Comment by sareh** [comment]
Now that this PR: https://github.com/bbc/simorgh/pull/3030 pulled in the latest consent banner, this current PR just adds unit test coverage. Therefore moving into `ready for merge` column to merge after CI passes.

**Pull request merged**
