### PR TITLE
prevent summary rendering in secondary column at medium gel widths

### LINKED ISSUE #6746: Resolve promo summary appearing in promo list in the secondary column
### Is your feature request related to a problem? Please describe.
Promos in the promo list within the secondary column on STY pages currently render captions, which also erroneously display at the medium breakpoint. We do not need to display captions at any breakpoint for the following components:
- Cps Related content 
- Cps Top stories
- Features and Analysis 

### Describe the solution you'd like
- Allow promo list promos to render without a caption.
- Adjust space between headline and timestamp accordingly. This should be the equivalent of 8px.
- Prevent caption data from being passed to promo list promos in the secondary column.

This may require a child Psammead issue.

### Describe alternatives you've considered
Hide the caption via styles at medium breakpoint, however this would mean we'd be rendering text unnecessarily.

### Testing notes
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.
- [x] This feature is expected to need a11y testing to check Summaries are no longer read out at any breakpoint.

### Additional context
n/a

### PR DESCRIPTION
**Pull request by rhenshaw56**
Resolves #6746 

**Overall change:**
_prevent summary rendering in secondary column at medium gel widths._

**Code changes:**

- set `displaySummary` to false for story page secondary column sections._

**To test**
- run this asset http://localhost:7080/mundo/23263889 locally
- reduce the screen width to GEL group 3 breakpoint (`600px - 1007px`)
- note that the summary isn't shown as compared to an story page on test
---

- [X] I have assigned myself to this PR and the corresponding issues
- [X] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [X] I have assigned this PR to the Simorgh project

**Testing:**

- [X] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [X] This PR requires manual testing

### CODE REVIEW

**Review by simonsinclair — APPROVED** [review]
This is brilliant, Rowland.
Let's make sure UX are happy before merging.

**Review by Simon2828 — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Used this link and checked various breakpoints. Summary is not displayed.

http://localhost:7080/mundo/23263889 

LGTM..

**Comment by paruchurisilpa** [comment]
Will have to do a11y testing to make sure summary is not read on any breakpoints - LGTM

**Comment by paruchurisilpa** [comment]
UX Review needs to happen before merging.

**Comment by jimjohnsonrollings** [comment]
I've reviewed this and am happy to pass it on behalf of UX if nobody is available

**Pull request merged**
