### PR TITLE
Dependency Updates

### PR DESCRIPTION
**Pull request by karinathomasbbc**
**Overall changes:**

***Miscellaneous***
-  Bump moment-timezone from 0.5.31 to 0.5.32 #8373 
-  Bump eslint from 7.13.0 to 7.14.0 #8424 

***Babel & Webpack***
-  Bump webpack-merge from 5.3.0 to 5.4.0 #8374 
-  Bump babel-loader from 8.1.0 to 8.2.1 #8378 
-  Bump webpack-bundle-analyzer from 3.9.0 to 4.1.0 #8326 
- Bump copy-webpack-plugin from 6.3.0 to 6.3.1 #8369 
- Bump compression-webpack-plugin from 6.1.0 to 6.1.1 #8400 
-  Bump @babel/preset-env from 7.12.1 to 7.12.7 #8426 
-  Bump @babel/core from 7.12.3 to 7.12.7 #8429 
-  Bump @babel/preset-react from 7.12.5 to 7.12.7 #8430 

***Testing Libraries***
- Bump cypress from 5.5.0 to 5.6.0 #8371
- Bump jest-junit from 11.1.0 to 12.0.0 #8068 
-  Bump jest-silent-reporter from 0.2.1 to 0.3.0 #8290 
- Bump supertest from 4.0.2 to 6.0.1 #8399 
-  Bump @testing-library/jest-dom from 5.11.5 to 5.11.6 #8376 
-  Bump @testing-library/react from 11.1.1 to 11.2.1 #8412 
-  Bump @testing-library/react from 11.2.1 to 11.2.2 #8425 
-  Bump @testing-library/dom from 7.26.5 to 7.26.6 #8381 
-  Bump @testing-library/dom from 7.28.0 to 7.28.1 #8422 
-  Bump fetch-mock from 9.10.7 to 9.11.0 #8428 

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by RichardPK — COMMENTED** [review]
Those Storybook bumps will break it in Simorgh!

It'll need the v6 migration treatment 😬 : https://github.com/bbc/psammead/pull/3728

**Comment by karinathomasbbc** [comment]
> Those Storybook bumps will break it in Simorgh!
> 
> It'll need the v6 migration treatment 😬 : [bbc/psammead#3728](https://github.com/bbc/psammead/pull/3728)

😬 good spot, I didn't even think. Let me remove the storybook PRs from here, and we'll deal with them separately

**Comment by RichardPK** [comment]
> 😬 good spot, I didn't even think. Let me remove the storybook PRs from here, and we'll deal with them separately

Is there a chance the other major ver bumps could also have breaking changes? `webpack-bundle-analyzer` `jest-junit` & `supertest `

**Comment by karinathomasbbc** [comment]
> > 😬 good spot, I didn't even think. Let me remove the storybook PRs from here, and we'll deal with them separately
> 
> Is there a chance the other major ver bumps could also have breaking changes? `webpack-bundle-analyzer` `jest-junit` & `supertest `

My thoughts are:
Passing bundle tests + integration tests prove that `webpack-bundle-analyzer` is 👍 
Passing unit + integration tests prove that `jest-junit` & `supertest` is 👍

**Comment by RichardPK** [comment]
> My thoughts are:
> Passing bundle tests + integration tests prove that `webpack-bundle-analyzer` is 👍
> Passing unit + integration tests prove that `jest-junit` & `supertest` is 👍

Yea that sounds like a very reasonable hypothesis!

**Review by jroebu14 — APPROVED** [review]

**Review by andrewscfc — APPROVED** [review]

**Pull request merged**
