### PR TITLE
Use @bbc/psammead-figure component

### LINKED ISSUE #1091: Pull Figure from Psammead
**Is your feature request related to a problem? Please describe.**
Blocked on https://github.com/BBC-News/psammead/issues/214

**Describe the solution you'd like**
A PR which pulls in Psammead's Figure component and deletes the corresponding code from Simorgh.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Regression test.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by sareh**
Resolves #1091 

Use @bbc/psammead-figure component

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Comment by sareh** [comment]
The `license/snyk` check passes, but the `security/snyk` test fails. I don't have permissions to view what the error is.

**Review by radiocontrolled — DISMISSED** [review]
🎆

**Review by bcmn — DISMISSED** [review]

**Review by radiocontrolled — DISMISSED** [review]
re-reviewing as this has gone stale

**Comment by bcmn** [comment]
The snapshots for this are failing locally for me, & I think that's the issue with Travis too. One of the 6 failing tests is related to #903 -- but everything else is just the order of the styled-components CSS groups.

**Review by bcmn — APPROVED** [review]

**Review by ChrisBAshton — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
LGTM 👍

**Pull request merged**
