### PR TITLE
Add icons for /scotland

### LINKED ISSUE #3845: Add icons for /scotland service
**Is your feature request related to a problem? Please describe.**
We are preparing the /scotland article.  We don't yet have icons.

**Describe the solution you'd like**
Add the icons to Simorgh.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by jimjohnsonrollings**
Resolves #3845 

**Overall change:** Adds icons for the /scotland service

**Code changes:**

- Add icons

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by simonsinclair — COMMENTED** [review]
All icons are suffering from a white border caused by resizing (see below), which will limit their use on backgrounds other than white. If this needs to be addressed, pixel fitting and rounding can be used in Sketch prior to export.

Screenshot 2019-09-19 at 11 41 35

**Comment by sareh** [comment]
The images are all a pixel too large. e.g. 513x513px, ... 73x73px

**Review by simonsinclair — CHANGES_REQUESTED** [review]
The border issue has been resolved, but each icon is still too large by 1 pixel.

**Review by simonsinclair — APPROVED** [review]
The dimensions and border look good!

I'm not sure if it's worth mentioning, but I ran these through PNGOUT and got an average reduction in file size by 64%. Let me know if you'd like me to send them across.

**Review by sareh — APPROVED** [review]
The sizes of the images are correct now. 🎉 I agree with @simonsinclair that it'd be good to optimise these asset file sizes.

**Comment by jimjohnsonrollings** [comment]
Argh I thought I'd pushed the happy lightweight versions that Simon sent me :(

**Comment by jimjohnsonrollings** [comment]
This is confusing, because it shows my commits before the review, even though they weren't here when the review took place.

**Review by simonsinclair — APPROVED** [review]
I checked this branch out. The border, dimensions and filesize of the optimised versions look good to me.

**Review by HarveyPeachey — APPROVED** [review]
LGTM

**Pull request merged**
