### PR TITLE
Changed the format of timestamps for story promos

### LINKED ISSUE #2913: Change date format of timestamp in /StoryPromo/index.jsx
**Is your feature request related to a problem? Please describe.**
Currently, timeFormats.js uses hardcoded formats which only cover mainly latin based languages rendering dates in asian languages for example read incorrectly. 
Eg. 7 七月 2018 in zhongwen from storybook usually reads as 2018年7月7日. 

**Describe the solution you'd like**
Use locale format for multiple locale support (Eg. LLLL found here: https://momentjs.com) instead of hard-coding one single format.

**Additional context**
Files affected:
https://github.com/bbc/simorgh/blob/latest/src/app/containers/StoryPromo/index.jsx#L99

### PR DESCRIPTION
**Pull request by OlgaLyubin**
Resolves #2913 

**Overall change:** Timestamps for story promos do not use a hardcoded format anymore. They now work not only for latin based languages but also for languages that use a different format for timestamps (e.g. Korean 2019년 7월 14일).

**Code changes:**
-  A simple change of the timestamp format from "D MMMM YYYY" to "LL"

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by andrew-nowak — APPROVED** [review]
lgtm

**Review by DenisHdz — APPROVED** [review]
LGTM

**Review by dr3 — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Timestamps should be entered in milliseconds to test this ticket..For eg; `1565146799000`..This worked , Looks good to me..

**Comment by paruchurisilpa** [comment]
LGTM..

**Pull request merged**
