### PR TITLE
Add sizes attribute to image component in Story, Photo Gallery, Article and Media Asset pages

### LINKED ISSUE #8954: Issue with lazy loading of images on Russian article pages in Portrait mode on Iphone
1. Go to https://www.bbc.com/russian/news-56320777 on an iPhone.
2. There is an issue with lazy loading of images for russian article pages.
3. Some images load only partially and the only way to fix them is to turn the phone to landscape, which reloads the images, and then back to portrait. 
4. This is not hapenning on all article pages though.
IMG_2E3FC0DABAE4-1

4. Attached is the screenshot.

### PR DESCRIPTION
**Pull request by jroebu14**
Might resolve https://github.com/bbc/simorgh/issues/8954

**Overall change:**
Adds a sizes attribute to images. This provides the browser with the information to help pick the most appropriate image from the srcset list.

**Code changes:**

- Adds a new prop `sizes` to the Image component
- Wherever the Image component is used we now provide the correct `sizes`. This is used in Story, Photo Gallery, Article and Media Asset pages.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

# Testing

1. Images on Story, Photo Gallery, Article and Media Asset pages should still render.

2. Image elements have the correct sizes attribute for the page type
    ## Articles page
    Image elements (``) should have a new attribute `sizes="(min-width: 1008px) 760px, 100vw"`
    
    ## Story page
    Image elements (``) should have a new attribute `sizes="(min-width: 1008px) 645px, 100vw"`
    
    ## Media Asset page
    Image elements (``) should have a new attribute `sizes="(min-width: 1008px) 760px, 100vw"`
    
    ## Photo Gallery page
    Image elements (``) should have a new attribute `sizes="(min-width: 1008px) 760px, 100vw"` unless:
    - it is a square image then it should be `sizes="(min-width: 600px) 80vw, (min-width: 1008px) 632px, 95vw"`
    - it is a tall image then it should be `sizes="(min-width: 400px) 60vw, (min-width: 600px) 80vw, (min-width: 1008px) 502px, 95vw"`

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by amoore108** [comment]
@jroebu14 Looks good to me. Just curious how you came up with the various `sizes` values, e.g. `"(min-width: 1008px) 760px, 100vw"`. Do these relate to the GEL breakpoints or are they more just trial and error to make them scale correctly?

**Comment by jroebu14** [comment]
@amoore108 thanks for reviewing. They do relate to GEL breakpoints. To get the sizes I observed the image width at each breakpoint for each page type.

**Review by amoore108 — APPROVED** [review]

**Review by mukama — APPROVED** [review]
Nice one! I hadn't thought of that 👍

**Comment by paruchurisilpa** [comment]
Checked STY, Articles, PGL locally:

* http://localhost:7080/russian/articles/ck7pz7re3zgo
* http://localhost:7080/russian/features-45782775
* http://localhost:7080/russian/23219699

**Comment by paruchurisilpa** [comment]
Checked STY, Articles, PGL locally:

* http://localhost:7080/russian/articles/ck7pz7re3zgo
* http://localhost:7080/russian/features-45782775
* http://localhost:7080/russian/23219699

**Pull request merged**
