### PR TITLE
Register service worker

### PR DESCRIPTION
**Pull request by sareh**
Register Service worker

* [x] Fixes https://github.com/bbc/simorgh/issues/72
* [ ] Tests added for new features

* [ ] Test engineer approval

### CODE REVIEW

**Comment by chris-hinds** [comment]
So, @sareh @mattgreenham and I implemented the service worker on Friday and started adding an integration test to help test whether the service worker has been registered or not.

However we have hit a problem that we were unable to solve at the time and would like some input from others.

When running the test it loads the service-worker.js file from `/build/public/service-worker.js` and immediately fails when it hits the `importScripts` logic. The code in this service-worker is auto generated from workbox. And `importScrips` is part of the web workers specification, so should be available.

Running theory so far is that this could be an issue with how cypress works? Any feedback is welcome.

The test is not complete as we are not able to get past this issue.

**Comment by jamesbhobbs** [comment]
@hindsc52 @sareh @mattgreenham Hi all, I started looking at your question this evening and found some helpful info for the e2e testing. I started (locally only) creating a PR against your PR to teach how to do it, and with minor critical corrections to this branch. During this I learnt a lot and discovered fundamental objections to the approach. e.g. which class was used in the the webpack config (didn't allow push). I also felt the amount of code added was unnecessary. During investigation (because I haven't done this before so couldn't teach with doing it) I created this alternative PR: https://github.com/bbc/simorgh/pull/394 It is I think a better approach, and if you agree I'm happy to finish it. 

Apologies for hijacking the work, but also I'm sure I couldn't have done it so fast without the example in this PR, so it was far from wasted.

**Comment by chris-hinds** [comment]
@benjaminhobbs what you have done, seems fairly promising. It takes what we had here and expands upon it a little with the extra config. I'd argue that the only reduction in code here is that with your implementation we do not have to write the logic to actually register the service worker, that seems to be handled for us.

As long as the e2e's can be written to test the service worker registration and caching strategies then this is a win win situation.

There are 52 open issues on the offline-plugin you have used, I had a quick look through them and cannot see anything that would directly affect what we are doing.

Although the documentation with workbox seemed to offer much more info, the docs here are not too bad.

**Comment by jamesbhobbs** [comment]
@hindsc52 ok I will look at the e2e test sometime in the next 14 days, hopefully tomorrow.

**Comment by jamesbhobbs** [comment]
Closing in favour of https://github.com/bbc/simorgh/pull/394 (after agreeing with authors) NB the replacement branch needs updating.

**Pull request closed without merging**
