### PR TITLE
remove /news links and updated burmese translation

### LINKED ISSUE #5800: Remove /news from BBC Bengali and BBC Nepali Nav
**Is your feature request related to a problem? Please describe.**
GIVEN a user visits the BBC Bengali or BBC Nepali websites
WHEN they see the navigation bar
THEN there is NO link to <service>/news on either site

**Describe the solution you'd like**
Update the navigation bar on BBC Bengali and Nepali so the nodes for /news are no longer featured in either of them. The link is currently in second position in the navigation.

https://www.bbc.com/bengali
title: 'খবর',
url: '/bengali/news',

https://www.bbc.com/nepali
title: 'समाचार',
url: '/nepali/news',

**Describe alternatives you've considered**
None

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

### LINKED ISSUE #5832: Update 'Listen' for Burmese
**Is your feature request related to a problem? Please describe.**
Update 'Listen' for Burmese

**Describe the solution you'd like**
Update listen with နားဆငျရနျ

**Describe alternatives you've considered**
Update simorgh config for Burmese

Translations should be seen when visiting the burmese front page:

http://localhost:7080/burmese?renderer_env=live

**Testing notes**
Translations should be seen when visiting the burmese front page:
http://localhost:7080/burmese?renderer_env=live

Dev insight: Snapshot tests should be sufficient.

- [x] This feature is expected to need manual testing.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by thekp**
Resolves #5800
Resolves https://github.com/bbc/simorgh/issues/5832

**Overall change:** 
_Remove `/news` links for Bengali and Nepali._
- _update `LISTEN` translation for burmese_

**Code changes:**
- _Update config files for bengali and nepali._
- _update translations for burmese_

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by FK78 — APPROVED** [review]
LGTM.

**Review by DenisHdz — APPROVED** [review]
68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4d6179555a6538356a64456b354f564830592f67697068792e676966

**Review by FK78 — APPROVED** [review]
New translations LGTM.

**Comment by PriyaKR** [comment]
LGTM.
Screen Shot 2020-03-11 at 11 46 53

**Pull request merged**
