### PR TITLE
Add Uzbek translations

### LINKED ISSUE #5117: Add Uzbek translations
**Describe the bug**
We're missing translations for Listen/Watch for the Uzbek site. 

**To Reproduce**
Currently the Radio/TV component doesn't have the right translations

**Expected behavior**
Translations for Listen/Watch

**Screenshots**
Currently on https://www.bbc.com/uzbek the translations are not visible
Screenshot 2020-01-13 at 11 07 32

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### LINKED ISSUE #5121: Add radio/tv bulletins to local fixtures for relevant services
**Is your feature request related to a problem? Please describe.**
Currently, on localhost, we do not have radio bulletin or tv bulletin examples. We should do, to enable easier testing and surfacing of issues on our local environment prior to work being deployed to Test/Live. 

**Describe the solution you'd like**
Take examples from the Test environment and add them to the localhost JSON files. 
`https://www.test.bbc.com/uzbek.json`

**Describe alternatives you've considered**
If we don't make this change, changes would need to be checked via building the test env first, following these instructions https://github.com/bbc/simorgh#using-environment-builds-locally

**Testing notes**
[Tester to complete]

Dev insight: Just checking locally should be sufficient. Snapshots for front pages will update. 

- [ ] This feature is expected to need manual testing.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by sareh**
Resolves #5121

**Overall change:** 
Updates translations

**Code changes:**
- Updates translations on Uzbek home page

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by sareh** [comment]
Screenshots obtained by running the Test env build: https://github.com/bbc/simorgh#using-environment-builds-locally so that we have Test env data that includes the Radio bulletin. 
http://localhost:7080/uzbek
Screenshot of promo with Listen translation

**Review by j-pendlebury — APPROVED** [review]
LGTM 👍 would be nice to have radio bulletin in our local fixture files, but as discussed with @sareh, there will be a separate issue created for that.

**Comment by sareh** [comment]
@jblaut Issue is here: https://github.com/bbc/simorgh/issues/5121

**Review by OlgaLyubin — APPROVED** [review]
Looks good, everything matches the translations spreadsheet

**Pull request merged**
