### PR TITLE
Use updated Pashto locale to introduce relative time support

### LINKED ISSUE #3147: Timestamps for Pashto locale
**Is your feature request related to a problem? Please describe.**
We need to ensure timestamps support Pashto, this includes correct translations and numerals.

When viewing an article in Pashto, the timestamp should:
- Use [Eastern Arabic numerals](https://en.wikipedia.org/wiki/Eastern_Arabic_numerals)
- Display both relative and absolute timestamps in Pashto
- Display updated timestamps correctly in Pashto
- Include both Gregorian and Jalaali calendar dates (already enabled in https://github.com/bbc/simorgh/pull/3552)
- Be rendered right-to-left
- Have onscreen and offscreen translations in Pashto

**Other links**
Storybook for examples of relative timestamps, e.g. https://bbc.github.io/simorgh/?path=/story/containers-article-article-timestamp--lastpublished-firstpublished-and-firstpublished-10-hours-ago

Pashto article fixture data: https://github.com/bbc/simorgh/tree/latest/data/pashto/articles

**Describe the solution you'd like**
Update the [`ps` locale in psammead-locales](https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-locales/moment/ps.js) to support the above requirements.

**Note** the locale does not need to include all Moment locale features, only enough to support our timestamp formats. 

**Describe alternatives you've considered**
None.

**Testing notes**
- Requires unit test coverage for Pashto locale

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

### PR DESCRIPTION
**Pull request by simonsinclair**
Resolves https://github.com/bbc/simorgh/issues/3147

**Overall change:** Use the latest `@bbc/psammead-locales` dependency, which contains an updated Pashto locale that supports relative timestamps. 

**Code changes:**

- Update `@bbc/psammead-locales` entry in `package.json` to the latest version.
- Add Pashto locale to Moment Locales story. http://localhost.bbc.com:9001/?path=/story/moment-locales-editorial-view--pashto-ps

**Manual testing performed:**

1. Use https://currentmillis.com/ to generate timestamps for:
    - A few seconds since epoch.
    - One minute since epoch.
    - Several minutes since epoch.
    - One hour since epoch.
    - Several hours since epoch.
    - Greater than 10 hours since epoch.
    - Greater than a day since epoch.
2. Change `firstPublished` and `lastPublished` values in `/data/pashto/articles/cng0e8v85eko.json` to verify the generated timestamps are displayed correctly in the application: http://localhost.bbc.com:7080/pashto/articles/cng0e8v85eko.
3. Verify the Pashto locale is displaying correctly in Storybook: http://localhost.bbc.com:9001/?path=/story/moment-locales-editorial-view--pashto-ps.

**Manual testing results:**

**A few seconds since epoch**
Although the Pashto locale supports this, `psammead-timestamp-container` doesn't. See: https://github.com/bbc/psammead/blob/latest/packages/containers/psammead-timestamp-container/src/timestampUtilities.js#L13-L20. Until that changes, the output is "A minute ago".
seconds-ago

**One minute since epoch** ✓
a-minute-ago

**Several minutes since epoch** ✓
several-minutes-ago

**One hour since epoch** ✓
an-hour-ago

**Several hours since epoch** ✓
several-hours-ago

**Greater than 10 hours since epoch (Absolute)**
Is this normal behaviour? Needs review.
over-10-hours-ago

**Greater than a day since epoch (Absolute)** ✓
one-day-one-hour-ago

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by jamesdonoh — APPROVED** [review]
Code change looks correct - just think this needs an editorial review and then it's good to go. Thanks for detailed context and screenshots 👍

**Review by dr3 — APPROVED** [review]

**Review by sareh — APPROVED** [review]
Thanks for all of the detail on the PR description regarding the cases you tested. Looks great. :+1:

**Comment by jamesdonoh** [comment]
Note that the absence of the Jalaali calendar on the second-from-bottom timestamp (>10h <1d) is a known issue and will be resolved by https://github.com/bbc/psammead/issues/1991

**Comment by simonsinclair** [comment]
Following an editorial review, we need to correct translations in `psammead-locales`. To ensure this  PR doesn't get merged, we will create a new one when this work is done.

**Pull request closed without merging**
