### PR TITLE
DO NOT MERGE: A11y swarm inline link alpha

### PR DESCRIPTION
**Pull request by pjlee11**
THIS SHOULD NOT BE MERGED. 

This is a draft PR used for a11y testing the new inline link styling on the article. 

http://localhost:7080/news/articles/ctestreith0o
http://localhost:7080/persian/articles/ctestreith0o - caveat: this isn't embedding the Nassim font so some bugs might be caused due to Arial or Helvetica being rendered as the fallback. 

---

Test notes: 
Checkout this branch and run `npm ci` the follow the test instructions on https://github.com/bbc/psammead/pull/1023, in particular cross browser and device testing. 

- [ ] Test engineer approval

### CODE REVIEW

**Comment by pjlee11** [comment]
This PR needs a dev a11y swarm, it’s purely a visual change so no need to screen reader test as it doesn’t affect the semantics. https://bbc-news.github.io/accessibility-news-and-you/accessibility-swarms#if-its-a-small-change 

It also needs some QA testing in terms of cross browser and device testing

**Comment by jamesbrumpton** [comment]
image
image
This was seen on IE11. The styling causes issues when hovering.
This was found using the URL provided in the description of this PR.

**Comment by pjlee11** [comment]
Raised https://github.com/bbc/psammead/issues/1404 as part of the testing for this.

**Comment by pjlee11** [comment]
## Dev a11y swarm screenshots

**Chrome, font-size setting set to 'Very Large'**

image

image

image

**FireFox, page zoomed to 200%**

image

image

image

image

**Comment by pjlee11** [comment]
Colour contrast:  🆗 
Without JS:  🆗 
Axe: 🆗 
Keyboard Navigation: N/A 
Heading order: N/A
Icons: N/A

FireFox colour preferences / high contrast

FireFox Colour preferences


**Colour blindness with ChromeLens**

Red blind
image

Green weak
image

RGB blind
image

Blue blind
image

**Comment by pjlee11** [comment]
On chrome or Opera, at 110% zoom, the caption styling when hovered slightly encroaches on the following line (see screenshot)

Chrome at 110% zoom ❓ 
image

This only happens at this exact zoom value and only on Chrome and Opera. Confirmed with @greenc05, that because this is caused by a very specific case we are happy to accept this behaviour. 

FireFox at 110% zoom 🆗 
image

**Comment by pjlee11** [comment]
Closing this as the dev swarm and cross browser testing was all okay. However, there has been a request from UX to have this fully accessibility reviewed by an external team so putting this on hold. 

https://github.com/bbc/psammead/issues/1411

**Comment by greenc05** [comment]
If this is re-opened @pjlee11 this needs some assistive technology swarming too, even though the HTML hasn't changed the CSS has (and this can affect screen reader output) and we should double check there aren't any adverse affects

**Pull request closed without merging**
