### PR TITLE
WSTEAM1-444 - Use pre-constructed value for ATI Article page identifier

### PR DESCRIPTION
**Pull request by HarveyPeachey**
Resolves JIRA [WSTEAM1-444](https://jira.dev.bbc.co.uk/browse/WSTEAM1-444)

Overall changes
======
Updates ATI page identifier for Articles to use `metadata.analyticsLabels.page` field

Code changes
======

- Updates article util `getPageIdentifier` to grab value from metadata
- Updates unit tests

Testing
======
1. Ensure that the ATI analytics p field is being set to the correct values as before and that the articles word in the string is translated when appropriate, e.g. to erthyglau for the Welsh language service

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

### CODE REVIEW

**Review by amoore108 — APPROVED** [review]
Noice

**Comment by karinathomasbbc** [comment]
👋 we are currently working on migrating the ATI analytics container from the legacy location, and we're also simplifying the API, so that you don't need to pass in the entire page data object, just a couple of very specific fields on an `ATIData` object and it will do the rest.

See https://github.com/bbc/simorgh/pull/10798 and https://github.com/bbc/simorgh/pull/10819

Is there any chance you could hold off on the ATI work until we have completed these PRs? (We're aiming for the next 2-3 weeks)

**Comment by HarveyPeachey** [comment]
> Is there any chance you could hold off on the ATI work until we have completed these PRs? (We're aiming for the next 2-3 weeks)

I'm sure that'll be fine, I'll mention it to the team in standup tomorrow and see what they say

**Comment by pvaliani** [comment]
10798 has now been merged (component has been migrated). However, 10819 is still to be picked up from the spike stage and involves the API simplification as @karinathomasbbc described above.

**Comment by alex-magana** [comment]
Hello.
https://github.com/bbc/simorgh/pull/10951 has been merged and it'll be
deployed on LIVE following resolution of failing e2es.
You may close this PR as the changes here are no longer required.

**Pull request closed without merging**
