### PR TITLE
Intergrate image placeholder

### LINKED ISSUE #449: Placeholder image
**Is your feature request related to a problem? Please describe.**
Users should have a visual indication of when an image needs to load or is simply missing (after failing to load).

**Describe the solution you'd like**
Add a placeholder image to all lazy-loaded images.
This will be displayed before images are loaded client-side or the request fails.

**Testing**
- Automated test for checking the presence of the placeholder
- Manual tests where we throttle an image request and even drop the connection for an image

### PR DESCRIPTION
**Pull request by pjlee11**
Resolves #449 

_This PR integrates the the placeholder image created in https://github.com/BBC-News/simorgh/pull/668_

- [x] Tests added for new features
- [ ] Test engineer approval

## Test instructions 
To see the placeholder use browser tools to throttle connection. This need to be tested cross browser and with images of various ratios. 

**Example URL's**
16x9 landscape image on http://localhost:7080/news/articles/c0000000025o
Square-ish image on http://localhost:7080/news/articles/c0000000004o
Smaller than 16x9 landscape image on http://localhost:7080/news/articles/c0000000012o
Larger then 9x16 portrait image on http://localhost:7080/news/articles/c0000000002o

## Screenshot 
image

### CODE REVIEW

**Comment by pjlee11** [comment]
Blocked until https://github.com/BBC-News/simorgh/pull/668 is merged as the component can't be integrate before it is merged.

**Comment by pjlee11** [comment]
#668 is merged, this is therefore unblocked

**Review by jamesbhobbs — DISMISSED** [review]

**Review by bcmn — DISMISSED** [review]
Looks good to me, aside from the CC recommendation, which could maybe be re-homed to `bodyTestHelper.js`?

**Review by radiocontrolled — DISMISSED** [review]
LGTM 👍

**Review by bcmn — DISMISSED** [review]

**Review by jtart — APPROVED** [review]

**Review by bcmn — APPROVED** [review]

**Pull request merged**
