### PR TITLE
No CSS timestamp fix

### LINKED ISSUE #5518: a11y P3 - No line break or space between published and updated time with No CSS enabled
**Describe the bug**
No line break or space between published and updated time - you should be able to tell when the published time ends and the updated time starts.

~~Possibly related https://github.com/bbc/simorgh/issues/5515.~~

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to any page that has timestamp and updated timestamp. https://www.test.bbc.com/pidgin/media-43768328?renderer_env=live
2. Disable CSS.

**Expected behaviour**
There should be a character space between the two timestamps.

**Screenshots**
Screenshot 2020-02-12 at 11 20 31

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by HarveyPeachey**
Resolves #5518

**Overall change:** 
Adds a `<div>` around `lastPublished` timestamps. This allows a `lastPublished` timestamp to be displayed underneath the `firstPublished` timestamp when a user has disabled CSS.

**Code changes:**
- Added `<div>` around lastPublished in ArticleTimestamp container.
- Amended unit test for ArticleTimestamp container.

**Before**
Screenshot 2020-02-12 at 11 20 31

**After**
Screenshot 2020-02-18 at 09 32 03

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by greenc05** [comment]
@HarveyPeachey does a br tag get read out with a screen reader? We shouldn't be adding a br element to fix this unless that's the only option?? Would some white space in the file not fix this?

**Comment by greenc05** [comment]
As we can't add white space to the file @HarveyPeachey please wrap each time element (or one of them) in a div. div's are block level elements and this will ensure each time element is on a new line when there is no CSS and we won't be adding any additional semantics (div's have no semantic meaning and we can be sure that they won't be acknowledged by screen reader).

**Comment by greenc05** [comment]
Thank you, looks good @HarveyPeachey

**Review by andrewscfc — COMMENTED** [review]
Have you confirmed the times now have a line break between them as opposed to the original screen grab from the issue?
image

**Comment by HarveyPeachey** [comment]
> Have you confirmed the times now have a line break between them as opposed to the original screen grab from the issue?

Added it to the PR https://github.com/bbc/simorgh/pull/5554#issue-375471491

**Review by andrewscfc — APPROVED** [review]

**Review by DenisHdz — APPROVED** [review]
LGTM

**Pull request merged**
