### PR TITLE
Fix live E2E tests using getBlockByType func

### PR DESCRIPTION
**Pull request by pjlee11**
~Resolves #NUMBER~

Live E2Es were failing because the payload had array items in a different order than the tests expected

**Overall change:** _Fixes the live E2E tests because they were dependant on the order of the blocks in the payload. Does this by adding a `getBlockByType` helper function and uses it for the failing copyright test. There is a follow up piece of work to change all tests that access an array using a number (EG: `array[0]`)._

**Code changes:**

- Adds a helper function and uses it to fix the failing E2E tests.

---

To test this ensure that `newBodySpec` tests pass when running `CYPRESS_APP_ENV=live npm run cypress:interactive`. The complete test suite is likely to fail due to running against live on the local env. 

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval
- [x] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Comment by pjlee11** [comment]
Running `CYPRESS_APP_ENV=live npm run cypress:interactive`

## On the feature branch

image

## On latest

image

**Review by dr3 — APPROVED** [review]

**Review by chris-hinds — APPROVED** [review]

**Review by 12 — APPROVED** [review]
Nice rapid fix, thanks Phil.

**Review by sareh — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
LGTM.

**Comment by jamesdonoh** [comment]
Late to the party but 👍 👍

**Pull request merged**
