### PR TITLE
CARL: Updating dependencies

### PR DESCRIPTION
**Pull request by DemonusPC**
Carl, has found some dependencies to update for this project. Please remember that Carl will update to the latest stable version.

### CODE REVIEW

**Comment by j-pendlebury** [comment]
image

**Comment by andrew-nowak** [comment]
react-amphtml@4 is now over 200kB (ungzipped). It's so large it causes bundlephobia to crash :( https://bundlephobia.com/result?p=react-amphtml

**Comment by DemonusPC** [comment]
Yea just so everyone are aware. This is a test Pr done by the Carl bot.

**Comment by dr3** [comment]
This PR is pretty untestable, as it basically touches everything. Can it be split down into related changes?

**Comment by jamesbhobbs** [comment]
>react-amphtml@4 is now over 200kB (ungzipped). It's so large it causes bundlephobia to crash :( https://bundlephobia.com/result?p=react-amphtml

this package should never be updated, this has been set in dependabot, we need the same functionality in any replacement.

PS I will not approve this PR until we have approved CARL, there needs to be an issue for that. And the PR needs to be less huge.

PPS pulling all these updates in before updating psammead is redundant, we need to work from the bottom of the dependency chain up.

**Pull request closed without merging**
