### PR TITLE
Fixed an issue where files ended in .mdx instead of stories.mdx, this…

### PR DESCRIPTION
**Pull request by Auxy6858**
… would cause the README as well as other files to direct to non-existent files.

### CODE REVIEW

**Comment by Auxy6858** [comment]
Is anyone actually going to check this?

**Comment by Auxy6858** [comment]
This issue still exists

**Comment by eagerterrier** [comment]
Hi @Auxy6858 

We did the renaming _from_ `.stories.mdx` to `.mdx` as part of upgrading to Storybook 8, so we're keen not to go back if possible. Can you describe briefly what problem you're trying to solve here? I'm looking at some of the files and I can spot some 404s, but they seem unrelated and I'll get those updated.

I've had a nosy in the codebase and can see there are 2 `stories.mdx` links in one of our legacy dirs - https://github.com/bbc/simorgh/blob/1f30901edda9a76d8c7dd1a0f95e46f2aedb66fe/src/app/legacy/psammead/README.md?plain=1#L12-L13 - so I can get those fixed while I'm looking around anyway...

**Comment by Auxy6858** [comment]
Yes some of the links still lead to stories.mdx files, the documentation still also tells you to name files ending in stories.mdx. I'll have another look at it later.

**Comment by karinathomasbbc** [comment]
👋 we're going to close this PR, as we have another PR which updates the links to the mdx files, as well as the documentation. #11987

**Pull request closed without merging**
