### PR TITLE
renderDocument() destruct props

### PR DESCRIPTION
**Pull request by pjlee11**
Resolves N/A (JFDI)

**Overall change:** Ensures the renderDocument() props are destructible this ensure the next prop passed to the function doesn't change the order the props are received and therefore break. EG: if a prop had been added above `isAmp` then all platforms would have added the AMP framework due to the order change

**Code changes:**

- _Passing props as an object, destructively assigns the props on the other end and alphabetises the props_

---

No manual testing is required, automated tests cover all regression

- [x] I have assigned myself to this PR and the corresponding issues
- ~[ ] Tests added for new features~
- ~[ ] Test engineer approval~ 
- [x] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by dr3 — APPROVED** [review]
The fact you didn't have to update any tests for this makes me cry a little

**Comment by pjlee11** [comment]
@dr3 completely agree 😭

**Comment by sareh** [comment]
Regarding tests - there should be a test file added `server/Document/index.test.jsx` to check inputs/outputs of the renderDocument function that it exports. 
We should ensure that changes to this critical file can't be made without having tests to have code coverage.

**Comment by pjlee11** [comment]
@sareh agreed, I've created https://github.com/bbc/simorgh/issues/2259 because this PR was meant to be a quick edit

**Comment by sareh** [comment]
Thanks for opening that issue.

**Comment by pjlee11** [comment]
Travis and CodeClimate seem to be hanging on this PR :/

**Review by 12 — APPROVED** [review]

**Comment by jamesbhobbs** [comment]
No testing needed

**Pull request merged**
