### PR TITLE
Footer links columns

### LINKED ISSUE #545: Footer List - columns at larger breakpoints
**Is your feature request related to a problem? Please describe.**
Currently the Footer doesn't have the correct number of columns at larger breakpoints:

Group 3: 600px- 1007px 

screen shot 2018-08-22 at 16 00 35

Group 4: 1008px - 1279px
screen shot 2018-08-22 at 16 01 02

Group 5: 1280px+
screen shot 2018-08-22 at 16 00 51

**Describe the solution you'd like**
The footer should have the correct number of columns, according to the designs.

### PR DESCRIPTION
**Pull request by sareh**
Resolves #545

Correct number of columns for all breakpoints.

```
npm install
npm run storybook
```
Visit http://localhost:9001/?selectedKind=Footer%20Container&selectedStory=default&full=1&addons=1&stories=1&panelRight=0

- [x] Tests added for new features
- [x] UX designer approval
- [ ] Test engineer approval

### CODE REVIEW

**Comment by sareh** [comment]
Note: this PR only addresses the columns within the Footer List. It does not address the red brand banner spacing, which is being addressed in PR #468, or the Footer padding/spacing which is being addressed in PR #537. 

**Group 5:**
screen shot 2018-08-22 at 17 22 14

**Group 4:**
screen shot 2018-08-22 at 17 22 25

**Group 3:**
screen shot 2018-08-22 at 17 22 34

**Group 2:**
screen shot 2018-08-22 at 17 22 46

**Group 1:**
screen shot 2018-08-22 at 17 22 58

**Comment by pjlee11** [comment]
I personally think we should extend the media queries here https://github.com/bbc/simorgh/blob/footer-links-columns/src/app/helpers/mediaQueries.js#L7-L11 rather than having specific media queries for each group within the FooterList component, such as `@media (min-width: ${group3ScreenWidthMin}) and (max-width: ${group3ScreenWidthMax}) {`. I would be happy if this change was made in a follow up PR rather than holding this one back.

**Review by pjlee11 — DISMISSED** [review]

**Comment by sareh** [comment]
@pjlee11 Thanks for the review. Those media queries need to be renamed and they'd need to be updated in multiple files. That's why I didn't make the change in this PR. Happy to do that in a follow-up PR.

**Review by PaulChinkwende — DISMISSED** [review]

**Review by radiocontrolled — DISMISSED** [review]
Great job 👍

**Comment by jamesbrumpton** [comment]
LGTM

**Review by PaulChinkwende — APPROVED** [review]

**Review by pjlee11 — APPROVED** [review]

**Pull request merged**
