### PR TITLE
Script link - Remove visually hidden text

### LINKED ISSUE #3290: Fix React warnings in src/app/containers/ChartbeatAnalytics/canonical/index.test.jsx
**Describe the bug**
There are React warnings in unit tests.

**To Reproduce**
Go to simorgh in terminal
Run npm run test:unit
Observe React warnings:
```
  console.error src/testHelpers/setupTests.js:53
    Warning: Failed prop type: The prop `chartbeatConfig.uid` is marked as required in `CanonicalChartbeatBeacon`, but its value is `undefined`.
        in CanonicalChartbeatBeacon
```
**Expected behaviour**

No React warning for test suite.

**Testing notes**

No testing required.

### LINKED ISSUE #3290: Script link - Remove visually hidden text
**Describe the bug**
The script link has visually hidden text with english translations on:

https://www.bbc.com/serbian/lat 
https://www.bbc.com/serbian/cyr 
https://www.bbc.com/ukchina/simp 
https://www.bbc.com/ukchina/trad

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/serbian/cyr
2. Inspect the script link
3. You will see ```<span class="VisuallyHiddenText-sc-1yjwwa5-0 jFfEvX"> Cyrillic</span>```

**Expected behaviour**
The script link should not have visually displayed text as per the UX screen reader spec. This also means that the displayed text should not have an aria hidden attribute, this will also need removing ```<span aria-hidden="true">Ћир</span>```

**Screenshots**
Screen Shot 2020-03-23 at 11 44 16

**Testing notes**

- [x] This bug fix is expected to need manual testing. When using AT, the script link should just read out the displayed text.

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves https://github.com/bbc/psammead/issues/3290

**Overall change:** 
The script link should not have visually displayed text as per the UX screen reader spec.

**Code changes:**
- Remove visually hidden text from the Script Link 
- Remove aria-hidden span
- Bump `@bbc/psammead-script-link`
- Remove `offscreenText` from the config files

---

- [X] I have assigned myself to this PR and the corresponding issues
- [X] I have added labels to this PR for the relevant pod(s) affected by these changes
- [X] I have assigned this PR to the Simorgh project

**Testing:**
- [X] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [X] This PR requires manual testing

### CODE REVIEW

**Review by mmcculloch — APPROVED** [review]

**Review by sareh — APPROVED** [review]
👍 Looks good.

**Review by sareh — CHANGES_REQUESTED** [review]
I noticed that the padding seems to be changed as a result of this.
Screenshot 2020-03-24 at 15 00 13

The reason is that unfortunately, the styles were applied like this, with a `> span` selector: https://github.com/bbc/psammead/blob/latest/packages/components/psammead-script-link/src/index.jsx#L44
Convention in our codebase is to, wherever possible, to use Styled Components for styling. It seems like it was missed in the original PR for `psammead-script-link`

**Comment by DenisHdz** [comment]
> I noticed that the padding seems to be changed as a result of this.
> Screenshot 2020-03-24 at 15 00 13
> 
> The reason is that unfortunately, the styles were applied like this, with a `> span` selector: https://github.com/bbc/psammead/blob/latest/packages/components/psammead-script-link/src/index.jsx#L44
> Convention in our codebase is to, wherever possible, to use Styled Components for styling. It seems like it was missed in the original PR for `psammead-script-link`

I noticed this change in Chromatic https://www.chromaticqa.com/snapshot?appId=5d28eb5ee163f6002046d6fb&id=5e79e3b9a8c0b0002202827b but I misunderstood it..
I'll update it in Psammead and put this back in progress 👍

**Comment by sareh** [comment]
@DenisHdz Thanks, Denis.

**Comment by DenisHdz** [comment]
> > I noticed that the padding seems to be changed as a result of this.
> > Screenshot 2020-03-24 at 15 00 13
> > The reason is that unfortunately, the styles were applied like this, with a `> span` selector: https://github.com/bbc/psammead/blob/latest/packages/components/psammead-script-link/src/index.jsx#L44
> > Convention in our codebase is to, wherever possible, to use Styled Components for styling. It seems like it was missed in the original PR for `psammead-script-link`
> 
> I noticed this change in Chromatic https://www.chromaticqa.com/snapshot?appId=5d28eb5ee163f6002046d6fb&id=5e79e3b9a8c0b0002202827b but I misunderstood it..
> I'll update it in Psammead and put this back in progress 👍

This has been fixed to keep it as it was https://www.chromaticqa.com/snapshot?appId=5d28eb5ee163f6002046d6fb&id=5e7b33e9bff8db00225b1e3a

**Review by j-pendlebury — APPROVED** [review]
LGTM 👍

**Review by EinsteinNjoroge — APPROVED** [review]

**Review by sareh — APPROVED** [review]
Thanks for the fix in Psammead and pulling it in here. It looks great.

**Comment by paruchurisilpa** [comment]
Looks good to me..

**Pull request merged**
