### PR TITLE
Bump Minor and Patch Dependencies

### PR DESCRIPTION
**Pull request by andrewscfc**
Closes #8034 #8013 #8011 #8010 #8009 #8008 #8007 #8006 #8005 #8004 #8003 #8002 #8001 #8000 #7999 #7998 #7997 #7996 #7995 #7994 #7993 #7992 #7991 #7990 #7989 #7987 #7986 #7985 #7984 #7983 #7982 #7981 #7980 #7979 #7978 #7976 #7975 #7974 #7973 #7972 #7971 #7970 #7931 #7923

**Overall change:**
Ran `rm -rf node_modules/ && npm install && npm update` to update all minor and patch dependencies. See linked PRs above for included bumps.

Added licence exception for sub-dependency.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by karinathomasbbc — APPROVED** [review]
Looks like there is also a high sev securuty vulnerability which is causing tests to fail 🙈

**Comment by andrewscfc** [comment]
> Looks like there is also a high sev securuty vulnerability which is causing tests to fail 🙈

Just ran `npm install` again after the `npm update`, that re-applies the forced resolutions after the npm update *sigh. https://github.com/bbc/simorgh/pull/8037/commits/8909c849af619164cdea993e60aefd86bef9c9ac

So looks like our reliable command to update patch and minor versions is: `rm -rf node_modules/ && npm install && npm update && npm install` 🙈 

Just using this PR to test the new process, looks okay now I think, hopefully that is the last gotcha.

**Comment by andrewscfc** [comment]
@jamesdonoh is there any reason I can't add this licence exception here: https://github.com/bbc/simorgh/pull/8037/commits/e647463baae7459aa80c13db9cc703543014d0f4 

I have not come across and process for these?

**Comment by karinathomasbbc** [comment]
> > Looks like there is also a high sev securuty vulnerability which is causing tests to fail 🙈
> 
> Just ran `npm install` again after the `npm update`, that re-applies the forced resolutions after the npm update *sigh. [8909c84](https://github.com/bbc/simorgh/commit/8909c849af619164cdea993e60aefd86bef9c9ac)
> 
> So looks like our reliable command to update patch and minor versions is: `rm -rf node_modules/ && npm install && npm update && npm install` 🙈
> 
> Just using this PR to test the new process, looks okay now I think, hopefully that is the last gotcha.

Is it worth adding a script to do this, just to make it a bit less error prone?

**Review by simonsinclair — APPROVED** [review]

**Pull request merged**
