### PR TITLE
Use @bbc/psammead-sitewide-links in Simorgh 

### PR DESCRIPTION
**Pull request by radiocontrolled**
Resolves https://github.com/BBC-News/simorgh/issues/1060

* Add @bbc/psammead-sitewide-links to Simorgh
* Remove/replace the existing sitewide links component in Simorgh  

**Screenshots**
screen shot 2018-12-11 at 15 31 56

screen shot 2018-12-11 at 15 31 47

screen shot 2018-12-11 at 15 31 41

- [X] I have assigned myself to this PR and the corresponding issues
- [NA] Tests added for new features (existing tests do not break)
- [x] Test engineer approval
- [x] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by bcmn — DISMISSED** [review]

**Review by sareh — APPROVED** [review]
👍 Looks great locally!

**Review by bcmn — APPROVED** [review]
Tested locally, looks good!

**Comment by nataliesmart** [comment]
Just reviewed and all looks good. Ready to proceed.

**Comment by jamesbrumpton** [comment]
LGTM

**Pull request merged**
