### PR TITLE
Pull in new Inline link styling 

### LINKED ISSUE #1710: Use new reith fonts
**Is your feature request related to a problem? Please describe.**
Following #1649, we are awaiting our third party to produce the full set of source font files for the GEL team to host. After these files have been hosted, we should update the font source files to use the new version. This version of Reith should have reduced whitespace around the rendered glyphs which will allow our UX team to have design freedom going forward. 

This issue should bump our Reith version to 2.5+ which will then include the changes for 2.4 and 2.5+ 

**Describe the solution you'd like**
Update ‘globalStyles’ to use the new version of the reith source font files. 

**Describe alternatives you've considered**
N/A

**Testing notes**
Regression across fonts including visual regression. Check across older OS's to ensure the fonts don't regress.

Dev insight: Update all relevant tests. Manually check that the 2.500 font files are being pulled in, in the network tab. 

**Additional context**
There should be no visual change in the rendered page.

### PR DESCRIPTION
**Pull request by pjlee11**
Resolves #1710

**Overall change:** Branch for testing the new UX link styling being added as part of https://github.com/bbc/psammead/pull/707. This PR adds the test fixture called `ctestreith0o` EG: http://localhost:7080/news/articles/ctestreith0o

**Code changes:**

- Updates the UX styling to the desired designs as per https://github.com/bbc/psammead/pull/707

Testing this:
- Ensure the special characters in mentioned in this [issue](https://github.com/bbc/simorgh/issues/1724) are fixed in the example story https://www.test.bbc.co.uk/news/articles/cev804m5n0vo (might need to copy this into local fixture data, can use the JSON endpoint to get the payload https://www.test.bbc.co.uk/news/articles/cev804m5n0vo.json)
- Visual regression of font, especially on components such as inline link.
- Check firefox high contrast mode (Go to FireFox -> Preference -> Language & Appearance -> Colours -> 'Override the colours ...' set as `Always`)
- Check Windows high contrast mode
- Check with page zoomed to high percentages (300%+)
- Check across different breakpoints 
- Check across different browsers

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval
- [x] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Comment by pjlee11** [comment]
As shown in the screenshot below the links which use a `border-bottom` for the underline now are slightly closer to the letters in the link, this is expected and is example of the whitespace changes we requested. Left is local environment using the new fonts, Right is the current live environment. 

image

image

image
The caption example is easiest to see the change on the descending letters. It is likely there needs to be a follow up piece of work from UX to evaluate the GEL line-heights but that is a seperate task

**Review by twinlensreflex — DISMISSED** [review]
looks great 👍

**Review by oluoluoxenfree — DISMISSED** [review]

**Review by oluoluoxenfree — DISMISSED** [review]
💯

**Review by twinlensreflex — DISMISSED** [review]

**Review by 12 — DISMISSED** [review]

**Comment by pjlee11** [comment]
Following the UX review some further changes are required so I’m making a test page for Natalie and Catharine to review based on using the initial styles that we had to move away from due to the font issues. This will be reviewed next week (early june)

**Comment by pjlee11** [comment]
This is still ongoing with UX reviews. 

To run: 
- checkout this branch
- checkout psammead branch `WIP-reith-font-fixes-and-styling`
- In psmmead run `npm run build` 
- in simorgh run:
```cp ../psammead/packages/components/psammead-inline-link/dist/index.js node_modules/@bbc/psammead-inline-link/dist/index.js && cp ../psammead/packages/components/psammead-sitewide-links/dist/index.js node_modules/@bbc/psammead-sitewide-links/dist/index.js && npm run dev```

NB: don't ask me why but `npm link`'ing psammead to simorgh for multiple packages has weird behaviour, I think it's something to do with styled components being a singleton and trying to load multiple times when linked. 

This currently needs feedback from UX and accessibility on the new link styles.

**Comment by pjlee11** [comment]
Myself and Natalie combined are on leave till the 24th so this will stay blocked. There is a meeting scheduled for the 25th where Catharine, Natalie and myself will sit down and finalise the link styling and tweaks required to use the new Reith font in production.

**Comment by sareh** [comment]
@pjlee11 The version of psammead-styles with this reith font accidentally went live (in a bumping of all dependencies).
When deciding whether to roll back or to fix forwards, I paired with @nataliesmart to investigate descenders with link underlines to see if they intersected.

At 100% zoom (standard) with standard and hover/focus states:
Screen Shot 2019-06-19 at 12 43 44
Screen Shot 2019-06-19 at 12 43 36
Screen Shot 2019-06-19 at 12 43 17

At 300% zoom with standard and hover/focus states:
Screen Shot 2019-06-19 at 12 48 56
Screen Shot 2019-06-19 at 12 48 49
Screen Shot 2019-06-19 at 12 48 40
Screen Shot 2019-06-19 at 12 48 25

As a result, it was agreed to fix forwards rather than roll back the font usage.

**Comment by jamesbhobbs** [comment]
@pjlee11 we did this package update anyway, but I'm leaving the PR open as a reminder in case there are minor fixes that UX would like.

**Comment by pjlee11** [comment]
## New link styling

**Normal Body Copy**

image
---

**Hovered Body Copy**

image
 ---

**Hovered Body Copy Multiline**

image
---

**Normal Caption**

image
---

**Hovered Caption **

image
---

**Hovered Caption Multiline**

image

**Comment by pjlee11** [comment]
Changed this issue from being to "bump the new Reith font version" to be "update the inline link styling" to the originally desired UX styling due to the Reith font being put live in seperate work

**Comment by pjlee11** [comment]
To summarise where this is at:
- Reith 2.5.1 is passable with the current styling
- The descenders are close to the border-bottom which is raising a potential a11y concern with dyslexic users, this needs to be investigated further by UX. If more space is needed we can add padding-bottom 1px to the inline link. However the line-heights for the caption may need increasing given the additional 1px spacing between lines
- The latest Reith version now enables the new inline link styling as per https://github.com/bbc/psammead/pull/707 which has a different potential a11y concern because the red background is not recommended for users with colour vision deficiencies, again this needs to be further investigated by UX

**Comment by pjlee11** [comment]
TODO: check Persian article

**Comment by pjlee11** [comment]
blocked on https://github.com/bbc/psammead/pull/707

**Comment by pjlee11** [comment]
This needs an a full a11y swarm to ensure the new link styling is completely accessible

**Pull request closed without merging**
