### PR TITLE
Move pre-process rules out of dataValidator

### LINKED ISSUE #1616: Move preprocess rules out of dataValidator
I've since realised that there is also timestamp logic homed in the same place as this. I'd be happy for the outcome to be that we create an issue to move both of these out of the `dataValidator/` directory rather than the change being in this PR.

_Originally posted by @pjlee11 in https://github.com/bbc/simorgh/pull/1596_

**Is your feature request related to a problem? Please describe.**
Within a previous refactor, the logic that's used to insert the timestamp into the middle of the JSON data was put into the `dataValidator` directory. However, the data validator is going to be pulled out of the repository very soon and we need to keep our timestamp logic in Simorgh. 

**Describe the solution you'd like**
Moving the timestamp positioning logic out of `dataValidator` and into `lib`.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: All integration tests should still pass. 

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

### PR DESCRIPTION
**Pull request by Bopchy**
Resolves #1616 

**Overall change:** _Move timestamp and pre-processor logic out of /dataValidator._

**Code changes:**

- _Move dataValidator/rules/timestamp.js & dataValidator/rules/timestamp.test.js into src/app/lib/utilities/rules._
- _Move src/app/dataValidator/preprocessor.js and its tests to lib/utilities/preprocessor.js._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [x] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by dr3 — CHANGES_REQUESTED** [review]
Can I be a pain and request we structure it
```
utilities/preprocessor/index.js
utilities/preprocessor/rules/timestamp.js
utilities/preprocessor/rules/topstories.js
```
As the rules are really only for the preprocessor

**Comment by pjlee11** [comment]
@dr3 if it's only for the preprocessor does it need to be in `utilities/`? Would it be better to have `/lib/preprocessor` rather than creating `lib/utilities/` then nesting it inside of `/preprocessor` in there?

**Comment by dr3** [comment]
@pjlee11 dont mind either way :)

**Review by dr3 — DISMISSED** [review]

**Review by sareh — APPROVED** [review]
Looks good!

**Review by dr3 — APPROVED** [review]
LGTM

**Comment by david-boydell** [comment]
This is RFM

**Pull request merged**
