### PR TITLE
Fix most read on article ie

### PR DESCRIPTION
**Pull request by thekp**
🐛 🛠 

**Overall change:** 
_IE does not support using max-width and margin: auto to dynamically center an element, the solution to this is the set a `width: 100%`_

Currently on LIVE: 
image

Local changes: 
image

**Code changes:**
- _Add `width:100%` where min width is being defined_
- _update snapshots_

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by Bopchy — APPROVED** [review]
Checked this on BrowserStack. Looks good 👍

**Review by EinsteinNjoroge — APPROVED** [review]

**Comment by PriyaKR** [comment]
Looks good to me except the most read doesn't seem to render on opera mini.Same issue on latest branch as well.

May be an issue because of ngrok.

**Comment by EinsteinNjoroge** [comment]
> Looks good to me except the most read doesn't seem to render on opera mini.Same issue on latest branch as well.
> 
> May be an issue because of ngrok.

Could be a data fetching issue, I think the data for most-read is not being fetched correctly in opera mini

**Comment by PriyaKR** [comment]
> > Looks good to me except the most read doesn't seem to render on opera mini.Same issue on latest branch as well.
> > May be an issue because of ngrok.
> 
> Could be a data fetching issue, I think the data for most-read is not being fetched correctly in opera mini

It looks good on test and live environment.The reason its not showing most read locally may be because i am using ngrok.

**Comment by tochwill** [comment]
> > > Looks good to me except the most read doesn't seem to render on opera mini.Same issue on latest branch as well.
> > > May be an issue because of ngrok.
> > 
> > 
> > Could be a data fetching issue, I think the data for most-read is not being fetched correctly in opera mini
> 
> It looks good on test and live environment.The reason its not showing most read locally may be because i am using ngrok.

Hey! Yeah it won't work with ngrok as javascript doesn't work when using that. The intermediate opera server _does_ execute some javascript, which is why we can see this in opera mini :)

**Pull request merged**
