### PR TITLE
Fix offscreen text for Brand for azeri, japanese, kyrgyz, punjabi and thai

### PR DESCRIPTION
**Pull request by sareh**
No ticket - bug raised by @greenc05 

**Overall change:** Add serviceLocalizedName for azeri, kyrgyz, punjabi and thai - this ensures that the markup for the offscreen text has the `BBC News` with the lang attribute `en-gb`
```
<span role="text" class="VisuallyHiddenText-sc">
  <span lang="en-GB">BBC News</span>, บีบีซีไทย
</span>
```
Screenshot of thai brand offscreen text on http://localhost.bbc.com:7080/thai

Screenshot of thai brand offscreen text

**Code changes:**

- Update product to be `BBC News` with serviceLocalizedName being the localised name. Services: azeri, kyrgyz, punjabi and thai 
- Update product to be `BBC` with serviceLocalizedName being the localised name for Japanese.

**Testing notes**
Visit these pages & see that the offscreen text for the brand component is split - with the English part in a span with `lang="en-GB"`
http://localhost.bbc.com:7080/azeri
http://localhost.bbc.com:7080/japanese
http://localhost.bbc.com:7080/kyrgyz
http://localhost.bbc.com:7080/punjabi
http://localhost.bbc.com:7080/thai

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by sareh** [comment]
High priority since it includes fixes for Thai and Punjabi, which are already live.

**Review by j-pendlebury — APPROVED** [review]
Looks good 👍

**Review by AlistairGempf — APPROVED** [review]
Looks good

**Review by DenisHdz — APPROVED** [review]
Looks good

**Comment by staylos92** [comment]
Happy for this to be merged based on the above 👍

**Pull request merged**
