### PR TITLE
Storybook each story renders something (technically not nothing)

### PR DESCRIPTION
**Pull request by jamesbhobbs**
Add test in issue. Also add storybook cypress interactive test.

* [x] Fixes https://github.com/bbc/simorgh/issues/201
~~* [ ] Tests added for new features~~

* [x] Test engineer approval

### CODE REVIEW

**Comment by DemonusPC** [comment]
These tests are only focused on storybook right? Because removing elements from our local storybook data to render our components doesn't change the outcome of this test.

**Review by jp-bbc — DISMISSED** [review]
Tested locally - seems good to me. Approved.

**Review by DemonusPC — DISMISSED** [review]
Nvm my comment. The test works

**Review by jtart — CHANGES_REQUESTED** [review]
`body.sb-show-main` still exists, even if the story is blank.

**Comment by jtart** [comment]
image

**Comment by jamesbhobbs** [comment]
@jtart change made

**Review by pjlee11 — APPROVED** [review]

**Review by jtart — APPROVED** [review]

**Pull request merged**
