### PR TITLE
DONT MERGE UNTIL WED - Enable LIVE e2es for Telugu Marathi Gujarati Tamil Uzbek

### LINKED ISSUE #5034: Live e2e tests for Telugu, Marathi, Gujarati, Tamil and Uzbek
**Is your feature request related to a problem? Please describe.**
Once the Telugu, Marathi, Gujarati, Tamil and Uzbek front pages are live, we need to make sure the e2e tests are running on the live pages. Blocked until the front pages are live, otherwise we have nothing to run the tests against.

**Describe the solution you'd like**
Edit the cypress service config so that Telugu, Marathi, Gujarati, Tamil and Uzbek front page tests are run on all environments instead of skipping live.

e.g
Replace
`path: Cypress.env('APP_ENV') === 'live' ? undefined : '/telugu',`
with
`path: '/telugu',`

**Describe alternatives you've considered**
Not testing live, don't do this!

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by j-pendlebury**
Resolves https://github.com/bbc/simorgh/issues/5034

**Overall change:** 
Enable LIVE E2E's for Telugu, Marathi, Gujarati, Tamil, and Uzbek.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- ~~Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)~~
- ~~If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)~~
- ~~This PR requires manual testing~~

### CODE REVIEW

**Comment by j-pendlebury** [comment]
Don't merge until services go live on Wednesday morning - `CHANGE-22961`

**Review by OlgaLyubin — APPROVED** [review]
Looks good

**Review by DenisHdz — APPROVED** [review]

**Review by tochwill — APPROVED** [review]

**Comment by amywalkerdev** [comment]
Moving to blocked column until Weds

**Comment by amywalkerdev** [comment]
The five services are live so this can be merged now

**Pull request merged**
