### PR TITLE
Update Arabic nav

### LINKED ISSUE #6297: Update Arabic Navigation
**Is your feature request related to a problem? Please describe.**
Update Arabic Navigation.
Check with Jon as this will need to be released with next PAL release (planned 28/29April)

**Describe the solution you'd like**
1. Remove Business, Art and Culture, Sport, Magazine, Women, In Pictures, Interactivy and In Depth: 

Remove: 
business
url : '/arabic/business'

artandculture
url : '/arabic/artandculture'

sport
url : '/arabic/sports'

magazine
url : '/arabic/magazine'

women
url : '/arabic/topics/e45cb5f8-3c87-4ebd-ac1c-058e9be22862'

pictures
url : '/arabic/media/photogalleries'

interactivity
url : '/arabic/interactivity'

indepth
url : '/arabic/in_depth'
 

2. Move trending under Press 
trending
url : '/arabic/trending'

3. Add documentaries item
item name 'documentaries'
title : 'تحقيقات'
url : '/arabic/tv-and-radio-42414864'

position: 9th item in the list between trending and programmes

This should end up this (taken from the PAL config):
 - &home
   title : 'رئيسية'
   url   : '/arabic'

 - &middleeast
   title : 'شرق أوسط'
   url   : '/arabic/middleeast'

 - &world
   title : 'عالم'
   url   : '/arabic/world'

 - &scienceandtech
   title : 'علوم وتكنولوجيا'
   url   : '/arabic/scienceandtech'

 - &health
   title : 'صحة'
   url   : '/arabic/topics/c4794229-7f87-43ce-ac0a-6cfcd6d3cef2'

 - &media
   title : 'فيديو'
   url   : '/arabic/media'

 - &press
   title : 'صحافة'
   url   : '/arabic/inthepress'

 - &trending
   title : 'ترند'
   url   : '/arabic/trending'

 - &documentaries
   title : 'تحقيقات'
   url   : '/arabic/tv-and-radio-42414864'

 - &programmes
   title : 'برامجنا'
   url   : '/arabic/tv-and-radio-37728883'

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by jimjohnsonrollings**
Resolves #6297 

**Overall change:**
Updates the Arabic nav

**Code changes:**

- Updates to the Arabic nav

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by DenisHdz — APPROVED** [review]
LGTM

**Review by sareh — APPROVED** [review]
👍 Looks good.

**Comment by PriyaKR** [comment]
The nav changes looks good to me.

**Comment by sareh** [comment]
This PR can be merged in now after CI passes.

**Pull request merged**
