### PR TITLE
Typography script update

### LINKED ISSUE #3837: Update typography settings for Azeri and Japanese
**Is your feature request related to a problem? Please describe.**
Azeri should use `latinDiacritics` script settings and Japanese should use `noAscendersOrDescenders` script settings. 

**Describe the solution you'd like**
The typography settings in Psammead's `@bbc/gel-foundations/scripts` are correct. They should be exported and imported here in Simorgh config for the relevant services. 

As part of this issue, we should also ensure we're importing the relevant script for all other services. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by sareh**
Resolves #3837

**Overall change:** Uses correct scripts for all services.

**Code changes:**
- Use latest gel-foundations version with updated script exports
- Use scripts noAscendersOrDescenders, latinDiacritics, bengali, burmese, tamil, devanagariAndGurmukhi
- Use cyrillicAndLatin for all instances of latin or cyrillic services

| script | services |
| -----  | ----- |
| arabic | arabic, pashto, persian, urdu |
| bengali | bengali |
| burmese | burmese |
| cyrillicAndLatin | afaanoromoo, gahuza, hausa, igbo, indonesia, kyrgyz, news, pidgin, russian, scotland, serbian, somali, swahili, ukrainian, uzbek, yoruba |
| devanagariAndGurmukhi | gujarati, hindi, marathi, nepali, punjabi, telugu |
| latinDiacritics | afrique, azeri, cymrufyw, mundo, naidheachdan, portuguese, serbian, turkce, vietnamese |
| noAscendersOrDescenders | amharic, japanese, korean, tigrinya, ukchina, zhongwen |
| sinhalese | sinhala |
| tamil | tamil |
| thai | thai |

e.g. 
[Azeri](http://localhost.bbc.com:7080/azeri) is using `latinDiacritics` - see the line-height for group D for the top story is 34px.
Screenshot 2019-09-18 at 15 12 58

[Japanese](http://localhost.bbc.com:7080/japanese) is using `noAscendersOrDescenders` - see the line-height for group D for the top story is 38px.
Screenshot 2019-09-18 at 15 14 01

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by jamesdonoh — APPROVED** [review]

**Review by DenisHdz — COMMENTED** [review]
Thanks for updating all the services scripts. 
Should `cymrufyw` import `cyrillicAndLatin`?

**Review by dr3 — APPROVED** [review]
LGTM, cant speak to their accuracy though. Please double check with UK pre-merge

**Comment by sareh** [comment]
@DenisHdz I've updated cymrufyw & naidheachdan to use `latinDiacritics`. Thanks for pointing that out.

**Review by DenisHdz — APPROVED** [review]
LGTM 👍

**Comment by sareh** [comment]
The WS services were UX reviewed by Laura. ✅ 
Noting that Cymru Fyw and Naidheachdan typography settings should be reviewed prior to those services going live.

**Comment by paruchurisilpa** [comment]
Looks good to me..

**Pull request merged**
