### PR TITLE
Remove caption story

### LINKED ISSUE #1017: Remove Caption Story which utilises Markdown
**Describe the bug**
The current "Figure with caption containing link" story uses Markdown. This means it has fixture data that is not representative of any value the component will currently ever receive.

**Plan of Action**
When discussed with Phil & Chris, we intend to remove the story in it's entirety, & the work to add a new, fragment-y version will be included in #801.

### PR DESCRIPTION
**Pull request by ChrisBAshton**
Resolves #1017

Removes unused caption-with-inline-link stories & tests.

- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by sareh — APPROVED** [review]
👍 Looks good. 
We should also raise an issue that adds the `Caption containing a link` scenario, but with Fragments instead of markdown. This is so that we don't forget to add it back in properly.

**Comment by ChrisBAshton** [comment]
Think that'll get added in #801 - my understanding is that links inside captions aren't possible in the E2E process at the moment.

**Comment by pjlee11** [comment]
@sareh that will be handled as part of https://github.com/BBC-News/simorgh/issues/801 which is blocked on new UX designs

**Review by pjlee11 — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
LGTM

**Pull request merged**
