### PR TITLE
Added new styled grid item for article AV player

### LINKED ISSUE #4311: AV player indented at smaller screen sizes
**Describe the bug**
The media player is currently indented on 375px, 600px, and 768px layouts.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://www.test.bbc.com/igbo/articles/cr1lw620ygjo
2. Toggle to the widths listed above.
3. Scroll down to the media player block. 
4. See that the media player block is indented.

**Expected behavior**
The media player needs to be flush on all layouts. See designs here: https://app.zeplin.io/project/5baa564c05c2eba0d2b89568/screen/5c596fa88971d341fae3fd53

**Screenshots**
Screenshot of the bug:
image

Screenshot of correct placement:
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
While testing this issue, we should ensure that it also fixes https://github.com/bbc/simorgh/issues/4735

### PR DESCRIPTION
**Pull request by HarveyPeachey**
Resolves #4311 #4735

**Overall change:** 
Added a new grid item layout to support medium grid items that require no margin specifically for the AV article media player. Shoutout to @EinsteinNjoroge for helping me figure out some issues on this PR.

**Code changes:**
- Added new `layoutGridItemMediumNoMargin` to our layout we have for our grid system.
- Added the new layout grid item to our styled grid called `GridItemConstrainedMediumNoMargin`.
- Updated and created snapshots/tests for the new Layout and Styled grid option.
- Added a new story in storybook to our Grid Examples.
- Used new grid constrained item for the article av container

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Review by jamesdonoh — APPROVED** [review]
Good work! Is there anything we need to do to make this easier to migrate the new grid once it leaves alpha?

**Comment by HarveyPeachey** [comment]
Looks like there's a discrepancy with one of the chromatic snapshots for an article, looks like this change has added some extra white spacing somehow to LargeConstrained items, not sure why. https://www.chromaticqa.com/snapshot?appId=5d28eb3fe163f6002046d6fa&id=5df10bd70fa0900020d3e7bb

**Comment by HarveyPeachey** [comment]
> Good work! Is there anything we need to do to make this easier to migrate the new grid once it leaves alpha?

I've spoken to Einstein and he said they haven't started on articles yet and are focusing on front pages, but he is aware of this new layout so it will be implemented when shared comps get round to it.

**Review by EinsteinNjoroge — APPROVED** [review]
:+1:

**Comment by jamesbrumpton** [comment]
lgtm

**Pull request merged**
