### PR TITLE
Cookie banner translations for Punjabi

### LINKED ISSUE #3512: Add cookie banner translations for Punjabi
**Is your feature request related to a problem? Please describe.**
The Punjabi cookie banner is currently in English, we should replace this with the translations provided in the spreadsheet. 
The link to the spreadsheet is in WSFRONTPGS-136

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by OlgaLyubin**
Resolves #3512 

**Overall change:** 
Added Punjabi cookie banner translations.

**Code changes:**
Added translations to Punjabi data config file.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by dr3 — APPROVED** [review]
LGTM, tested via in browser translations & translations doc. Cookie link works as expected with spacings :)

**Review by FK78 — APPROVED** [review]

**Comment by dr3** [comment]
Tested locally, LGTM, im happy to just merge this

**Comment by PriyaKR** [comment]
Looks good to me.

**Pull request merged**
