### PR TITLE
Fade Images in Articles

### LINKED ISSUE #1762: Investigate Image Fade In
**Is your feature request related to a problem? Please describe.**
Following on from #1734, UX have suggested investigating adding a fade to ease an image into its container when the image is lazyloaded. An example can be found [here](https://www.bbc.co.uk/news/uk-48368346) by scrolling down the page and observing the fading in of images as they are lazyloaded.

UX context - during user research it was found that often users scroll quickly through the page. We'd like to improve this experience.

**Describe the solution you'd like**
When the image component is lazyloaded, we should ease it into the page with a fade. UX should be involved with the timings of this. 

Investigate several options and present with gifs/videos showing the alternatives & review with UX.

**Testing notes**
Regression testing, checking performance isn't negatively impacted. 
Browser testing to ensure the fade in is working in multiple browsers. 

Dev insight: Visual regression cross device / browser.

### PR DESCRIPTION
**Pull request by 12**
Resolves #1762 

**Overall change:** Sets images in articles to fade in by default. _(note: this will not fade in images on front pages)_

**Code changes:**

- Similar to how lazyloading logic is passed through, we set a `fade` prop to `true` in `ImageContainer`
- Update snapshots

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by ryanmccombe — APPROVED** [review]

**Review by chris-hinds — APPROVED** [review]
👍 Just need to resolve the `package-lock.json` conflicts

**Comment by chris-hinds** [comment]
> 👍 Just need to resolve the `package-lock.json` conflicts

Conflicts resolved, should be good to merge on Monday morning

**Comment by sareh** [comment]
Moved back into the UX review column since this is a change to add a fade-in for Article's lazyloaded images and it should be reviewed by a UX designer prior to being put in ready-for-test.

**Comment by jamesbrumpton** [comment]
LGTM

**Pull request merged**
