### PR TITLE
add support for safari 10+

### LINKED ISSUE #9749: Broken Javascript on Live on Safari 13.x
**Describe the bug**
Javascript seems to be broken on Safari 13.x and older* (across MacOS desktop & iOS mobile) 
i.e no cookie banner & images not loading, drop-down menu not working

This was found testing on the following BrowserStack devices: MacOS Catalina,  iPhone 11 Pro Max, iPhone XS.

*Noticed also on Safari 12, 11 and 10 - but these are not Level A/B supported browsers so assume not that important. 
Same issue is not appearing on Safari 15, 14. 

**To Reproduce**
1. Go to webpage, eg: https://www.bbc.com/afaanoromoo

**Expected behaviour**
- Cookie banner should appear
- Images below main image should load up
- Drop-down menu (top-left) should expand upon click 

**Screenshots**

**Desktop / Mobile:**

- OS: MacOS Catalina,  iPhone 11 Pro Max, iPhone XS.
- Browser: Safari 13.x

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

### PR DESCRIPTION
**Pull request by jroebu14**
Resolves https://github.com/bbc/simorgh/issues/9749

**Overall change:**
Fixes broken javascript in safari 13.1.

**Code changes:**

- Updates babel-config with browserlist safari 10+ as well as e6 modules support

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

Will need manually tested on affected Safari versions and also a check on other browsers.

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by DarioR01 — APPROVED** [review]

**Review by HarveyPeachey — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]

**Review by DarioR01 — COMMENTED** [review]
Why did the bundle sizes for burmese StoryPage have changed?

**Review by Louis-Matsika — APPROVED** [review]

**Review by MuhammadAHussain — APPROVED** [review]
LGTM 👍

**Comment by ryanmccombe** [comment]
> Why did the bundle sizes for burmese StoryPage have changed?

I think it's all bundles - not this one specifically.  Older browsers support fewer modern JS features.  In order to polyfill or work around those missing features, babel will need to include additional code in the bundles.

**Comment by DarioR01** [comment]
> polyfill

Ohhh, ok makes sense. Thanks for the explanation 🙇

**Comment by LilyL0u** [comment]
Mac OS Catalina Safari 13.1 - cookie banner is present, images load, dropdown menu works.

The bug issue also says this was broken on  iPhone 11 Pro Max. I tested this with OS 13, but I don't know the browser version. It was also all working.
Same with iPhone XS 12.

**Pull request merged**
