### PR TITLE
override html 'lang' attribute with computed 'lang' override in service config

### LINKED ISSUE #7262: Ensure the HTML 'lang' attribute is updated when a language override is present
### Is your feature request related to a problem? Please describe.
When a language override is present, we must indicate that the language of the content has changed from the default.

### Describe the solution you'd like
- Ensure that when a language override is present the root element's (`<html>`) `lang` attribute indicates the language of the content being served. E.G. If BBC Ukrainian serves a Russian Story, the value should match that found in the `ru-UA` config property.

#### A11y acceptance criteria

```
Given I’m using a screen reader
When I navigate the header with Ukrainian language content
Then it is announced with a Ukrainian accent

Given I’m using a screen reader
When I navigate the main column with Russian language content
Then it is announced with a Russian accent
```

Note: @OlgaLyubin will be able to help us with the dev a11y swarm.

### Describe alternatives you've considered
n/a

### Testing notes
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

### Additional context
None.

### PR DESCRIPTION
**Pull request by rhenshaw56**
Resolves #7262

**Overall change:**
_Override html lang attribute with lang value in service config for story pages._

**Code changes:**

- _Override html lang attribute with lang value in service config for story pages._

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [X] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [X] This PR requires manual testing

### CODE REVIEW

**Review by thekp — APPROVED** [review]
LGTM

I can see there has been work done prior to this PR to use `ru-UA` config when the metadata language is `ru`.

Screen shot of local page with lang code of `ru-UA`
Screen shot of local page with lang code of `ru-UA`

**Comment by rhenshaw56** [comment]
> LGTM
> 
> I can see there has been work done prior to this PR to use `ru-UA` config when the metadata language is `ru`.
> 
> Screen shot of local page with lang code of `ru-UA`
> Screen shot of local page with lang code of ru-UA

yeah, most of the work's been done prior to this. Even the IDX page uses the overridden 'lang', I wonder if it's worth having an issue to make all page types use this for consistency, as some are still using `metadata.language`

**Comment by thekp** [comment]
> I wonder if it's worth having an issue to make all page types use this for consistency, as some are still using metadata.language

yeah that sounds like a good idea, just so we have consistency across our pages

**Review by simonsinclair — APPROVED** [review]
Brilliant!

**Pull request merged**
