### PR TITLE
Gh page redirect

### PR DESCRIPTION
**Pull request by DarioR01**
Resolves bbc/simorgh-infrastructure#1463

**Overall change:**
Old implementation replaced by a redirect to a new hosted sotrybook page

**Code changes:**

- Delete old implementation of storybook deployment
- Add redirect to chromatic host, where latest storybook currently lives

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by pvaliani — APPROVED** [review]
LGTM is there an issue attached to this PR? Maybe add it to the description of the PR.

**Comment by DarioR01** [comment]
> LGTM is there an issue attached to this PR? Maybe add it to the description of the PR.

bbc/simorgh-infrastructure#1463

**Comment by DarioR01** [comment]
Yes, thank you for reminding me 😄 👍

**Review by nicola-d-bbc — APPROVED** [review]
Looks good, although I'm curious as to why the font files were deleted? I may not be fully understanding.

**Comment by DarioR01** [comment]
> Looks good, although I'm curious as to why the font files were deleted? I may not be fully understanding.

We are deploying storybook twice, in gh-page [https://bbc.github.io/simorgh/ ] and in chromatic [https://latest--5d28eb3fe163f6002046d6fa.chromatic.com].
I am deleting gh-page so that instead of building a storypage, it simply redirects to the chromatic one.
Hence, we don't need all the files needed to deploy storybook, file such as builded stories and fonts used for the stories.

Note that gh-page and chromatic build both build the latest branch, the only difference is that gh-page stopped working since we adopted signed commits.

Let me know if you want more information about it 😄.

**Pull request merged**
