### PR TITLE
Change navigation links from CPS indexes to WS topics

### LINKED ISSUE #4360: Change nav links from CPS indexes to WS topics
**Is your feature request related to a problem? Please describe.**
Where a WS site currently has CPS indexes as part of its navigation, we need to remove those links and replace them with the respective WS topic.

**Gujarati**
Nav link: ભારત 
Current url: /gujarati/india
New url: /gujarati/topics/5a08f030-710f-4168-acee-67294a90fc75

**Igbo**
Nav link: Egwuregwu 
Current url: /igbo/egwuregwu
New url: /igbo/topics/4063f80f-cccc-44c8-9449-5ca44e4c8592	 

**Marathi**
Nav link: भारत
Current url: /marathi/india
New url: /marathi/topics/5a08f030-710f-4168-acee-67294a90fc75

**Pidgin**
Nav link: Sport
Current url: /pidgin/sport
New url: /pidgin/topics/4063f80f-cccc-44c8-9449-5ca44e4c8592

**Punjabi**
Nav link: ਭਾਰਤ
Current url: /punjabi/india
New url: /punjabi/topics5a08f030-710f-4168-acee-67294a90fc75

**Serbian Lat**
Nav link: Srbija
Current url: /serbian/lat/srbija
New url: /serbian/lat/1791445f-977a-4e6d-b490-51f84bb4fc52

**Serbian Cyrl**
Nav link: Србија
Current url: /serbian/cyr/srbija
New url: /serbian/cyr/1791445f-977a-4e6d-b490-51f84bb4fc52

**Telugu**
Nav link: జాతీయం
Current url: /telugu/india
New url: /telugu/topics/5a08f030-710f-4168-acee-67294a90fc75

**Yoruba**
Nav link: Eré Ìdárayá
Current url: /yoruba/ere_idaraya
New url: /yoruba/topics/4063f80f-cccc-44c8-9449-5ca44e4c8592

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by OlgaLyubin**
Resolves #4360 

**Overall change:** 
Removed CPS indexes in navigation and replaced them with respective WS topics.

**Code changes:**
- Updated navigation links in service configs
- Updated snapshots

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by hotinglok — APPROVED** [review]
Looks good!

**Review by DenisHdz — APPROVED** [review]
LGTM 👍

**Review by sareh — APPROVED** [review]
👍 Looks good!

**Review by tochwill — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
lgtm

**Pull request merged**
