### PR TITLE
Adds PGL and STY pages to storybook

### LINKED ISSUE #5281: Add PGL and STY pages to Storybook
**Is your feature request related to a problem? Please describe.**
We currently use Storybook within Simorgh to preview components/pages/containers and most importantly have them previewed on chromaticQA so we can properly monitor unexpected changes. As of now we have no storybook previews for PGL and STY page types.

Example of an Article in storybook https://github.com/bbc/simorgh/blob/latest/src/app/containers/ArticleMain/index.stories.jsx

**Describe the solution you'd like**
Add PGL/STY pages and other related components to storybook which will additionally cause them to appear in chromaticQA.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [X] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by HarveyPeachey**
Resolves #5281

**Overall change:** 
Added storybook example for CPS PGL and STY pages.

**Code changes:**
- Added processed fixture data for STY and PGL.
- Added stories for STY and PGL pages.
- Updated ATI analytic unit tests to reflect amended PGL tests for the new processed fixture data.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by jamesdonoh** [comment]
Rather than having the page type show up in the hierarchy as `PGL`/`STY` which isn't very clear to people, maybe we could give the service name like it does under *Front page*. And would it be worth doing AMP as well as canonical while we're at it?

**Review by andrewscfc — APPROVED** [review]
Checked out, looks nice 🚢 🙂

**Comment by HarveyPeachey** [comment]
> Rather than having the page type show up in the hierarchy as `PGL`/`STY` which isn't very clear to people, maybe we could give the service name like it does under _Front page_. And would it be worth doing AMP as well as canonical while we're at it?

Yep, it makes sense to change the name. In regards to AMP, I can make a knob which gives the ability to switch between canonical and AMP. The main reason I didn't add them is because of our Article story not having an AMP version. Also is it feasible enough to have AMP versions of the page types even though there aren't any visual differences from my understanding? Or is it that we want them for the benefit of chromatic snapshots? @jamesdonoh

**Comment by jamesdonoh** [comment]
@HarveyPeachey OK let's just do the canonical one then!

**Review by oluoluoxenfree — APPROVED** [review]

**Pull request merged**
