### PR TITLE
Persian Article redirect tests

### LINKED ISSUE #1704: Article redirect tests
**Is your feature request related to a problem? Please describe.**

Where _:service_ is any service that should be served exclusively off .com (that is all non-UK services)

_NB scenarios below in strikethru relating to HTTPS uplift are out of scope till https://github.com/bbc/simorgh-infrastructure/issues/632 is resolved_

**Not .co.uk**

Given I go to https://www.bbc.co.uk/:service/articles/:id
Then I am given a 301 redirect to https://www.bbc.com/:service/articles/:id

~**Not http**~

~Given I go to http://www.bbc.co.uk/:service/articles/:id~
~Then I am given a 301 redirect to https://www.bbc.com/:service/articles/:id~

**AMP not on .co.uk**

Given I go to https://www.bbc.co.uk/:service/articles/:id.amp
Then I am given a 301 redirect to https://www.bbc.com/:service/articles/:id.amp

~**AMP not on http**~

~Given I go to http://www.bbc.co.uk/:service/articles/:id.amp~
~Then I am given a 301 redirect to https://www.bbc.com/:service/articles/:id.amp~

**Describe the solution you'd like**
- We should handle redirects within Mozart https://github.com/bbc/simorgh-infrastructure/issues/435. This ticket is only capturing the testing of redirects for our application. 
- These tests should only run against Test and Live environments, not local. 
- These can be run separately to the PR life cycle as a cron job.

Note: that until all of these services are routed on live, the tests should only be run against the test environment. An issue should be created to enable these on live when they are available.

**Describe alternatives you've considered**
We considered having the Cypress end-to-end tests in our current test suite repository, but decided against it - see the discussion thread below

**Testing notes**
We will need to add Cypress tests to make sure that the redirects happen as expected.
`Given I visit URL A, When I am redirected (served a 301 redirect), Then I will land on URL B`

Dev insight: Cypress tests will be sufficient.

### PR DESCRIPTION
**Pull request by DemonusPC**
Resolves #1704 

**Overall change:** 
Added Cypress tests that test the newly added Persian redirects. Currently Persian is only on test which means that it is locked to run on local and test only.

**Code changes:**
- Added a new spec file containing the tests.
- Tested that .co.uk is redirected to .com on both canonical and amp urls
- Tested that a http request is redirected to an https version on both canonical and amp urls

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Comment by dr3** [comment]
Why are we testing mozart functionality in simorgh? Is that not what mozarts tests do?

**Comment by DemonusPC** [comment]
Yes and no, as per my comment on the issue, these are e2e tests and Mozart is part of our stack. These tests just verify that Mozart is working as intended for **our** product.

**Review by jamesbhobbs — CHANGES_REQUESTED** [review]
Blocking this until I have time to look at it (hopefully later today).

**Comment by jamesbhobbs** [comment]
Please see my comments on the issue re why we shouldn't do this.

**Pull request closed without merging**
