### PR TITLE
Add frontpage & frontpage/beta route with dummy content

### LINKED ISSUE #1754: Add ws frontpage dummy route
**Is your feature request related to a problem? Please describe.**
In order to ensure that mozart routing work isnt blocked by simorgh, we can add a simple dummy route which will allow mozart to route something

**Describe the solution you'd like**
Add the following code to the production section of the server index express setup

```js
.get('/:service(igbo|pidgin|yoruba)(/beta)?', ({ params }, res) => {
  // This is a temporary route to unblock route setup in Mozart. 
  // Simply returns a 200 response which can we route to until 
  // it's set up properly in simorgh.
  const { service } = params;
  res.status(200).send(`Welcome to the temporary ${service} homepage simorgh route`);
})
```

Route will work for 
`/igbo`
`/pidgin`
`/yoruba`
`/igbo/beta`
`/pidgin/beta`
`/yoruba/beta`

**Testing notes**
[Tester to complete]

Dev insight: Unit tests, probably doesnt need cypress tests as its temporary and has very small scope for issue when partnered with existing e2e tests to ensure existing routes continue to work

### PR DESCRIPTION
**Pull request by dr3**
Resolves #1754

**Overall change:** Adds dummy frontpage routes to unblock routing in mozart
**Code changes:**

- Adds simply dummy route
- Adds some unit tests

Test that the new Route works for:
`/igbo`
`/pidgin`
`/yoruba`
`/igbo/beta`
`/pidgin/beta`
`/yoruba/beta`
`/igbo.amp`
`/pidgin.amp`
`/yoruba.amp`
`/igbo/beta.amp`
`/pidgin/beta.amp`
`/yoruba/beta.amp`

Ensure it does not work for nested requests on these routes:
`/pidgin/foo`
`/pidgin/beta/bar`

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by 12 — DISMISSED** [review]
LGTM 👍

**Review by DenisHdz — DISMISSED** [review]
Nice and tidy 👍

**Review by chris-hinds — DISMISSED** [review]
LGTM.

**Review by pjlee11 — DISMISSED** [review]
Nice one!

**Review by DenisHdz — APPROVED** [review]

**Review by chris-hinds — APPROVED** [review]

**Comment by david-boydell** [comment]
This is RFM

**Pull request merged**
