### PR TITLE
Group dependabot PRs - #5185 to #5208

### PR DESCRIPTION
**Pull request by j-pendlebury**
**Overall change:** 

## Dependabot
1. https://github.com/bbc/simorgh/pull/5185 - Bump wait-on from 3.3.0 to 4.0.0
2. https://github.com/bbc/simorgh/pull/5186 - Bump @bbc/psammead-styles from 4.1.2 to 4.2.0
3. https://github.com/bbc/simorgh/pull/5187 - Bump @babel/plugin-syntax-dynamic-import from 7.7.4 to 7.8.3
4. https://github.com/bbc/simorgh/pull/5188 - Bump @bbc/psammead-sitewide-links from 4.0.2 to 4.0.3 -> further updated to 4.0.5
5. https://github.com/bbc/simorgh/pull/5189 - Bump express-static-gzip from 2.0.5 to 2.0.6
6. https://github.com/bbc/simorgh/pull/5190 - Bump @storybook/addon-knobs from 5.3.3 to 5.3.6 -> further updated to 5.3.8
7. https://github.com/bbc/simorgh/pull/5191 - Bump @testing-library/jest-dom from 4.2.4 to 5.0.0 -> further updated to 5.0.2
8. https://github.com/bbc/simorgh/pull/5192 - Bump husky from 4.0.6 to 4.0.10 -> further updated to 4.2.0
9. https://github.com/bbc/simorgh/pull/5193 - Bump @storybook/react from 5.3.3 to 5.3.6 -> further updated to 5.3.8
10. https://github.com/bbc/simorgh/pull/5194 - Bump @bbc/psammead-storybook-helpers from 8.2.0 to 8.2.2 -> further updated to 8.2.3
11. https://github.com/bbc/simorgh/pull/5195 - Bump @bbc/psammead-copyright from 1.2.18 to 1.2.19 -> further updated to 1.2.21
12. https://github.com/bbc/simorgh/pull/5196 - Bump @bbc/psammead-media-indicator from 2.6.19 to 2.6.21 -> further updated to 2.6.24
13. https://github.com/bbc/simorgh/pull/5197 - Bump jsdom from 15.2.1 to 16.0.0
14. https://github.com/bbc/simorgh/pull/5198 - Bump @bbc/psammead-caption from 2.2.20 to 2.2.21
15. https://github.com/bbc/simorgh/pull/5199 - Bump cypress from 3.8.1 to 3.8.2
16. https://github.com/bbc/simorgh/pull/5200 - Bump @bbc/psammead-paragraph from 2.2.20 to 2.2.21 -> further updated to 2.2.23
17. https://github.com/bbc/simorgh/pull/5201 - Bump @bbc/psammead-consent-banner from 2.3.22 to 2.3.23 -> further updated to 2.3.25
18. https://github.com/bbc/simorgh/pull/5202 - Bump stylelint from 12.0.1 to 13.0.0
19. https://github.com/bbc/simorgh/pull/5203 - Bump @bbc/psammead-figure from 1.2.8 to 1.2.9 -> further updated to 1.2.10
20. https://github.com/bbc/simorgh/pull/5204 - Bump @bbc/psammead-useful-links from 1.0.9 to 1.0.10 -> further updated to 1.0.12
21. https://github.com/bbc/simorgh/pull/5205 - Bump @bbc/psammead-section-label from 3.0.8 to 3.0.9 -> further updated to 3.0.11
22. https://github.com/bbc/simorgh/pull/5206 - Bump @bbc/psammead-timestamp-container from 2.6.15 to 2.6.18 -> further updated to 2.6.20
23. https://github.com/bbc/simorgh/pull/5207 - Bump @storybook/theming from 5.3.3 to 5.3.6 -> further updated to 5.3.8
24. https://github.com/bbc/simorgh/pull/5208 - Bump @bbc/psammead-headings from 3.1.21 to 3.1.22 -> further updated to 3.1.24

### BBC packages after several Talos updates

1. "@bbc/gel-foundations": "^3.4.3",
2. "@bbc/psammead-assets": "^2.12.0",
3. "@bbc/psammead-brand": "^5.1.7",
4. "@bbc/psammead-bulletin": "^1.0.6",
5. "@bbc/psammead-caption": "^2.2.23",
6. "@bbc/psammead-grid": "^1.1.4",
7. "@bbc/psammead-image-placeholder": "^1.2.31",
8. "@bbc/psammead-inline-link": "^1.3.19",
9. "@bbc/psammead-media-player": "^2.6.0",
10. "@bbc/psammead-story-promo-list": "^2.1.25", 

### Other dependencies

1. "path-to-regexp": "^3.2.0",
2. "uuid": "^3.4.0",
3. "jsdom": "^16.0.1",
4. "inspectpack": "^4.3.1",

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- ~~Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)~~
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by j-pendlebury** [comment]
Blocked on https://github.com/bbc/psammead/pull/2991 - E2Es for media player are failing.

**Review by FK78 — APPROVED** [review]

**Review by AlistairGempf — APPROVED** [review]
Looks good to me

**Review by amywalkerdev — APPROVED** [review]

**Comment by PriyaKR** [comment]
Looks good to me.The PRs below are the main PRs that needed verification with the version bumps
https://github.com/bbc/psammead/pull/2569
https://github.com/bbc/psammead/pull/2807
https://github.com/bbc/psammead/pull/2199
https://github.com/bbc/psammead/pull/2806
https://github.com/bbc/psammead/pull/2826
https://github.com/bbc/psammead/pull/2935

**Pull request merged**
