### PR TITLE
Upload fixture data onto the box for frontpage launch

### PR DESCRIPTION
**Pull request by dr3**
Fix forward for https://github.com/bbc/simorgh/pull/1983

We need to use fixture data for the frontpage STM change, which 1982 intended to do. However we dont currently upload the data for it to use, this adds it :)

**Overall change:** Upload fixture data to the box

**Code changes:**

- Upload fixture data to the box

To be reverted in https://github.com/bbc/simorgh/issues/1996

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by DemonusPC — APPROVED** [review]
Dank, just make sure to rever this change once the routing is approved

**Review by 12 — APPROVED** [review]
Makes sense to me

But
```
Historic versions of the cp utility had a -r option.  This implementation supports that option; however, its use is strongly discouraged, as it does not correctly copy special files, symbolic links, or fifo's.
```

We should probably write an issue to get rid of `-r`

**Comment by dr3** [comment]
@rhell cheers for volunteering to write the issue :)

**Comment by david-boydell** [comment]
Agreed no test input required, this is ready for merge.

**Review by chris-hinds — APPROVED** [review]

**Comment by DemonusPC** [comment]
@rhell good catch the infra pod will look into improving any of those scripts.

**Pull request merged**
