### PR TITLE
Update contributing to mention new CHANGELOG.md

### PR DESCRIPTION
**Pull request by dr3**
**Overall change:** Update contributing to mention new CHANGELOG.md

**Code changes:**

- Update contributing guide to mention package bumping and changelog

---

- [x] I have assigned myself to this PR and the corresponding issues
- ~[ ] Tests added for new features~
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by rossgaskell — CHANGES_REQUESTED** [review]
Just catching up on this, this is the first time that I’ve known we were going to implement a changelog and can’t find an issue where this was discussed.

Could you forward over where this was discussed and decided on? We shouldn’t be making significant process changes without oversight of both core and I&T.

I agree this makes sense in Psammead as these are a public packages that can be installed individually and so could have breaking changes. Simorgh however isn’t (as far as I’m aware) an npm package and therefore non of the component changes should be major, minor or patch to highlight their risk. Latest should be at a stable working stage.

The first part of the Semver spec states

> Software using Semantic Versioning MUST declare a public API. This API could be declared in the code itself or exist strictly in documentation. However it is done, it should be precise and comprehensive.

Can you add to the changelog where we declare this public API.

**Comment by sareh** [comment]
@dr3 Can you please close this PR? We should have a discussion regarding Simorgh versioning with agreement across other pods prior to PRs being made. 

@rossgaskell I agree with you that it should be discussed first. 

I think there is some value with describing what is included in each release of Simorgh, which in this repository is each PR merged. This is useful for debugging issues on Test and Live environments. 

How we log this - whether a Changelog, GitHub Releases, or something else, should be discussed prior to opening PRs.

**Comment by rossgaskell** [comment]
If each Simorgh release is a PR merge, shouldn't the comments in the PR be clear as to what has been released?

**Comment by sareh** [comment]
I agree that each PR should have sufficient information regarding what has changed in that release.

Without any log of releases, we rely on going through commits on the `latest` branch for merge commits to have a clear overview of changes in our application. https://github.com/bbc/simorgh/commits/latest . 

Having a high-level summary of PRs mapping to what has changed in a document would be useful for giving clear visibility of changes made to this Repo that doesn't rely trawling through commit history.

**Pull request closed without merging**
