### PR TITLE
Update the 'Contact us' links for all sites

### LINKED ISSUE #7916: FOOTER - All sites - Update the 'Contact us' links
**Is your feature request related to a problem? Please describe.**
The editorial team have moved the 'contact us' pages to iSite so there will be a new url.
The link has been updated on Mundo but now needs to be done on all other sites.
Please let editorial know before starting this ticket (via Jim,Jon,Josh) so they can send out comms to the teams 

**Describe the solution you'd like**
Update the Footer (contact us) with the new url
https://github.com/bbc/simorgh/tree/latest/src/app/lib/config/services

Service | Old "Contact Us" form | New "Contact Us" form
-- | -- | --
Afaan Oromoo | https://www.bbc.com/afaanoromoo/institutional-42228538 | https://www.bbc.co.uk/send/u50777768
Afrique | https://www.bbc.com/afrique/institutionelles-36826644 | https://www.bbc.co.uk/send/u50853159
Amharic | https://www.bbc.com/amharic/institutional-42228117 | https://www.bbc.co.uk/send/u50853181
Arabic | https://www.bbc.com/arabic/institutional-37731355 | https://www.bbc.co.uk/send/u50853203
Azeri | https://www.bbc.com/azeri/institutional-37131054 | https://www.bbc.co.uk/send/u50853225
Bengali | https://www.bbc.com/bengali/institutional-37289967 | https://www.bbc.co.uk/send/u50853247
Burmese | https://www.bbc.com/burmese/institutional-37577525 | https://www.bbc.co.uk/send/u50853269
Gahuza | https://www.bbc.com/gahuza/institutional-35754061 | https://www.bbc.co.uk/send/u50853291
Gujarati | https://www.bbc.com/gujarati/institutional-42224948 | https://www.bbc.co.uk/send/u50853313
Hausa | https://www.bbc.com/hausa/game-da-mu-37377092 | https://www.bbc.co.uk/send/u50853335
Hindi | https://www.bbc.com/hindi/institutional-37342616 | https://www.bbc.co.uk/send/u50853379
Igbo | https://www.bbc.com/igbo/institutional-43090448 | https://www.bbc.co.uk/send/u50853379
Indonesian | https://www.bbc.com/indonesia/institutional-37818427 | https://www.bbc.co.uk/send/u50853401
Korean | https://www.bbc.com/korean/institutional-42224941 | https://www.bbc.co.uk/send/u50853423
Kyrgyz | https://www.bbc.com/kyrgyz/institutional-38157284 | https://www.bbc.co.uk/send/u50853445
Marathi | https://www.bbc.com/marathi/institutional-42227676 | https://www.bbc.co.uk/send/u50853467
Nepali | https://www.bbc.com/nepali/institutional-38159617 | https://www.bbc.co.uk/send/u50853511
Pashto | https://www.bbc.com/pashto/institutional-37622768 | https://www.bbc.co.uk/send/u50853533
Persian | https://www.bbc.com/persian/institutional-37542244 | https://www.bbc.co.uk/send/u50853555
Pidgin | https://www.bbc.com/pidgin/institutional-42188215 | https://www.bbc.co.uk/send/u50853577
Portuguese | https://www.bbc.com/portuguese/institutional-36202456 | https://www.bbc.co.uk/send/u50853599
Punjabi | https://www.bbc.com/punjabi/institutional-42227903 | https://www.bbc.co.uk/send/u50853621
Russian | https://www.bbc.com/russian/institutional-36517237 | https://www.bbc.co.uk/send/u50853643
Serbian | https://www.bbc.com/serbian/lat/institutional-43543431 | https://www.bbc.co.uk/send/u50853665
Sinhala | https://www.bbc.com/sinhala/institutional-36019593 | https://www.bbc.co.uk/send/u50853687
Somali | https://www.bbc.com/somali/hayadeed-37098613 | https://www.bbc.co.uk/send/u50853709
Swahili | https://www.bbc.com/swahili/taasisi/2011/10/000001_contactus | https://www.bbc.co.uk/send/u50853731
Tamil | https://www.bbc.com/tamil/institutional-37288738 | https://www.bbc.co.uk/send/u50853753
Telugu | https://www.bbc.com/telugu/institutional-42227910 | https://www.bbc.co.uk/send/u50853775
Thai | https://www.bbc.com/thai/institutional-37981748 | https://www.bbc.co.uk/send/u50853797
Tigrinya | https://www.bbc.com/tigrinya/institutional-42228875 | https://www.bbc.co.uk/send/u50853819
Turkce | https://www.bbc.com/turkce/kurumsal-36767474 | https://www.bbc.co.uk/send/u50853841
UK China | https://www.bbc.com/ukchina/simp/institutional-38733406 | https://www.bbc.co.uk/send/u50853863
Ukrainian | https://www.bbc.com/ukrainian/institutional-38146278 | https://www.bbc.co.uk/send/u50853885
Urdu | https://www.bbc.com/urdu/institutional-37588285 | https://www.bbc.co.uk/send/u50853907
Uzbek | https://www.bbc.com/uzbek/institutional-36826360 | https://www.bbc.co.uk/send/u50853929
Vietnamese | https://www.bbc.com/vietnamese/institutional-37623842 | https://www.bbc.co.uk/send/u50853951
Yoruba | https://www.bbc.com/yoruba/institutional-43091540 | https://www.bbc.co.uk/send/u50853973
Zhongwen | https://www.bbc.com/zhongwen/simp/institutional-38664417 | https://www.bbc.co.uk/send/u50778626

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by FK78**
Resolves #7916

**To merge on Thursday 8th October**

**Overall change:**
_Update the 'Contact us' links for all sites._

**Code changes:**

- _Update the 'Contact us' links for all sites._
- _Update integration and unit test snapshots._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by karinathomasbbc — APPROVED** [review]
Looks good, thanks!

**Comment by chewu** [comment]
@JonBeeb Just looking at the new link pages, none of them have any of the correct translations, they all a have a generic text in French for the form (which is odd) and the rest in English.

Hope we not merging this to live in this current state?

Contact-BBC-Indonesia-BBC-News-Indonesia-Send-BBC

**Comment by JonBeeb** [comment]
Vlad and Jordi are aware of the forms

**Review by chewu — APPROVED** [review]

**Comment by jimjohnsonrollings** [comment]
Agreed to merge and release on ~Tuesday 6th October~ Thursday 8th October

**Review by karinathomasbbc — APPROVED** [review]

**Pull request merged**
