### PR TITLE
Manifest images json

### LINKED ISSUE #1790: Add Manifest.json and Images for WS sites
Images found in WSFRONTPGS-66

**Is your feature request related to a problem? Please describe.**
We need to generate and create manifest.json files for our 3 new services `Igbo, pidgin & Yoruba`

**Describe the solution you'd like**
1) Create a manifest.json file for each service in the style of [existing ones](https://github.com/bbc/simorgh/blob/latest/public/persian/manifest.json)
2) Ensure the manifest.json can be accessed via `/{service}/articles/manifest.json`
3) Add required images [to match existing ones](https://github.com/bbc/simorgh/tree/latest/public/persian/images/icons)

NB: the manifest uses live URLs like `https://news.files.bbci.co.uk/include/articles/public/persian/images/icons/icon-72x72.png`, untill we upload them, they wont exist on this domain. Its fine to merge this in 1 go, with the expectation they will work after merge.

NB: The manifest url of `/{service}/articles/manifest.json` isnt suitable for us, This will however be fixed in a later issue :)

**Testing notes**
[Tester to complete]

Dev insight: Manual testing, maybe a cypress test?

### PR DESCRIPTION
**Pull request by dr3**
Resolves #1790

**Overall change:** Adds service images and manifest.json file

**Code changes:**

- Adds images for 3 ws sites
- Adds manifest json for 3 sites with future URLs to those images

**Testing notes:** 
You should be able to hit the manifest files at `http://localhost:7080/igbo/articles/manifest.json`

The Image URLs wont work yet, but if you change the URLs to `persian` they should, as they have been merged in the same name and structure.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by DenisHdz — APPROVED** [review]

**Review by andrew-nowak — APPROVED** [review]

**Review by andrew-nowak — CHANGES_REQUESTED** [review]
woops; went too fast:
running locally and navigating to `http://localhost:7080/igbo/articles/manifest.json` (and same with news)
returns
`Unable to find manifest.`
and this error in the console:
```js
{ [Error: ENOENT: no such file or directory, stat '/Users/MYUSERNAME/workspace/simorgh/build/public/igbo/manifest.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path:
   '/Users/MYUSERNAME/workspace/simorgh/build/public/igbo/manifest.json',
  expose: false,
  statusCode: 404,
  status: 404 }
```
is this an issue with my setup?

**Comment by dr3** [comment]
@aacn500 are you running `npm run dev` instead of build & start?

**Review by andrew-nowak — APPROVED** [review]
yep, that was it :+1:

**Comment by david-boydell** [comment]
Hi @dr3, I checked this out and the files look fine. The only question I have is something to do with routing, with this checked out when I hit http://localhost:7080/igbo I get a 301 redirect to /igbo/, this then gets a 404.

I saw in the manifest "Scope": "/igbo/", and didn't know whether this was a factor. There was a question about the routing with trailing slashed in #1810, not sure if this is something we need to address.

**Comment by dr3** [comment]
@david-boydell the `/igbo/` behaviour is the same as on latest, the igbo route hasnt been merged yet :)

**Comment by david-boydell** [comment]
Cool, thanks.

**Pull request merged**
