### PR TITLE
Features analysis tracking

### LINKED ISSUE #9128: Use view and click tracking hooks on the features & analysis component
**Is your feature request related to a problem? Please describe.**
As a ws product manager I want to know how many users who see the features & analysis promos on our pages click on the links so that I have a baseline to measure improvements to the component.

features

**Describe the solution you'd like**
Enable tracking to the features & analysis block that will send a single view event when the block is in view and a single click event if any link within the block is clicked. The content of the view and click event must be the same for the block so ATI can calculate the click/view value.  The tracking must contain details of what service is being tracked.

Configure the features & analysis block on cps articles and media asset pages to enable block level tracking. This will give a view in ATI where we can track the views/clicks of the block.

### The click event
Send a block level click event if any link/promo within the block is clicked. (we are only tracking the interaction and not tracking the link location)

Don't send a click event if any other part of the block is clicked.

`atc=PUB-[Campaign]-[Creation]-[Variant]-[Format]-[General Placement]-[Detailed Placement]-[Advertiser ID]-[Url]&type=AT`

```
(atc)
atc=PUB-[article-sty]-[features]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]&type=AT
```

### The view/impression event

`ati=PUB-[Campaign]-[Creation]-[Variant]-[Format]-[General]-[Detailed]-[Advertiser]-[Url]&type=AT`

```
(ati)
ati=PUB-[article-sty]-[features]-[]-[]-[pidgin.world.story.56829018.page]-[]-[]-[]&type=AT
```

### Example values from click/impression events

|                    |                                                                  |
| ------------------ | ---------------------------------------------------------------- |
| Campaign           | 'article-sty' (this is dynamic and relates to the page type)                                                        |
| Creation           | 'features'                                                    |
| Variant            | empty                                                            |
| Format             | empty                                                            |
| General Placement  | _page_ eg pidgin.world.story.56829018.page (same as the p value) |
| Detailed Placement | empty                                                            |
| Advertiser ID      | empty                                                            |
| Url                | empty                                                            |

### ATI Tag Inspector
In the Tag Inspector these values should be present:
- Site - 598342
- Level2 - 70
- (Under -Ad)
- Campaign ID - article-sty
- Creation ID - features
- General placement - pidgin.world.story.56829018.page

### Accessibility
The solution should have no adverse affects with any of our support assistive technology. This will require a developer accessiblity swarm to check that nothing unexpected is read out, such as 'clickable'. e.g. Only the content and HTML semantics should be announced for elements, nothing extra to the defined screen reader UX for components.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
The WS event tracking matrix contains all tracking campaigns and which components are appear on which page types NEWSWORLDSERVICE/WS+event+matrix.

### PR DESCRIPTION
**Pull request by HarryVerhoef**
Resolves #9128 

**Overall change:**
Adds view and click tracking to the features & analysis component.

**Code changes:**

- Attaches the view tracking reference to `StoryPromoLi`.
- Passes `eventTrackingData` to each `StoryPromo`, where the click tracker handler is generated and attached.

---

- [X] I have assigned myself to this PR and the corresponding issues
- [X] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [X] I have assigned this PR to the Simorgh project
- [X] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [X] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [X] This PR requires manual testing

### CODE REVIEW

**Review by jroebu14 — APPROVED** [review]
Nice one. Should we add unit tests checking the spies here too?

**Comment by HarryVerhoef** [comment]
> Nice one. Should we add unit tests checking the spies here too?

Thanks! As in checking that fetch was called with the correct params on view and click?

**Review by andrewscfc — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Testing:

* http://localhost:7080/pidgin/tori-51745682 -- Noticed an error particularly on this asset and myself & Harry thought we will put this on test and check again as its only hapenning on this asset. Attached is the error below.
* http://localhost:7080/mundo/media-23283126

LGTM..
Screenshot 2021-06-14 at 13 46 20

**Comment by paruchurisilpa** [comment]
https://www.test.bbc.com/pidgin/tori-23146434
https://www.test.bbc.com/marathi/india-23129746

Didn't see any errors observed on local and LGTM..

**Pull request merged**
