### PR TITLE
Update ATI destination and tests for /scotland

### LINKED ISSUE #3810: Update ATI destination for /scotland
**Is your feature request related to a problem? Please describe.**
Update ATI destination for /scotland, and remove the default bucket

Arises from @sareh's comment at https://github.com/bbc/simorgh/pull/3727#discussion_r324604440

**Describe the solution you'd like**
Set the destination for /scotland as:
- 598295 (known as PLACEHOLDER) on LIVE
- 598297 (PLACEHOLDER_TEST) on TEST

Note: We will update again in future, but we need to wait for future ATI destinations to be configured.

**Testing notes**
Manual testing to make sure that the value expected (dependant on `ENV`) is returned correctly. When testing this locally, we want to create a `TEST` & `LIVE` build, run it locally and check to make sure that the correct value has been returned on the ATI Dashboard.

If you do not have login access to the ATI Dashboard speak with @jimjohnsonrollings .

Dev insight: Update unit tests.
https://github.com/bbc/simorgh/blob/latest/src/app/lib/analyticsUtils/index.js 
https://github.com/bbc/simorgh/blob/latest/src/app/lib/analyticsUtils/index.test.js 
https://github.com/bbc/simorgh/blob/latest/src/app/contexts/RequestContext/getStatsDestination/index.js

Update Cypress tests.
https://github.com/bbc/simorgh/blob/latest/cypress/support/config/envs.js
https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/testsForAllAMPPages.js
https://github.com/bbc/simorgh/blob/latest/cypress/integration/pages/testsForAllCanonicalPages.js

- [x] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by jimjohnsonrollings**
Resolves #3810 

**Overall change:**
Changes the ATI destination field for /scotland

**Code changes:**

- Creates the PLACEHOLDER and PLACEHOLDER_TEST destinations
- Applies them to /scotland
- Updates Cypress tests
- Updates unit tests
- Removes the now unused DEFAULT and DEFAULT_TEST destinations

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by jimjohnsonrollings** [comment]
On hold waiting for confirmation on Thursday that we don't need to imminently change the destination again

**Comment by jimjohnsonrollings** [comment]
We will not be making an imminent change so this is unblocked

**Review by sareh — APPROVED** [review]
👍 Looks good.  
I didn't see the name of the bucket `PLACEHOLDER_TEST` when I logged into the ATI Tag inspector, but the value of it is being sent correctly. 
Screenshot Scotland ATI destination

**Review by jamesdonoh — APPROVED** [review]

**Comment by PriyaKR** [comment]
Looks good to me.

**Pull request merged**
