### PR TITLE
WSTEAMA-288: Ensure page type is passed as a parameter to the simorgh BFF

### PR DESCRIPTION
**Pull request by karinathomasbbc**
Resolves #WSTEAMA-288

**Overall change:**
Ensures that pageType is set to topic when invoking the simorgh-bff, because it will become a mandatory parameter in future

**Code changes:**
- set pageType=topic when invoking the bff for topic pages
- Update tests

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by amoore108 — APPROVED** [review]

**Review by HarveyPeachey — APPROVED** [review]
LGTM

Would be nice to see this as a typescript type, maybe we need a tech ticket to convert all the getinitialdata files to typescript at some point

**Review by Louis-Matsika — APPROVED** [review]

**Comment by karinathomasbbc** [comment]
> Would be nice to see this as a typescript type, maybe we need a tech ticket to convert all the getinitialdata files to typescript at some point

That's a good shout. I can make sure that `getInitialData` for our new homepage is written in typescript, but it would be nice if some of the others were TS too.

**Comment by amoore108** [comment]
> > Would be nice to see this as a typescript type, maybe we need a tech ticket to convert all the getinitialdata files to typescript at some point
> 
> That's a good shout. I can make sure that `getInitialData` for our new homepage is written in typescript, but it would be nice if some of the others were TS too.

Could be worth taking inspiration from the article/cps data fetcher. Its type checked and improves upon the Topic fetcher by allowing for local json fixture data fetching as well:
 https://github.com/bbc/simorgh/blob/6ad2bea8a8de254380dd50f25103f3a7a3637816/src/app/routes/article/getInitialData/index.ts

**Comment by karinathomasbbc** [comment]
> Could be worth taking inspiration from the article/cps data fetcher. Its type checked and improves upon the Topic fetcher by allowing for local json fixture data fetching as well:
> https://github.com/bbc/simorgh/blob/6ad2bea8a8de254380dd50f25103f3a7a3637816/src/app/routes/article/getInitialData/index.ts

The plan is absolutely to copy pasta the article/topic data fetcher - it's our next ticket 😄

**Pull request merged**
