### PR TITLE
WSTEAM1-807 Live label pulse vertical alignment for burmese with no header image

### PR DESCRIPTION
**Pull request by emilysaffron**
Resolves https://github.com/bbc/simorgh/pull/11372#issuecomment-1978690168

Overall changes
======
Reduces the font size of live label text and the size of the pulse from the `GROUP_3` breakpoint and above in line with new styles. Makes sure the burmese live label text is aligned correctly with the pulse.

Code changes
======

- Sets `fontSize` to `paragon bold` at `GROUP_3_MIN_WIDTH` on `liveLabelTextWithImage` and `liveLabelTextWithoutImage`

Testing
======
1. Visit the [storybook link](https://live-label-for-burmese--5d28eb3fe163f6002046d6fa.chromatic.com/?path=/story/new-components-livepageheader--title-only-with-live-label) and check that at the largest breakpoint for burmese the live label looks like this. Also worth double checking other services to make sure they still work as expected from https://github.com/bbc/simorgh/pull/11372

Screenshot 2024-03-05 at 14 57 07

Helpful Links
======
_Add Links to useful resources related to this PR if applicable._

[Coding Standards](https://github.com/bbc/simorgh/blob/latest/docs/Coding-Standards/README.md)

[Repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

### CODE REVIEW

**Review by Isabella-Mitchell — COMMENTED** [review]
To confirm is this being done because the text is being broken like so 
Screenshot 2024-03-05 at 15 50 21

I wonder if it would be better to approach to this? E.g. defaulting to the mobile layout if the text is too long. We do something I bit like this for [Burmese Most Read.](https://github.com/bbc/simorgh/blob/b8232b80df3943c48df97d83e97ebb8398a4f874/src/app/components/MostRead/Canonical/List/index.tsx#L17-L18).

Not sure I love the idea of overriding the text size for one specific service. But interested to see what others think.

**Comment by emilysaffron** [comment]
> To confirm is this being done because the text is being broken like so Screenshot 2024-03-05 at 15 50 21
> 
> I wonder if it would be better to approach to this? E.g. defaulting to the mobile layout if the text is too long. We do something I bit like this for [Burmese Most Read.](https://github.com/bbc/simorgh/blob/b8232b80df3943c48df97d83e97ebb8398a4f874/src/app/components/MostRead/Canonical/List/index.tsx#L17-L18).
> 
> Not sure I love the idea of overriding the text size for one specific service. But interested to see what others think.

Yeah that's why, it came about because the pulse wasn't aligned with the top line of text, and then when checking with wendy we agreed its best not to have just one character split onto the next line. 

I see what u mean , so are you suggesting to default it to be like :
Screenshot 2024-03-05 at 16 14 27

at all breakpoints for burmese?

**Comment by amoore108** [comment]
May go against the design slightly, but could we just increase the width for this to `30%`:
https://github.com/bbc/simorgh/blob/6eb7a4a8a6959196e308b2f15104b70a9db9369f/ws-nextjs-app/pages/%5Bservice%5D/live/%5Bid%5D/Header/LiveLabelHeader/index.styles.ts#L51

and decrease this to `70%`:
https://github.com/bbc/simorgh/blob/6eb7a4a8a6959196e308b2f15104b70a9db9369f/ws-nextjs-app/pages/%5Bservice%5D/live/%5Bid%5D/Header/styles.tsx#L92

to accommodate larger live label translations?

This seems to only be an issue when there is no header image used, which I imagine will be quite rare in reality.

**Review by karinathomasbbc — APPROVED** [review]
LGTM

**Comment by Isabella-Mitchell** [comment]
> May go against the design slightly, but could we just increase the width for this to `30%`:
> 
> https://github.com/bbc/simorgh/blob/6eb7a4a8a6959196e308b2f15104b70a9db9369f/ws-nextjs-app/pages/%5Bservice%5D/live/%5Bid%5D/Header/LiveLabelHeader/index.styles.ts#L51
> 
> and decrease this to `70%`:
> 
> https://github.com/bbc/simorgh/blob/6eb7a4a8a6959196e308b2f15104b70a9db9369f/ws-nextjs-app/pages/%5Bservice%5D/live/%5Bid%5D/Header/styles.tsx#L92
> 
> to accommodate larger live label translations?
> 
> This seems to only be an issue when there is no header image used, which I imagine will be quite rare in reality.

Here is a little preview of what this looks like.

We would also need to push across the description - which might be tricky but I think doable.

Screenshot 2024-03-06 at 12 25 02

**Comment by amoore108** [comment]
> Here is a little preview of what this looks like.
> 
> We would also need to push across the description - which might be tricky but I think doable.

Ah fair, didn't think of the description. Looks like it aligns on the left vertical edge all the way down the page, so the width change may not be possible.

**Comment by Isabella-Mitchell** [comment]
> To confirm is this being done because the text is being broken like so Screenshot 2024-03-05 at 15 50 21
> 
> I wonder if it would be better to approach to this? E.g. defaulting to the mobile layout if the text is too long. We do something I bit like this for [Burmese Most Read.](https://github.com/bbc/simorgh/blob/b8232b80df3943c48df97d83e97ebb8398a4f874/src/app/components/MostRead/Canonical/List/index.tsx#L17-L18).
> 
> Not sure I love the idea of overriding the text size for one specific service. But interested to see what others think.

To do this I think we would need to unset the media queries [here](https://github.com/bbc/simorgh/blob/1259babbd823b479491223795ae0cb9020ac989e/ws-nextjs-app/pages/%5Bservice%5D/live/%5Bid%5D/Header/styles.tsx#L85-L92) and [here](https://github.com/bbc/simorgh/blob/1259babbd823b479491223795ae0cb9020ac989e/ws-nextjs-app/pages/%5Bservice%5D/live/%5Bid%5D/Header/styles.tsx#L103-L107), or only apply these to services that are not Burmese. Which is maybe more complicated to unpick than overriding the text size.

Screenshot 2024-03-06 at 12 45 51

**Comment by amoore108** [comment]
> > To confirm is this being done because the text is being broken like so Screenshot 2024-03-05 at 15 50 21
> > I wonder if it would be better to approach to this? E.g. defaulting to the mobile layout if the text is too long. We do something I bit like this for [Burmese Most Read.](https://github.com/bbc/simorgh/blob/b8232b80df3943c48df97d83e97ebb8398a4f874/src/app/components/MostRead/Canonical/List/index.tsx#L17-L18).
> > Not sure I love the idea of overriding the text size for one specific service. But interested to see what others think.
> 
> To do this I think we would need to unset the media queries [here](https://github.com/bbc/simorgh/blob/1259babbd823b479491223795ae0cb9020ac989e/ws-nextjs-app/pages/%5Bservice%5D/live/%5Bid%5D/Header/styles.tsx#L85-L92) and [here](https://github.com/bbc/simorgh/blob/1259babbd823b479491223795ae0cb9020ac989e/ws-nextjs-app/pages/%5Bservice%5D/live/%5Bid%5D/Header/styles.tsx#L103-L107), or only apply these to services that are not Burmese. Which is maybe more complicated to unpick than overriding the text size.
> 


Is it worth checking with UX if this is an acceptable approach in general for all services when there is no image? I quite like the look of what you have there.

**Comment by emilysaffron** [comment]
> > > To confirm is this being done because the text is being broken like so Screenshot 2024-03-05 at 15 50 21
> > > I wonder if it would be better to approach to this? E.g. defaulting to the mobile layout if the text is too long. We do something I bit like this for [Burmese Most Read.](https://github.com/bbc/simorgh/blob/b8232b80df3943c48df97d83e97ebb8398a4f874/src/app/components/MostRead/Canonical/List/index.tsx#L17-L18).
> > > Not sure I love the idea of overriding the text size for one specific service. But interested to see what others think.
> > 
> > 
> > To do this I think we would need to unset the media queries [here](https://github.com/bbc/simorgh/blob/1259babbd823b479491223795ae0cb9020ac989e/ws-nextjs-app/pages/%5Bservice%5D/live/%5Bid%5D/Header/styles.tsx#L85-L92) and [here](https://github.com/bbc/simorgh/blob/1259babbd823b479491223795ae0cb9020ac989e/ws-nextjs-app/pages/%5Bservice%5D/live/%5Bid%5D/Header/styles.tsx#L103-L107), or only apply these to services that are not Burmese. Which is maybe more complicated to unpick than overriding the text size.
> 
> Is it worth checking with UX if this is an acceptable approach in general for all services when there is no image? I quite like the look of what you have there.

Checked this with UX, they think this approach isnt ideal as it aligns with the PS dual column design , but have suggested that we could reduce the font size for all the services instead of just for burmese? Im not too sure if this is better than just doing it for burmese or not , would be good to get opinions 😊

**Comment by amoore108** [comment]
> Checked this with UX, they think this approach isnt ideal as it aligns with the PS dual column design , but have suggested that we could reduce the font size for all the services instead of just for burmese? Im not too sure if this is better than just doing it for burmese or not , would be good to get opinions 😊

I think any approach that applies to all services is good imo. Its the per-service bits that get a bit unmaintainable over time.

**Review by amoore108 — APPROVED** [review]

**Review by louisearchibald — APPROVED** [review]

**Pull request merged**
