### PR TITLE
Added front page titles to service configs

### LINKED ISSUE #3406: Add all the front page titles to service config
**Is your feature request related to a problem? Please describe.**
After https://github.com/bbc/simorgh/pull/3376 we have a new service config key `frontPageTitle` which is used to override the title found in the data feed. In discussion, it would be best if this was used for each service.

**Describe the solution you'd like**
Add the `frontPageTitle` config key to each service, so that the title is no longer obtained from the data feed.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by OlgaLyubin**
Resolves #3406 

**Overall change:** 
Added the `frontPageTitle` config key to each service, so that the title is no longer obtained from the data feed.

**Code changes:**
- Added front page titles to each service config.
- Updated snapshot tests.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by andrew-nowak — APPROVED** [review]
:+1: the translations for igbo, pidgin & yoruba lgtm, the rest can be double checked as they go live IMO

**Review by DenisHdz — APPROVED** [review]
Assuming the translations are correct, it lgtm. I checked the box to be tested manually.

**Review by dr3 — APPROVED** [review]

**Review by sareh — COMMENTED** [review]
@OlgaLyubin @aacn500 I note that you're following the instructions in the issue, but what's the reason for having a separate value for `frontPageTitle` when you have `translations.home` which is the same value? 

Note - I am adding Cypress tests to test to ensure all of our pages are using the same pattern `title - brandName` https://github.com/bbc/simorgh/pull/3364 
https://github.com/bbc/simorgh/pull/3364/files#diff-6ef73c82b1834f188b8648a2ce247f32R188

**Comment by andrew-nowak** [comment]
> @OlgaLyubin @aacn500 I note that you're following the instructions in the issue, but what's the reason for having a separate value for `frontPageTitle` when you have `translations.home` which is the same value?


because they're not always the same value - use Thai as an example.

`    home: 'หน้าแรก',`
`  frontPageTitle: 'ข่าว ข่าวสด วัน นี้ ข่าว ล่าสุด วีดีโอ',`

**Review by jroebu14 — APPROVED** [review]

**Comment by sareh** [comment]
@OlgaLyubin Okay - but the latter value `'ข่าว ข่าวสด วัน นี้ ข่าว ล่าสุด วีดีโอ'` translates to `News Fresh news Today Latest news Videos` which is good for SEO but not the title of a page, which being `Homepage - BBC News Thai` would be better. I'll check with Clare.

**Comment by sareh** [comment]
Having talked with Tom, the SEO expert, he noted this: 
>Yep, we’ve been optimising towards top generic news searches so this is mostly geared towards search performance. Best practice for SEO and in line with successful changes such as https://www.bbc.com/hindi and https://www.bbc.com/portuguese. ‘Homepage’ isn’t a big search for audiences so we’ve been trying to change this (albeit slowly) for a while now. This also mirrors competitors who optimise title tag towards broad generic news search phrases, so it is mostly down to search, but a lot towards falling behind against competitors too.

Makes sense.

**Pull request merged**
